from ds_part1 import _e

REFLECTION_DATA = [
_e("Reflect on a web application pentest where SQLi was found but not exploited",
   ["Client scope limited to discovery only","SQLi confirmed via error-based detection","Full exploitation would exceed authorization"],
   ["Document finding","Capture PoC screenshot","Recommend remediation","Note for report"],
   ["Confirm injection point with sqlmap --level=1","Capture error output as evidence","Stop before data extraction","Document in finding tracker"],
   [("sqlmap","confirm injection without extraction"),("burpsuite","capture request/response as evidence")],
   "Authorization boundary respected — discovery-only scope honored. PoC documented without actual data exfiltration. Client can validate finding safely.",
   "SQLi found in login form parameter. Confirmed error-based. Stopped at detection per scope. Reported as Critical.",
   "concise","**Finding: SQL Injection (Critical)**\nParameter: `username`\nType: Error-based\nEvidence: DB error on `'` input\nRecommendation: Use parameterized queries."),

_e("Reflect on failed brute force due to account lockout",
   ["Target had 5-attempt lockout policy","Attack triggered lockout on test accounts","Needed to adjust strategy"],
   ["Switch to password spray","Use common passwords only","Respect lockout threshold"],
   ["Detect lockout policy via failed login response","Switch to spray: 1 password per account","Wait between attempts","Log results"],
   [("hydra","initial brute force attempt"),("custom_script","password spray with delay")],
   "Lockout policy detected early. Switching to spray prevented account lockouts on production accounts. Better enumeration of policy before attack.",
   "Account lockout at 5 attempts. Spray with 1 password per 30min window. Found 3 valid accounts with 'Winter2024!'",
   "technical","Password spray succeeded where brute force failed. Lockout policy: 5 attempts/30min. Valid creds found via spray."),

_e("Reflect on network scan that triggered IDS alerts",
   ["Aggressive scan triggered SIEM alerts","Blue team notified during test","Needed to reduce scan noise"],
   ["Switch to slow scan","Use stealth techniques","Coordinate with blue team"],
   ["Reduce scan rate with -T2","Use decoy IPs with -D","Scan during off-hours","Verify IDS rules with blue team"],
   [("nmap","stealth scan with timing control"),("hping3","custom packet crafting")],
   "Scan triggered detection — valuable data for blue team. Adjusted to T2 timing. This revealed IDS sensitivity which is useful for tuning.",
   "Nmap T4 triggers IDS at rule threshold. T2 with -f fragmentation reduces detection. Document IDS sensitivity for blue team.",
   "analytical","IDS triggered at T4 scan rate. Switched to T2 with fragmentation. Blue team confirmed alert. Valuable for detection tuning."),

_e("Reflect on privilege escalation via misconfigured sudo",
   ["sudo -l revealed NOPASSWD entry","Binary allowed shell escape","Root obtained unexpectedly quickly"],
   ["Document sudo misconfiguration","Test shell escape","Report as critical finding"],
   ["Run sudo -l","Identify dangerous NOPASSWD binaries","Use GTFOBins escape technique","Verify root access","Document immediately"],
   [("sudo","privilege check"),("gtfobins","shell escape technique")],
   "Critical misconfiguration found immediately. Root in 2 minutes via sudo vim shell escape. Highlights importance of sudo auditing.",
   "sudo NOPASSWD on vim. GTFOBins: :!/bin/sh gives root. Always check sudo -l first in Linux privesc.",
   "concise","**PrivEsc: sudo Misconfiguration**\n`sudo -l` shows `(ALL) NOPASSWD: /usr/bin/vim`\nEscape: `sudo vim -c ':!/bin/sh'`\nResult: root shell"),

_e("Reflect on cloud audit where S3 bucket was publicly accessible",
   ["S3 bucket had public-read ACL","Sensitive config files exposed","No encryption at rest"],
   ["List bucket contents","Identify sensitive files","Document exposure","Recommend remediation"],
   ["aws s3 ls s3://target-bucket --no-sign-request","Download sample files","Check for secrets","Document all exposed data types"],
   [("aws_cli","enumerate public bucket"),("trufflehog","scan for secrets in files")],
   "Public S3 bucket exposed internal configs and API keys. Critical finding. Demonstrates need for S3 Block Public Access setting.",
   "Public S3: check with --no-sign-request. Common exposures: .env files, backups, API keys. Always enable Block Public Access.",
   "professional","S3 bucket publicly accessible. Found: config.json with DB credentials, backup.sql. Recommend: Enable Block Public Access, rotate all credentials."),

_e("Reflect on XSS found in reflected search parameter",
   ["Search parameter reflected without encoding","Confirmed XSS with alert payload","Stored vs reflected distinction important"],
   ["Confirm reflection","Test XSS payload","Assess impact","Document for report"],
   ["Input <script>alert(1)</script>","Confirm reflection in response","Test for cookie theft potential","Document with screenshot"],
   [("burpsuite","intercept and modify request"),("xsstrike","advanced XSS detection")],
   "Reflected XSS confirmed. No CSP header present increases impact. Cookie accessible via document.cookie. Medium-High severity.",
   "Reflected XSS: check for CSP header, HttpOnly cookie flag. No CSP = higher impact. Test cookie theft feasibility.",
   "technical","Reflected XSS in `q` parameter. No CSP. HttpOnly not set on session cookie. Impact: session hijacking possible."),

_e("Reflect on failed phishing simulation — email blocked by gateway",
   ["Phishing emails caught by email gateway","Need to analyze gateway rules","Adjust template and resend"],
   ["Analyze gateway logs","Modify email template","Test delivery","Document gateway capabilities"],
   ["Review gateway quarantine logs","Identify triggering rules","Modify headers and content","Retest delivery"],
   [("gophish","phishing campaign management"),("swaks","test email delivery")],
   "Email gateway caught initial template. Analyzing blocked rules improved bypass rate from 0% to 40%. Gateway effectively blocking obvious phishing.",
   "Email gateway blocks: suspicious links, mismatched From/Reply-To, certain file types. Test delivery before campaign launch.",
   "analytical","Initial phishing template blocked 100%. After header adjustment and link modification: 40% delivery. Gateway rules documented for blue team."),

_e("Reflect on wireless assessment with WPA2 Enterprise",
   ["WPA2 Enterprise uses RADIUS authentication","Cannot capture handshake like personal","Evil twin attack for credential capture"],
   ["Set up evil twin AP","Capture RADIUS credentials","Analyze certificate validation"],
   ["Create rogue AP with hostapd-wpe","Wait for client connection","Capture MSCHAPv2 challenge","Crack offline with hashcat"],
   [("hostapd_wpe","rogue AP for enterprise capture"),("hashcat","crack MSCHAPv2 offline")],
   "Enterprise WPA2 more complex than personal. MSCHAPv2 crackable offline. Certificate validation bypass key vulnerability.",
   "WPA2-Enterprise: evil twin captures MSCHAPv2. Hashcat mode 5500 for NetNTLMv1. Weak passwords crack quickly.",
   "technical","WPA2-Enterprise assessment. Evil twin captured MSCHAPv2 hash. Cracked in 4hrs with hashcat mode 5500. Root cause: no certificate pinning."),

_e("Reflect on incident response for ransomware attack",
   ["Ransomware detected on 3 workstations","Spread vector via SMB","Immediate containment needed"],
   ["Isolate affected systems","Identify patient zero","Preserve evidence","Begin recovery"],
   ["Network isolation of affected VLANs","Capture memory dumps","Analyze ransomware sample","Restore from clean backups"],
   [("volatility","memory forensics"),("wireshark","network traffic analysis")],
   "Rapid containment limited spread to 3 systems. Patient zero identified via firewall logs. Backups allowed 4hr recovery time.",
   "Ransomware IR: isolate first, then investigate. Check SMB traffic for lateral spread. Clean backups essential for recovery.",
   "professional","Ransomware IR complete. 3 systems affected. Contained in 45min. Patient zero: workstation-07 via phishing email. Recovery: 4hrs from backup."),

_e("Reflect on API security test revealing IDOR vulnerability",
   ["API used sequential user IDs","Changing ID parameter accessed other user data","No authorization check on object access"],
   ["Test ID manipulation","Access other user records","Document exposure scope","Report IDOR"],
   ["Login as user A","Access /api/user/123","Change to /api/user/124","Confirm unauthorized access","Document all accessible endpoints"],
   [("burpsuite","intercept API requests"),("postman","systematic API testing")],
   "IDOR found on multiple endpoints. Sequential IDs made exploitation trivial. All user data accessible. Critical finding.",
   "IDOR pattern: sequential IDs + no object-level auth. Test all ID parameters. Check GET, PUT, DELETE methods.",
   "concise","**IDOR Vulnerability**\nEndpoint: `/api/user/{id}`\nImpact: All user data accessible\nMethod: Change numeric ID\nFix: Object-level authorization check"),

_e("Reflect on container escape attempt in Docker environment",
   ["Container running as root","Docker socket mounted inside container","Possible escape via socket"],
   ["Check container privileges","Test Docker socket access","Attempt host access"],
   ["Check if root in container","ls /var/run/docker.sock","docker run -v /:/host alpine chroot /host","Access host filesystem"],
   [("docker","container management for escape"),("chroot","filesystem pivot to host")],
   "Container escape successful via mounted Docker socket. Host filesystem fully accessible. Critical infrastructure vulnerability.",
   "Docker socket mount = container escape. Check: ls /var/run/docker.sock. Escape: mount host / and chroot.",
   "technical","Container escape via Docker socket. Socket mounted at /var/run/docker.sock. Full host access achieved. Fix: Never mount Docker socket in containers."),

_e("Reflect on AD assessment finding Kerberoastable accounts",
   ["Service accounts with SPNs found","TGS tickets requested for offline cracking","Weak passwords on service accounts"],
   ["Enumerate SPNs","Request TGS tickets","Extract hashes","Attempt offline crack"],
   ["GetUserSPNs.py to enumerate","Request all TGS tickets","Extract hashes to file","Hashcat attack mode 13100"],
   [("impacket","GetUserSPNs for Kerberoasting"),("hashcat","crack Kerberos TGS hashes")],
   "5 Kerberoastable accounts found. 2 cracked in under 1hr. Service accounts had weak passwords. High severity finding.",
   "Kerberoasting: GetUserSPNs finds targets. Hashcat mode 13100 for TGS. Service accounts often have weak passwords.",
   "analytical","Kerberoasting results: 5 SPNs found, 2 cracked (svc_backup: 'Service123!', svc_sql: 'Summer2023'). Recommend: Use gMSA for service accounts."),

_e("Reflect on web app assessment with WAF bypass needed",
   ["WAF blocking common SQLi payloads","Need to encode/obfuscate payloads","Test WAF bypass techniques"],
   ["Identify WAF type","Test bypass techniques","Find working payload","Document bypass method"],
   ["Fingerprint WAF via response headers","Test URL encoding bypass","Try comment injection","Use sqlmap with tamper scripts"],
   [("sqlmap","SQLi with tamper scripts"),("wafw00f","WAF fingerprinting")],
   "WAF identified as Cloudflare. URL encoding bypass ineffective. Comment injection worked. Tamper script 'space2comment' successful.",
   "WAF bypass: try space2comment, between, charunicodeescape. Identify WAF first with wafw00f before testing bypasses.",
   "technical","WAF bypass achieved. WAF: Cloudflare. Working bypass: comment injection (space2comment tamper). SQLi confirmed after bypass."),

_e("Reflect on mobile app assessment finding hardcoded credentials",
   ["APK decompiled successfully","Found hardcoded API key in source","Key still active on production"],
   ["Decompile APK","Search for secrets","Test credentials","Report severity"],
   ["jadx -d app.apk","grep -r 'api_key\\|password\\|secret'","Test key against API","Document exposure"],
   [("jadx","APK decompilation"),("apktool","APK resource extraction")],
   "Hardcoded API key found in BuildConfig class. Key grants admin API access. Critical severity. Immediate rotation required.",
   "Mobile hardcoded secrets: decompile APK with jadx, search source for key patterns. Check BuildConfig and string resources.",
   "concise","**Hardcoded Credentials**\nFile: `BuildConfig.java`\nValue: `API_KEY = 'sk-admin-xxxxx'`\nImpact: Full admin API access\nFix: Move to secure remote config"),

_e("Reflect on network segmentation bypass via VLAN hopping",
   ["Network used 802.1Q trunking","Switch misconfigured with native VLAN","VLAN hopping via double tagging possible"],
   ["Test native VLAN config","Craft double-tagged frame","Access restricted VLAN","Document path"],
   ["Identify native VLAN","Craft 802.1Q double-tagged frame","Send to switch","Capture traffic from target VLAN"],
   [("scapy","craft custom 802.1Q frames"),("wireshark","capture VLAN traffic")],
   "VLAN hopping successful. Native VLAN 1 misconfiguration allowed double-tagging attack. Accessed finance VLAN from guest network.",
   "VLAN hopping: requires native VLAN match. Double-tag technique. Switch port must not be in access mode for exploitation.",
   "technical","VLAN hopping confirmed. Native VLAN: 1. Target VLAN: 10 (finance). Method: double-tagging. Fix: Change native VLAN to unused VLAN ID."),

_e("Reflect on threat hunting exercise finding C2 beacon",
   ["Unusual outbound traffic pattern noticed","Beaconing every 30 seconds to unknown IP","Process: svchost.exe making HTTP requests"],
   ["Analyze traffic pattern","Identify source process","Extract C2 indicators","Block and investigate"],
   ["Filter traffic by destination","Check process tree","Extract HTTP headers","Analyze beacon timing","Block C2 IP"],
   [("wireshark","network traffic analysis"),("volatility","process memory analysis")],
   "C2 beacon identified via traffic timing analysis. svchost.exe making 30s interval HTTP GET to 185.x.x.x. Malware injected into legitimate process.",
   "C2 detection: look for regular interval outbound connections. Check User-Agent strings. Analyze process making connections.",
   "professional","C2 beacon detected. Process: svchost.exe (PID 1234). Destination: 185.x.x.x:443. Interval: 30s. Protocol: HTTPS with custom User-Agent. Blocked at firewall."),

_e("Reflect on password audit revealing weak password policy",
   ["Dumped NTLM hashes from AD","Cracked 60% within 1 hour","Common patterns: seasons+year"],
   ["Analyze cracked passwords","Identify patterns","Recommend policy changes","Document statistics"],
   ["hashcat with rockyou.txt","Apply rule files","Analyze cracked passwords for patterns","Generate statistics report"],
   [("hashcat","password cracking with rules"),("pypykatz","NTLM hash extraction analysis")],
   "60% crack rate in 1hr reveals weak policy. Top patterns: Summer2023, Winter2024, Company123. Policy must enforce complexity.",
   "Password audit: crack rate >30% = weak policy. Common patterns: seasons, company name, years. Recommend passphrase policy.",
   "analytical","Password audit: 847 hashes, 508 cracked (60%). Top passwords: 'Summer2023' (47), 'Winter2024' (31). Recommend: 15-char minimum, passphrase policy."),

_e("Reflect on physical security assessment — tailgating success",
   ["No turnstile or badge enforcement at side entrance","Followed employee through secure door","Reached server room without challenge"],
   ["Test physical controls","Document gaps","Photograph evidence","Report findings"],
   ["Attempt tailgating at main entrance","Test side entrances","Try reaching restricted areas","Document each attempt result"],
   [("camera","evidence documentation"),("access_log","badge access records")],
   "Tailgating successful at side entrance. Reached server room. No challenge by any employee. Physical controls insufficient.",
   "Physical pentest: tailgating usually works at side doors. Employees rarely challenge. Server rooms often reachable without badge.",
   "professional","Physical assessment: Tailgating successful at Building B side entrance. Server room accessed without badge or challenge. 3 of 5 employees held door open."),

_e("Reflect on source code review finding command injection",
   ["PHP application using shell_exec() with user input","No input sanitization","Direct OS command execution possible"],
   ["Identify dangerous functions","Trace input flow","Confirm injection","Document PoC"],
   ["Search for shell_exec, system, exec calls","Trace parameter to function","Craft injection payload","Confirm execution"],
   [("semgrep","static analysis for dangerous functions"),("burpsuite","confirm injection in running app")],
   "Command injection in file conversion feature. User filename passed directly to shell_exec. RCE confirmed with ; whoami payload.",
   "Code review: search for shell_exec, system(), exec(), passthru(). Trace all user inputs to these functions.",
   "technical","Command injection in /convert endpoint. `filename` parameter → `shell_exec('convert '.$filename)`. PoC: `file.jpg; id` returns www-data."),

_e("Reflect on crypto assessment finding weak cipher usage",
   ["Application using MD5 for password hashing","No salt used","Rainbow table attack feasible"],
   ["Identify hashing algorithm","Confirm no salt","Test rainbow table attack","Recommend bcrypt"],
   ["Review hashing code","Test known MD5 hash","Confirm lookup table success","Document weakness"],
   [("hashcat","rainbow table and wordlist attack"),("john","hash identification and cracking")],
   "MD5 without salt cracked instantly via rainbow table. Entire password database at risk. Critical cryptographic weakness.",
   "Weak crypto: MD5/SHA1 for passwords = critical. Always check for salt. Rainbow tables break unsalted MD5 in seconds.",
   "concise","**Weak Password Hashing**\nAlgorithm: MD5 (no salt)\nCrack time: <1 second via rainbow table\nFix: Use bcrypt/Argon2 with salt"),

_e("Reflect on log analysis during incident investigation",
   ["Suspicious login from unusual country","Multiple failed attempts before success","Credential stuffing pattern"],
   ["Analyze auth logs","Identify attack timeline","Correlate with other logs","Determine scope"],
   ["Parse auth.log for failed logins","Identify source IPs","Check successful login times","Correlate with file access logs"],
   [("splunk","log analysis and correlation"),("python","log parsing script")],
   "Credential stuffing attack from 47 IPs over 6 hours. 3 accounts compromised. Data accessed: customer records. Attack started at 02:00 UTC.",
   "Credential stuffing: distributed IPs, high volume failed logins. Check for successful logins after failures from same IP.",
   "analytical","Credential stuffing attack. Duration: 6hrs. Source IPs: 47. Compromised: 3 accounts. Data accessed: customer_data table (2,400 records)."),

_e("Reflect on DNS reconnaissance revealing internal infrastructure",
   ["Zone transfer allowed on DNS server","Exposed internal hostnames and IPs","Dev and staging servers revealed"],
   ["Test zone transfer","Document internal hosts","Map internal network","Report misconfiguration"],
   ["dig axfr @ns1.target.com target.com","Document all records","Identify sensitive hostnames","Map to IP ranges"],
   [("dig","DNS zone transfer"),("dnsrecon","comprehensive DNS enumeration")],
   "Zone transfer exposed 147 internal DNS records. Dev servers, internal tools, and backup systems revealed. Critical information disclosure.",
   "DNS zone transfer: always test with dig axfr. Reveals internal infrastructure. Fix: restrict zone transfers to authorized secondaries.",
   "professional","DNS zone transfer allowed. Records exposed: 147. Notable: dev.internal, backup.internal, vpn.internal. IP range: 10.0.0.0/8 mapped."),

_e("Reflect on lateral movement via pass-the-hash",
   ["NTLM hash obtained from lsass dump","Used hash to authenticate without plaintext","Accessed multiple systems"],
   ["Extract NTLM hash","Test hash on other systems","Map accessible systems","Document lateral movement path"],
   ["mimikatz sekurlsa::logonpasswords","Test hash with pth-winexe","Access systems","Document each hop"],
   [("mimikatz","extract NTLM hashes"),("impacket","pass-the-hash with psexec.py")],
   "PTH successful across 8 systems. Admin reuse of same local admin hash enabled wide lateral movement. Critical finding.",
   "Pass-the-hash: extract NTLM from lsass, use with psexec/wmiexec/smbexec. Local admin hash reuse common in enterprises.",
   "technical","Pass-the-hash: Used admin NTLM hash across 8 systems. Same local admin password across all workstations. LAPS not deployed."),

_e("Reflect on successful social engineering via vishing",
   ["Called help desk posing as IT","Requested password reset for target account","Help desk complied without verification"],
   ["Prepare pretext","Call target","Request sensitive action","Document response"],
   ["Research target employee","Prepare IT pretext script","Call help desk","Request account action","Log outcome"],
   [("osint","research target employee details"),("phone","vishing call")],
   "Help desk reset password without identity verification. Social engineering successful. Training gap identified.",
   "Vishing: help desk often weakest link. Pretext as IT/HR effective. Test verification procedures during assessment.",
   "professional","Vishing success. Help desk reset password for 'jsmith' without verification. Pretext: IT support needing urgent access. Time to success: 3 minutes."),

_e("Reflect on buffer overflow exploitation in legacy service",
   ["Service running vulnerable strcpy","Calculated offset to EIP","Shellcode executed successfully"],
   ["Fuzz to find crash point","Calculate EIP offset","Find bad chars","Locate return address","Generate shellcode"],
   ["Fuzz with increasing input","Use pattern_create for offset","Test bad characters","Find JMP ESP","Generate shellcode with msfvenom"],
   [("gdb","debugging and offset calculation"),("msfvenom","shellcode generation")],
   "BOF exploited on legacy FTP service. 1024-byte buffer, offset at 992. JMP ESP in non-ASLR DLL. Stable shell obtained.",
   "BOF: fuzz → find crash → pattern_create offset → bad chars → JMP ESP → shellcode. Check ASLR/DEP status first.",
   "technical","BOF exploitation: Buffer size 1024, EIP offset 992. Return addr: 0x625011af (JMP ESP in ftpd.dll). Shellcode: bind shell port 4444."),

_e("Reflect on forensics investigation of compromised server",
   ["Server showing unusual outbound traffic","Suspected backdoor installed","Full disk image acquired"],
   ["Acquire disk image","Analyze running processes","Check persistence mechanisms","Identify malware"],
   ["dd for disk image","Analyze with Autopsy","Check startup items","Examine web shell locations","Extract malware"],
   [("autopsy","forensic disk analysis"),("volatility","memory forensics")],
   "Web shell found in /var/www/html/images/. PHP backdoor using base64 encoding. Installed 3 weeks prior via vulnerable upload function.",
   "Forensics: check web shells in image upload directories. Common names: shell.php, cmd.php, img_upload.php. Base64 encoded payloads.",
   "analytical","Compromise forensics: Web shell at /var/www/html/images/thumb_cache.php. Installed: 2024-01-15. Persistence: cron job every 5min calling shell."),

_e("Reflect on JWT token vulnerability exploitation",
   ["JWT using 'none' algorithm accepted","Server not validating signature","Forged tokens accepted"],
   ["Decode JWT","Test algorithm confusion","Forge token","Escalate privileges"],
   ["Decode JWT with jwt.io","Modify header to alg:none","Remove signature","Test with forged token","Access admin endpoint"],
   [("burpsuite","JWT manipulation and testing"),("jwt_tool","JWT security testing")],
   "JWT 'none' algorithm accepted. Admin token forged without knowing secret. Complete authentication bypass. Critical.",
   "JWT vulns: test alg:none, RS256→HS256 confusion, weak secrets. jwt_tool automates all JWT attacks.",
   "technical","JWT algorithm confusion: Server accepts alg:none. Forged admin token. Access: /api/admin/* all endpoints. Fix: Enforce algorithm whitelist."),

_e("Reflect on SSRF vulnerability in file import feature",
   ["File import URL accepts any URL","Internal metadata accessible via SSRF","AWS metadata leaked"],
   ["Test SSRF with internal URLs","Access cloud metadata","Extract credentials","Document impact"],
   ["Test with http://localhost","Try http://169.254.169.254/latest/meta-data/","Extract IAM role credentials","Document scope of access"],
   [("burpsuite","SSRF testing"),("curl","manual SSRF payload testing")],
   "SSRF confirmed. AWS metadata accessible. IAM role credentials extracted. EC2 instance has S3 full access policy. Critical.",
   "SSRF → cloud metadata: try 169.254.169.254 for AWS, 169.254.169.254/metadata for Azure. Extract IAM credentials.",
   "concise","**SSRF → Cloud Metadata**\nEndpoint: `/import?url=`\nPayload: `http://169.254.169.254/latest/meta-data/iam/`\nResult: IAM role credentials extracted"),

_e("Reflect on XXE injection in XML processing endpoint",
   ["Application processes XML input","External entity injection possible","Internal files readable"],
   ["Test XML input handling","Inject external entity","Read internal files","Assess impact"],
   ["Send XML with DOCTYPE declaration","Define external entity pointing to /etc/passwd","Send request","Extract file contents"],
   [("burpsuite","XXE payload injection"),("xxeinjector","automated XXE testing")],
   "XXE successful. /etc/passwd readable. Tested blind XXE for internal network scanning. Server-side request forgery also possible.",
   "XXE: inject DOCTYPE with SYSTEM entity. Try /etc/passwd, /etc/shadow, app config files. Blind XXE for internal recon.",
   "technical","XXE injection confirmed. File read: /etc/passwd, /etc/hosts. Internal network revealed: 10.0.1.0/24 range. Blind XXE SSRF also works."),

_e("Reflect on insecure deserialization exploitation",
   ["Java application deserializing user data","Ysoserial gadget chain applicable","RCE achieved via deserialization"],
   ["Identify serialization format","Test with ysoserial payload","Confirm RCE","Escalate access"],
   ["Identify Java serialized objects (AC ED 00 05)","Generate ysoserial payload","Base64 encode","Send in request","Confirm execution"],
   [("ysoserial","Java deserialization gadget chains"),("burpsuite","intercept and modify requests")],
   "Insecure Java deserialization. CommonsCollections6 gadget chain worked. RCE as tomcat user. Webshell deployed for persistence.",
   "Java deserialization: look for AC ED 00 05 bytes. Try ysoserial with CommonsCollections, Spring, Groovy gadget chains.",
   "analytical","Deserialization RCE: Java object in viewState parameter. Gadget: CommonsCollections6. Execution: `id` → tomcat. Webshell uploaded."),

_e("Reflect on OAuth 2.0 misconfiguration allowing account takeover",
   ["OAuth redirect_uri not strictly validated","Wildcard domain accepted","Authorization code interceptable"],
   ["Test redirect_uri validation","Craft malicious redirect","Capture auth code","Exchange for token"],
   ["Test various redirect_uri values","Try open redirect on target domain","Capture authorization code","Exchange code for access token"],
   [("burpsuite","OAuth flow interception"),("python","OAuth token exchange script")],
   "OAuth redirect_uri wildcard allowed code theft. Account takeover via code interception. All user accounts potentially affected.",
   "OAuth vulns: test redirect_uri with partial matches, wildcard domains. Capture code via open redirect on allowed domain.",
   "professional","OAuth account takeover: redirect_uri accepts *.target.com. Open redirect at target.com/redirect?url= captured auth code. Full ATO achieved."),

_e("Reflect on memory forensics revealing credential material",
   ["System memory dump acquired","Mimikatz artifacts in memory","Cleartext passwords in lsass"],
   ["Acquire memory image","Run volatility plugins","Extract credential material","Document findings"],
   ["volatility -f mem.raw imageinfo","volatility mimikatz","volatility lsadump","Document all credentials found"],
   [("volatility","memory analysis and credential extraction"),("rekall","alternative memory forensics")],
   "5 cleartext passwords in memory. Domain admin credentials present. Credential exposure window: since last reboot (30 days).",
   "Memory forensics: volatility mimikatz plugin extracts creds directly. Check lsass.DMP if full image unavailable.",
   "technical","Memory forensics: 5 cleartext creds extracted. Including: administrator (domain admin), svc_sql (service account). Recommend: Credential Guard."),

_e("Reflect on broken access control in admin panel",
   ["Admin panel accessible without role check","Regular user cookie accepted","All admin functions available"],
   ["Test admin URL with regular user session","Enumerate admin functions","Access sensitive operations","Document scope"],
   ["Login as regular user","Navigate to /admin","Test all admin functions","Download user database","Document findings"],
   [("burpsuite","session management testing"),("ffuf","admin path enumeration")],
   "Admin panel fully accessible with regular user session. No server-side role check. 50,000 user records exported.",
   "Broken access control: always test admin paths with low-privilege sessions. Check API endpoints too, not just UI.",
   "concise","**Broken Access Control**\nPath: `/admin/`\nTest: Regular user cookie accepted\nImpact: Full admin access, 50K user records exposed"),

_e("Reflect on subdomain takeover opportunity found",
   ["DNS CNAME pointing to deprovisioned service","Azure blob storage endpoint unclaimed","Takeover possible"],
   ["Verify CNAME target","Check if target is unclaimed","Claim the service","Upload content to confirm"],
   ["dig CNAME dev.target.com","Confirm target: azureblob.windows.net","Attempt to claim storage account","Upload PoC page"],
   [("dig","DNS record enumeration"),("subfinder","subdomain discovery")],
   "Subdomain takeover on dev.target.com via unclaimed Azure Blob Storage. CNAME to target.blob.windows.net, account available.",
   "Subdomain takeover: find CNAME to unclaimed service. Common targets: Azure, AWS S3, GitHub Pages, Heroku, Fastly.",
   "professional","Subdomain takeover: dev.target.com CNAME → unclaimed Azure storage. Claimed storage account. Serving content under target domain."),

_e("Reflect on privilege escalation via scheduled task",
   ["Scheduled task running as SYSTEM","Task script in user-writable location","Script modification leads to SYSTEM"],
   ["Enumerate scheduled tasks","Check script permissions","Modify script","Wait for execution"],
   ["schtasks /query /fo LIST","icacls on task script path","Replace script with payload","Wait for scheduled execution"],
   [("schtasks","scheduled task enumeration"),("icacls","file permission checking")],
   "SYSTEM scheduled task executing script in C:\\Temp (world-writable). Modified script to add admin user. SYSTEM access obtained.",
   "Scheduled task privesc: check task script/binary paths. If writable, replace with payload. Common on Windows.",
   "technical","PrivEsc via scheduled task: Task 'Backup_Daily' runs as SYSTEM. Script: C:\\Temp\\backup.bat (Everyone:F). Modified for SYSTEM shell."),

_e("Reflect on NoSQL injection in MongoDB application",
   ["Login form vulnerable to NoSQL injection","MongoDB operator injection bypasses auth","All user data accessible"],
   ["Test NoSQL injection","Bypass authentication","Extract user data","Document vulnerability"],
   ["Test with {$ne: null} operator","Bypass login: username=admin&password[$ne]=x","Enumerate users","Document impact"],
   [("burpsuite","NoSQL injection testing"),("nosqlmap","automated NoSQL injection")],
   "NoSQL injection bypassed login. MongoDB operator injection ($ne) accepted in query. All user accounts accessible.",
   "NoSQL injection: try $ne, $gt, $regex operators. Test in JSON body and URL params. MongoDB and CouchDB most common.",
   "concise","**NoSQL Injection**\nPayload: `password[$ne]=invalid`\nResult: Login bypass as admin\nFix: Input validation, parameterized queries"),

_e("Reflect on CORS misconfiguration allowing credential theft",
   ["API reflects any Origin header","Includes Access-Control-Allow-Credentials: true","Cross-origin requests with cookies possible"],
   ["Test CORS with malicious origin","Confirm credential inclusion","PoC cross-origin request","Assess data exposure"],
   ["Send request with Origin: https://evil.com","Check if reflected in response","Test with credentials","Confirm data returned"],
   [("burpsuite","CORS testing"),("corsy","automated CORS misconfiguration scanner")],
   "CORS reflects arbitrary origins with credentials. Any website can make authenticated API requests on behalf of victim.",
   "CORS: check if Origin reflected + credentials allowed. Critical if API returns sensitive data. PoC HTML page as evidence.",
   "technical","CORS misconfiguration: Reflects arbitrary Origin + Allow-Credentials: true. Any attacker site can read authenticated API responses."),

_e("Reflect on path traversal vulnerability in file download",
   ["File download uses filename parameter","No sanitization of ../sequences","System files readable"],
   ["Test path traversal","Read system files","Determine depth","Document sensitive files accessed"],
   ["Test /download?file=../../../etc/passwd","Try URL encoding: %2e%2e%2f","Access sensitive files","Document all readable paths"],
   [("burpsuite","path traversal testing"),("dotdotpwn","path traversal fuzzer")],
   "Path traversal confirmed. /etc/passwd, /etc/shadow, application config files readable. Web server private key accessible.",
   "Path traversal: test ../, ..\\, %2e%2e%2f, ..%252f. Try double encoding. Common targets: /etc/passwd, app configs, private keys.",
   "professional","Path traversal: `/download?file=../../../etc/shadow` returns /etc/shadow. Also readable: /var/www/config.php (DB credentials)."),

_e("Reflect on business logic flaw in e-commerce application",
   ["Negative quantity accepted in cart","Price calculation vulnerable","Free goods obtained"],
   ["Test boundary values","Enter negative quantity","Check calculation","Document exploitation"],
   ["Add item to cart","Change quantity to -1","Check if credit applied","Complete purchase with negative total"],
   [("burpsuite","intercept and modify cart requests"),("postman","API business logic testing")],
   "Negative quantity accepted. Cart total became negative = store credit applied. Items obtained for free plus credit earned.",
   "Business logic: test negative values, max integer, zero, decimal quantities. Check price manipulation, coupon stacking.",
   "analytical","Business logic flaw: Negative quantity (-1) in cart reduces total. Order with qty=-100 → store credit of $9,999. Fix: Validate qty > 0 server-side."),

_e("Reflect on HTTP request smuggling attack",
   ["Front-end uses Content-Length, back-end uses Transfer-Encoding","CL.TE smuggling possible","Requests can be poisoned"],
   ["Test smuggling technique","Confirm discrepancy","Poison next request","Access restricted path"],
   ["Send CL.TE probe request","Confirm timing attack","Smuggle HEAD request to /admin","Capture next user's request"],
   [("burpsuite","HTTP request smuggling testing"),("turbo_intruder","timing-based smuggling detection")],
   "CL.TE request smuggling confirmed. Next user's request captured including their session cookie. Admin panel accessible.",
   "Request smuggling: CL.TE or TE.CL discrepancy. Use Burp HTTP Request Smuggler extension. Timing-based detection.",
   "technical","HTTP smuggling: CL.TE type. Poisoned next request, captured session cookie of admin user. Achieved admin access."),

_e("Reflect on race condition in payment processing",
   ["Payment applied once but race allows multiple uses","Concurrent requests exploit TOCTOU","Balance exceeded limits"],
   ["Identify TOCTOU window","Send concurrent requests","Confirm balance manipulation","Document impact"],
   ["Identify check-then-act pattern","Use Turbo Intruder for parallel requests","Send 20 simultaneous requests","Check balance after race"],
   [("burpsuite_turbo","race condition exploitation"),("python","concurrent request script")],
   "Race condition allowed $10 coupon to be applied 15 times simultaneously. Financial impact: $150 loss per race window.",
   "Race conditions: payment, voting, inventory. Use parallel requests. Window often milliseconds. Turbo Intruder best tool.",
   "professional","Race condition in coupon application. Concurrent requests: 20. Successful duplications: 15. Fix: Atomic DB transaction with row locking."),

_e("Reflect on prototype pollution in JavaScript application",
   ["Node.js application vulnerable to prototype pollution","__proto__ property accepted in JSON","Object.prototype modified"],
   ["Test prototype pollution","Modify Object.prototype","Check impact","Escalate to RCE"],
   ["Send JSON with __proto__","Check if property added to all objects","Attempt RCE via template engines","Document exploitation"],
   [("burpsuite","prototype pollution payload injection"),("nodejs_audit","Node.js security analysis")],
   "Prototype pollution confirmed. Object.prototype.admin=true granted admin access. Template engine RCE also achieved.",
   "Prototype pollution: test __proto__, constructor.prototype in JSON. Check for admin bypass, DoS, RCE via template engines.",
   "technical","Prototype pollution: `{\"__proto__\":{\"admin\":true}}` adds admin property globally. Pug template RCE via polluted options."),

_e("Reflect on GraphQL introspection revealing hidden fields",
   ["GraphQL introspection enabled in production","Hidden admin fields exposed","Sensitive mutations accessible"],
   ["Query introspection","Map schema","Find hidden types","Test sensitive operations"],
   ["Send __schema query","Map all types and fields","Find admin mutations","Test deleteUser, resetAllPasswords"],
   [("burpsuite","GraphQL introspection queries"),("graphql_map","GraphQL schema analysis")],
   "Introspection revealed admin mutations not shown in UI. deleteUser, massResetPassword accessible without authorization.",
   "GraphQL: always query __schema in testing. Look for admin types, hidden mutations. Test each with low-privilege token.",
   "concise","**GraphQL Exposure**\nIntrospection: Enabled\nHidden: `deleteUser`, `adminReset` mutations\nAccess: No auth required\nFix: Disable introspection in prod"),

_e("Reflect on open redirect leading to phishing",
   ["Redirect URL parameter not validated","Arbitrary external redirect possible","Phishing URL uses trusted domain"],
   ["Confirm open redirect","Craft phishing URL","Test redirect chain","Assess phishing risk"],
   ["Test /redirect?url=https://evil.com","Confirm redirect occurs","Build convincing phishing URL","Document PoC"],
   [("burpsuite","redirect parameter testing"),("ffuf","redirect parameter discovery")],
   "Open redirect confirmed. Phishing URL uses trusted domain: target.com/redirect?url=evil.com. Bypasses email filters.",
   "Open redirect: test url=, redirect=, next=, return= parameters. High value for phishing, OAuth bypass, SSRF chain.",
   "professional","Open redirect at /sso/redirect?next=. Phishing URL: https://target.com/sso/redirect?next=https://evil.com. Email gateway bypass confirmed."),
]

MEMORY_DATA = [
_e("Store reconnaissance findings for target network",
   ["Network range identified","Services enumerated","Open ports mapped"],
   ["Record findings systematically","Cross-reference with threat intelligence","Update attack surface map"],
   ["Document IP ranges","Record open ports and services","Note OS fingerprints","Store for reference during engagement"],
   [("nmap","network reconnaissance"),("shodan","internet exposure check")],
   "Reconnaissance phase complete. Network map built. Key targets identified for next phase.",
   "Target: 192.168.1.0/24. Open: 22,80,443,3306,8080. OS: Ubuntu 20.04 (web), Windows 2019 (DC). Key target: DC at 192.168.1.10.",
   "structured","**Recon Memory**\n- Range: 192.168.1.0/24\n- DC: 192.168.1.10 (Windows Server 2019)\n- Web: 192.168.1.20 (Apache 2.4.41)\n- DB: 192.168.1.30 (MySQL 8.0)"),

_e("Remember valid credentials found during assessment",
   ["Credentials discovered via various methods","Need to track for later phases","Organize by privilege level"],
   ["Categorize by system","Note privilege level","Track source of discovery","Plan usage strategy"],
   ["Log all discovered credentials","Categorize as user/admin/service","Note which systems they work on","Plan lateral movement"],
   [("keepass","secure credential storage"),("mimikatz","credential extraction tool")],
   "Credential inventory maintained. Clear picture of access levels. Enables efficient lateral movement planning.",
   "Creds found: admin:Admin123! (web panel), jsmith:Password1 (VPN), svc_sql:SqlPass99 (DB). Admin creds = highest priority.",
   "structured","**Credential Memory**\n| User | Pass | System | Level |\n|------|------|--------|-------|\n| admin | Admin123! | WebPanel | Admin |\n| jsmith | Password1 | VPN | User |"),

_e("Track exploitation attempts and results",
   ["Multiple exploits attempted","Results vary by target","Need to track what worked where"],
   ["Log each attempt","Record success/failure","Note system responses","Avoid repeating failed attempts"],
   ["Document exploit name and target","Record payload used","Note result and access obtained","Plan next steps"],
   [("metasploit","exploit framework"),("burpsuite","web exploitation")],
   "Exploitation log maintained. Clear record prevents duplicate attempts. Documents successful attack paths.",
   "Exploit log: ms17-010 → success on 192.168.1.15 (SYSTEM). EternalBlue → failed on 192.168.1.20 (patched). Web SQLi → user-level on .25.",
   "technical","**Exploit Memory**\n- EternalBlue: 192.168.1.15 ✅ SYSTEM access\n- Apache Struts: 192.168.1.20 ❌ patched\n- SQLi: 192.168.1.25 ✅ user-level"),

_e("Remember network topology discovered during engagement",
   ["Internal network structure mapped","VLAN segmentation identified","Trust relationships documented"],
   ["Map network segments","Document VLAN structure","Note firewall placement","Identify trust paths"],
   ["Build network diagram","Note gateway IPs","Document routing","Identify potential pivot points"],
   [("nmap","network mapping"),("netdiscover","ARP-based host discovery")],
   "Network topology stored. VLAN structure understood. Pivot paths identified for next phase.",
   "Topology: VLAN10=DMZ(192.168.10.0/24), VLAN20=Corp(10.0.0.0/24), VLAN30=Mgmt(172.16.0.0/24). FW between DMZ↔Corp.",
   "structured","**Network Memory**\n- DMZ: 192.168.10.0/24 (VLAN10)\n- Corporate: 10.0.0.0/24 (VLAN20)\n- Management: 172.16.0.0/24 (VLAN30)\n- Firewall: 192.168.10.1"),

_e("Store indicators of compromise from incident investigation",
   ["IOCs collected from compromised systems","Need for threat hunting across network","Share with security team"],
   ["Catalog all IOCs","Categorize by type","Generate STIX format","Share with team"],
   ["Extract file hashes","Record malicious IPs","Document malicious domains","Create IOC list","Share with SIEM"],
   [("volatility","extract IOCs from memory"),("yara","scan for IOC patterns")],
   "IOC list compiled. Ready for threat hunting. SIEM rules created from IOCs.",
   "IOCs: MD5 a1b2c3... (malware), IP 185.x.x.x (C2), domain evil-c2.com, mutex GlobalMalwareMutex, reg key HKLM\\..\\Run\\Updater.",
   "professional","**IOC Memory**\n- File hash: a1b2c3d4e5f6... (trojan.exe)\n- C2 IP: 185.220.101.x\n- C2 Domain: update-service.net\n- Mutex: Global\\SystemMon32"),

_e("Track AD domain information gathered",
   ["Domain structure enumerated","User accounts discovered","Group memberships mapped"],
   ["Document domain info","Map privileged groups","Note service accounts","Identify attack paths"],
   ["BloodHound collection","Document domain name","Map admin accounts","Note Kerberoastable accounts"],
   [("bloodhound","AD attack path analysis"),("ldapdomaindump","AD enumeration")],
   "AD information stored. Attack paths identified via BloodHound. Kerberoastable targets noted.",
   "Domain: CORP.LOCAL. DA: 3 accounts. Kerberoastable: svc_backup, svc_sql. Path to DA: via svc_backup (weak password).",
   "structured","**AD Memory**\n- Domain: CORP.LOCAL\n- Domain Admins: administrator, adminuser, svc_admin\n- Kerberoastable: svc_backup, svc_sql\n- Path to DA: Kerberoast svc_backup"),

_e("Remember web application structure and endpoints",
   ["Application endpoints mapped","Authentication mechanism identified","API structure documented"],
   ["Document all endpoints","Note auth requirements","Map API structure","Identify interesting parameters"],
   ["Spider application","Document endpoint list","Note authentication type","Map API endpoints","Identify IDOR opportunities"],
   [("burpsuite","web application mapping"),("ffuf","endpoint discovery")],
   "Web application structure stored. All endpoints documented. Testing priorities set.",
   "App: Laravel. Auth: JWT. Endpoints: /api/v1/users, /api/v1/admin (interesting!), /api/v1/files. IDOR potential on /users/{id}.",
   "technical","**Web App Memory**\n- Framework: Laravel 9\n- Auth: JWT (RS256)\n- Key endpoints: /api/v1/admin, /api/v1/users/{id}\n- Interesting: admin endpoint with no auth check"),

_e("Store cloud environment findings",
   ["AWS environment assessed","Misconfigured services found","IAM permissions excessive"],
   ["Document AWS account structure","Note misconfigured services","Map IAM roles","Identify privilege escalation paths"],
   ["AWS CLI enumeration","Document S3 buckets","Check IAM roles","Note Lambda functions","Map account structure"],
   [("aws_cli","cloud enumeration"),("pacu","AWS exploitation framework")],
   "Cloud environment documented. Misconfigurations catalogued. IAM escalation path identified.",
   "AWS: Account 123456789. Buckets: 3 public (backup-data, dev-files, logs). IAM: svc-user has iam:PassRole + ec2:RunInstances = privesc.",
   "structured","**Cloud Memory**\n- Account: 123456789\n- Public S3: backup-data, dev-files\n- IAM Privesc: svc-user → iam:PassRole + ec2:RunInstances\n- Region: us-east-1"),

_e("Track vulnerability scan results by severity",
   ["Vulnerability scan completed","Results need organization","Priority order needed for exploitation"],
   ["Organize by CVSS score","Group by system","Note exploitability","Create attack priority list"],
   ["Export scan results","Filter by severity","Group by target","Create prioritized list","Plan exploitation order"],
   [("nessus","vulnerability scanning"),("openvas","open source vulnerability scanner")],
   "Vulnerability inventory organized. Critical findings prioritized. Exploitation plan created.",
   "Crits: CVE-2017-0144 (EternalBlue) on .15, CVE-2021-44228 (Log4Shell) on .20. High: 5 findings. Medium: 12. Total: 23 vulns.",
   "analytical","**Vuln Memory**\n| CVE | Target | CVSS | Status |\n|-----|--------|------|--------|\n| CVE-2017-0144 | .15 | 9.8 | Exploited |\n| CVE-2021-44228 | .20 | 10.0 | Testing |"),

_e("Remember persistence mechanisms established",
   ["Multiple persistence mechanisms installed","Need to track for cleanup","Document for report"],
   ["Log each persistence mechanism","Note location and method","Plan removal at end","Document for report"],
   ["Document backdoor locations","Note scheduled tasks created","Record registry keys added","Plan cleanup procedure"],
   [("metasploit","persistence module"),("schtasks","Windows scheduled task")],
   "Persistence inventory complete. Cleanup plan ready. All mechanisms documented for report.",
   "Persistence: webshell /var/www/html/img/cache.php, schtask 'Windows Update' (SYSTEM), reg HKLM\\Run\\SvcHost32, cron @reboot /tmp/.x.",
   "structured","**Persistence Memory**\n- Webshell: /var/www/html/img/cache.php\n- Task: 'Windows Update' runs payload.exe\n- Registry: HKLM\\Run\\SvcHost32\n- Cron: @reboot callback"),

_e("Store network traffic patterns observed",
   ["Network traffic analyzed","Anomalous patterns identified","Baseline established"],
   ["Document normal traffic patterns","Note anomalies","Identify C2 patterns","Create detection signatures"],
   ["Capture baseline traffic","Identify protocols in use","Note unusual connections","Document C2 communication pattern"],
   [("wireshark","packet capture and analysis"),("zeek","network traffic analysis")],
   "Traffic baseline stored. Anomalies documented. Detection signatures created for SIEM.",
   "Normal: DNS to 8.8.8.8, HTTPS to known CDNs. Anomaly: port 4444 TCP to 185.x.x.x every 60s. C2 pattern identified.",
   "technical","**Traffic Memory**\n- Baseline: HTTP/HTTPS to CDNs, DNS to 8.8.8.8\n- Anomaly: TCP 4444 → 185.x.x.x every 60s\n- C2 signature: User-Agent 'Mozilla/5.0 (custom)'"),

_e("Track lateral movement paths through network",
   ["Multiple systems compromised","Movement paths documented","Trust relationships exploited"],
   ["Map movement path","Document each hop","Note access levels","Identify dead ends"],
   ["Document each system hopped","Note technique used","Record access level","Map full path from entry to target"],
   [("mimikatz","credential harvesting for lateral movement"),("impacket","lateral movement tools")],
   "Lateral movement path documented. Complete kill chain from initial access to domain admin recorded.",
   "Path: phishing → workstation01 (user) → workstation03 via PTH (admin) → fileserver via PsExec (admin) → DC via Kerberoast (DA).",
   "professional","**Lateral Movement Memory**\n1. Phishing → WS01 (user)\n2. PTH admin hash → WS03 (local admin)\n3. PsExec → FileServer (domain admin)\n4. Kerberoast → DC (domain admin)"),

_e("Remember social engineering pretext used",
   ["Social engineering scenarios prepared","Results documented","Effectiveness measured"],
   ["Document pretexts used","Record success rates","Note which employees were targeted","Document verification failures"],
   ["Log each SE attempt","Record pretext used","Note success/failure","Document what worked and why"],
   [("gophish","phishing campaign tracking"),("phone","vishing attempts")],
   "Social engineering effectiveness documented. Successful pretexts recorded for training purposes.",
   "SE results: IT helpdesk pretext → 3/5 password resets without verification. Delivery pretext → 2/3 physical access. Phishing: 23% click rate.",
   "analytical","**SE Memory**\n- IT pretext: 60% success (help desk)\n- Delivery: 67% success (physical)\n- Phishing CTR: 23% (industry avg: 15%)\n- Best pretext: urgency + IT authority"),

_e("Store findings from wireless assessment",
   ["Wireless networks discovered","Security configs assessed","Attack paths identified"],
   ["Document all SSIDs","Note encryption type","Record signal strength","Identify attack opportunities"],
   ["airodump-ng scan results","Document SSID/BSSID/encryption","Note client devices","Identify targets"],
   [("airodump_ng","wireless network discovery"),("kismet","wireless monitoring")],
   "Wireless environment documented. Attack targets identified. Client devices noted for deauth attacks.",
   "Networks: CORP-WiFi (WPA2-Enterprise), CORP-Guest (WPA2-Personal/weak), PRINTERS (WEP!). Clients: 47 on CORP, 12 on Guest.",
   "structured","**Wireless Memory**\n- CORP-WiFi: WPA2-Enterprise (strong)\n- CORP-Guest: WPA2-Personal (weak PSK)\n- PRINTERS: WEP (critical - deprecated)\n- Target: PRINTERS network first"),

_e("Track container and Kubernetes findings",
   ["Container environment assessed","Misconfigurations found","Escape paths identified"],
   ["Document container setup","Note privilege levels","Record escape opportunities","Map K8s RBAC"],
   ["kubectl get all","Check pod security policies","Note privileged containers","Map service account permissions"],
   [("kubectl","Kubernetes management"),("kube_hunter","Kubernetes vulnerability scanner")],
   "Container environment documented. Privilege escalation paths identified. Escape techniques noted.",
   "K8s: 3 privileged pods, hostPath mounts on 2 pods, default SA has cluster-admin, etcd unauthenticated on :2379.",
   "technical","**K8s Memory**\n- Privileged pods: 3 found\n- HostPath mount: pod/web-app\n- SA permissions: cluster-admin (default)\n- etcd: unauthenticated port 2379"),

_e("Remember application authentication weaknesses",
   ["Authentication mechanisms assessed","Weaknesses catalogued","Bypass methods identified"],
   ["Document auth type","Note weaknesses found","Record bypass techniques","Assess MFA implementation"],
   ["Test login mechanisms","Check for weak session tokens","Test MFA bypass","Document all findings"],
   [("burpsuite","authentication testing"),("hydra","credential brute force")],
   "Authentication weakness inventory complete. Bypass methods documented. Impact of each weakness assessed.",
   "Auth issues: no lockout (brute force possible), JWT with HS256 weak secret, MFA bypass via response manipulation, session no expiry.",
   "structured","**Auth Memory**\n- No lockout: brute force possible\n- JWT: HS256 weak secret (cracked)\n- MFA: bypass via response edit\n- Sessions: no expiration set"),

_e("Store malware analysis findings",
   ["Malware sample analyzed","Behavior documented","IOCs extracted"],
   ["Static analysis results","Dynamic behavior","Network indicators","Persistence mechanism"],
   ["strings analysis","IDA Pro disassembly","Cuckoo sandbox execution","Network capture during execution"],
   [("cuckoo","malware sandbox analysis"),("ida_pro","reverse engineering")],
   "Malware analysis complete. Full behavior profile created. IOCs ready for detection rules.",
   "Sample: Trojan dropper. Drops: payload.exe to %TEMP%. C2: 185.x.x.x:443 (HTTPS). Persistence: Run key. Evasion: VM check, sleep.",
   "professional","**Malware Memory**\n- Type: Trojan dropper\n- Drops: %TEMP%\\svchost32.exe\n- C2: 185.x.x.x:443\n- Persistence: HKCU\\Run\n- Evasion: VM/sandbox detection"),

_e("Track findings from code review",
   ["Source code reviewed for vulnerabilities","Critical findings documented","Remediation guidance prepared"],
   ["Document vulnerable functions","Note code location","Record vulnerability type","Prepare fix recommendation"],
   ["Document file and line number","Note vulnerability class","Assess exploitability","Provide secure code example"],
   [("semgrep","static code analysis"),("bandit","Python security linting")],
   "Code review findings documented with locations. Ready for developer remediation meeting.",
   "Code vulns: sql_query.php:45 SQL injection (unsanitized), auth.py:123 hardcoded secret, file_upload.php:67 unrestricted upload.",
   "technical","**Code Review Memory**\n- SQLi: sql_query.php:45 (`$_GET['id']` in query)\n- Secret: auth.py:123 (`API_KEY = 'hardcoded'`)\n- Upload: file_upload.php:67 (no type check)"),

_e("Store incident timeline for IR report",
   ["Attack timeline reconstructed","Key events timestamped","Evidence correlated"],
   ["Order events chronologically","Correlate log sources","Identify attacker actions","Document timeline"],
   ["Correlate firewall, AD, endpoint logs","Build timeline","Identify patient zero","Document attacker dwell time"],
   [("splunk","log correlation and timeline"),("timesketch","forensic timeline analysis")],
   "Incident timeline complete. Dwell time calculated. Full attack chain reconstructed.",
   "Timeline: T-30d initial phishing, T-29d persistence, T-7d lateral movement, T-1d exfil prep, T-0 ransomware deploy. Dwell: 30 days.",
   "analytical","**IR Timeline Memory**\n- Day 1: Phishing email (user clicked)\n- Day 2: Persistence established\n- Day 23: Lateral movement to DC\n- Day 29: Data exfiltration\n- Day 30: Ransomware deployed"),

_e("Remember successful evasion techniques used",
   ["AV/EDR evasion needed during assessment","Techniques documented","Success rates recorded"],
   ["Document each evasion technique","Record against which defenses","Note success/failure","Guide future engagements"],
   ["Test payload against AV","Document detection rate","Test EDR bypass","Record what works against each product"],
   [("veil","payload evasion framework"),("shellter","PE injection tool")],
   "Evasion techniques documented. Defense capabilities assessed as part of red team engagement.",
   "Evasion results: Metasploit raw payload detected. Veil shellcode - evades Windows Defender. Process injection - evades CrowdStrike. AMSI bypass needed.",
   "structured","**Evasion Memory**\n- Meterpreter raw: ❌ detected by Defender\n- Veil shellcode: ✅ evades Defender\n- Process hollowing: ✅ evades CrowdStrike\n- AMSI bypass: required for PS scripts"),

_e("Track open ports and services across all targets",
   ["Port scan results organized","Services fingerprinted","Vulnerability surface mapped"],
   ["Organize by host","Note service versions","Identify outdated software","Prioritize attack surface"],
   ["Nmap results parsed","Grouped by host","Service versions noted","CVE lookup for each version"],
   [("nmap","comprehensive port scanning"),("searchsploit","vulnerability lookup by service version")],
   "Port and service inventory complete. Attack surface clearly mapped. Prioritized targets identified.",
   "Services: 192.168.1.10 - 53,88,389,445,636,3268 (DC). .20 - 22,80,443 (web). .30 - 3306 (MySQL 5.7.39 - outdated!).",
   "professional","**Service Memory**\n- DC (10): DNS,Kerberos,LDAP,SMB,LDAPS\n- Web (.20): SSH,HTTP,HTTPS\n- DB (.30): MySQL 5.7.39 (EOL - CVE lookup needed)"),

_e("Store custom exploit modifications made",
   ["Public exploits modified for target environment","Modifications documented","Reliability improvements noted"],
   ["Document original exploit","Note modifications made","Record why changes needed","Store for report"],
   ["Note base exploit used","Document each modification","Record environment-specific changes","Test reliability"],
   [("metasploit","exploit framework"),("python","custom exploit scripting")],
   "Custom exploit modifications stored. Reliable version created for target environment. Original vs modified documented.",
   "Modified: ms17-010.py - added custom target fingerprinting, adjusted for Win2019. EternalBlue port to Python3. Reliability: 95%.",
   "technical","**Exploit Memory**\n- Base: ms17-010 (Python2)\n- Modified: Python3 port\n- Change: Custom fingerprinting for Win2019\n- Reliability: 95% vs original 70%"),

_e("Remember data exfiltration paths tested",
   ["Data exfiltration techniques tested","Detection rate assessed","Successful channels documented"],
   ["Test various exfil methods","Note which triggered alerts","Document successful channels","Assess data loss prevention"],
   ["Test DNS exfiltration","Try HTTPS to cloud","Attempt ICMP tunnel","Check USB DLP","Document results"],
   [("dnscat2","DNS-based exfiltration"),("iodine","IP-over-DNS tunneling")],
   "Exfiltration channels assessed. DLP gaps identified. Successful channels documented for blue team awareness.",
   "Exfil results: DNS exfil undetected, HTTPS to Google Drive undetected, ICMP tunnel detected, USB blocked by DLP. Gap: DNS monitoring needed.",
   "structured","**Exfil Memory**\n- DNS exfil: ✅ undetected\n- HTTPS to GDrive: ✅ undetected\n- ICMP tunnel: ❌ detected\n- USB: ❌ blocked by DLP\n- Gap: DNS egress monitoring"),

_e("Store application error messages and stack traces",
   ["Verbose error messages discovered","Technology stack revealed","Debug info exposed"],
   ["Document error messages","Note technologies revealed","Assess information disclosure","Recommend fix"],
   ["Trigger various error conditions","Capture verbose responses","Extract technology information","Document findings"],
   [("burpsuite","error trigger testing"),("nikto","web server information disclosure")],
   "Error message analysis complete. Technology stack fully revealed via verbose errors. Framework versions exposed.",
   "Errors reveal: PHP 8.1.0, Laravel 9.12, MySQL 8.0 at 10.0.0.30, app path /var/www/html/production/. Stack traces in all 500 errors.",
   "analytical","**Error Memory**\n- PHP version: 8.1.0\n- Framework: Laravel 9.12\n- DB: MySQL 8.0 @ 10.0.0.30\n- Path: /var/www/html/production/"),

_e("Remember timing-sensitive attack windows",
   ["Certain attacks require specific timing","Maintenance windows identified","Admin activity patterns noted"],
   ["Document admin patterns","Note low-traffic windows","Plan timing-sensitive attacks","Maximize success probability"],
   ["Observe traffic patterns","Note admin login times","Identify maintenance windows","Plan attacks for best timing"],
   [("wireshark","traffic pattern analysis"),("custom_script","timing observation")],
   "Timing information stored. Attack windows identified. Scheduled tasks aligned with low-detection periods.",
   "Patterns: Admin active 09:00-18:00. Batch jobs run 02:00-03:00. Backup window 01:00. Low traffic: 03:00-06:00 = best attack window.",
   "structured","**Timing Memory**\n- Admin hours: 09:00-18:00\n- Batch jobs: 02:00-03:00\n- Best window: 03:00-06:00\n- Backup: Sunday 01:00 (system busy)"),

_e("Track security control effectiveness",
   ["Security controls tested","Effectiveness measured","Gaps documented"],
   ["Test each security control","Measure detection/prevention rate","Document gaps","Provide improvement recommendations"],
   ["Test AV, EDR, WAF, SIEM","Record what each detected","Note bypass techniques","Document control effectiveness"],
   [("custom_payloads","security control testing"),("nmap","firewall rule testing")],
   "Security control assessment complete. Effectiveness measured. Gap analysis ready for report.",
   "Controls: AV 60% detection (evadable), EDR good but AMSI bypassable, WAF blocks SQLi but not NoSQLi, SIEM misses C2 beacons.",
   "professional","**Control Memory**\n- AV: 60% detection rate\n- EDR: strong but AMSI bypassable\n- WAF: blocks SQLi, misses NoSQLi\n- SIEM: no C2 beacon detection rules"),

_e("Store OSINT findings about target organization",
   ["OSINT research completed","Employee data gathered","Technology stack identified from public sources"],
   ["Document key employees","Note technologies from job postings","Record public exposure","Map external attack surface"],
   ["LinkedIn employee enumeration","Job posting technology hints","GitHub code analysis","Shodan external exposure"],
   [("theHarvester","email and domain OSINT"),("maltego","relationship mapping")],
   "OSINT profile complete. Attack surface mapped from public sources. Phishing targets identified.",
   "OSINT: 847 employees on LinkedIn, tech stack from jobs: AWS/Python/Django, GitHub leaks old API key (revoked), Shodan: 3 exposed services.",
   "structured","**OSINT Memory**\n- Employees: 847 (LinkedIn)\n- Tech stack: AWS, Python, Django (job posts)\n- GitHub: old API key found (check if revoked)\n- Shodan: 3 unexpected open services"),

_e("Remember file upload restrictions tested",
   ["File upload functionality assessed","Restrictions tested","Bypass techniques documented"],
   ["Test allowed file types","Try MIME type bypass","Test extension bypass","Attempt path traversal in filename"],
   ["Upload various file types","Test MIME manipulation","Try double extension","Test null byte injection in filename"],
   [("burpsuite","file upload manipulation"),("weevely","web shell generation")],
   "File upload restrictions documented. Bypass technique identified. Web shell upload possible.",
   "Upload: blocks .php but accepts .php5, .phtml, .pHp. MIME check client-side only. Null byte bypass: shell.php%00.jpg. Webshell uploaded.",
   "technical","**Upload Memory**\n- Blocked: .php (basic check only)\n- Bypass: .php5, .phtml, .pHp\n- MIME: client-side only (bypassable)\n- Null byte: shell.php%00.jpg works"),

_e("Store DNS records and domain information",
   ["DNS enumeration completed","All records documented","Subdomain list compiled"],
   ["Document all DNS records","Note MX for phishing","Map subdomains","Check for zone transfer"],
   ["dig ANY target.com","subfinder enumeration","Zone transfer test","Document all findings"],
   [("dig","DNS querying"),("subfinder","subdomain enumeration")],
   "DNS profile complete. Subdomains documented. MX records noted for phishing campaign preparation.",
   "DNS: 47 subdomains found. Mail: mail.target.com (Exchange 2019). Zone transfer: allowed on ns2! SPF: soft fail (-all missing).",
   "professional","**DNS Memory**\n- Subdomains: 47 found\n- Mail: Exchange 2019 at mail.target.com\n- Zone transfer: allowed on ns2.target.com\n- SPF: soft fail (phishing easier)"),

_e("Track authentication tokens and session information",
   ["Session tokens analyzed","Entropy and predictability assessed","Session management weaknesses found"],
   ["Analyze token entropy","Test for predictability","Check expiration","Test token reuse"],
   ["Collect multiple tokens","Analyze for patterns","Test fixed prefix/suffix","Check expiration time","Test after logout"],
   [("burpsuite_sequencer","token entropy analysis"),("python","token analysis script")],
   "Session token analysis complete. Predictability issues documented. Session management findings ready for report.",
   "Tokens: 32-char hex but first 8 chars static (reduces entropy). No expiration. Valid after logout (no server-side invalidation).",
   "analytical","**Session Memory**\n- Token: 32-char hex\n- Issue: First 8 chars fixed (username hash)\n- Expiry: No server-side expiration\n- Logout: Token remains valid"),

_e("Remember pivot points and tunneling methods",
   ["Pivot points established through network","Tunneling methods documented","Access from various positions"],
   ["Document each pivot host","Note tunneling method","Record accessible networks from each pivot","Map pivot chain"],
   ["SSH tunnels established","SOCKS proxies noted","Port forwards documented","Pivot chain mapped"],
   [("ssh","SSH tunneling and pivoting"),("chisel","fast TCP/UDP tunnel")],
   "Pivot chain documented. Access to internal networks from external position established and stable.",
   "Pivots: External→DMZ via RCE, DMZ→Corp via SSH tunnel on port 443, Corp→Mgmt via chisel SOCKS5 on pwned workstation.",
   "structured","**Pivot Memory**\n- Pivot 1: External → DMZ (RCE on web server)\n- Pivot 2: DMZ → Corp (SSH tunnel :443)\n- Pivot 3: Corp → Mgmt (chisel SOCKS5)\n- Access: Full internal network"),
]

STYLE_DATA = [
_e("Write a professional penetration test executive summary",
   ["Executive audience needs high-level overview","Avoid technical jargon","Focus on business risk and impact"],
   ["Write for C-suite audience","Quantify business risk","Highlight critical findings","Recommend priority actions"],
   ["Draft executive summary","Lead with risk posture","Summarize critical findings","Business impact focus","Clear recommendations"],
   [("report_template","professional reporting"),("cvss_calculator","risk scoring")],
   "Executive summary written in business language. Technical details minimized. Business impact and risk clearly communicated.",
   "Executive reports: lead with overall risk rating, 3-5 key findings, business impact in dollars/risk, top 3 recommendations.",
   "executive","**Executive Summary**\n\nOverall Risk Rating: **CRITICAL**\n\nDuring this assessment, [Company] was found to have critical security vulnerabilities that expose the organization to significant business risk, including potential data breach affecting 50,000 customers.\n\n**Key Findings:**\n1. Unauthorized access to customer database\n2. Weak authentication controls\n3. Unpatched critical vulnerabilities\n\n**Recommended Immediate Actions:**\n1. Patch critical systems within 24 hours\n2. Reset all administrative credentials\n3. Enable multi-factor authentication"),

_e("Write a technical finding with full detail",
   ["Technical audience needs precise detail","Include reproduction steps","Provide code examples"],
   ["Use technical language","Include exact commands","Show request/response examples","Provide remediation code"],
   ["Write vulnerability title","Add CVSS score","Detail reproduction steps","Include evidence","Provide code fix"],
   [("burpsuite","evidence capture"),("cvss_calculator","severity scoring")],
   "Technical finding documented with full reproduction steps. Developer can understand and fix without further clarification.",
   "Technical findings: CVSS score, reproduction steps, evidence (requests/responses), impact, and specific code-level remediation.",
   "technical","**SQL Injection in Login Parameter**\n\nCVSS: 9.8 (Critical)\nCWE: CWE-89\n\n**Reproduction:**\n```\nPOST /login HTTP/1.1\nusername=admin'--&password=x\n```\n\n**Response:** Login successful as admin\n\n**Remediation:**\n```php\n// Vulnerable:\n$query = \"SELECT * FROM users WHERE username='$username'\";\n// Fixed:\n$stmt = $pdo->prepare('SELECT * FROM users WHERE username=?');\n$stmt->execute([$username]);\n```"),

_e("Write a concise security alert notification",
   ["Alert needs to be actionable immediately","Short and clear","Include severity and action needed"],
   ["One paragraph maximum","Lead with severity","State exact action needed","Include contact"],
   ["Write alert header","State severity","Describe threat","Required action","Contact information"],
   [("siem","alert generation"),("email","notification delivery")],
   "Alert written concisely. Recipient knows severity and required action immediately without reading full report.",
   "Alerts: severity first, threat description second, required action third. Under 100 words. One clear action item.",
   "concise","🚨 **CRITICAL SECURITY ALERT**\n\nActive intrusion detected on CORP-SRV-01. Attacker has SYSTEM access. **Immediate action required:** Isolate CORP-SRV-01 from network now.\n\nContact SOC: ext. 911 or security@company.com"),

_e("Write an incident response report",
   ["IR report needs timeline and technical details","Management and technical audiences","Lessons learned important"],
   ["Structure with executive summary","Include detailed timeline","Document response actions","Lessons learned section"],
   ["Executive summary","Incident overview","Timeline","Technical analysis","Response actions","Lessons learned","Recommendations"],
   [("ir_template","incident response reporting"),("splunk","log analysis for timeline")],
   "IR report complete. Timeline clear. Lessons learned actionable. Both executive and technical needs met.",
   "IR reports: executive summary, timeline (with UTC timestamps), technical analysis, response actions, lessons learned.",
   "professional","# Incident Response Report\n**Incident ID:** IR-2024-001\n**Severity:** Critical\n**Status:** Resolved\n\n## Executive Summary\nOn [date], ransomware was detected affecting 3 workstations...\n\n## Timeline\n- 14:32 UTC: Initial alert triggered\n- 14:35 UTC: SOC analyst confirmed threat\n- 14:40 UTC: Systems isolated\n- 18:00 UTC: Systems restored from backup\n\n## Lessons Learned\n1. Email gateway rules need strengthening\n2. User security training required"),

_e("Write a threat intelligence report",
   ["TI report needs attribution and TTPs","Structured around MITRE ATT&CK","Actionable for defensive teams"],
   ["Threat actor profile","TTPs mapped to ATT&CK","IOCs provided","Detection recommendations"],
   ["Actor overview","Motivation","TTPs with ATT&CK IDs","IOC list","Detection signatures","Recommendations"],
   [("mitre_attack","TTP mapping"),("yara","detection rule creation")],
   "Threat intelligence report ready. SOC team can use IOCs and detection rules immediately.",
   "TI reports: actor profile, ATT&CK TTP mapping, actionable IOCs, YARA/Sigma rules for detection. Be specific and current.",
   "analytical","# Threat Intelligence Report\n**Threat Actor:** APT-XX\n**Confidence:** High\n\n## TTPs (MITRE ATT&CK)\n- T1566.001: Spearphishing Attachment\n- T1059.001: PowerShell\n- T1486: Data Encrypted for Impact\n\n## IOCs\n- IP: 185.x.x.x (C2)\n- Hash: a1b2c3... (payload)\n\n## Detections\n```yaml\ntitle: APT-XX C2 Communication\ndetection:\n  selection:\n    dst_ip: '185.x.x.x'\n```"),

_e("Write a risk assessment matrix",
   ["Risk matrix needs likelihood and impact","Stakeholders need visual clarity","Priority order required"],
   ["Define risk categories","Rate likelihood and impact","Calculate risk score","Prioritize mitigation"],
   ["List all risks","Rate each on 1-5 scale","Calculate risk score (L×I)","Sort by score","Assign ownership"],
   [("risk_framework","risk assessment methodology"),("excel","risk matrix creation")],
   "Risk matrix complete. All risks quantified and prioritized. Ownership assigned for each risk.",
   "Risk matrix: use 5x5 scale (1-5 likelihood × 1-5 impact = 1-25 score). Critical ≥20, High 15-19, Medium 10-14, Low <10.",
   "structured","**Risk Assessment Matrix**\n\n| Risk | Likelihood | Impact | Score | Priority |\n|------|-----------|--------|-------|----------|\n| SQLi vulnerability | 5 | 5 | 25 | Critical |\n| Weak passwords | 4 | 4 | 16 | High |\n| Missing patches | 3 | 4 | 12 | Medium |\n| Verbose errors | 2 | 2 | 4 | Low |"),

_e("Write a remediation tracking document",
   ["Remediation needs clear ownership and deadlines","Progress needs to be trackable","Priorities must be clear"],
   ["List all findings","Assign owner and deadline","Track status","Follow up on overdue items"],
   ["Create finding list","Assign responsible team","Set realistic deadlines","Define verification criteria","Track completion"],
   [("jira","vulnerability tracking"),("report_template","remediation tracking")],
   "Remediation tracker ready. All findings have owner, deadline, and verification criteria. Follow-up process defined.",
   "Remediation tracking: each finding needs owner, deadline (Critical<24h, High<7d, Medium<30d), and verification step.",
   "professional","**Remediation Tracker**\n\n| ID | Finding | Owner | Deadline | Status | Verified |\n|----|---------|-------|----------|--------|----------|\n| F-001 | SQLi | Dev Team | 24 hrs | In Progress | ❌ |\n| F-002 | Weak Passwords | IT | 7 days | Pending | ❌ |\n| F-003 | Missing Patches | Ops | 7 days | Complete | ✅ |"),

_e("Write a security assessment scope document",
   ["Scope defines what is and isn't authorized","Legal protection requires clear boundaries","Team needs unambiguous guidance"],
   ["Define in-scope systems","List out-of-scope items","Specify authorized techniques","Note testing windows"],
   ["List target IPs/domains","Specify excluded systems","Define allowed attack types","Note business hours restrictions"],
   [("scope_template","assessment scoping"),("rules_of_engagement","authorized testing boundaries")],
   "Scope document clear and unambiguous. All testers understand boundaries. Legal authorization documented.",
   "Scope docs: explicit IP ranges, excluded systems, allowed techniques, testing hours, emergency contacts. No ambiguity allowed.",
   "structured","**Assessment Scope**\n\n**In-Scope:**\n- 192.168.1.0/24\n- app.target.com, api.target.com\n\n**Out-of-Scope:**\n- 192.168.2.0/24 (production)\n- mail.target.com\n- DoS attacks\n\n**Testing Window:** Mon-Fri 09:00-18:00\n\n**Emergency Contact:** John Smith +1-555-0100"),

_e("Write a vulnerability disclosure report for responsible disclosure",
   ["Vendor needs enough info to reproduce","Timeline matters for coordinated disclosure","Professional tone essential"],
   ["Describe vulnerability clearly","Include reproduction steps","Suggest remediation","Propose disclosure timeline"],
   ["Vulnerability overview","Technical details","PoC (limited)","Impact assessment","Suggested fix","Timeline proposal"],
   [("cvd_template","coordinated vulnerability disclosure"),("pgp","secure communication")],
   "Responsible disclosure report ready. Vendor has all info needed to reproduce and fix. Timeline proposed.",
   "CVD reports: clear description, minimal PoC, impact assessment, fix suggestion, 90-day disclosure timeline (industry standard).",
   "professional","**Vulnerability Report**\n\nTo: security@vendor.com\nFrom: researcher@example.com\nDate: [date]\n\n**Summary:** SQL injection in login endpoint\n**Severity:** Critical (CVSS 9.8)\n**Affected:** v2.1.0-v2.3.1\n\n**Timeline:**\n- [Date]: Discovered\n- [Date]: Vendor notified\n- [Date+90d]: Public disclosure\n\nPlease confirm receipt within 7 days."),

_e("Write a SOC runbook for alert response",
   ["SOC analysts need step-by-step guidance","Consistency across analysts important","Decision trees help"],
   ["Define alert trigger","List initial triage steps","Create decision tree","Define escalation criteria"],
   ["Alert description","Initial triage steps","Automated queries","Decision points","Escalation path","Documentation requirements"],
   [("splunk","SIEM alert investigation"),("ir_platform","case management")],
   "SOC runbook complete. Any analyst can follow procedure consistently. Escalation paths clear.",
   "SOC runbooks: trigger condition, triage steps (with exact queries), decision tree, escalation criteria, documentation requirements.",
   "technical","# SOC Runbook: Ransomware Alert\n\n**Trigger:** >100 file extension changes in 5min\n\n**Triage Steps:**\n1. Identify affected endpoint\n2. Check process list: `process where EventID=4688`\n3. Isolate if confirmed\n\n**Decision Tree:**\n- Confirmed? → Isolate + Escalate P1\n- Suspicious? → Investigate + Escalate P2\n- False Positive? → Document + Close\n\n**Escalate to:** SOC Lead + CISO"),

_e("Write pentest findings in bug bounty format",
   ["Bug bounty platforms have specific format","Reproducibility is key","CVSS score needed"],
   ["Title with vulnerability type","Clear reproduction steps","Impact assessment","Suggested fix"],
   ["One-line title","Vulnerability description","Step-by-step reproduction","Expected vs actual","Impact","Fix suggestion"],
   [("hackerone","bug bounty submission"),("bugcrowd","alternative bug bounty platform")],
   "Bug bounty report properly formatted. All required fields complete. Reproduction steps clear and testable.",
   "Bug bounty format: descriptive title, CVSS score, clear repro steps, screenshots/videos, business impact, fix recommendation.",
   "concise","**Title:** SQL Injection in /search endpoint leads to database dump\n\n**Severity:** Critical (CVSS 9.8)\n\n**Steps to Reproduce:**\n1. Navigate to /search?q=test\n2. Inject payload: `test' UNION SELECT username,password FROM users--`\n3. Observe database credentials in response\n\n**Impact:** Full database exposure\n**Fix:** Parameterized queries"),

_e("Write a security posture improvement roadmap",
   ["Roadmap needs prioritization and timeline","Executive approval needed","Resources must be considered"],
   ["Assess current state","Define target state","Identify gaps","Create phased roadmap","Assign resources"],
   ["Current security posture","Target state definition","Gap analysis","Phase 1-3 roadmap","Resource requirements","Success metrics"],
   [("nist_csf","security framework reference"),("project_plan","roadmap creation")],
   "Security roadmap created. 3-phase plan with clear milestones. Executive-ready presentation format.",
   "Security roadmaps: 3-phase (quick wins, medium-term, long-term). Each phase: findings addressed, cost estimate, risk reduction.",
   "professional","**Security Improvement Roadmap**\n\n**Phase 1 (0-30 days) - Critical:**\n- Patch critical vulnerabilities\n- Enable MFA for all admins\n- Cost: $0 (config changes)\n- Risk Reduction: 40%\n\n**Phase 2 (30-90 days) - High:**\n- Deploy EDR solution\n- Implement SIEM\n- Cost: $50K\n- Risk Reduction: 30%\n\n**Phase 3 (90-180 days) - Medium:**\n- Zero Trust implementation\n- Security awareness training\n- Cost: $100K"),

_e("Write MITRE ATT&CK threat mapping",
   ["ATT&CK framework provides common language","Maps findings to known TTPs","Enables threat-informed defense"],
   ["Identify observed techniques","Map to ATT&CK IDs","Note detection opportunities","Recommend mitigations"],
   ["List observed attacker actions","Find matching ATT&CK techniques","Note tactic categories","Identify detection and mitigation"],
   [("mitre_attack","TTP framework"),("attack_navigator","visualization tool")],
   "ATT&CK mapping complete. Full kill chain documented in framework language. Detection and mitigation recommendations provided.",
   "ATT&CK mapping: technique ID, name, description of observed use, detection opportunities, mitigations. Use Navigator for visualization.",
   "analytical","**MITRE ATT&CK Mapping**\n\n| Tactic | Technique | ID | Observed |\n|--------|-----------|-----|----------|\n| Initial Access | Phishing | T1566 | Email with malicious attachment |\n| Persistence | Registry Run Keys | T1547.001 | HKCU\\Run entry added |\n| Credential Access | LSASS Memory | T1003.001 | Mimikatz used |\n| Lateral Movement | Pass the Hash | T1550.002 | NTLM hash reuse |"),

_e("Write network diagram documentation",
   ["Visual representation of network topology","Clear labeling of security zones","Attack paths visible"],
   ["Document network zones","Show traffic flows","Note security controls placement","Mark sensitive assets"],
   ["List all network segments","Document connections between segments","Note firewall/IDS placement","Mark critical assets"],
   [("draw_io","network diagram creation"),("nmap","network discovery for documentation")],
   "Network documentation ready. Architecture clear to both technical and non-technical readers.",
   "Network docs: zones (DMZ/Corp/Mgmt), connections with protocols, security control placement, and critical asset locations.",
   "structured","**Network Architecture**\n\n```\n[Internet]\n    |\n[Firewall] - IDS/IPS\n    |\n[DMZ: 192.168.10.0/24]\n  ├── Web Server (.20)\n  └── Mail Server (.30)\n    |\n[Firewall]\n    |\n[Corporate: 10.0.0.0/24]\n  ├── Workstations\n  └── File Server\n    |\n[Mgmt: 172.16.0.0/24]\n  └── Domain Controller\n```"),

_e("Write a security awareness training scenario",
   ["Training needs realistic but safe scenarios","Employees must understand risk","Action steps must be clear"],
   ["Create realistic phishing scenario","Explain red flags to look for","Describe proper response","Reinforce learning"],
   ["Realistic email example","Red flags highlighted","What to do","What not to do","Reporting procedure"],
   [("gophish","phishing simulation"),("training_platform","security awareness training")],
   "Training scenario created. Red flags clearly identified. Employees know exact steps to take when suspicious.",
   "Security awareness: realistic scenarios, clear red flags, simple action steps (report, don't click), positive reinforcement.",
   "professional","**Security Awareness: Phishing Example**\n\n⚠️ **Red Flags in this Email:**\n- Sender: IT-Support@company.secure-login.com (not @company.com)\n- Urgent language: 'Account expires in 1 HOUR'\n- Generic greeting: 'Dear User'\n- Suspicious link: hover shows different URL\n\n**What To Do:**\n1. Do NOT click any links\n2. Report to security@company.com\n3. Delete the email\n\n**Never** enter credentials via email links."),
]
